/*
  # Add Latin American and Middle Eastern Passport Pathways

  ## Overview
  Comprehensive immigration pathways for citizens from:
  - Latin America: Colombia, Argentina, Chile, Peru, Venezuela
  - Middle East: Turkey, Egypt, Jordan, Lebanon, Saudi Arabia
  
  ## Destinations
  All major immigration destinations

  ## Goals
  Work, Study, Visit, Residency
*/

INSERT INTO immigration_pathways (
  passport_slug, destination_slug, goal, pathway_type, pathway_name,
  summary, eligibility, key_requirements, requirements, typical_timeline,
  processing_time, estimated_fees, validity_period, official_url
) VALUES

-- Colombia to Canada
('co', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('co', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('co', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Colombian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Colombia to US
('co', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for professionals.',
 'Bachelor degree, employer sponsorship.',
 'Job offer, employer petition, degree.',
 'US employer petition, bachelor degree, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('co', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP school acceptance.',
 'I-20, SEVIS fee, financial proof.',
 'I-20, SEVIS fee, financial capacity, interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('co', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Colombian passport holders.',
 'Valid passport, interview, funds.',
 'Valid passport, visa interview, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

-- Argentina to Canada
('ar', 'ca', 'Work', 'Work', 'International Experience Canada',
 'Working holiday for Argentine youth.',
 'Argentine citizens 18-35 years old.',
 'Valid passport, CAD 2,500 funds.',
 'Passport, CAD 2,500 proof of funds, health insurance.',
 '8-12 weeks', '8-12 weeks', 'CAD 250',
 '1 year',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/iec.html'),

('ar', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('ar', 'ca', 'Visit', 'Visit', 'Electronic Travel Authorization (eTA)',
 'Electronic visa for air travel.',
 'Argentine passport holders.',
 'Valid passport.',
 'Valid passport, online eTA application.',
 'Minutes', 'Minutes', 'CAD 7',
 'Up to 5 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html'),

-- Chile to Canada
('cl', 'ca', 'Work', 'Work', 'International Experience Canada',
 'Working holiday for Chilean youth.',
 'Chilean citizens 18-35 years old.',
 'Valid passport, CAD 2,500 funds.',
 'Passport, CAD 2,500 proof of funds, health insurance.',
 '8-12 weeks', '8-12 weeks', 'CAD 250',
 '1 year',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/iec.html'),

('cl', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('cl', 'ca', 'Visit', 'Visit', 'Electronic Travel Authorization (eTA)',
 'Electronic visa for air travel.',
 'Chilean passport holders.',
 'Valid passport.',
 'Valid passport, online eTA application.',
 'Minutes', 'Minutes', 'CAD 7',
 'Up to 5 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html'),

-- Peru to Canada
('pe', 'ca', 'Work', 'Work', 'Temporary Foreign Worker Program',
 'Employer-specific work permit.',
 'Job offer with LMIA.',
 'LMIA-approved job offer.',
 'LMIA from employer, qualifications, employment contract.',
 '2-4 months', '2-4 months', 'CAD 155-230',
 '1-4 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/hire-temporary-foreign/temporary-foreign-worker-program.html'),

('pe', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('pe', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Peruvian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Venezuela to US
('ve', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for professionals.',
 'Bachelor degree, employer sponsorship.',
 'Job offer, employer petition, degree.',
 'US employer petition, bachelor degree, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('ve', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP school acceptance.',
 'I-20, SEVIS fee, financial proof.',
 'I-20, SEVIS fee, financial capacity, interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('ve', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Venezuelan passport holders.',
 'Valid passport, interview, funds.',
 'Valid passport, visa interview, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

-- Turkey to Canada
('tr', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('tr', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('tr', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Turkish passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Turkey to Germany
('tr', 'de', 'Work', 'Work', 'EU Blue Card',
 'Work permit for highly qualified workers.',
 'University degree, job offer €45,300+ salary.',
 'Degree, employment contract.',
 'University degree, employment contract €45,300+, health insurance.',
 '1-3 months', '1-3 months', 'EUR 100',
 '4 years',
 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card'),

('tr', 'de', 'Study', 'Study', 'Student Visa',
 'Study at German university.',
 'University admission.',
 'Admission letter, blocked account, health insurance.',
 'University admission, blocked account €11,208, health insurance.',
 '6-12 weeks', '6-12 weeks', 'EUR 75',
 'Duration of studies',
 'https://www.make-it-in-germany.com/en/study-training/study/preparations/prerequisites'),

('tr', 'de', 'Visit', 'Visit', 'Schengen Visa',
 'Tourism and business visits.',
 'Turkish passport holders.',
 'Valid passport, travel insurance.',
 'Valid passport, travel insurance €30,000+, return ticket, funds.',
 '2-4 weeks', '2-4 weeks', 'EUR 80',
 'Up to 90 days',
 'https://www.schengenvisainfo.com/'),

-- Egypt to Canada
('eg', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('eg', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('eg', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Egyptian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Egypt to UK
('eg', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK sponsor.',
 'Certificate of Sponsorship, English test.',
 'CoS, English proficiency, £1,270 funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('eg', 'gb', 'Study', 'Study', 'Student Visa',
 'Study at UK institution.',
 'Acceptance from licensed sponsor.',
 'CAS, English test, funds.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration',
 'https://www.gov.uk/student-visa'),

('eg', 'gb', 'Visit', 'Visit', 'Standard Visitor Visa',
 'Tourism and business visits.',
 'Egyptian passport holders.',
 'Valid passport, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '3 weeks', '3 weeks', 'GBP 100',
 '6 months',
 'https://www.gov.uk/standard-visitor-visa'),

-- Jordan to Canada
('jo', 'ca', 'Work', 'Work', 'Temporary Foreign Worker Program',
 'Employer-specific work permit.',
 'Job offer with LMIA.',
 'LMIA-approved job offer.',
 'LMIA from employer, qualifications, employment contract.',
 '2-4 months', '2-4 months', 'CAD 155-230',
 '1-4 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/hire-temporary-foreign/temporary-foreign-worker-program.html'),

('jo', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('jo', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Jordanian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Lebanon to Canada
('lb', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('lb', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('lb', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Lebanese passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Saudi Arabia to Canada
('sa', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('sa', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Saudi passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

('sa', 'ca', 'Work', 'Work', 'Temporary Foreign Worker Program',
 'Employer-specific work permit.',
 'Job offer with LMIA.',
 'LMIA-approved job offer.',
 'LMIA from employer, qualifications.',
 '2-4 months', '2-4 months', 'CAD 155-230',
 '1-4 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/hire-temporary-foreign/temporary-foreign-worker-program.html')

ON CONFLICT (id) DO NOTHING;