/*
  # Populate Japan, India, Ireland, and Italy Immigration Pathways
  
  Comprehensive pathways for major Asian and European destinations.
*/

-- JAPAN PATHWAYS
INSERT INTO immigration_pathways (
  destination_slug, passport_slug, pathway_type, goal, pathway_name, summary,
  eligibility, key_requirements, typical_timeline, estimated_fees,
  requirements, processing_time, validity_period, last_updated
) VALUES
('japan', 'any', 'Work Visa', 'Work', 'Japan Highly Skilled Professional Visa',
'Japan''s premium visa for highly skilled workers using a points-based system. Offers fast-track to permanent residence, spousal work permission, and multiple benefits. Scores 70+ points get preferential treatment.',
'Score 70+ points based on academic background, work experience, annual salary, age, and Japanese language ability. Points calculator available on Immigration Services Agency website. Categories: Advanced academic research, specialized technical work, or business management.',
'70+ points (academic/technical/business), Job offer or business plan, University degree, Work experience',
'1-3 months',
'Application fee ¥4,000, Certificate of Eligibility processing free',
'University degree certificates, Proof of work experience (10+ years preferred), Job offer or business plan, Passport, Photos, Points calculation sheet, Resume, Financial documents, Company registration (if applicable), Japanese language certificate (for extra points)',
'1-3 months for Certificate of Eligibility. 1 week for visa at embassy after COE approval.',
'Initially 5 years (70-79 points) or renewable. After 3 years with 70+ points or 1 year with 80+ points, eligible for permanent residence. Spouse can work. Parents and domestic helpers allowed under certain conditions.',
CURRENT_DATE),

('japan', 'any', 'Work Visa', 'Work', 'Japan Engineer/Specialist Visa',
'Standard work visa for professionals with technical expertise or specialized knowledge. Common for IT, engineering, humanities, and international services roles.',
'University degree relevant to job field OR 10+ years relevant work experience (3 years for some fields). Job offer from Japanese company. Salary equal to or greater than Japanese worker in same role. Company must be registered and operating.',
'University degree or 10+ years experience, Job offer, Comparable salary',
'2-4 months',
'Certificate of Eligibility ¥0, Visa fee ¥3,000-6,000',
'Certificate of Eligibility (company applies), University degree with certified translation, Employment contract, Company documents (registration, financials, tax certificates), Resume, Passport and photos, Proof of relevant experience',
'2-4 months for Certificate of Eligibility. 1 week for visa after COE.',
'Initially 1-5 years depending on company status and experience. Renewable indefinitely. After 10 years (or 5 years for highly skilled), eligible for permanent residence. Can change jobs within same visa category.',
CURRENT_DATE),

('japan', 'any', 'Study Visa', 'Study', 'Japan Student Visa',
'Study at Japanese universities, vocational schools, or language schools. Can work part-time up to 28 hours/week during term (40 hours during breaks). Post-graduation job search visa available.',
'Acceptance from Japanese educational institution approved by Immigration Services Agency. Financial resources (¥1.5-2 million/year typically). Basic Japanese language ability for most programs (N5-N2 level). English programs available at some universities.',
'School acceptance, ¥1.5-2 million/year funds, Language ability',
'3-6 months',
'Certificate of Eligibility ¥0, Visa fee ¥3,000, School application fees vary',
'Certificate of Eligibility (school applies), School acceptance letter, Financial guarantee (bank statements, scholarship, sponsor guarantee), Academic records with translations, Language proficiency certificate (JLPT, EJU, or school test), Passport and photos, Study plan',
'3-6 months for COE and admission. 1 week for visa after COE.',
'Duration of studies. Can work 28 hours/week during term, 40 hours during breaks. After graduation, can apply for job-seeking visa (up to 1 year). Convert to work visa when employed. Some universities offer direct transition programs.',
CURRENT_DATE),

('japan', 'any', 'Digital Nomad Visa', 'Work', 'Japan Business Manager Visa',
'For entrepreneurs starting businesses in Japan or managing operations. Requires significant investment and business plan. Can bring immediate business benefits.',
'Invest ¥5 million+ in Japanese business OR employ 2+ full-time staff. Secure office space in Japan. Viable business plan demonstrating sustainability. Business must benefit Japanese economy. Manager role with clear responsibilities.',
'¥5 million investment or 2+ employees, Business plan, Office space',
'3-6 months',
'Certificate of Eligibility ¥0, Visa fee ¥6,000, Company registration ¥60,000-240,000',
'Business plan in Japanese, Proof of investment (¥5 million) or 2+ employee contracts, Office lease agreement, Company registration documents, Resume and business experience, Financial statements, Passport and photos, Certificate of Eligibility',
'3-6 months for business setup and COE.',
'Initially 1 year, renewable to 3-5 years based on business performance. After 10 years or if highly skilled status achieved, eligible for permanent residence. Family can accompany.',
CURRENT_DATE),

('japan', 'any', 'Family Visa', 'Family', 'Japan Dependent Visa',
'For family members of work visa holders. Spouses and unmarried minor children can join. Work permission available with approval (28 hours/week).',
'Sponsor must hold valid work visa (excluding some short-term statuses). Proof of relationship. Sufficient income to support family. Adequate housing.',
'Valid sponsor visa, Relationship proof, Sufficient income, Housing',
'2-4 months',
'Certificate of Eligibility ¥0, Visa fee ¥3,000 per person',
'Certificate of Eligibility (sponsor applies), Marriage certificate or birth certificate with translation, Sponsor''s residence card and employment proof, Financial documents (pay slips, tax certificates), Housing proof (lease, residence certificate), Passport and photos of dependent',
'2-4 months for Certificate of Eligibility. 1 week for visa after COE.',
'Aligned with sponsor''s visa period. Can work up to 28 hours/week with permission (separate application at immigration). Cannot engage in restricted activities. Eligible for permanent residence after sponsor qualifies.',
CURRENT_DATE),

('japan', 'any', 'Visitor Visa', 'Visit', 'Japan Temporary Visitor Visa',
'Short-term visit for tourism, business meetings, visiting family/friends. Many nationalities visa-exempt for 14-90 days. No employment or extended stay permitted.',
'Valid travel purpose. Sufficient funds for stay. Return arrangements. Intent to leave Japan. No prior immigration violations.',
'Valid purpose, Sufficient funds, Return ticket, Intent to leave',
'1-2 weeks (if visa required)',
'Visa fee ¥3,000-6,000 (many nationalities exempt)',
'Passport (6+ months validity), Application form and photo, Travel itinerary and hotel bookings, Financial proof (bank statements), Employment certificate or business registration, Return flight booking, Invitation letter if applicable',
'1-2 weeks for visa-required nationals. Visa-exempt nationals enter directly.',
'15-90 days depending on nationality (most get 90 days). Cannot work or engage in paid activities. Single or multiple entry available. Extensions rarely granted.',
CURRENT_DATE),

-- INDIA PATHWAYS
('india', 'any', 'Work Visa', 'Work', 'India Employment Visa',
'For foreign nationals employed by Indian companies or foreign companies with Indian operations. Requires minimum salary threshold and employer compliance.',
'Job offer from Indian registered company. Minimum annual salary USD $25,000 (may vary by sector and experience). Relevant qualifications and experience. Position cannot be easily filled by Indian worker. Employer must be registered and compliant.',
'Job offer, USD $25,000+ salary, Relevant qualifications, Employer compliance',
'4-8 weeks',
'Visa fee USD $80-160 (varies by nationality and duration)',
'Employment contract from Indian company, Company registration documents, Proof of qualifications (degrees with transcripts), Experience certificates, Passport (6+ months validity), Photos, Company tax documents and financials, Detailed job description, Salary proof',
'4-8 weeks for visa processing.',
'Initially 1 year or contract duration (up to 5 years for certain cases). Renewable. Multiple entry. After visa approval, must register with FRRO within 14 days of arrival. Can bring dependents. After 5+ years, may explore OCI (limited) options.',
CURRENT_DATE),

('india', 'any', 'Work Visa', 'Work', 'India Business Visa',
'For business visits, meetings, exhibitions, establishing business ventures. Cannot be directly employed but can engage in business activities.',
'Legitimate business purpose in India (meetings, negotiations, purchases, establishing venture). Invitation from Indian company or documentation. Financial capacity. Business credentials.',
'Business purpose, Indian company invitation, Business credentials, Funds',
'1-2 weeks (e-Visa) or 2-4 weeks (regular)',
'e-Business Visa USD $100-120, Regular visa USD $80-160',
'Passport (6+ months validity), Business invitation letter from Indian company, Company registration of inviting organization, Bank statements, Business card or company introduction, Photos, Travel itinerary, Hotel bookings',
'1-2 weeks for e-Business Visa. 2-4 weeks for regular visa.',
'e-Business Visa: 1 year, multiple entry, 180 days max per visit. Regular Business Visa: up to 5 years. Cannot take up employment. Must conduct business only. Can bring dependents on separate visas.',
CURRENT_DATE),

('india', 'any', 'Study Visa', 'Study', 'India Student Visa',
'Study at Indian universities and institutions. India offers diverse programs from traditional studies to yoga, Ayurveda, and technical courses. Affordable education with rich cultural experience.',
'Admission to recognized Indian educational institution. Financial resources to support studies. Academic qualifications for program. Some institutions may require entrance exams.',
'Institution admission, Financial resources, Academic qualifications',
'3-6 weeks',
'Visa fee USD $60-160 (varies by nationality)',
'Admission letter from Indian institution, University registration documents, Academic records and certificates, Financial proof (bank statements or sponsor letter), Passport (6+ months validity), Photos, Medical certificate, Study plan or research proposal if applicable',
'3-6 weeks for visa processing.',
'Duration of course plus vacation periods. Must register with FRRO within 14 days. Can engage in part-time work or internship with permission. Extensions granted for valid academic reasons. After completion, 60-day grace period for departure or visa conversion.',
CURRENT_DATE),

('india', 'any', 'Digital Nomad Visa', 'Work', 'India Project Visa',
'For specific projects or assignments in India. Common for technical installations, project management, or consulting work. Different from regular employment visa.',
'Specific project or contract with Indian entity. Project details and timeline. Relevant technical qualifications. Project must have clear deliverables and fixed duration.',
'Project contract, Technical qualifications, Fixed timeline, Deliverables',
'3-6 weeks',
'Visa fee USD $80-160',
'Project contract or agreement, Company documents from both sides, Technical qualifications, Project description and timeline, Passport (6+ months validity), Photos, Financial documents, Previous project experience proof',
'3-6 weeks for processing.',
'Project duration (typically 1-2 years maximum). Single purpose, cannot switch employers. Must register with FRRO. Extensions difficult. Must leave upon project completion.',
CURRENT_DATE),

('india', 'any', 'Family Visa', 'Family', 'India Dependent/Entry Visa',
'For dependents of employment visa holders, students, or research visa holders. Allows family members to stay in India but work restrictions apply.',
'Valid sponsor visa (employment, student, research). Proof of relationship. Adequate financial support from sponsor.',
'Sponsor visa, Relationship proof, Financial support',
'3-6 weeks',
'Visa fee USD $60-120',
'Sponsor visa copy, Relationship proof (marriage certificate, birth certificate), Sponsor employment/student documents, Financial documents showing support, Passport (6+ months validity), Photos, Accommodation proof in India',
'3-6 weeks for processing.',
'Aligned with sponsor visa validity. Must register with FRRO within 14 days. Employment generally not permitted (requires separate employment visa). Can attend short courses. Must maintain valid status.',
CURRENT_DATE),

('india', 'any', 'Visitor Visa', 'Visit', 'India Tourist e-Visa',
'Electronic visa for tourism, visiting friends/family, or short yoga/Ayurveda programs. Fast online application. Most convenient option for eligible nationalities.',
'Valid passport from eligible country (160+ nationalities). Tourism or casual visit purpose. Financial means for stay. Return arrangements.',
'Eligible nationality, Tourism purpose, Funds, Return plan',
'3-7 days online',
'USD $10-100 (varies by nationality and season)',
'Passport (6+ months validity, 2 blank pages), Digital passport photo, Return flight booking, Hotel bookings or invitation letter, Financial proof (bank statement), Travel itinerary',
'3-7 days online processing. Instant for some nationalities during certain periods.',
'30 days double entry or 1 year multiple entry (depending on type selected). Cannot engage in business, employment, journalism, or missionary work. Extension not permitted on e-Visa.',
CURRENT_DATE),

-- IRELAND PATHWAYS
('ireland', 'any', 'Work Visa', 'Work', 'Ireland Critical Skills Employment Permit',
'Fast-track work permit for highly skilled occupations in demand. No labor market test required. Provides immediate pathway to family reunification and permanent residence.',
'Job offer in eligible occupation (Critical Skills List). Minimum annual salary €32,000 for most roles (€64,000 for jobs not on list). University degree or equivalent. Job offer for 2+ years.',
'Critical skills occupation or €64,000+ salary, €32,000+ minimum, University degree, 2+ year offer',
'8-12 weeks',
'Application fee €1,000',
'Job offer letter (2+ years), Employment contract, University degree certificates, Passport, CV, Employer evidence (registration, tax compliance), Proof salary meets threshold, Cover letter from employer explaining need',
'8-12 weeks for permit processing.',
'2 years initially. After 2 years, eligible for Stamp 4 (similar to permanent residence). Can bring family immediately. Spouse can work without permit. After 2 years, can renew or convert to Stamp 4. Path to citizenship after 5 years.',
CURRENT_DATE),

('ireland', 'any', 'Work Visa', 'Work', 'Ireland General Employment Permit',
'Standard work permit for occupations on Ineligible List. Requires labor market test. Longer pathway to permanent residence than Critical Skills.',
'Job offer in eligible occupation (not on Ineligible List). Minimum annual salary €30,000. Employer advertised role to EEA nationals first. Educational qualifications relevant to role.',
'Eligible occupation, €30,000+ salary, Labor market test passed, Relevant qualifications',
'8-12 weeks',
'Application fee €1,000',
'Job offer letter, Employment contract, Proof of qualifications, Labor market test evidence (ads placed), Passport, CV, Employer registration and tax documents, Salary specification, Cover letter',
'8-12 weeks for permit processing.',
'2 years initially, renewable. After 5 years continuous employment, eligible for Stamp 4. Family reunification possible after holding permit for 12 months. Spouse needs own work permit. Long-term residence after 5 years.',
CURRENT_DATE),

('ireland', 'any', 'Study Visa', 'Study', 'Ireland Student Visa (Stamp 2)',
'Study at Irish universities and language schools. Can work part-time during studies. Graduate visa available after completion.',
'Acceptance from Irish educational institution on Interim List of Eligible Programmes (ILEP). Proof of fees paid (or scholarship). Financial resources (€10,000/year plus fees). Private medical insurance.',
'ILEP institution acceptance, €10,000/year plus fees, Health insurance',
'6-8 weeks (8-12 weeks peak season)',
'Visa application fee €60 (if required)',
'ILEP institution acceptance letter, Proof of fees paid, Financial evidence (€10,000 minimum + fees), Private medical insurance, Passport (6+ months validity), Academic records, Language test results if applicable, Photos, Explanation letter',
'6-8 weeks standard. 8-12 weeks during peak university intake seasons.',
'Duration of course. Can work 20 hours/week during term, 40 hours during holidays. After degree completion, eligible for Third Level Graduate Scheme (1-2 years). Can then seek Critical Skills Permit.',
CURRENT_DATE),

('ireland', 'any', 'Digital Nomad Visa', 'Work', 'Ireland Start-up Entrepreneur Programme',
'For innovative entrepreneurs with high-potential start-ups. Requires approval from Irish government. Provides pathway to establish and grow business in Ireland.',
'Innovative business idea with high-potential. €50,000 funding secured. Approved by Evaluation Committee. Business plan showing job creation potential and innovation.',
'€50,000 funding, Innovative idea, Committee approval, Job creation plan',
'4-6 months',
'Application fee €350',
'Detailed business plan, Proof of €50,000 funding, Academic and professional qualifications, CV, Passport, Photos, Market research and financial projections, Letters of support, Proof of innovation (patents, unique offering)',
'4-6 months including committee evaluation.',
'Initially 2 years. Must create jobs and show business progress. Can renew for 3 more years. After 3 years, may apply for permission to remain. Brings economic value. Family can accompany.',
CURRENT_DATE),

('ireland', 'any', 'Family Visa', 'Family', 'Ireland Family Reunification',
'Join family members legally resident in Ireland. Covers spouses, partners, and dependent children. Different rules for EU and non-EU sponsors.',
'Sponsor must have valid permission to remain (Stamp 4, Critical Skills Permit holder, refugee, etc.). Proof of relationship. Adequate accommodation. Sufficient income without public funds.',
'Sponsor permission, Relationship proof, Accommodation, Income',
'6-12 months',
'No fee for application',
'Relationship proof (marriage certificate, birth certificates, civil partnership), Passport and photos, Sponsor''s immigration status proof, Accommodation evidence, Sponsor''s employment and income proof, Medical insurance, Previous relationship evidence if applicable',
'6-12 months processing time. Varies significantly.',
'Initially linked to sponsor status. Some family members get Stamp 3 (no work), others Stamp 1 (work allowed) depending on sponsor type. Critical Skills Permit families get immediate work rights. Long-term residence possible after 5 years.',
CURRENT_DATE),

('ireland', 'any', 'Visitor Visa', 'Visit', 'Ireland Visit Visa (Short Stay)',
'Short-term visit for tourism, business, family visits. Ireland not in Schengen, requires separate visa from EU visas.',
'Genuine visit purpose. Sufficient funds for stay. Accommodation arrangements. Strong ties to home country. Intent to return.',
'Valid purpose, Sufficient funds, Accommodation, Intent to return',
'8 weeks recommended apply time',
'Visa fee €60 single entry, €100 multiple entry',
'Passport (6+ months validity), Completed online application, Photos, Travel itinerary, Accommodation bookings, Financial evidence (bank statements 6 months), Employment/student/business evidence, Invitation letter if visiting family, Travel insurance',
'8 weeks recommended. Can be faster or slower. Apply well in advance.',
'90 days maximum per visit. Single or multiple entry available. Cannot work or study. Cannot switch to other visa types from within Ireland.',
CURRENT_DATE),

-- ITALY PATHWAYS
('italy', 'any', 'Work Visa', 'Work', 'Italy Highly Qualified Worker Visa (EU Blue Card)',
'EU Blue Card for highly qualified workers. Fast-track residence permit with benefits. One of most accessible routes for skilled workers to Italy.',
'University degree (minimum 3 years). Job offer with minimum annual salary (approximately €27,000-30,000, varies yearly). Employment contract at least 1 year. Health insurance.',
'University degree (3+ years), €27,000-30,000+ salary, 1+ year contract, Health insurance',
'90-120 days',
'Visa fee €116, Residence permit €100-200',
'University degree with translations and Diploma Supplement, Job contract (1+ year minimum), Proof of adequate salary, Employer registration documents, Passport (validity beyond stay), Photos, Accommodation proof in Italy, Health insurance coverage, Nulla Osta (work clearance from Italian authorities)',
'90-120 days including Nulla Osta and visa processing.',
'2 years initially. Renewable. Can move within EU after 18 months. Easier family reunification. Path to long-term residence after 5 years. Can change employers freely after initial period.',
CURRENT_DATE),

('italy', 'any', 'Work Visa', 'Work', 'Italy Subordinate Work Visa',
'Standard work visa for employees. Quota system applies annually. Must wait for annual decree opening positions.',
'Job offer within annual quota. Employer submits request during quota window. Relevant qualifications. Fair employment terms per Italian standards.',
'Job within quota, Qualifications, Fair employment terms',
'120-180 days (highly dependent on quota timing)',
'Visa fee €116, Residence permit €100-200',
'Nulla Osta (employer applies during quota), Job contract, Qualifications and experience proof, Passport and photos, Accommodation proof, Health insurance, Employer tax documents and registration',
'120-180 days. Must coordinate with annual quota decree (usually March-April). Long wait times common.',
'Duration of contract (typically 1-2 years initially). Renewable if employment continues. Quota restrictions make renewals complex. After 5 years legal residence, eligible for long-term permit.',
CURRENT_DATE),

('italy', 'any', 'Study Visa', 'Study', 'Italy Student Visa',
'Study at Italian universities and institutions. Italy offers rich academic tradition, art, culture. Affordable tuition. Can work part-time.',
'Admission to Italian university or institution. Financial resources (€448.07/month for 2024). Accommodation arrangements. Health insurance.',
'University admission, €448/month funds (€5,376/year), Accommodation, Insurance',
'30-90 days',
'Visa fee €116',
'University admission letter with enrollment certificate, Financial proof (€5,376/year minimum, bank guarantee or scholarship), Accommodation proof (rental, residence hall), Health insurance coverage, Passport (validity beyond study period), Photos, Academic records with translations, Language certificate (Italian B1-B2 or English per program)',
'30-90 days for visa. Apply at least 90 days before intended start.',
'Duration of study program. Can work part-time (20 hours/week). Must obtain residence permit within 8 days of arrival. After graduation, can convert to job-seeking visa (1 year). Eligible for work visa conversion when employed.',
CURRENT_DATE),

('italy', 'any', 'Digital Nomad Visa', 'Work', 'Italy Self-Employment Visa',
'For entrepreneurs, freelancers, and self-employed professionals. Requires demonstrating economic value to Italy. Must have clients or business plan.',
'Viable business activity in Italy. Sufficient financial resources. Professional qualifications or expertise. Business registration in Italy. Must benefit Italian economy.',
'Business plan, Financial resources, Professional qualifications, Economic benefit',
'90-150 days',
'Visa fee €116, Business registration varies',
'Business plan in Italian, Professional qualifications and CV, Proof of funds (€30,000+ recommended), Client contracts or letters of intent, Passport and photos, Accommodation proof, Health insurance, Police clearance certificate',
'90-150 days for visa and clearances.',
'2 years initially. Must demonstrate ongoing business activity for renewal. After 5 years, eligible for long-term residence. Must register with Italian tax authorities and social security.',
CURRENT_DATE),

('italy', 'any', 'Family Visa', 'Family', 'Italy Family Reunification',
'Reunite with family members in Italy. Clear procedures for spouses, children, parents. Integration requirements apply.',
'Sponsor must have residence permit valid 1+ year. Adequate income (€8,263/year for one person, increases per family member). Adequate housing (minimum space requirements). Health insurance for family members.',
'Sponsor permit (1+ year), €8,263+ income per person, Adequate housing, Health insurance',
'90-180 days',
'Visa fee €116 per person, Integration test fee if applicable',
'Nulla Osta for family reunification (sponsor applies at Sportello Unico), Relationship documents (marriage certificate, birth certificates with apostille and translations), Sponsor residence permit, Income proof (employment contract, pay slips, tax returns), Housing certificate with space requirements, Health insurance for family members, Passport and photos',
'90-180 days including Nulla Osta and visa processing.',
'Initially 2 years. Can work (spouses). Children attend school. Must obtain residence permit within 8 days of arrival. After 5 years, eligible for independent long-term residence. Integration agreement required.',
CURRENT_DATE),

('italy', 'any', 'Visitor Visa', 'Visit', 'Italy Schengen Tourist Visa',
'Short-stay Schengen visa for tourism, business, family visits. Access to Schengen Area.',
'Valid visit purpose. Sufficient funds. Accommodation. Travel insurance. Strong ties to home country.',
'Valid purpose, Sufficient funds, Accommodation, €30,000 insurance, Return plan',
'15-30 days',
'Visa fee €80 (€40 for children 6-12)',
'Passport (3+ months beyond stay, issued within 10 years), Application form and photos, Travel itinerary, Accommodation bookings or invitation letter, Financial means (bank statements 3-6 months, €50-60/day), Travel insurance (€30,000+), Employment/student proof, Return flight reservation',
'15-30 days standard. Apply at least 15 days before travel, maximum 6 months in advance.',
'Up to 90 days within 180-day period. Cannot work. Multiple-entry available. Cannot extend or change status from within Italy on short-stay visa.',
CURRENT_DATE);
