/*
  # Add Full Rich Content - Batch 4a

  Countries covered:
  - Argentina, Austria, Belgium, Brazil, Chile, China, Colombia, Croatia

  Each country gets:
  - Comprehensive intro_md (400-550 chars)
  - 7 detailed FAQs (faq_json)
  - warning_md with practical cautions
  - next_steps_md with actionable guidance
*/

DO $$
DECLARE
  v_id uuid;
BEGIN

  -- ============================================================
  -- ARGENTINA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'argentina';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Argentina has become a top destination for digital nomads and expats seeking low costs in a culturally rich, cosmopolitan environment. Buenos Aires consistently ranks among the world''s best nomad cities. The Rentista and Pensionado residency visas are straightforward and low-cost. Argentina''s peso has experienced ongoing devaluation, meaning hard-currency earners benefit significantly from favorable exchange rates. Cordoba, Mendoza, and Bariloche are popular secondary destinations.',
      '[
        {"question": "What is the Argentina Rentista Visa?", "answer": "The Rentista (Passive Income) Visa grants temporary residency to those receiving regular income from abroad — remote work, investments, rental income, or pensions. There is no officially published minimum income threshold, but most applicants show USD 1,000-1,500/month. Application at an Argentine consulate: fee approximately USD 200-300 depending on nationality. After 1 year of temporary residency, you can apply for permanent residency. Processing takes 2-6 months."},
        {"question": "What is the Argentina Pensionado Visa?", "answer": "The Pensionado Visa is for retirees receiving a regular pension from their home country. Minimum pension income: approximately USD 850/month (equivalent to 3x the Argentine minimum wage — amount fluctuates with peso changes). Application at Argentine consulate. Fee approximately USD 200-300. Valid for 1 year initially, renewable, then permanent residency after 2 years. One of the most affordable formal retiree visa programs globally."},
        {"question": "How does the Argentine peso exchange rate benefit hard-currency earners?", "answer": "Argentina has multiple exchange rates. The official rate, ''blue dollar'' (informal), and MEP/CCL financial rates diverge significantly. As of 2024, those converting USD or EUR at financial rates can receive 3-5x more pesos than the official rate in some periods. This dramatically lowers effective living costs for those earning abroad. Always use legal financial exchange mechanisms (MEP rate through brokerage accounts) and consult a local accountant to stay compliant."},
        {"question": "How much does it cost to live in Buenos Aires?", "answer": "Buenos Aires is one of the world''s most affordable major cities when earning hard currency. A 1-bedroom apartment in Palermo/Recoleta: USD 400-900/month (at financial exchange rate). Restaurant meals: USD 5-15 at financial rate. Total monthly budget for comfortable living: USD 1,000-2,000. These costs shift with exchange rate movements, so budgeting in USD terms is more stable than budgeting in pesos."},
        {"question": "What is the DNI and why is it needed in Argentina?", "answer": "The DNI (Documento Nacional de Identidad) is Argentina''s national identity document, issued to temporary and permanent residents after their residency is approved. Required for: opening a bank account, renting property formally, accessing healthcare, and most official transactions. Apply at RENAPER (National Registry of Persons) or the National Directorate of Migration. Processing takes 2-8 weeks. Without a DNI, even basic administrative tasks require additional documentation."},
        {"question": "What are Argentine income tax obligations for foreign residents?", "answer": "Argentina taxes residents on worldwide income. Tax rates: 5% on ARS 242,570-484,870/year, progressive to 35% above ARS 2,121,867/year (these thresholds update with inflation). The AFIP (tax authority) CUIT/CUIL number is required for all financial activities. Foreign-source income is taxable for Argentine residents. Many digital nomads structure stays to under 183 days to avoid Argentine tax residency. Consult an Argentine contador (accountant) before establishing residency."},
        {"question": "Is Argentina safe for expats?", "answer": "Argentina''s major cities, particularly Buenos Aires'' expat neighborhoods (Palermo, Recoleta, San Telmo, Belgrano), are generally safe for day-to-day life. Petty crime (bag snatching, phone theft) is the main concern rather than violent crime. Express kidnapping reports have increased in some periods; basic precautions (avoiding ostentatious displays of wealth, using private or radio taxis) are recommended. Buenos Aires has a large established expat community with extensive support resources."}
      ]'::jsonb,
      'Argentina''s economic volatility means cost estimates change rapidly. Always research current exchange rates before financial planning. The informal ''blue dollar'' exchange is technically illegal; use legal MEP or CCL financial rates via brokerage accounts instead. Residency visa income thresholds are linked to the Argentine minimum wage and change with peso fluctuations — verify current requirements with the Argentine consulate at time of application. Document apostilles are required for all foreign documents.',
      'Apply for your Argentine residency visa at the Argentine consulate in your home country with all apostilled documents, obtain your CUIL/CUIT number from AFIP upon arrival, apply for DNI at RENAPER promptly after residency approval, open an Argentine bank account (Banco Galicia, Santander Argentina, or Naranja X for digital banking), consult a local contador about legal exchange mechanisms and tax obligations, and join Buenos Aires expat communities for practical local knowledge.'
    );
  END IF;

  -- ============================================================
  -- AUSTRIA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'austria';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Austria is a high-income EU and Schengen member with a strong economy anchored in tourism, finance, pharmaceuticals, and engineering. Vienna consistently ranks as one of the world''s most livable cities. The Red-White-Red Card is Austria''s points-based immigration system for skilled workers and qualified graduates. Austria Immigration Service (AMS) coordinates work permit approvals. High quality of life, excellent public services, and central European location make Austria an attractive destination for professionals.',
      '[
        {"question": "What is the Austrian Red-White-Red Card?", "answer": "The Red-White-Red (RWR) Card is Austria''s points-based work and residence permit. Categories include: Very Highly Qualified Workers (40+ points from criteria like salary, qualifications, language), Skilled Workers in Shortage Occupations (no points — just meet criteria), Other Key Workers (30+ points), and Graduates of Austrian Universities. Application through the Austrian Immigration Authority. Fee EUR 160. Processing 6-10 weeks. Grants 2 years combined work and residence permit."},
        {"question": "How does the RWR Card points system work?", "answer": "Points are awarded for: special qualifications (up to 20), language skills in German or English (up to 15), age (up to 15 points for ages 25-35), work experience (up to 15), research/innovation experience (up to 20), and having a job offer meeting the salary threshold. The salary threshold for Very Highly Qualified Workers is EUR 3,386/month (2024 gross). AMS labour market check required unless the occupation is on the shortage list."},
        {"question": "What is the Austria Rotationsarbeitskraft permit for shortage occupations?", "answer": "Workers in shortage occupations (published on the AMS shortage list: IT, healthcare, engineering, skilled trades) can bypass the full points test. Employer applies to AMS. Key requirements: recognized qualifications, salary at least EUR 2,685/month (2024). Application fee EUR 160. Processed in 6-10 weeks. Shortage occupation permits offer faster processing because no labour market test is required."},
        {"question": "How much does Austria income tax cost?", "answer": "Austrian income tax is progressive: 0% up to EUR 12,816/year, 20% to EUR 20,818, 30% to EUR 34,192, 40% to EUR 66,612, 48% to EUR 99,266, 50% to EUR 1,000,000, 55% above. Social security contributions (employee): approximately 18% of gross salary. The total effective tax burden on EUR 60,000/year: approximately 35-40%. Austria has excellent public healthcare, unemployment insurance, and social services funded by these contributions."},
        {"question": "How long until Austrian permanent residence (Daueraufenthalt-EU)?", "answer": "Permanent residence (Daueraufenthalt-EU permit) is available after 5 years of continuous legal residence. Requirements: stable income, basic German proficiency (A2 at minimum, B1 preferred), health insurance, and no criminal record. Application fee EUR 160. EU Long-Term Resident Permit grants rights to live and work in any EU member state. Austrian citizenship requires 10 years of legal residence (6 years with exceptional integration proof)."},
        {"question": "Is German language required for Austrian work permits?", "answer": "German is not required for the RWR Card application itself, but earns significant points in the points system (up to 15 points). For permanent residence (Niederlassungsnachweis), A2 German is required. Austrian citizenship requires B1. German is essential for daily life outside Vienna''s English-speaking professional environments. The Integration Agreement requires language and values courses for most permit holders, completable within 2 years."},
        {"question": "What is the Vienna registration (Meldezettel) requirement?", "answer": "All persons residing in Austria must register at the local registration authority (Meldeamt or magistrate) within 3 days of establishing a residence. The Meldezettel (registration confirmation) is required for almost everything: bank accounts, employer registration, health insurance, and utilities. Deregistration is required when leaving. Non-compliance is a minor offense but can complicate other administrative procedures. Registration is free and takes about 15 minutes."}
      ]'::jsonb,
      'Austria''s Integration Agreement requires completion of German language (A2) and values courses within 2 years of receiving your permit — failure can result in a fine. AMS labour market tests can add months to processing time for non-shortage occupations. Vienna''s housing market is competitive; secure accommodation before arrival if possible. All foreign documents need apostilles and certified German translation. The shortage occupation list is updated regularly; verify current status before applying.',
      'Check whether your occupation is on the current AMS shortage list to bypass the labour market test, submit your RWR Card application through the Austrian Immigration Authority with all apostilled and translated documents, complete the Meldezettel registration within 3 days of establishing your address, enroll in the Integration Agreement German language course immediately, register with the Sozialversicherung (social security) through your employer, and open an Austrian bank account (Erste Bank, Raiffeisen, or Bank Austria are common).'
    );
  END IF;

  -- ============================================================
  -- BELGIUM
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'belgium';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Belgium is an EU and Schengen member and home to EU and NATO headquarters, making Brussels a major hub for diplomats, lobbyists, lawyers, and international organization staff. The Single Permit combines work and residence authorization for non-EU nationals. Belgium has a complex federal structure with three regions (Brussels, Flanders, Wallonia), each handling some immigration administration. High taxes are offset by excellent public services, social security, and central European location.',
      '[
        {"question": "What is the Belgian Single Permit?", "answer": "The Single Permit (Enige Vergunning) combines work authorization and residence permit for non-EU nationals employed by Belgian companies. The employer applies to the regional employment authority (Actiris in Brussels, VDAB in Flanders, FOREM in Wallonia). Once approved, the employee applies for a work visa at the Belgian consulate. Fee approximately EUR 215. Processing 2-4 months. Valid for the duration of the employment contract, up to 3 years."},
        {"question": "What are Belgian income tax rates?", "answer": "Belgium has some of the highest income tax rates in Europe. Progressive rates: 25% up to EUR 15,820, 40% to EUR 27,920, 45% to EUR 48,320, 50% above. Social security contributions (employee): approximately 13.07% of gross salary. Total effective tax on EUR 60,000/year: approximately 45-50%. However, senior expats may benefit from the Special Tax Regime (STR) for expats, which reduces taxable income significantly — worth investigating upon arrival."},
        {"question": "What is the Belgian Special Tax Regime (STR) for expats?", "answer": "The STR is available to qualifying foreign executives and specialists recruited from abroad. It allows 30% of gross salary to be treated as tax-free expenses (up to EUR 90,000/year cap introduced in 2022). Significant deductions for housing, schooling, and home travel are also available. Application within 3 months of starting work. Requires employer sponsorship and earning above a minimum threshold. Reduces the effective tax burden substantially compared to standard Belgian taxation."},
        {"question": "What is the EU Blue Card in Belgium?", "answer": "Belgium issues EU Blue Cards for highly qualified non-EU nationals earning at least EUR 61,011/year (2024) with a recognized degree. Application through the relevant regional employment office. Fee approximately EUR 215. Valid 3 years. Blue Card holders have enhanced labor mobility within Belgium and, after 18 months, can transfer to another EU member state on a Blue Card. Faster access to permanent residence after 5 years of EU legal residence."},
        {"question": "How does the Belgian commune registration work?", "answer": "All residents (including expats) must register at their local commune (municipality) within 8 days of establishing a Belgian address. The commune sends a police officer to verify your residence, then issues a Foreigners'' Annex (Bijlage 26/Annexe 26) while your e-ID card is processed (4-6 weeks). Your e-ID (electronic identity card) is your primary identification document. Commune registration is required before opening bank accounts, healthcare registration, and most administrative tasks."},
        {"question": "How long until Belgian permanent residence?", "answer": "Non-EU nationals can apply for unlimited stay (permanent residence) after 5 years of continuous legal residence. Requirements: stable employment or income, health insurance, no criminal record, integration requirements (civic integration course in Flanders; similar in other regions). Application at your commune. Belgian citizenship requires 5 years of legal residence plus passing a civic integration test and demonstrating social integration. Belgium allows dual citizenship."},
        {"question": "What is Belgium''s healthcare system for expats?", "answer": "Belgium has a compulsory health insurance system (RIZIV/INAMI). Employed workers are automatically enrolled through their employer contributions (approximately 8.86% employer, 3.55% employee). Non-employed residents must register with a mutualist (health insurance fund: CM/MC, Solidaris, etc.) and pay quarterly contributions. Coverage is comprehensive: 75-100% reimbursement for most medical costs. Private supplemental insurance (hospitalization insurance from EUR 15-30/month) is recommended for full coverage."}
      ]'::jsonb,
      'Belgium''s three-region administrative structure means different rules apply in Brussels, Flanders, and Wallonia — confirm which authority handles your application based on where your employer is located. The Special Tax Regime application window is strictly 3 months from starting work; missing this deadline means losing the benefit for that year. Commune registration police visit must show you genuinely living at the address. Belgian bureaucracy is complex; an immigration lawyer or relocation service is strongly recommended.',
      'Have your employer apply for the Single Permit through the relevant regional employment office before you apply for your work visa, apply for the STR within 3 months of starting work if you qualify, register at your commune within 8 days of arriving at your Belgian address, register with a mutualist for health insurance, obtain your Belgian National Register Number (NISS/INSZ) from the commune, and open a Belgian bank account (BNP Paribas Fortis, KBC, or ING Belgium are major retail banks).'
    );
  END IF;

  -- ============================================================
  -- BRAZIL
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'brazil';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Brazil is South America''s largest economy and a destination for professionals in energy, agriculture, mining, finance, and technology. Sao Paulo is the primary business hub; Rio de Janeiro, Florianopolis, and Recife attract digital nomads. The SINCRE system managed by the Federal Police handles residence permits. Brazil introduced a Digital Nomad Visa in 2022. Cost of living varies widely by city; Sao Paulo is expensive by regional standards, while northeastern cities and Florianopolis offer more affordable alternatives.',
      '[
        {"question": "What is the Brazil Digital Nomad Visa?", "answer": "Brazil launched its Digital Nomad Visa (VITEM XIV) in 2022. Requirements: minimum income of USD 1,500/month or USD 18,000 in a bank account, employment with a company or clients outside Brazil, valid health insurance covering Brazil. Visa fee approximately BRL 200-400 at the consulate or USD 100-200 equivalent. Valid 1 year, extendable to 2 years. Application at Brazilian consulate abroad or within Brazil through the Federal Police."},
        {"question": "What are Brazil''s work authorization categories?", "answer": "Brazil''s main work authorization is the CTPS (work card) for formal employees. Foreign nationals need a temporary work visa (VITEM V) requiring employer sponsorship from an MDRJ-registered Brazilian employer. Quota rules limit foreign employees to 1/3 of a company''s workforce. Application via Ministry of Justice/Federal Police. Intracompany transfers are common for multinationals. Processing takes 2-4 months. Salary must meet industry standards."},
        {"question": "What is the CPF and why is it essential in Brazil?", "answer": "The CPF (Cadastro de Pessoas Fisicas) is Brazil''s individual taxpayer registration number. Required for: opening a bank account, signing leases, purchasing property, accessing healthcare, filing taxes, and virtually all official transactions. Foreign residents apply at the Federal Revenue Service (Receita Federal), Brazilian consulates abroad, or the Post Office (Correios) in Brazil. Fee is nominal. Processing takes 1-7 days. Without CPF, basic life in Brazil is extremely difficult."},
        {"question": "How much does it cost to live in Sao Paulo vs Florianopolis?", "answer": "Sao Paulo: 1-bedroom apartment in Jardins/Vila Madalena: BRL 3,500-6,000/month (USD 680-1,165). Total monthly budget: USD 1,500-2,500. Florianopolis: increasingly popular with nomads; 1-bedroom: BRL 2,500-4,500/month. Rio de Janeiro: Ipanema/Leblon: BRL 3,000-5,500/month. Northeastern cities (Recife, Fortaleza): significantly cheaper. São Paulo salaries are higher but costs are proportionally higher too."},
        {"question": "What are Brazilian income tax rates?", "answer": "Brazilian income tax (IRPF): 0% up to BRL 2,824/month, 7.5% to BRL 3,751, 15% to BRL 4,664, 22.5% to BRL 6,101, 27.5% above. INSS (social security): 7.5-14% employee contribution. Foreign residents (183+ days/year) are taxed on Brazilian-source income. Those who become Brazilian tax residents are taxed on worldwide income. CPF registration triggers tax residency monitoring. Annual tax return (DIRPF) is mandatory for residents earning above the threshold."},
        {"question": "What is Brazil''s CRNM (National Registration of Migrants)?", "answer": "The CRNM (Carteira de Registro Nacional Migratório) is the official residence document for all foreign residents in Brazil. Issued by the Federal Police after approved residency application. Required for: employment, opening formal bank accounts, accessing public services. Application at the Federal Police delegacy in your city with valid visa, passport, CPF, and proof of address. Fee approximately BRL 200-300. Processing takes 2-8 weeks. Must be renewed before expiry."},
        {"question": "Can I get Brazilian permanent residence and citizenship?", "answer": "Brazilian permanent residence can be obtained after 1-4 years depending on the pathway (digital nomad visa holders after 2 years, those married to Brazilians immediately, investors after qualifying period). Brazilian citizenship is available after 1 year of permanent residence with continuous legal residence (or 15 years total legal residence for standard path). Brazil allows dual citizenship. Brazilian passport provides visa-free access to 170+ countries including the EU Schengen area."}
      ]'::jsonb,
      'Brazil''s bureaucracy is complex; engaging a local immigration lawyer (advogado de imigração) and accountant (contador) is strongly recommended. Portuguese language, while not required for some visas, is essential for daily life, banking, and government interactions outside major expat areas. The digital nomad visa was recently introduced and processes may still be refined at consulates. Health insurance covering Brazil is mandatory for the digital nomad visa and should be verified before application.',
      'Get your CPF before any other financial or administrative step in Brazil, apply for your CRNM at the Federal Police delegacy within the required timeframe after arrival, engage a Brazilian immigration lawyer for work permit or residency applications, open a Brazilian bank account (Itaú, Bradesco, Nubank, or Inter are popular), register with the Receita Federal for tax obligations if earning Brazilian-source income, and learn basic Portuguese as early as possible to navigate daily life and government offices.'
    );
  END IF;

  -- ============================================================
  -- CHILE
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'chile';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Chile is South America''s most stable and developed economy, ranking highly for business environment, rule of law, and infrastructure. Santiago is a modern, cosmopolitan capital with a strong tech and startup ecosystem. Chile reformed its immigration law in 2021, introducing clearer visa categories. The Temporary Residence Visa covers workers, retirees, and digital nomads. Cost of living is higher than regional neighbors but lower than North America or Western Europe.',
      '[
        {"question": "What are Chile''s main immigration visa categories?", "answer": "Under the 2021 immigration law, Chile offers: Temporary Residence Visa (categories include worker, rentista/investor, student, and special); Permanent Residence (after 2 years of continuous temporary residence). The Temporary Visa is valid 1-2 years, renewable. Government fee approximately USD 50-100 at the consulate. Chile does not have a dedicated digital nomad visa; remote workers typically apply under the Rentista (passive income) category."},
        {"question": "How do digital nomads and remote workers get Chilean residency?", "answer": "Remote workers apply for a Temporary Residence Visa under the Rentista category, showing regular foreign-source income. Suggested income: CLP 1,500,000-2,500,000/month (approximately USD 1,700-2,800). Application can be made at Chilean consulate abroad or within Chile. Within Chile: apply at the Extranjería office (now Servicio Nacional de Migraciones — SERMIG). Processing 2-4 months. This is the most practical long-stay route for remote workers."},
        {"question": "How much does it cost to live in Santiago?", "answer": "Santiago is comparable to smaller European cities in cost. 1-bedroom apartment in Providencia/Las Condes/Vitacura: CLP 700,000-1,200,000/month (USD 800-1,350). Monthly food and transport: USD 400-600. Total monthly budget for comfortable living: USD 1,500-2,500. Valparaíso (120km from Santiago) is significantly cheaper and increasingly popular with artists and nomads. Chile''s wine regions (Mendoza area access from Santiago) add lifestyle value."},
        {"question": "What is the RUT and why is it needed in Chile?", "answer": "The RUT (Rol Único Tributario) is Chile''s universal tax and identity number, equivalent to a national ID number. Required for: opening a bank account, signing a lease, mobile phone contracts, and any formal financial transactions. Residents apply at the SII (Internal Revenue Service) or at a civil registry (Registro Civil). Temporary residents get a RUT automatically when their visa is approved. Without a RUT, basic financial life in Chile is impossible."},
        {"question": "What is Chile''s Permanent Residence pathway?", "answer": "Permanent residence (Permanencia Definitiva) is available after 2 years of continuous temporary residence. Application fee approximately USD 200. Requirements: maintained legal status throughout, no serious criminal record, and intent to remain in Chile. Processing takes 3-6 months. Permanent residents can work for any employer without restriction. Chilean citizenship requires 5 years of continuous legal residence (permanent or temporary), B1 Spanish, and good standing."},
        {"question": "What are Chilean income tax rates?", "answer": "Chilean income tax (Impuesto Único de Segunda Categoría) is progressive: 0% up to CLP 820,833/month, 4% to CLP 1,093,111, 8% to CLP 1,821,851, 13.5% to CLP 2,550,590, 23% to CLP 3,279,329, 30% to CLP 4,463,183, 35% above. Social security contributions for employees: approximately 11.44% of salary for pension (AFP) and 7% for health insurance (ISAPRE or Fonasa). Total effective burden for a CLP 3,000,000/month salary: approximately 25-30%."},
        {"question": "Is Chile safe and stable for expats?", "answer": "Chile is consistently ranked among Latin America''s safest and most politically stable countries. Santiago has similar safety levels to medium-sized European cities: petty crime in tourist areas is the main concern. The 2019-2020 social unrest has largely subsided. Natural disasters (earthquakes, volcanic activity) are a real consideration; Chile has excellent early warning systems and building codes. The Atacama, Patagonia, and wine regions make Chile exceptionally attractive for outdoor-oriented expats."}
      ]'::jsonb,
      'Chile''s SERMIG (immigration service) underwent a full system overhaul in 2021; some processes are still being refined. Processing times for residency applications can exceed stated timelines. All foreign documents must be apostilled and officially translated into Spanish by a certified translator. Income thresholds for the Rentista visa are not officially published and are assessed case by case; prepare robust financial documentation. Santiago''s air quality (smog in winter) can be a concern for those with respiratory conditions.',
      'Apply for your Temporary Residence Visa with comprehensive financial documentation at a Chilean consulate or SERMIG office, obtain your RUT from SII or Registro Civil immediately upon residency approval, open a Chilean bank account (BancoEstado is accessible for residents; Banco de Chile and Santander Chile also popular), register with SII for tax obligations, enroll in Chilean health insurance (ISAPRE for private, Fonasa for public), and track your 2-year permanent residence clock from your first temporary residence approval date.'
    );
  END IF;

  -- ============================================================
  -- CHINA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'china';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'China is the world''s second-largest economy and a major destination for multinational professionals, educators, and entrepreneurs. Shanghai, Beijing, Shenzhen, and Guangzhou are the main expat hubs. The Z (work) visa and Residence Permit for Work (RSDL) are the primary pathways. China''s "Green Card" (Permanent Residence Permit) is extremely difficult to obtain. Internet restrictions (the Great Firewall) affect daily digital life. Post-COVID, China has re-opened for foreign workers and is rebuilding its expat community.',
      '[
        {"question": "What is the China Z Visa (Work Visa)?", "answer": "The Z Visa is the entry visa for foreign nationals taking up employment in China. Required before entering China (cannot be converted from a tourist visa). Employer must obtain a work permit notification letter first. Z Visa is issued at Chinese embassies: fee varies by nationality (USD 30-140). After arrival, within 30 days, convert to a Residence Permit for Work at the Exit and Entry Administration Bureau (EEA). Failure to convert is a serious violation."},
        {"question": "How does the China Work Permit application process work?", "answer": "Step 1: Employer applies for Work Permit Notification Letter from the local human resources department (takes 5-15 business days). Step 2: Employee applies for Z Visa at Chinese embassy with the notification letter + employment contract + degree + health certificate + police clearance. Step 3: After arrival, apply for Residence Permit for Work at EEA within 30 days. Total processing: 4-8 weeks. The employer handles most of Step 1; an immigration service handles Steps 2-3."},
        {"question": "What salary and qualifications are required for a China work permit?", "answer": "China''s work permit system categorizes foreign workers into Class A (high-end talent), Class B (professional), and Class C (other). Class B (most common) requires: relevant university degree, 2+ years of related work experience, no criminal record, annual salary typically USD 30,000-50,000+. Class A (scientists, top executives) face fewer restrictions and get faster processing. Requirements are assessed by the local human resources department and vary by city and industry."},
        {"question": "What is the China Permanent Residence Permit (''Green Card'')?", "answer": "China''s Permanent Residence Permit (Foreign Permanent Residence ID) is extremely difficult to obtain. Criteria include: investing USD 500,000+ in encouraged sectors for 3+ years, holding a senior position for 4+ consecutive years and earning 6x the average local salary, special contributions to China (scientists, Olympic medalists, etc.), or being a spouse/parent of a Chinese citizen for 5+ years of residence. Approximately 10,000 cards issued annually across all categories combined."},
        {"question": "How does China''s internet restriction (Great Firewall) affect daily life?", "answer": "China blocks major Western platforms: Google, Facebook, Instagram, YouTube, WhatsApp, Twitter/X, most news sites, and many VPN protocols. Chinese alternatives exist (WeChat, Baidu, Bilibili, Weibo) and are widely used. Most expats use a commercial VPN for personal use — technically against regulations but widely tolerated for personal use. Business VPNs for corporate networks are common and accepted. This is an important quality-of-life factor to research and prepare for before relocating."},
        {"question": "What are Chinese income tax rates for foreign workers?", "answer": "China''s individual income tax rates are progressive: 3% on CNY 0-36,000/year, 10% to CNY 144,000, 20% to CNY 300,000, 25% to CNY 420,000, 30% to CNY 660,000, 35% to CNY 960,000, 45% above. Foreigners who are tax residents (183+ days/year) are taxed on worldwide income. The ''foreigner tax concession'' (lump deductions) was partially phased out in 2022. Tax equalization packages from multinational employers are common."},
        {"question": "What is the Foreigner''s Residence Permit and how does it differ from a visa?", "answer": "The Residence Permit is the document you live on in China after converting your Z visa — it is stamped in your passport and is the actual authorization to work and reside. It must be renewed annually (or for the duration of your employment contract, up to 5 years for senior executives). Renewal requires updated employment contract and employer filing. The EEA processes renewals in major cities; appointments are required. Residence Permit holders can exit and re-enter China without a separate visa."}
      ]'::jsonb,
      'China requires a Z Visa before entry — you cannot convert a tourist visa to a work visa inside China. All foreign documents (degrees, police clearances) must be notarized and authenticated through Chinese embassy legalization (not just apostilled, as China is not an Apostille Convention member). Internet restrictions significantly affect daily digital life; set up your VPN solution before arrival. Political and regulatory environment can change; monitor your employer''s compliance guidance and maintain copies of all immigration documents.',
      'Have your employer obtain the Work Permit Notification Letter before you apply for your Z Visa, get all documents notarized and Chinese-embassy authenticated (not apostilled), register with local police within 24 hours of arrival if not staying in a hotel (hotels do this automatically), convert your Z Visa to a Residence Permit at the EEA within 30 days of arrival, set up WeChat (essential for daily life, payments, and communication in China), and register with your national embassy for emergency contact purposes.'
    );
  END IF;

  -- ============================================================
  -- COLOMBIA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'colombia';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Colombia has transformed its international image and emerged as a top destination for digital nomads, retirees, and entrepreneurs. Medellin, Bogota, Cartagena, and Santa Marta are major expat hubs. Medellin in particular has become one of the world''s most popular nomad cities, celebrated for its spring-like climate, modern infrastructure, and affordable cost of living. Migración Colombia introduced a Digital Nomad Visa (DNV) in 2022. Cost of living is very affordable for hard-currency earners.',
      '[
        {"question": "What is the Colombia Digital Nomad Visa (DNV)?", "answer": "Colombia''s M Visitor Digital Nomad subcategory allows remote workers to live in Colombia for up to 2 years. Requirements: demonstrate employment with a company outside Colombia or clients abroad, income of at least 3x the Colombian minimum wage (approximately COP 3,900,000/month or USD 985/month as of 2024). Application fee approximately USD 50-60. Apply online through the Migración Colombia website or at their offices. A highly accessible and affordable digital nomad visa."},
        {"question": "What is the Colombia V Investor Migrant Visa?", "answer": "The V Migrant Investor Visa is for those investing a minimum of 100 SMMLV (approximately USD 27,000 in 2024) in Colombian real estate, a Colombian company, or a Colombian financial product. Valid up to 3 years. Application fee approximately USD 50-60. After 5 years on investor or other qualifying visas, permanent residency (Residente) can be applied for. Colombia''s real estate market in Medellin and Bogota has been popular with foreign investors."},
        {"question": "How much does it cost to live in Medellin vs Bogota?", "answer": "Medellin: 1-bedroom apartment in El Poblado/Laureles: COP 1,500,000-3,000,000/month (USD 380-760). Total monthly budget: USD 1,000-1,800. Bogota (Chapinero/Zona Rosa): 1-bedroom COP 1,800,000-3,500,000/month (USD 455-885). Cartagena (historic center) is slightly more expensive due to tourist demand. All Colombian cities offer extremely good value for hard-currency earners. Healthcare costs are also very low."},
        {"question": "What is the Colombian Cedula de Extranjeria?", "answer": "The Cédula de Extranjería is the official identity document for foreign residents holding a Migrant or Resident visa. Applied for at Migración Colombia offices after visa approval. Fee approximately COP 80,000-160,000 (USD 20-40). Required for: opening a Colombian bank account, signing formal leases, accessing healthcare through EPS, and most official transactions. Must be renewed when the underlying visa is renewed. The cédula is not issued for Visitor visas including the Digital Nomad subcategory."},
        {"question": "Can digital nomad visa holders open a Colombian bank account?", "answer": "Opening a traditional Colombian bank account typically requires a Cédula de Extranjería (not issued for Visitor/DNV category). However, digital-first banks and neobanks (Nequi, Daviplata) can be opened with a passport and valid visa. Some foreign residents use these for everyday transactions. For a full bank account with Bancolombia, Davivienda, or BBVA Colombia, upgrading to a Migrant visa that grants a cédula is generally required."},
        {"question": "What are Colombian income tax rules for expats?", "answer": "Colombia taxes residents (183+ days/year in a 365-day period) on worldwide income at rates: 0% up to COP 51,330,000/year, 19% to COP 154,000,000, 28% to COP 360,000,000, 33% to COP 640,000,000, 35% to COP 1,000,000,000, 39% above. Non-residents are taxed only on Colombian-source income at 35%. Digital nomads earning exclusively from abroad and staying under 183 days technically do not trigger Colombian tax residency. Consult a Colombian accountant for specific situations."},
        {"question": "Is Colombia safe for expats?", "answer": "Colombia''s safety has improved dramatically over the past 20 years. Medellin''s El Poblado, Laureles, and Envigado neighborhoods are considered very safe by Latin American standards. Bogota''s Chapinero, Zona Rosa, and Usaquén are safe expat areas. Cartagena''s historic center is safe for tourists and residents. Street crime (phone theft, bag snatching) remains the primary risk. Avoid poorly lit areas at night, use Uber or InDriver rather than street taxis, and follow local expat community advice."}
      ]'::jsonb,
      'Colombia''s Digital Nomad Visa does not issue a Cédula de Extranjería, which limits access to formal banking and some services. Staying over 183 days in a calendar year triggers Colombian tax residency obligations. Colombia''s public safety situation varies significantly by neighborhood — research your specific area thoroughly before committing. All foreign documents must be apostilled and officially translated into Spanish. Verify current income thresholds at the time of application as they are linked to the Colombian minimum wage, which changes annually.',
      'Apply for the DNV through the Migración Colombia online portal with proof of foreign income and health insurance, open a Nequi or Daviplata account for day-to-day transactions while on Visitor visa, consider upgrading to Migrant Investor or Worker visa if planning to stay long-term and needing formal banking, get an apostilled police clearance and health insurance before applying, track your days in Colombia carefully to manage tax residency implications, and join local expat communities in Medellin or Bogota for practical insights.'
    );
  END IF;

  -- ============================================================
  -- CROATIA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'croatia';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Croatia joined the EU in 2013 and the Schengen Area in January 2023, significantly increasing its appeal for non-EU nationals seeking EU residency. Croatia was one of the first countries globally to introduce a dedicated Digital Nomad Visa in 2021. Split, Dubrovnik, Zagreb, and Zadar attract digital nomads and retirees. Cost of living is lower than Western Europe, though coastal areas have risen in price due to tourism and nomad demand. Croatia offers a path to EU citizenship.',
      '[
        {"question": "What is the Croatia Digital Nomad Visa?", "answer": "Croatia''s Digital Nomad Residence Permit allows remote workers to stay for up to 1 year (non-renewable consecutively — must leave Croatia for a period before reapplying). Income requirement: approximately EUR 2,539/month (2024, set at 2.5x Croatian minimum wage). Permit income is exempt from Croatian income tax. Application at Croatian police (MUP) offices or consulates abroad. Fee approximately EUR 70-150. One of Europe''s earliest and most established digital nomad permits."},
        {"question": "What are the tax implications of Croatia''s Digital Nomad Permit?", "answer": "Income earned by digital nomad permit holders from foreign sources is EXEMPT from Croatian income tax. This is explicitly written into Croatian law, making it one of the most clear and favorable digital nomad tax arrangements in Europe. Permit holders must not work for Croatian clients or employers. Health insurance covering Croatia is required. Standard Croatian income tax (15-30%) applies only if you are a standard Croatian tax resident working for Croatian entities."},
        {"question": "How does EU residency through Croatia work?", "answer": "Non-EU nationals who obtain Croatian long-term residence (after 5 years of continuous temporary residence) receive an EU Long-Term Residence Permit, which grants the right to live and work in any EU member state. Croatia became a Schengen member in January 2023, meaning Croatian residents can travel freely within the Schengen zone. Croatian citizenship can be applied for after 8 years of legal residence (5 years for those married to Croatian citizens)."},
        {"question": "What is the Croatia work permit for regular employment?", "answer": "Non-EU nationals employed by Croatian companies need a work and residence permit (Dozvola za boravak i rad). Employer applies to the Croatian Employment Service (HZZ). Requirements: recognized qualifications, salary meeting sector standards, and an advertised position showing no suitable local candidate. Fee approximately EUR 65-70. Processing 6-12 weeks. Croatia, as an EU member, requires employers to verify EU citizens were unavailable before sponsoring non-EU workers."},
        {"question": "How affordable is Croatia for expats?", "answer": "Split 1-bedroom apartment: EUR 700-1,200/month (higher in peak summer seasons). Zagreb 1-bedroom: EUR 500-900/month. Dubrovnik is more expensive due to tourism demand: EUR 800-1,400/month. Monthly grocery and living expenses: EUR 400-700. Total monthly budget for comfortable living: EUR 1,200-2,200 depending on city. Coastal areas are summer-expensive and winter-affordable. Zagreb offers the best year-round value with the strongest job market."},
        {"question": "What is the OIB number in Croatia?", "answer": "The OIB (Osobni Identifikacijski Broj) is Croatia''s personal identification number. Assigned automatically when you register your residence. Required for: opening a Croatian bank account, signing contracts, accessing healthcare through the Croatian Health Insurance Fund (HZZO), and all official transactions. EU citizens can obtain OIB by registering at the Porezna uprava (Tax Administration). Non-EU residents receive their OIB when their temporary residence permit is approved."},
        {"question": "What healthcare options are available for Croatia digital nomads?", "answer": "Digital nomad permit holders must have valid private health insurance covering Croatia (minimum EUR 30,000 coverage). This cannot be Croatian public HZZO insurance (which requires employment or long-term residence). International health insurance plans that include Croatia typically cost EUR 80-200/month depending on age and coverage. For standard long-term residents and workers, HZZO (public health insurance) is compulsory and covers comprehensive healthcare including specialists and hospital care."}
      ]'::jsonb,
      'Croatia''s Digital Nomad Permit cannot be consecutively renewed — you must leave Croatia for a period before reapplying. Croatian administrative processes, particularly for residence permits at MUP offices, can involve long queues and multiple visits. Coastal property rental prices increase significantly in summer; consider this for budget planning. All foreign documents need apostilles; Croatia accepts the Apostille Convention. Croatian becoming a Schengen member in 2023 means your Croatian residence permit allows travel throughout the Schengen zone.',
      'Apply for the Digital Nomad Permit at the Croatian MUP (police) office in the city where you intend to reside with health insurance documentation and proof of foreign income, obtain your OIB from the Tax Administration, open a Croatian bank account (Erste Bank, Privredna banka Zagreb, or ZABA are major retail banks), register with HZZO if transitioning to standard employment, track the 1-year permit duration carefully to plan your next steps, and research Schengen travel implications of your Croatian residence status.'
    );
  END IF;

END $$;
