/*
  # Add Missing Pathways - Batch 3

  Adds missing goal pathways for:
  Maldives, Malta, Mongolia, Myanmar, Nepal, Oman, Pakistan, Panama,
  Paraguay, Serbia, Slovakia, Slovenia, Sri Lanka, Tanzania, Tunisia,
  Uruguay, Uzbekistan, Zimbabwe
*/

INSERT INTO immigration_pathways (passport_slug, destination_slug, goal, pathway_name, summary, eligibility, key_requirements, typical_timeline, estimated_fees, pathway_type, requirements, processing_time, validity_period, official_url, last_updated)
VALUES

-- MALDIVES missing goals
('any','maldives','Study','Maldives Student Visa','Study at Maldivian institutions or international universities in the Maldives.','International students accepted to Maldivian educational institutions.','Valid passport; school acceptance letter; proof of finances; health insurance.','2-4 weeks','USD 50-150','study','School acceptance letter, proof of finances, health insurance, valid passport.','2-4 weeks','Duration of study','https://www.immigration.gov.mv','2025-01-01'),
('any','maldives','Family','Maldives Family Residence Visa','Join a family member residing legally in the Maldives.','Spouses and children of Maldivian residents.','Valid passport; proof of family relationship; sponsor documents; financial support.','2-4 weeks','USD 50-200','family','Proof of family relationship, sponsor documents, financial support.','2-4 weeks','1 year, renewable','https://www.immigration.gov.mv','2025-01-01'),
('any','maldives','Retirement','Maldives Retirement Residence','Retire in the Maldives on a long-stay residence visa.','Retirees with sufficient foreign income and property or business investment.','Valid passport; proof of income or investment; health insurance; clean criminal record.','4-8 weeks','USD 200-500','retirement','Proof of income or investment, health insurance, clean criminal record.','4-8 weeks','1 year, renewable','https://www.immigration.gov.mv','2025-01-01'),
('any','maldives','Digital Nomad','Maldives Digital Nomad Visa','Work remotely from one of the world most beautiful island destinations.','Remote workers employed by non-Maldivian companies.','Valid passport; proof of remote employment; income ($3,000+/month); health insurance.','2-4 weeks','USD 300-500','digital_nomad','Proof of remote employment, income ($3,000+/month), health insurance.','2-4 weeks','1 year','https://www.immigration.gov.mv','2025-01-01'),

-- MALTA missing goals
('any','malta','Study','Malta Student Visa (D)','Study at the University of Malta or private institutions.','International students accepted to Maltese higher education.','Valid passport; university acceptance; proof of finances (EUR 420+/month); health insurance.','4-8 weeks','EUR 50-200','study','University acceptance, proof of finances (EUR 420+/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.identitymalta.com','2025-01-01'),
('any','malta','Family','Malta Family Reunification','Join a legally residing family member in Malta.','Spouses and children of Maltese residents (non-EU).','Valid passport; proof of family relationship; sponsor income (EUR 1,200+/month); accommodation; health insurance.','2-3 months','EUR 100-300','family','Proof of family relationship, sponsor income (EUR 1,200+/month), accommodation, health insurance.','2-3 months','1 year, renewable','https://www.identitymalta.com','2025-01-01'),
('any','malta','Retirement','Malta Retirement Programme','Retire in Malta with the Malta Retirement Programme (MRP).','Retirees receiving a pension of at least EUR 2,500/month.','Valid passport; proof of pension (EUR 2,500+/month); Maltese property (rent EUR 10,000+/year or buy EUR 275,000+); health insurance.','3-6 months','EUR 6,000 application fee','retirement','Proof of pension (EUR 2,500+/month), Maltese property, health insurance.','3-6 months','Permanent (annual compliance check)','https://www.identitymalta.com','2025-01-01'),

-- MONGOLIA missing goals
('any','mongolia','Study','Mongolia Student Visa','Study at Mongolian universities including the National University of Mongolia.','International students accepted to Mongolian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','2-4 weeks','MNT 50,000-200,000 (~$15-60)','study','University acceptance, proof of finances, health insurance, valid passport.','2-4 weeks','1 year, renewable','https://www.immigration.gov.mn','2025-01-01'),
('any','mongolia','Family','Mongolia Family Visa','Join a legally residing family member in Mongolia.','Spouses and children of Mongolian residents.','Valid passport; family relationship proof; sponsor documents; financial support.','2-4 weeks','MNT 50,000-200,000 (~$15-60)','family','Family relationship proof, sponsor documents, financial support.','2-4 weeks','1 year, renewable','https://www.immigration.gov.mn','2025-01-01'),
('any','mongolia','Retirement','Mongolia Retirement Long-Stay Visa','Retire in Mongolia, an off-the-beaten-path destination.','Retirees with sufficient pension income.','Valid passport; proof of pension; health insurance; accommodation proof.','2-4 weeks','MNT 100,000-300,000 (~$30-90)','retirement','Proof of pension, health insurance, accommodation proof.','2-4 weeks','1 year, renewable','https://www.immigration.gov.mn','2025-01-01'),
('any','mongolia','Digital Nomad','Mongolia Digital Nomad Long Stay','Work remotely from Ulaanbaatar.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','2-3 weeks','MNT 100,000-300,000 (~$30-90)','digital_nomad','Proof of remote employment, income documentation, health insurance.','2-3 weeks','1 year','https://www.immigration.gov.mn','2025-01-01'),

-- MYANMAR missing goals
('any','myanmar','Study','Myanmar Student Visa','Study at Myanmar universities.','International students accepted to Myanmar higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','USD 50-200','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.mip.gov.mm','2025-01-01'),
('any','myanmar','Family','Myanmar Family Visa','Join a legally residing family member in Myanmar.','Spouses and children of Myanmar residents.','Valid passport; family relationship proof; sponsor documents; financial support.','3-6 weeks','USD 50-200','family','Family relationship proof, sponsor documents, financial support.','3-6 weeks','1 year, renewable','https://www.mip.gov.mm','2025-01-01'),
('any','myanmar','Retirement','Myanmar Retirement Visa','Retire in Myanmar on a retirement visa.','Retirees 60+ with sufficient passive income.','Valid passport; proof of pension ($1,000+/month); health insurance; clean criminal record.','4-8 weeks','USD 100-300','retirement','Proof of pension ($1,000+/month), health insurance, clean criminal record.','4-8 weeks','1 year, renewable','https://www.mip.gov.mm','2025-01-01'),
('any','myanmar','Digital Nomad','Myanmar Digital Nomad Long Stay','Work remotely from Myanmar on a long-stay visa.','Remote workers with foreign employment.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','USD 100-300','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.mip.gov.mm','2025-01-01'),

-- NEPAL missing goals
('any','nepal','Study','Nepal Student Visa','Study at Tribhuvan University or other Nepali institutions.','International students accepted to Nepali higher education.','Valid passport; university acceptance; proof of finances; health insurance.','2-4 weeks','USD 25-100','study','University acceptance, proof of finances, health insurance, valid passport.','2-4 weeks','1 year, renewable','https://www.dofe.gov.np','2025-01-01'),
('any','nepal','Family','Nepal Family Visa','Join a legally residing family member in Nepal.','Spouses and children of Nepali residents.','Valid passport; family relationship proof; sponsor documents; financial support.','2-4 weeks','USD 30-100','family','Family relationship proof, sponsor documents, financial support.','2-4 weeks','1 year, renewable','https://www.dofe.gov.np','2025-01-01'),
('any','nepal','Retirement','Nepal Retirement Visa','Retire in Nepal on a non-tourist long-stay visa.','Retirees 60+ with proof of pension income.','Valid passport; proof of pension or savings; health insurance; accommodation proof.','2-4 weeks','USD 30-100','retirement','Proof of pension or savings, health insurance, accommodation proof.','2-4 weeks','1 year, renewable','https://www.dofe.gov.np','2025-01-01'),
('any','nepal','Digital Nomad','Nepal Digital Nomad Long Stay','Work remotely from Nepal, popular with trekkers and digital nomads.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','2-3 weeks','USD 30-100','digital_nomad','Proof of remote employment, income documentation, health insurance.','2-3 weeks','1 year','https://www.dofe.gov.np','2025-01-01'),

-- OMAN missing goals
('any','oman','Study','Oman Student Visa','Study at Sultan Qaboos University or other Omani institutions.','International students accepted to Omani higher education.','Valid passport; university acceptance; financial support; health insurance.','3-6 weeks','OMR 50-200 (~$130-520)','study','University acceptance, financial support, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.rop.gov.om','2025-01-01'),
('any','oman','Family','Oman Family Residence Visa','Sponsor family members to reside in Oman.','Omani residents/citizens sponsoring spouse and children.','Valid passport; proof of relationship; sponsor salary (OMR 300+/month); accommodation; medical checks.','3-6 weeks','OMR 50-200 (~$130-520)','family','Proof of relationship, sponsor salary (OMR 300+/month), accommodation, medical checks.','3-6 weeks','2 years, renewable','https://www.rop.gov.om','2025-01-01'),
('any','oman','Retirement','Oman Retirement Residence','Retire in Oman on a retirement residence visa.','Retirees with substantial property investment or pension income.','Valid passport; proof of pension or property investment (OMR 70,000+); health insurance.','4-8 weeks','OMR 100-300 (~$260-780)','retirement','Proof of pension or property investment (OMR 70,000+), health insurance.','4-8 weeks','2 years, renewable','https://www.rop.gov.om','2025-01-01'),
('any','oman','Digital Nomad','Oman Digital Nomad Long Stay','Work remotely from Oman on a long-stay permit.','Remote workers employed by foreign companies.','Valid passport; employment contract; proof of income; health insurance.','3-6 weeks','OMR 50-200 (~$130-520)','digital_nomad','Employment contract, proof of income, health insurance.','3-6 weeks','1 year','https://www.rop.gov.om','2025-01-01'),

-- PAKISTAN missing goals
('any','pakistan','Study','Pakistan Student Visa','Study at Pakistani universities.','International students accepted to Pakistani higher education.','Valid passport; university acceptance; proof of finances; health insurance.','4-8 weeks','PKR 5,000-20,000 (~$18-72)','study','University acceptance, proof of finances, health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.nadra.gov.pk','2025-01-01'),
('any','pakistan','Family','Pakistan Family Visa','Join a legally residing family member in Pakistan.','Spouses and children of Pakistani residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','PKR 5,000-20,000 (~$18-72)','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.nadra.gov.pk','2025-01-01'),
('any','pakistan','Retirement','Pakistan Retirement Residence Visa','Retire in Pakistan on a long-stay retirement visa.','Retirees with sufficient foreign pension income.','Valid passport; proof of pension; health insurance; accommodation proof; clean criminal record.','4-8 weeks','PKR 5,000-20,000 (~$18-72)','retirement','Proof of pension, health insurance, accommodation proof, clean criminal record.','4-8 weeks','1 year, renewable','https://www.nadra.gov.pk','2025-01-01'),
('any','pakistan','Digital Nomad','Pakistan Digital Nomad Long Stay','Work remotely from Pakistan on a multiple-entry visa.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','PKR 5,000-15,000 (~$18-54)','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.nadra.gov.pk','2025-01-01'),

-- PANAMA missing goals
('any','panama','Study','Panama Student Visa','Study at Panamanian universities.','International students accepted to Panamanian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','4-8 weeks','USD 100-300','study','University acceptance, proof of finances, health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.migracion.gob.pa','2025-01-01'),
('any','panama','Family','Panama Family Visa','Join a legally residing family member in Panama.','Spouses and children of Panamanian residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','USD 200-500','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.migracion.gob.pa','2025-01-01'),
('any','panama','Retirement','Panama Pensionado Visa','Retire in Panama on the famous Pensionado program with extensive benefits.','Retirees with pension income of at least $1,000/month.','Valid passport; proof of pension ($1,000+/month); health insurance; clean criminal record; authenticated documents.','2-3 months','USD 300-600','retirement','Proof of pension ($1,000+/month), health insurance, clean criminal record, authenticated documents.','2-3 months','Permanent residency','https://www.migracion.gob.pa','2025-01-01'),

-- PARAGUAY missing goals
('any','paraguay','Study','Paraguay Student Visa','Study at Paraguayan universities.','International students accepted to Paraguayan higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','USD 50-200','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.migraciones.gov.py','2025-01-01'),
('any','paraguay','Family','Paraguay Family Reunification Visa','Join a legally residing family member in Paraguay.','Spouses and children of Paraguayan residents or citizens.','Valid passport; marriage/birth certificate; sponsor documents; financial proof.','4-8 weeks','USD 100-300','family','Marriage/birth certificate, sponsor documents, financial proof.','4-8 weeks','1 year, renewable','https://www.migraciones.gov.py','2025-01-01'),
('any','paraguay','Retirement','Paraguay Retirement Residence','Retire in Paraguay, one of South America most affordable countries.','Retirees with pension income of at least $1,500/month.','Valid passport; proof of pension ($1,500+/month); health insurance; clean criminal record.','3-6 months','USD 200-500','retirement','Proof of pension ($1,500+/month), health insurance, clean criminal record.','3-6 months','2 years, renewable toward permanent residency','https://www.migraciones.gov.py','2025-01-01'),
('any','paraguay','Digital Nomad','Paraguay Digital Nomad Visa','Work remotely from Paraguay.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','USD 100-300','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.migraciones.gov.py','2025-01-01'),

-- SERBIA missing goals
('any','serbia','Study','Serbia Student Visa','Study at Serbian universities such as the University of Belgrade.','Students accepted to Serbian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','RSD 3,000-10,000 (~$27-91)','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.mup.gov.rs','2025-01-01'),
('any','serbia','Family','Serbia Family Reunification','Join a legally residing family member in Serbia.','Spouses and children of Serbian residents.','Valid passport; family relationship proof; sponsor documents; financial support; accommodation.','4-8 weeks','RSD 3,000-10,000 (~$27-91)','family','Family relationship proof, sponsor documents, financial support, accommodation.','4-8 weeks','1 year, renewable','https://www.mup.gov.rs','2025-01-01'),
('any','serbia','Retirement','Serbia Retirement Residence Permit','Retire in Serbia, an affordable European destination.','Retirees with proven pension income.','Valid passport; proof of pension (EUR 400+/month); health insurance; accommodation; clean criminal record.','4-8 weeks','RSD 5,000-15,000 (~$45-136)','retirement','Proof of pension (EUR 400+/month), health insurance, accommodation, clean criminal record.','4-8 weeks','1 year, renewable','https://www.mup.gov.rs','2025-01-01'),
('any','serbia','Digital Nomad','Serbia Digital Nomad Visa','Work remotely from Serbia in a growing tech hub.','Remote workers and freelancers employed by non-Serbian companies.','Valid passport; proof of employment abroad; income EUR 1,500+/month; health insurance.','3-6 weeks','RSD 3,000-10,000 (~$27-91)','digital_nomad','Proof of employment abroad, income EUR 1,500+/month, health insurance.','3-6 weeks','1 year','https://www.mup.gov.rs','2025-01-01'),
('any','serbia','Investor','Serbia Investor Residence','Invest in Serbia and obtain long-term residency.','Investors making qualifying investments in Serbia.','Valid passport; business registration; proof of investment; clean criminal record.','4-8 weeks','RSD 5,000-20,000 (~$45-182)','investor','Business registration, proof of investment, clean criminal record.','4-8 weeks','3 years, renewable','https://www.ras.gov.rs','2025-01-01'),

-- SLOVAKIA missing goals
('any','slovakia','Study','Slovakia Student Visa (D)','Study at Slovak universities such as Comenius University.','Students accepted to Slovak higher education.','Valid passport; university acceptance; proof of finances (EUR 265+/month); health insurance.','4-8 weeks','EUR 50-200','study','University acceptance, proof of finances (EUR 265+/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.minv.sk','2025-01-01'),
('any','slovakia','Family','Slovakia Family Reunification','Join a legally residing family member in Slovakia.','Spouses and children of Slovak residents.','Valid passport; proof of family relationship; sponsor income; accommodation.','6-10 weeks','EUR 50-200','family','Proof of family relationship, sponsor income, accommodation.','6-10 weeks','1 year, renewable','https://www.minv.sk','2025-01-01'),
('any','slovakia','Retirement','Slovakia Retirement Residence Permit','Retire in Slovakia, an affordable EU destination.','Retirees with proven pension income.','Valid passport; proof of pension; health insurance; accommodation; clean criminal record.','6-10 weeks','EUR 50-200','retirement','Proof of pension, health insurance, accommodation, clean criminal record.','6-10 weeks','1 year, renewable','https://www.minv.sk','2025-01-01'),
('any','slovakia','Digital Nomad','Slovakia Digital Nomad Visa','Work remotely from Slovakia in the EU.','Remote workers employed by non-Slovak companies.','Valid passport; proof of employment abroad; income EUR 2,000+/month; health insurance.','4-8 weeks','EUR 50-150','digital_nomad','Proof of employment abroad, income EUR 2,000+/month, health insurance.','4-8 weeks','1 year','https://www.minv.sk','2025-01-01'),

-- SLOVENIA missing goals
('any','slovenia','Study','Slovenia Student Residence Permit','Study at the University of Ljubljana or other Slovenian institutions.','Students accepted to Slovenian higher education.','Valid passport; university acceptance; proof of finances (EUR 400+/month); health insurance.','4-8 weeks','EUR 50-200','study','University acceptance, proof of finances (EUR 400+/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.gov.si/en/topics/residence-in-slovenia','2025-01-01'),
('any','slovenia','Family','Slovenia Family Reunification','Join a legally residing family member in Slovenia.','Spouses and children of Slovenian residents.','Valid passport; proof of family relationship; sponsor income; accommodation; health insurance.','2-3 months','EUR 50-200','family','Proof of family relationship, sponsor income, accommodation, health insurance.','2-3 months','1 year, renewable','https://www.gov.si/en/topics/residence-in-slovenia','2025-01-01'),
('any','slovenia','Retirement','Slovenia Retirement Residence Permit','Retire in Slovenia, a picturesque EU country.','Retirees with proven pension income.','Valid passport; proof of pension (EUR 700+/month); health insurance; accommodation; clean criminal record.','2-3 months','EUR 50-200','retirement','Proof of pension (EUR 700+/month), health insurance, accommodation, clean criminal record.','2-3 months','1 year, renewable','https://www.gov.si/en/topics/residence-in-slovenia','2025-01-01'),
('any','slovenia','Digital Nomad','Slovenia Digital Nomad Visa','Work remotely from Slovenia.','Remote workers employed by non-Slovenian companies.','Valid passport; proof of employment abroad; income EUR 2,500+/month; health insurance.','4-8 weeks','EUR 50-150','digital_nomad','Proof of employment abroad, income EUR 2,500+/month, health insurance.','4-8 weeks','1 year','https://www.gov.si/en/topics/residence-in-slovenia','2025-01-01'),

-- SRI LANKA missing goals
('any','sri-lanka','Study','Sri Lanka Student Visa','Study at Sri Lankan universities.','International students accepted to Sri Lankan higher education.','Valid passport; university acceptance; proof of finances; health insurance.','2-4 weeks','LKR 5,000-20,000 (~$16-65)','study','University acceptance, proof of finances, health insurance, valid passport.','2-4 weeks','1 year, renewable','https://www.immigration.gov.lk','2025-01-01'),
('any','sri-lanka','Family','Sri Lanka Family Visa','Join a legally residing family member in Sri Lanka.','Spouses and children of Sri Lankan residents.','Valid passport; family relationship proof; sponsor documents; financial support.','2-4 weeks','LKR 5,000-20,000 (~$16-65)','family','Family relationship proof, sponsor documents, financial support.','2-4 weeks','1 year, renewable','https://www.immigration.gov.lk','2025-01-01'),
('any','sri-lanka','Retirement','Sri Lanka Retirement Visa','Retire in Sri Lanka on the My Dream Home Visa.','Retirees with qualifying savings ($15,000 deposited in a Sri Lankan bank account annually).','Valid passport; deposit of $15,000 in Sri Lankan bank account; health insurance; clean criminal record.','4-8 weeks','USD 50-200','retirement','Deposit of $15,000 in Sri Lankan bank account, health insurance, clean criminal record.','4-8 weeks','2 years, renewable','https://www.immigration.gov.lk','2025-01-01'),
('any','sri-lanka','Digital Nomad','Sri Lanka Digital Nomad Long Stay','Work remotely from Sri Lanka.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','2-4 weeks','USD 50-200','digital_nomad','Proof of remote employment, income documentation, health insurance.','2-4 weeks','1 year','https://www.immigration.gov.lk','2025-01-01'),

-- TANZANIA missing goals
('any','tanzania','Study','Tanzania Student Visa','Study at the University of Dar es Salaam or other Tanzanian institutions.','International students accepted to Tanzanian higher education.','Valid passport; university acceptance; proof of finances; health insurance; yellow fever certificate.','3-6 weeks','USD 50-250','study','University acceptance, proof of finances, health insurance, yellow fever certificate.','3-6 weeks','1 year, renewable','https://www.immigration.go.tz','2025-01-01'),
('any','tanzania','Family','Tanzania Family Visa','Join a legally residing family member in Tanzania.','Spouses and children of Tanzanian residents.','Valid passport; family relationship proof; sponsor documents; financial support.','3-6 weeks','USD 100-300','family','Family relationship proof, sponsor documents, financial support.','3-6 weeks','1 year, renewable','https://www.immigration.go.tz','2025-01-01'),
('any','tanzania','Retirement','Tanzania Retirement Residence','Retire in Tanzania near Kilimanjaro or Zanzibar.','Retirees with sufficient foreign income.','Valid passport; proof of pension income; health insurance; accommodation proof; yellow fever certificate.','4-8 weeks','USD 200-500','retirement','Proof of pension income, health insurance, accommodation proof, yellow fever certificate.','4-8 weeks','1 year, renewable','https://www.immigration.go.tz','2025-01-01'),
('any','tanzania','Digital Nomad','Tanzania Digital Nomad Long Stay','Work remotely from Tanzania, including Zanzibar.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','USD 100-300','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.immigration.go.tz','2025-01-01'),

-- TUNISIA missing goals
('any','tunisia','Study','Tunisia Student Visa','Study at Tunisian universities.','International students accepted to Tunisian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','TND 50-200 (~$16-64)','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.diplomatie.gov.tn','2025-01-01'),
('any','tunisia','Family','Tunisia Family Reunification Visa','Join a legally residing family member in Tunisia.','Spouses and children of Tunisian residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','TND 50-200 (~$16-64)','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.diplomatie.gov.tn','2025-01-01'),
('any','tunisia','Retirement','Tunisia Retirement Residence','Retire in Tunisia, a Mediterranean destination with low cost of living.','Retirees with sufficient pension income.','Valid passport; proof of pension; health insurance; accommodation proof; clean criminal record.','4-8 weeks','TND 100-300 (~$32-97)','retirement','Proof of pension, health insurance, accommodation proof, clean criminal record.','4-8 weeks','1 year, renewable','https://www.diplomatie.gov.tn','2025-01-01'),
('any','tunisia','Digital Nomad','Tunisia Digital Nomad Long Stay','Work remotely from Tunisia on a long-stay visa.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','TND 100-250 (~$32-81)','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.diplomatie.gov.tn','2025-01-01'),

-- URUGUAY missing goals
('any','uruguay','Study','Uruguay Student Visa','Study at the Universidad de la Republica or other Uruguayan institutions.','International students accepted to Uruguayan higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','USD 100-300','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.migracion.minterior.gub.uy','2025-01-01'),
('any','uruguay','Family','Uruguay Family Reunification Visa','Join a legally residing family member in Uruguay.','Spouses and children of Uruguayan residents or citizens.','Valid passport; marriage/birth certificate; sponsor documents; financial proof.','4-8 weeks','USD 100-300','family','Marriage/birth certificate, sponsor documents, financial proof.','4-8 weeks','1 year, renewable','https://www.migracion.minterior.gub.uy','2025-01-01'),
('any','uruguay','Retirement','Uruguay Retirement Residence','Retire in Uruguay, one of South America most stable and peaceful countries.','Retirees with pension income of at least $1,500/month.','Valid passport; proof of pension ($1,500+/month); health insurance; clean criminal record.','2-3 months','USD 200-500','retirement','Proof of pension ($1,500+/month), health insurance, clean criminal record.','2-3 months','2 years, renewable toward permanent residency','https://www.migracion.minterior.gub.uy','2025-01-01'),
('any','uruguay','Digital Nomad','Uruguay Digital Nomad Visa','Work remotely from Uruguay.','Remote workers and freelancers employed by non-Uruguayan companies.','Valid passport; proof of employment abroad; income ($2,000+/month); health insurance.','3-6 weeks','USD 200-500','digital_nomad','Proof of employment abroad, income ($2,000+/month), health insurance.','3-6 weeks','1 year','https://www.migracion.minterior.gub.uy','2025-01-01'),
('any','uruguay','Investor','Uruguay Investor Residence','Invest in Uruguay and obtain permanent residency.','Investors making qualifying investments in Uruguay.','Valid passport; business registration or investment documentation; proof of investment; clean criminal record.','2-4 months','USD 300-700','investor','Business registration or investment documentation, proof of investment, clean criminal record.','2-4 months','Permanent residency','https://www.migracion.minterior.gub.uy','2025-01-01'),

-- UZBEKISTAN missing goals
('any','uzbekistan','Study','Uzbekistan Student Visa','Study at Tashkent State Technical University or other Uzbek institutions.','International students accepted to Uzbek higher education.','Valid passport; university acceptance; proof of finances; health insurance.','2-4 weeks','USD 30-100','study','University acceptance, proof of finances, health insurance, valid passport.','2-4 weeks','1 year, renewable','https://www.mfa.uz','2025-01-01'),
('any','uzbekistan','Family','Uzbekistan Family Visa','Join a legally residing family member in Uzbekistan.','Spouses and children of Uzbek residents.','Valid passport; family relationship proof; sponsor documents; financial support.','2-4 weeks','USD 30-100','family','Family relationship proof, sponsor documents, financial support.','2-4 weeks','1 year, renewable','https://www.mfa.uz','2025-01-01'),
('any','uzbekistan','Retirement','Uzbekistan Retirement Long-Stay Visa','Retire in Uzbekistan, a growing destination in Central Asia.','Retirees with sufficient pension income.','Valid passport; proof of pension; health insurance; accommodation proof; clean criminal record.','2-4 weeks','USD 50-200','retirement','Proof of pension, health insurance, accommodation proof, clean criminal record.','2-4 weeks','1 year, renewable','https://www.mfa.uz','2025-01-01'),

-- ZIMBABWE missing goals
('any','zimbabwe','Study','Zimbabwe Student Permit','Study at the University of Zimbabwe or other Zimbabwean institutions.','International students accepted to Zimbabwean higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','USD 50-200','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.zimimmigration.gov.zw','2025-01-01'),
('any','zimbabwe','Family','Zimbabwe Family Permit','Join a legally residing family member in Zimbabwe.','Spouses and children of Zimbabwean residents.','Valid passport; family relationship proof; sponsor documents; financial support.','3-6 weeks','USD 50-200','family','Family relationship proof, sponsor documents, financial support.','3-6 weeks','1 year, renewable','https://www.zimimmigration.gov.zw','2025-01-01'),
('any','zimbabwe','Retirement','Zimbabwe Retirement Residence','Retire in Zimbabwe.','Retirees with sufficient foreign income.','Valid passport; proof of pension income; health insurance; accommodation proof.','4-8 weeks','USD 100-300','retirement','Proof of pension income, health insurance, accommodation proof.','4-8 weeks','1 year, renewable','https://www.zimimmigration.gov.zw','2025-01-01'),
('any','zimbabwe','Digital Nomad','Zimbabwe Digital Nomad Long Stay','Work remotely from Zimbabwe.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','USD 100-300','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.zimimmigration.gov.zw','2025-01-01')

ON CONFLICT DO NOTHING;
