/*
  # Populate Mexico, Greece, Egypt, Finland, Hungary, and Morocco Pathways
  
  Comprehensive pathways for diverse destinations.
*/

-- MEXICO PATHWAYS
INSERT INTO immigration_pathways (
  destination_slug, passport_slug, pathway_type, goal, pathway_name, summary,
  eligibility, key_requirements, typical_timeline, estimated_fees,
  requirements, processing_time, validity_period, last_updated
) VALUES
('mexico', 'any', 'Work Visa', 'Work', 'Mexico Temporary Resident Visa (Work)',
'Temporary resident visa allowing employment in Mexico. Can work for Mexican companies or remote work. Renewable and leads to permanent residence.',
'Job offer from Mexican employer OR proof of remote work income. Financial solvency. Clean criminal record. Health requirements.',
'Job offer or remote income proof, Financial solvency, Clean record',
'4-8 weeks',
'Consular fee USD $36, Residence card MXN $4,000-5,000',
'Job offer letter or remote work contract, Proof of income (bank statements last 12 months showing USD $2,000+ monthly), Passport (valid 6+ months), Photos, Criminal background check (apostilled), Application forms, Proof of address, Health certificate if required',
'4-8 weeks at consulate. Then immigration office visit within 30 days of entry for residence card.',
'1 year renewable up to 4 years. Can work legally. After 4 years, eligible for permanent residence. Family members can obtain dependent visas. Multiple entry.',
CURRENT_DATE),

('mexico', 'any', 'Digital Nomad Visa', 'Work', 'Mexico Temporary Resident Visa (Remote Worker)',
'Increasingly popular for digital nomads and remote workers. Allows living in Mexico while working for foreign companies. No Mexican employment.',
'Remote work for foreign company OR freelance income. Monthly income USD $2,000+ from non-Mexican sources. Financial stability proof. Clean criminal record.',
'USD $2,000+ monthly remote income, Financial proof, Clean record',
'4-8 weeks',
'Consular fee USD $36-48, Residence card MXN $4,000-5,000',
'Remote work contract or freelance client agreements, Bank statements (12 months showing USD $2,000+ monthly), Portfolio or business proof, Passport (6+ months validity), Photos, Criminal background check (apostilled), Application forms, Proof of accommodation in Mexico',
'4-8 weeks at consulate. Immigration card issued within 30 days of entry.',
'1 year initially, renewable annually up to 4 years total. Can live anywhere in Mexico. After 4 years as temporary resident, eligible for permanent residence. Popular among remote workers from US, Canada, Europe.',
CURRENT_DATE),

('mexico', 'any', 'Study Visa', 'Study', 'Mexico Student Temporary Resident Visa',
'Study at Mexican universities, language schools, or cultural programs. Affordable education, rich culture. Part-time work allowed with restrictions.',
'Admission to Mexican educational institution. Financial solvency to cover tuition and living expenses. Clean criminal record.',
'School admission, Financial solvency, Clean record',
'4-8 weeks',
'Consular fee USD $36, Residence card MXN $4,000-5,000, Tuition varies',
'School acceptance letter, Proof of tuition payment or scholarship, Financial proof (sufficient for living expenses), Passport (6+ months validity), Photos, Criminal background check (apostilled), Academic records, Application forms',
'4-8 weeks for visa. Residence card within 30 days of entry.',
'Duration of studies (renewable annually). Can engage in limited paid activities with permission. After completing studies, can convert to work visa if employment found. Many students transition to temporary resident status.',
CURRENT_DATE),

('mexico', 'any', 'Residency Visa', 'Permanent Residency', 'Mexico Permanent Resident Visa',
'Permanent residence in Mexico. No renewal required. Can work freely. Common path for retirees and investors.',
'Financial solvency (investments, retirement income, or property) OR family ties to Mexican citizens/residents OR 4 years as temporary resident. Clean criminal record.',
'Financial requirements or 4 years temporary residence, Clean record',
'2-4 months',
'Consular fee USD $48, Permanent residence card MXN $6,000-7,000',
'Financial proof (investments USD $200,000+ or monthly income USD $4,000+), Bank statements (12-24 months), Property title if applicable, Marriage certificate if family-based, Passport and photos, Criminal background check (apostilled), Proof of 4 years temporary residence if applicable',
'2-4 months at consulate and immigration.',
'Indefinite. No renewal required. Can work freely. Can leave Mexico for up to 4 years without losing status. Path to citizenship after 5 years. Similar rights to citizens except voting.',
CURRENT_DATE),

('mexico', 'any', 'Family Visa', 'Family', 'Mexico Family Unity Visa',
'For family members of Mexican citizens or permanent/temporary residents. Streamlined process with family connection.',
'Family relationship with Mexican citizen or legal resident. Financial support from sponsor. Clean criminal record.',
'Family relationship, Sponsor support, Clean record',
'4-8 weeks',
'Consular fee USD $36, Residence card MXN $4,000-5,000',
'Marriage certificate or birth certificate (apostilled and translated), Mexican sponsor''s ID and immigration status, Sponsor''s financial proof (employment, income), Passport and photos, Criminal background check (apostilled), Proof of relationship (photos, correspondence), Application forms',
'4-8 weeks for visa. Residence card within 30 days.',
'Initial temporary residence (1-4 years) or permanent residence depending on sponsor status. Can work. Children get same status. After 2 years married to Mexican citizen, eligible for citizenship.',
CURRENT_DATE),

('mexico', 'any', 'Visitor Visa', 'Visit', 'Mexico Tourist Permit (FMM)',
'Tourist card for short visits. Many nationalities enter visa-free. Simple online or on-arrival process.',
'Valid passport from eligible country. Tourism or business visit purpose. Sufficient funds. Return ticket.',
'Eligible passport, Valid purpose, Funds, Return ticket',
'Instant on arrival (visa-free nationals)',
'FMM fee USD $30 (often included in flight)',
'Valid passport (6+ months), Return flight ticket, Proof of accommodation, Travel itinerary, Financial means (credit card or cash), FMM form (online or on arrival)',
'Instant for visa-free nationals. 1-2 weeks for those requiring visa.',
'Up to 180 days (officer discretion, typically 30-180 days granted). Cannot work or study. Multiple entries require new FMM each time. Very accessible for US, Canadian, EU, and many other nationals.',
CURRENT_DATE),

-- GREECE PATHWAYS
('greece', 'any', 'Work Visa', 'Work', 'Greece Employment Visa',
'Work visa for employed positions in Greece. Quota system applies. Employer sponsorship required.',
'Job offer from Greek employer. Within annual quota. Relevant qualifications. Employer registration and compliance.',
'Job offer, Within quota, Qualifications',
'60-120 days',
'Visa fee €75-180, Residence permit €300',
'Job contract from Greek employer, Employer documents (registration, tax compliance, social security), Proof of qualifications, CV, Passport (3+ months beyond stay), Photos, Health insurance, Accommodation proof, Criminal record certificate',
'60-120 days including quota allocation and processing.',
'Initially 1-2 years. Renewable if employment continues. After 5 years legal residence, eligible for long-term residence permit. EU Blue Card option available for highly qualified with €36,000+ salary.',
CURRENT_DATE),

('greece', 'any', 'Digital Nomad Visa', 'Work', 'Greece Digital Nomad Visa',
'New visa for remote workers and digital nomads. Work for non-Greek employers while living in Greece. Growing program.',
'Remote employment with non-Greek company OR freelance work. Monthly income €3,500+ from non-Greek sources. Health insurance. Accommodation.',
'€3,500+ monthly remote income, Health insurance, Accommodation',
'30-60 days',
'Application fee €75, Residence permit €300',
'Employment contract with non-Greek company or client contracts, Proof of income (€3,500+ monthly, 6+ months bank statements), CV and professional background, Health insurance valid in Greece, Passport and photos, Accommodation proof (lease 12+ months), Tax residence certificate from home country, Criminal record',
'30-60 days for processing.',
'1 year initially, renewable for up to 2 more years (3 years total). Cannot work for Greek companies. Favorable tax regime possible. Family members can join. After program, can transition to other residence types.',
CURRENT_DATE),

('greece', 'any', 'Study Visa', 'Study', 'Greece Student Visa',
'Study at Greek universities and institutions. Low tuition costs. English-taught programs available. Mediterranean lifestyle.',
'Admission to Greek university or institution. Financial resources (€450-600/month). Health insurance. Accommodation.',
'University admission, €450-600/month funds, Insurance',
'60-90 days',
'Visa fee €75, Residence permit €150-300',
'University admission letter, Financial proof (€5,400-7,200/year), Health insurance (EU/Greek coverage), Passport (3+ months beyond stay), Photos, Academic records, Language certificate if required, Accommodation proof, Travel itinerary',
'60-90 days for visa and residence permit.',
'Duration of studies. Can work part-time with restrictions. Residence permit must be renewed annually. After graduation, 12-month job search extension possible. Can convert to work visa when employed.',
CURRENT_DATE),

('greece', 'any', 'Residency Visa', 'Permanent Residency', 'Greece Golden Visa',
'Residence by investment. Purchase €250,000+ property and receive 5-year renewable residence. Very popular program.',
'Purchase real estate €250,000+ (€500,000+ for some areas from 2023 onwards). Property fully owned. Health insurance.',
'€250,000-500,000 property investment, Health insurance',
'60-90 days',
'Application fee €500, Residence card €500 per person',
'Property purchase deed (notarized), Proof of payment (€250,000-500,000+), Property valuation, Passport and photos, Health insurance for applicants, Proof of funds for living expenses, Criminal record, Application forms',
'60-90 days after property purchase.',
'5 years renewable indefinitely. No residency requirement (can live elsewhere). Family included. Cannot work in Greece (can invest/own businesses). After 7 years, eligible for citizenship. Free Schengen travel.',
CURRENT_DATE),

('greece', 'any', 'Family Visa', 'Family', 'Greece Family Reunification',
'Join family members legally residing in Greece. For spouses, children, parents in some cases.',
'Sponsor must have legal residence in Greece (1+ year valid). Adequate income (varies by family size). Adequate housing. Health insurance for family.',
'Sponsor residence, Adequate income, Housing, Insurance',
'60-120 days',
'Visa fee €75 per person, Residence permit €300 per person',
'Sponsor residence permit, Relationship proof (marriage certificate, birth certificates - translated and legalized), Sponsor income proof (employment, business), Housing proof (lease or property deed meeting space requirements), Health insurance for family members, Passport and photos, Family integration plan',
'60-120 days for processing.',
'Initially aligned with sponsor permit. Renewable. Spouses can work after obtaining own work permit or under certain residence categories. Children attend school. After 5 years, eligible for independent long-term residence.',
CURRENT_DATE),

('greece', 'any', 'Visitor Visa', 'Visit', 'Greece Schengen Tourist Visa',
'Short-stay Schengen visa for tourism. Greece is gateway to islands and ancient history.',
'Valid visit purpose. Sufficient funds. Accommodation. Travel insurance. Intent to return.',
'Valid purpose, Funds, Accommodation, €30,000 insurance, Return ticket',
'15-30 days',
'Visa fee €80 (€40 for children 6-12)',
'Passport (3+ months beyond stay), Application form and photos, Travel itinerary, Hotel bookings or invitation, Financial proof (bank statements, €50/day), Travel insurance (€30,000+), Employment/retirement/student proof, Return flight',
'15-30 days standard processing.',
'Up to 90 days within 180-day period. Cannot work. Schengen access. Multiple-entry available.',
CURRENT_DATE),

-- EGYPT PATHWAYS
('egypt', 'any', 'Work Visa', 'Work', 'Egypt Work Visa',
'Employment visa for foreign workers. Requires Ministry of Manpower approval. Common in oil, gas, tourism, education sectors.',
'Job offer from Egyptian employer. Work permit from Ministry of Manpower. Relevant qualifications. Position cannot be easily filled by Egyptian.',
'Job offer, Work permit, Qualifications',
'4-8 weeks',
'Visa fee USD $25-60, Work permit fees vary',
'Work permit approval from Ministry of Manpower, Employment contract, University degrees and certifications (notarized and legalized), Passport (6+ months validity), Photos, Criminal background check (legalized), Medical certificate, Company registration documents, Employer letter explaining need',
'4-8 weeks including work permit approval.',
'1 year initially, renewable. Must obtain residence permit after arrival. Can bring family on dependent visas. Extensions require continued employment and permit renewal.',
CURRENT_DATE),

('egypt', 'any', 'Study Visa', 'Study', 'Egypt Student Visa',
'Study at Egyptian universities. Egypt has ancient academic tradition, particularly in Islamic studies, Arabic, archaeology. Very affordable.',
'Admission to Egyptian university or institution. Financial resources for living expenses. Health certificate.',
'University admission, Financial resources, Health certificate',
'4-6 weeks',
'Visa fee USD $25, Residence permit EGP 1,000-2,000',
'University admission letter, Proof of tuition payment, Financial proof (bank statements), Passport (6+ months validity), Photos, Medical certificate (HIV test, general health), Academic records (notarized), Police clearance, Accommodation proof',
'4-6 weeks for visa.',
'Duration of studies (renewable annually). Must obtain residence permit after arrival. Limited part-time work opportunities. Popular for Arabic language and Islamic studies students.',
CURRENT_DATE),

('egypt', 'any', 'Digital Nomad Visa', 'Work', 'Egypt Freelance/Self-Employment Visa',
'For freelancers and remote workers. Less common but possible with proper documentation. Cairo and coastal areas attract remote workers.',
'Freelance contracts or remote work proof. Sufficient income. Professional credentials. Registration intention.',
'Freelance/remote income, Professional credentials',
'6-10 weeks',
'Visa fee USD $60, Residence permit EGP 2,000-3,000',
'Freelance contracts or remote work agreement, Bank statements showing income, Professional certificates, Portfolio, Passport and photos, Criminal background check, Health certificate, Proof of accommodation, Business registration if applicable',
'6-10 weeks for processing and approvals.',
'1 year renewable. Must obtain residence permit. Can work remotely. Registration with tax authorities recommended. Lower cost of living attractive.',
CURRENT_DATE),

('egypt', 'any', 'Residency Visa', 'Permanent Residency', 'Egypt Long-term Residence',
'Long-term residence for retirees, investors, or property owners. Egypt offers low cost of living and historical richness.',
'Property investment (USD $100,000+) OR monthly income USD $2,000+ OR 10+ years continuous residence. Age 40+ for retirement route.',
'Property investment or USD $2,000+ income or 10 years residence',
'2-4 months',
'Application fee USD $100, Residence fee USD $500-1,000',
'Property deed or investment proof, Bank statements (6+ months showing income), Passport and photos, Criminal background check, Medical certificate, Proof of accommodation, Marriage certificate if applicable, Previous residence permits if claiming 10-year route',
'2-4 months for processing.',
'5 years renewable. Can work or invest. Favorable for retirees. Low cost of living (USD $1,000-2,000/month comfortable). Popular Red Sea and Cairo.',
CURRENT_DATE),

('egypt', 'any', 'Family Visa', 'Family', 'Egypt Family Residence',
'For family members of residents or Egyptian citizens. Straightforward process with proper documentation.',
'Family relationship with Egyptian citizen or legal resident. Sponsor financial capacity. Proper documentation.',
'Family relationship, Sponsor capacity',
'4-8 weeks',
'Visa fee USD $25 per person, Residence EGP 1,000-2,000 per person',
'Marriage certificate or birth certificate (notarized and legalized), Sponsor Egyptian ID or residence permit, Sponsor financial documents, Passport and photos, Medical certificate for family members, Police clearance, Accommodation proof',
'4-8 weeks for visa.',
'Initially 1 year, renewable. Aligned with sponsor status. Children attend school. Spouses may work with separate work permit.',
CURRENT_DATE),

('egypt', 'any', 'Visitor Visa', 'Visit', 'Egypt Tourist Visa',
'Tourist visa or e-Visa for visiting pyramids, diving Red Sea, exploring history. Very accessible.',
'Valid passport. Tourism purpose. Return ticket. Sufficient funds.',
'Valid passport, Tourism purpose, Funds, Return ticket',
'7-10 days (e-Visa instant to 7 days)',
'e-Visa USD $25 single entry, USD $60 multiple entry',
'Passport (6+ months validity), Online application for e-Visa, Passport photo, Hotel reservations, Return flight booking, Travel insurance recommended',
'e-Visa: instant to 7 days. Visa on arrival available for many nationalities at USD $25.',
'30 days (single entry) or 90 days (multiple entry within 180 days). Cannot work. Extensions possible at government offices. Very accessible for most nationalities.',
CURRENT_DATE),

-- FINLAND PATHWAYS
('finland', 'any', 'Work Visa', 'Work', 'Finland Specialist Visa',
'For specialists, researchers, and professionals. Fast-track processing. No labor market test for certain positions.',
'Job offer requiring special expertise. Salary €3,000+ monthly (lower for specific fields like research). Relevant qualifications. Cannot be easily filled by Finnish/EU worker.',
'Specialist job offer, €3,000+ monthly salary, Relevant qualifications',
'1-4 months',
'Residence permit fee €520 (electronic) or €540 (first time)',
'Job contract (specialist position), Employer documents (Y-tunnus, registration), University degree and transcripts, CV and references, Passport (valid beyond stay), Photos, Proof of accommodation, Health insurance (EU healthcare or private), Criminal record if required',
'1-4 months for residence permit decision.',
'Initially 1-2 years based on contract. Renewable. After 4 years continuous residence (EU Blue Card) or 5 years (regular), eligible for permanent residence. Family can join. Spouse works freely.',
CURRENT_DATE),

('finland', 'any', 'Work Visa', 'Work', 'Finland EU Blue Card',
'For highly qualified professionals. Minimum salary threshold. Fast path to permanent residence and family benefits.',
'University degree (3+ years). Job offer with €4,568+ monthly salary (2024). Employment 3+ months. Health insurance.',
'University degree, €4,568+ monthly salary, 3+ months employment',
'1-2 months',
'Residence permit fee €520 (electronic)',
'University degree certificates, Job contract (€4,568+ monthly), Employer registration, Passport and photos, Health insurance, Proof of accommodation, CV, Degree recognition if required',
'1-2 months for processing.',
'Initially up to 2 years. Renewable. After 4 years with Blue Card, eligible for permanent residence. Family included. Can move within EU after 18 months. Spouse works without permit.',
CURRENT_DATE),

('finland', 'any', 'Study Visa', 'Study', 'Finland Student Residence Permit',
'Study at Finnish universities. High-quality education. Many English programs. Can work part-time.',
'Admission to Finnish institution. Financial proof (€560/month or €6,720/year). Health insurance. Accommodation.',
'University admission, €560/month funds, Insurance, Accommodation',
'1-3 months',
'Residence permit fee €350 (first time), €160 (extension)',
'University admission letter, Financial proof (€6,720/year minimum via bank account, scholarship, or sponsor guarantee), Health insurance (EU healthcare card or private), Passport and photos, Academic records, Accommodation proof (rental contract or dorm), Motivation letter if requested',
'1-3 months for decision.',
'Duration of studies. Can work 25 hours/week during term, full-time in holidays. After graduation, 1-year extension to find employment. Convert to work permit when employed. After 4 years continuous residence, eligible for permanent residence.',
CURRENT_DATE),

('finland', 'any', 'Digital Nomad Visa', 'Work', 'Finland Entrepreneur Residence Permit',
'For entrepreneurs and self-employed. Must demonstrate viable business benefiting Finland. Growing startup scene.',
'Viable business plan. Sufficient income from business or capital. Professional expertise. Business benefits Finnish economy.',
'Business plan, Sufficient income/capital, Professional expertise',
'2-4 months',
'Residence permit fee €540',
'Detailed business plan, Financial projections and capital proof, Professional qualifications and CV, Client contracts or letters of intent, Passport and photos, Accommodation proof, Health insurance, Company registration documents if already established, Market research',
'2-4 months for evaluation and decision.',
'Initially 1-2 years. Must demonstrate business progress for renewal. After 4 years, eligible for permanent residence. Can bring family. Helsinki has vibrant startup ecosystem.',
CURRENT_DATE),

('finland', 'any', 'Family Visa', 'Family', 'Finland Family Ties Residence Permit',
'For family members of Finnish residents or citizens. Relatively straightforward with proper documentation.',
'Family relationship with Finnish resident or citizen. Adequate income from sponsor (€1,700+ monthly for couple, more for children). Adequate housing.',
'Family relationship, €1,700+ sponsor income, Housing',
'4-8 months',
'Residence permit fee €520 per adult, €260 per child',
'Marriage certificate or birth certificate (apostilled), Sponsor residence permit or Finnish ID, Sponsor income proof (employment, business), Housing proof (lease or ownership meeting size requirements), Passport and photos, Health insurance, Relationship evidence (photos, communication), Integration plan',
'4-8 months for family permit processing.',
'Initially aligned with sponsor status (1-4 years). Renewable. Spouses can work immediately. Children attend school. After 4 years continuous residence, eligible for permanent residence.',
CURRENT_DATE),

('finland', 'any', 'Visitor Visa', 'Visit', 'Finland Schengen Visa',
'Short-stay visa for tourism, business, family visits. Access to Schengen Area. Northern lights and summer midnight sun.',
'Valid visit purpose. Sufficient funds (€30/day minimum). Accommodation. Travel insurance. Intent to return.',
'Valid purpose, €30/day funds, Accommodation, €30,000 insurance',
'15-30 days',
'Visa fee €80 (€40 for children 6-12)',
'Passport (3+ months beyond stay), Application and photos, Travel itinerary, Accommodation bookings, Financial proof (bank statements, €30/day), Travel insurance (€30,000+), Employment or study proof, Return flight, Invitation letter if applicable',
'15-30 days standard processing.',
'Up to 90 days within 180-day period. Cannot work or study. Schengen access. Multiple-entry available.',
CURRENT_DATE);
