/*
  # Add Pathways for Asian Passports

  ## Overview
  Comprehensive immigration pathways for citizens from Asian countries including:
  - China, South Korea, Philippines, Pakistan, Bangladesh, Vietnam, Thailand
  
  ## Destinations
  All major immigration destinations

  ## Goals
  Work, Study, Visit, Residency
*/

INSERT INTO immigration_pathways (
  passport_slug, destination_slug, goal, pathway_type, pathway_name,
  summary, eligibility, key_requirements, requirements, typical_timeline,
  processing_time, estimated_fees, validity_period, official_url
) VALUES

-- China to Canada
('cn', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('cn', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity, language test.',
 'Letter of Acceptance, CAD 10,000+ funds, English/French test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('cn', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism and business visits.',
 'Chinese passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- China to US
('cn', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for professionals.',
 'Bachelor degree, US employer sponsorship.',
 'Job offer, employer petition, degree, lottery.',
 'US employer petition, bachelor degree, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('cn', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP-approved school acceptance.',
 'I-20, SEVIS fee, financial proof, interview.',
 'I-20, SEVIS fee, financial capacity, visa interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('cn', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Chinese passport holders.',
 'Valid passport, interview, funds.',
 'Valid passport, visa interview, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

-- China to UK
('cn', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK sponsor.',
 'Certificate of Sponsorship, English test.',
 'CoS, English proficiency, £1,270 funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('cn', 'gb', 'Study', 'Study', 'Student Visa',
 'Study at UK institution.',
 'Acceptance from licensed sponsor.',
 'CAS, English test, funds.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration',
 'https://www.gov.uk/student-visa'),

('cn', 'gb', 'Visit', 'Visit', 'Standard Visitor Visa',
 'Tourism and business visits.',
 'Chinese passport holders.',
 'Valid passport, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '3 weeks', '3 weeks', 'GBP 100',
 '6 months',
 'https://www.gov.uk/standard-visitor-visa'),

-- China to Australia
('cn', 'au', 'Work', 'Work', 'Temporary Skill Shortage Visa (Subclass 482)',
 'Employer-sponsored work visa.',
 'Job offer from Australian employer.',
 'Employer sponsorship, skills assessment.',
 'Employer sponsorship, skills assessment, English test, experience.',
 '2-4 months', '2-4 months', 'AUD 1,290-2,690',
 '2-4 years',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482'),

('cn', 'au', 'Study', 'Study', 'Student Visa (Subclass 500)',
 'Full-time study visa.',
 'Enrollment in registered course.',
 'CoE, financial capacity, English test.',
 'Confirmation of Enrollment, financial proof, English proficiency, OSHC.',
 '1-2 months', '1-2 months', 'AUD 650',
 'Course duration',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),

('cn', 'au', 'Visit', 'Visit', 'Visitor Visa (Subclass 600)',
 'Tourism visits.',
 'Chinese passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'AUD 145',
 'Up to 12 months',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600'),

-- South Korea to Canada
('kr', 'ca', 'Work', 'Work', 'International Experience Canada',
 'Working holiday for South Korean youth.',
 'South Korean citizens 18-30 years old.',
 'Valid passport, CAD 2,500 funds, health insurance.',
 'Passport, CAD 2,500 proof of funds, comprehensive health insurance.',
 '8-12 weeks', '8-12 weeks', 'CAD 250',
 '1 year',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/iec.html'),

('kr', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('kr', 'ca', 'Visit', 'Visit', 'Electronic Travel Authorization (eTA)',
 'Electronic visa for air travel.',
 'South Korean passport holders.',
 'Valid passport.',
 'Valid passport, online eTA application.',
 'Minutes', 'Minutes', 'CAD 7',
 'Up to 5 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html'),

-- South Korea to US
('kr', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for professionals.',
 'Bachelor degree, employer sponsorship.',
 'Job offer, employer petition, degree.',
 'US employer petition, bachelor degree, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('kr', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP school acceptance.',
 'I-20, SEVIS fee, financial proof.',
 'I-20, SEVIS fee, financial capacity, interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('kr', 'us', 'Visit', 'Visit', 'ESTA Visa Waiver',
 'Tourism and business visits.',
 'South Korean passport holders.',
 'Valid passport, ESTA.',
 'Valid passport, ESTA authorization, return ticket.',
 '72 hours', '72 hours', 'USD 21',
 '90 days',
 'https://esta.cbp.dhs.gov/'),

-- Philippines to Canada
('ph', 'ca', 'Work', 'Work', 'Temporary Foreign Worker Program',
 'Employer-specific work permit.',
 'Job offer with LMIA.',
 'LMIA-approved job offer, qualifications.',
 'LMIA from employer, relevant qualifications, employment contract.',
 '2-4 months', '2-4 months', 'CAD 155-230',
 '1-4 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/hire-temporary-foreign/temporary-foreign-worker-program.html'),

('ph', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('ph', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Filipino passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Philippines to US
('ph', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for professionals.',
 'Bachelor degree, employer sponsorship.',
 'Job offer, employer petition, degree.',
 'US employer petition, bachelor degree, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('ph', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP school acceptance.',
 'I-20, SEVIS fee, financial proof.',
 'I-20, SEVIS fee, financial capacity, interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('ph', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Filipino passport holders.',
 'Valid passport, interview, funds.',
 'Valid passport, visa interview, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

-- Pakistan to Canada
('pk', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('pk', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('pk', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Pakistani passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Pakistan to UK
('pk', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK sponsor.',
 'Certificate of Sponsorship, English test.',
 'CoS, English proficiency, £1,270 funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('pk', 'gb', 'Study', 'Study', 'Student Visa',
 'Study at UK institution.',
 'Acceptance from licensed sponsor.',
 'CAS, English test, funds.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration',
 'https://www.gov.uk/student-visa'),

('pk', 'gb', 'Visit', 'Visit', 'Standard Visitor Visa',
 'Tourism and business visits.',
 'Pakistani passport holders.',
 'Valid passport, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '3 weeks', '3 weeks', 'GBP 100',
 '6 months',
 'https://www.gov.uk/standard-visitor-visa'),

-- Bangladesh to Canada
('bd', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('bd', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('bd', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Bangladeshi passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Vietnam to Canada
('vn', 'ca', 'Work', 'Work', 'Temporary Foreign Worker Program',
 'Employer-specific work permit.',
 'Job offer with LMIA.',
 'LMIA-approved job offer.',
 'LMIA from employer, qualifications, employment contract.',
 '2-4 months', '2-4 months', 'CAD 155-230',
 '1-4 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/hire-temporary-foreign/temporary-foreign-worker-program.html'),

('vn', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('vn', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Vietnamese passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Thailand to Canada
('th', 'ca', 'Work', 'Work', 'International Experience Canada',
 'Working holiday for Thai youth.',
 'Thai citizens 18-30 years old.',
 'Valid passport, CAD 2,500 funds.',
 'Passport, CAD 2,500 proof of funds, health insurance.',
 '8-12 weeks', '8-12 weeks', 'CAD 250',
 '1 year',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/iec.html'),

('th', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('th', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Thai passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html')

ON CONFLICT (id) DO NOTHING;