/*
  # Populate Germany, France, and Netherlands Immigration Pathways
  
  Comprehensive, fact-checked pathways with all required fields including fees.
*/

-- GERMANY PATHWAYS
INSERT INTO immigration_pathways (
  destination_slug, passport_slug, pathway_type, goal, pathway_name, summary,
  eligibility, key_requirements, typical_timeline, estimated_fees,
  requirements, processing_time, validity_period, last_updated
) VALUES
('germany', 'any', 'Work Visa', 'Work', 'Germany Skilled Worker Visa',
'Allows qualified professionals from non-EU countries to work in Germany with recognized qualifications and a job offer. Part of Germany''s Skilled Immigration Act, providing a clear pathway to permanent residence.',
'Recognized vocational or academic qualification equivalent to German standards. Concrete job offer matching qualifications. Employer must meet German employment standards.',
'Recognized qualification, Job offer, Recognition certificate, Passport, Insurance',
'4-12 weeks processing',
'Visa fee €75, Recognition fee €100-600',
'Recognized qualification certificate with translation, Job contract from German employer, Proof of qualification recognition, Valid passport (6+ months), Health insurance, Financial proof if required, Application form, Photos, Degrees with certified translations, Professional certifications, CV with work experience',
'4-12 weeks after submission. Fast-track available for urgent cases. Add 2-4 months for qualification recognition if needed.',
'Initially for contract duration up to 4 years. After 4 years with B1 German, eligible for permanent residence. After 33 months with B2 German, can apply for permanent residence.',
CURRENT_DATE),

('germany', 'any', 'Work Visa', 'Work', 'Germany EU Blue Card',
'Premium work permit for highly qualified workers offering fastest pathway to permanent residence. Allows EU freedom of movement. Ideal for IT, engineering, healthcare, and science professionals.',
'University degree (Bachelor+) recognized in Germany. Job offer with minimum €58,400 annually (€45,552 for shortage occupations like IT, engineering, medicine, sciences). Employment must match qualification level.',
'University degree, €58,400+ salary job, Insurance',
'2-8 weeks',
'Visa fee €100',
'University degree with certified translation, Job contract meeting salary threshold, Degree recognition proof if required, Passport, Health insurance, Application and photos, CV and experience proof, Language skills (German/English per job), Accommodation proof',
'2-8 weeks processing. Accelerated procedure available. Add 1-3 months for qualification recognition if needed.',
'Up to 4 years or contract duration + 3 months. After 33 months with A1 German, eligible for permanent residence. After 21 months with B1 German, can apply for permanent residence. Free job changes after 2 years.',
CURRENT_DATE),

('germany', 'any', 'Study Visa', 'Study', 'Germany Student Visa',
'Study at German universities with low/no tuition at public institutions. Work part-time during studies (120 full days or 240 half days yearly). 18-month job search permit after graduation.',
'Admission to recognized German institution. Financial resources (€11,208/year via blocked account for 2024). Health insurance. Sufficient language skills (German B1-C1 or English per program).',
'Admission, €11,208 funds, Insurance, Language certificate',
'6-12 weeks visa, 2-6 months admission',
'Visa fee €75, Blocked account fee €50-150, Public university tuition €0-500/semester',
'University admission letter, Blocked account (€934/month for 2024) or scholarship, Health insurance, Passport, Academic records with translations, Language certificate (TestDaF/DSH/Goethe or TOEFL/IELTS), Motivation letter, CV, Application and photos',
'6-12 weeks visa processing. Apply 3 months before start. University admission takes 2-6 months.',
'Initially 3 months, extended for study duration. Can work 120 full/240 half days yearly. 18-month job search permit after graduation. Convert to work permit when employed. Eligible for permanent residence after 2 years employment.',
CURRENT_DATE),

('germany', 'any', 'Digital Nomad Visa', 'Work', 'Germany Freelance Visa',
'For self-employed professionals and freelancers. Popular among creatives, IT specialists, and consultants. Thriving freelance communities in Berlin and Munich.',
'Viable business plan with service demand proof. Professional qualifications and experience. Sufficient financial resources. German clients or contacts (letters of intent helpful). Must benefit German economy. Regulated professions need German licensing.',
'Business plan, Qualifications, Client letters, €10,000-20,000 funds',
'4-12 weeks',
'Visa fee €100',
'Business plan (market, services, projections), Professional qualifications (degrees, certificates, portfolio), Client letters of intent or contracts, €10,000-20,000 funds proof, Health insurance, CV with experience, Passport, Accommodation proof, Application and photos, Professional license for regulated professions',
'4-12 weeks. Requires Foreigners Office and Chamber of Commerce consultation. IT, creative, and consulting professionals have higher approval rates.',
'1-3 years initially per circumstances. Must show ongoing income and tax compliance for extensions. After 3 years, can apply for permanent residence if meeting income requirements.',
CURRENT_DATE),

('germany', 'any', 'Family Visa', 'Family', 'Germany Family Reunification',
'Reunite with family members in Germany. Clear pathways for spouses, children, and sometimes parents. Process varies by sponsor status and relationship.',
'Sponsor must have valid residence permit (1+ year for some), permanent residence, or citizenship. Adequate space (12 sqm/person minimum). Sufficient income without public assistance. Spouses need A1 German (exceptions for skilled workers, refugees, EU Blue Card families). Children under 16 exempt from language requirement.',
'Relationship proof, Sponsor status, Accommodation, Income, A1 German (spouses)',
'2-6 months',
'Visa fee €75 per person, Language course €150-400',
'Passport, Relationship proof (marriage/birth certificates), Photos, Application form, Sponsor''s permit or passport, Accommodation proof, Sponsor''s income proof (contract, pay slips, tax returns), Health insurance, Spouses: A1 German certificate (Goethe or equivalent), Marriage certificate with translation, Children: birth certificates, custody documents, school records',
'2-6 months depending on embassy. Add 2-4 months for language course. Long appointment wait times at some embassies. Faster processing for Blue Card/skilled worker families.',
'Aligned with sponsor''s permit. With permanent residence/citizenship, family gets 1-3 year permits initially. After 3-5 years, can apply for independent permanent residence. Spouses work immediately. Children attend school.',
CURRENT_DATE),

('germany', 'any', 'Visitor Visa', 'Visit', 'Germany Visit Visa',
'Short-term visit visa for tourism, business, family visits. Part of Schengen Area allowing travel across 27 European countries.',
'Valid reason for visit (tourism, business, family). Sufficient funds for stay. Return ticket. Travel insurance. Intent to return to home country.',
'Passport, Itinerary, Funds proof, €30,000 insurance, Return ticket',
'2-4 weeks',
'Visa fee €80 (€40 for children 6-12)',
'Passport (3+ months beyond stay), Completed application, Photos, Travel itinerary, Hotel bookings or invitation letter, Proof of funds (bank statements), Travel insurance (€30,000 minimum), Employment proof or business registration, Return flight booking',
'2-4 weeks standard. Peak seasons may be longer.',
'Up to 90 days within 180-day period. Cannot work or study. Multiple-entry options available.',
CURRENT_DATE),

-- FRANCE PATHWAYS
('france', 'any', 'Work Visa', 'Work', 'France Skills and Talents Visa',
'For highly skilled professionals, entrepreneurs, and talented individuals contributing to French economy. Multi-year visa with simplified procedures.',
'Exceptional talent in field OR professional project benefiting France. Minimum salary threshold or business plan. Recognition from relevant authorities.',
'Exceptional talent/skills, Business plan or job offer, Recognition proof',
'2-3 months',
'Visa fee €99, OFII fee €225',
'Professional qualifications (degrees, certifications), Job contract or business plan, Proof of expertise (portfolio, publications, awards), Passport, Financial resources proof, Health insurance, Application and photos, Letters of recommendation, CV highlighting achievements',
'2-3 months processing. Requires evaluation by relevant French authority.',
'4 years renewable. Family members included. Can work freely. Path to permanent residence after 5 years.',
CURRENT_DATE),

('france', 'any', 'Work Visa', 'Work', 'France Employee Visa',
'Standard work permit for foreign employees with job offers from French employers. Most common work visa type.',
'Job offer from French employer. Employer must prove no French/EU candidate available (labor market test). Qualifications match position. Fair salary per French standards.',
'Job offer, Employer authorization, Qualifications, Passport',
'2-4 months',
'Visa fee €99, OFII fee €200-300',
'Job contract from French employer, Employer DIRECCTE authorization, Passport (6+ months), Proof of qualifications, CV and references, Health insurance commitment, Accommodation proof, Application and photos, Previous employment records',
'2-4 months including employer authorization process.',
'Initially 1 year, renewable. After 5 years continuous residence, eligible for 10-year residence card. Family reunification possible after 18 months.',
CURRENT_DATE),

('france', 'any', 'Study Visa', 'Study', 'France Student Visa',
'Study at French universities, grandes écoles, and institutions. Can work part-time (964 hours/year). Post-study work permit available.',
'Admission to French higher education institution. Financial resources (€615/month or €7,380/year minimum). Health insurance. Adequate French or English language skills.',
'Admission, €615/month funds, Insurance, Language certificate',
'2-8 weeks',
'Visa fee €50-99, Campus France fee €70-215, OFII fee €90',
'University admission letter or pre-enrollment certificate, Financial proof (€615/month, bank statements or scholarship), Health insurance, Passport, Academic records with translations, Language certificate (DELF/DALF B2+ for French programs or IELTS/TOEFL for English), Motivation letter, CV, Application and photos, Accommodation proof',
'2-8 weeks after Campus France interview. Apply 3-4 months before start.',
'Duration of studies. Can work 964 hours/year part-time. After graduation, 1-year job search permit (APS) available. Convert to work permit when employed.',
CURRENT_DATE),

('france', 'any', 'Digital Nomad Visa', 'Work', 'France Auto-Entrepreneur Visa',
'For self-employed professionals and entrepreneurs. Popular among consultants, designers, developers, and service providers.',
'Viable business plan serving French or international clients. Professional qualifications. Sufficient financial resources. Business must benefit French economy.',
'Business plan, Qualifications, €15,000+ funds, Insurance',
'1-3 months',
'Visa fee €99, Registration fees €25-150',
'Detailed business plan, Professional qualifications, Portfolio or previous work samples, €15,000+ financial proof, Health insurance for 1 year, Passport, Accommodation proof, CV, Application and photos, Client contracts or letters of intent',
'1-3 months. May require French Chamber of Commerce consultation.',
'1 year initially, renewable if business viable. After 3-5 years, can apply for 10-year residence card. Must register as auto-entrepreneur with URSSAF.',
CURRENT_DATE),

('france', 'any', 'Family Visa', 'Family', 'France Family Reunification',
'Join family members in France. Covers spouses, minor children, and sometimes parents. Clear requirements and procedures.',
'Sponsor must have stable residence status (residence card valid 1+ year). Adequate housing (minimum sizes apply per family size). Sufficient stable income (minimum varies by region, typically €1,300+/month). Resources without social assistance. 18+ months residence for sponsor before applying.',
'Sponsor status (18+ months), Adequate housing, €1,300+ income, Relationship proof',
'6-12 months',
'Visa fee €99, OFII fee €200',
'Passport, Relationship proof (marriage/birth certificates with translations), Photos, Application (OFII), Sponsor residence permit, Housing proof (lease, property deed, utility bills), Income proof (3+ months pay slips, tax returns), Health insurance, French language evaluation (for spouses), Integration contract signature',
'6-12 months processing time. OFII evaluation required.',
'Linked to sponsor status. Family receives residence permit. After admission, attend OFII integration program. Spouses work immediately. Children attend school. After 3-5 years, can apply for independent status.',
CURRENT_DATE),

('france', 'any', 'Visitor Visa', 'Visit', 'France Schengen Visa',
'Short-term visa for tourism, business, family visits. Access to Schengen Area (27 countries).',
'Valid visit purpose. Sufficient funds for stay. Return arrangements. Travel insurance. Intent to leave Schengen area.',
'Passport, Itinerary, Funds, €30,000 insurance, Return ticket',
'2-3 weeks',
'Visa fee €80 (€40 for children 6-12)',
'Passport (3+ months beyond stay), Application and photos, Travel itinerary, Accommodation proof, Financial means (€65-120/day depending on accommodation), €30,000+ travel insurance, Employment/student/retirement proof, Return flight, Invitation letter if visiting family',
'2-3 weeks standard processing.',
'Up to 90 days within 180-day period. Cannot work or study. Multiple-entry available.',
CURRENT_DATE),

-- NETHERLANDS PATHWAYS
('netherlands', 'any', 'Work Visa', 'Work', 'Netherlands Highly Skilled Migrant Visa',
'Streamlined work permit for highly skilled workers. Recognized sponsors can hire without labor market testing. Popular route for international professionals.',
'Job offer from IND-recognized sponsor. Minimum monthly salary: €5,331 (2024, under 30) or €6,166 (30+). Lower for recent graduates: €3,909. Position requires high qualification level. Sponsor handles application.',
'Recognized sponsor job, €5,331+ salary (under 30) or €6,166+ (30+), Qualifications',
'1-2 weeks',
'Application fee €291 (paid by sponsor)',
'Job contract from recognized sponsor, Passport, Diploma and transcripts with apostille, CV, Passport photos, Health insurance proof, Criminal record certificate (if required), Proof of previous legal residence if applicable',
'1-2 weeks for most applications when sponsor applies. Very fast processing.',
'Initially up to 5 years based on contract. Free job mobility after first year with same salary level. After 5 years, eligible for permanent residence. Family members included on same permit.',
CURRENT_DATE),

('netherlands', 'any', 'Digital Nomad Visa', 'Work', 'Netherlands Self-Employment Visa',
'For entrepreneurs and freelancers. Requires demonstrating value to Dutch economy. Point-based assessment system.',
'Viable business plan benefiting Netherlands. Pass points test (score 30+ from 300). Financial resources. Relevant experience and qualifications. Some nationalities need mentor agreements.',
'Business plan, 30+ points, €4,500+ funds, Relevant experience',
'3-6 months',
'Application fee €1,412, KVK registration €50',
'Business plan (detailed, in English), Financial statements (€4,500+ in business account), Proof of expertise (diplomas, work experience), CV, Chamber of Commerce registration intent, Passport, Health insurance comprehensive coverage, Accommodation proof, Application form, Additional requirements vary by nationality (some need Dutch mentor/host)',
'3-6 months for decision. Complex evaluation process.',
'2 years initially. Must show business progress for renewal. After 5 years successful self-employment, eligible for permanent residence. Must register with KVK (Chamber of Commerce).',
CURRENT_DATE),

('netherlands', 'any', 'Study Visa', 'Study', 'Netherlands Student Visa',
'Study at Dutch universities and institutions. Many programs in English. Can work part-time and find employment after graduation.',
'Admission to Dutch recognized institution. Financial resources (€11,600/year minimum for 2024). Health insurance. Sufficient English or Dutch language skills.',
'Admission, €11,600/year funds, Insurance, Language certificate',
'4-12 weeks',
'MVV fee €350, Residence permit €311',
'University admission letter (unconditional), Financial proof (€11,600+/year via bank statement, scholarship, or guarantee), Health insurance meeting Dutch requirements, Passport (6+ months validity), Academic records, Language certificate (IELTS 6.0+/TOEFL 80+ or Dutch NT2), Completed MVV application, Passport photos, Tuberculosis test results (for some nationalities)',
'4-12 weeks after application submission.',
'Duration of studies. Can work 16 hours/week during term, full-time in June-August. After graduation, 1-year search year permit to find work. Convert to work permit when employed.',
CURRENT_DATE),

('netherlands', 'any', 'Work Visa', 'Work', 'Netherlands Orientation Year Visa',
'For recent graduates from top universities worldwide to find employment in Netherlands. No job offer required initially.',
'Graduated within past 3 years from top 200 university (QS, Times Higher Education, or Shanghai Ranking). Bachelor or higher degree. Under certain age limits. Sufficient financial resources.',
'Top 200 university degree, Graduated within 3 years, €11,000+ funds',
'4-8 weeks',
'Application fee €341',
'University degree (Bachelor, Master, or PhD), Proof university in top 200 at graduation time, Graduation within last 3 years proof, Passport, Financial resources (€11,000+ recommended), Health insurance, Criminal record certificate, Completed application, Passport photos',
'4-8 weeks processing.',
'1 year. Can work without restrictions during this year. No extension, but can switch to Highly Skilled Migrant or other permit when employment found. Popular pathway for international graduates.',
CURRENT_DATE),

('netherlands', 'any', 'Family Visa', 'Family', 'Netherlands Family Reunification',
'Join family members in Netherlands. Pathways for spouses, partners, children, and parents.',
'Sponsor must have valid residence permit or Dutch nationality. Adequate housing (minimum space requirements apply). Sufficient income (120% of social assistance level, approximately €1,800/month). Health insurance. Meet integration requirements if applicable.',
'Sponsor permit, €1,800+ income, Adequate housing, Relationship proof, Basic Dutch (spouses)',
'3-6 months',
'MVV fee €350 per person, Residence permit €311, Basic Dutch exam €150',
'Passport, Relationship proof (marriage certificate, birth certificates, partnership registration), Proof of identity and nationality (birth certificate, national ID), Photos, Health declaration, Sponsor residence permit or Dutch passport, Income proof (employment contract, 3 months pay slips, bank statements), Housing proof (rental contract minimum 6 months or property deed), Health insurance, Tuberculosis test (some nationalities), Basic Dutch exam results (for spouses/partners - exceptions apply)',
'3-6 months processing time.',
'Initially linked to sponsor permit duration. When sponsor has permanent residence or citizenship, family gets permit for 5 years. After 5 years, eligible for permanent residence. Spouses can work immediately. Children attend school. Integration program participation required.',
CURRENT_DATE),

('netherlands', 'any', 'Visitor Visa', 'Visit', 'Netherlands Schengen Visa',
'Short-term visa for tourism, business, visiting family/friends. Part of Schengen Area.',
'Valid visit reason. Sufficient funds. Accommodation arrangements. Travel insurance. Intent to return.',
'Passport, €30,000 insurance, Accommodation, €34/day funds, Return ticket',
'2-3 weeks',
'Visa fee €80 (€40 for children 6-12)',
'Passport (3+ months beyond stay, issued within 10 years), Completed application signed, Recent passport photos, Travel insurance (€30,000+ coverage), Proof of accommodation, Financial means proof (€34/day minimum, bank statements), Return flight booking, Employment letter or business registration, Invitation letter if visiting someone, Travel itinerary',
'2-3 weeks standard processing. Peak season may be longer.',
'Up to 90 days within 180-day period. Cannot work. Multiple-entry available.',
CURRENT_DATE);
