/*
  # Complete Country Guides Part 3 - Healthcare and Education Systems

  1. Purpose
    - Adds healthcare_system and education_system information
    - Comprehensive information for all 52 countries
*/

UPDATE country_guides SET
  healthcare_system = CASE country_slug
    WHEN 'argentina' THEN 'Public healthcare available but quality varies. Private insurance recommended. Good care in major cities.'
    WHEN 'australia' THEN 'Excellent public healthcare (Medicare). Private insurance available. High quality care nationwide.'
    WHEN 'austria' THEN 'Universal public healthcare. Excellent quality. Private options available. EU citizens covered.'
    WHEN 'belgium' THEN 'Universal healthcare. Excellent quality. Reimbursement system. Private insurance supplements.'
    WHEN 'brazil' THEN 'Public system (SUS) free but overburdened. Private insurance recommended. Good private care.'
    WHEN 'canada' THEN 'Universal public healthcare. Free for residents. Wait times can be long. High quality care.'
    WHEN 'chile' THEN 'Public and private systems. Private insurance common. Good quality care in private sector.'
    WHEN 'china' THEN 'Public insurance expanding. Private care better quality. International hospitals in major cities.'
    WHEN 'colombia' THEN 'Universal healthcare. Good quality. Medical tourism destination. Private insurance available.'
    WHEN 'croatia' THEN 'Public healthcare for residents. EU coverage. Good quality. Private options available.'
    WHEN 'czech-republic' THEN 'Universal public healthcare. Good quality. EU citizens covered. Private options available.'
    WHEN 'denmark' THEN 'Universal public healthcare. Excellent quality. Free for residents. High satisfaction rates.'
    WHEN 'egypt' THEN 'Public healthcare limited. Private care recommended. Affordable private hospitals in cities.'
    WHEN 'finland' THEN 'Universal public healthcare. Excellent quality. Some private options. High standard of care.'
    WHEN 'france' THEN 'Excellent universal healthcare. World-class system. Reimbursement model. Supplemental insurance common.'
    WHEN 'germany' THEN 'Universal healthcare. Public and private options. Excellent quality. Mandatory insurance.'
    WHEN 'greece' THEN 'Public healthcare for residents. EU coverage. Quality varies. Private options better.'
    WHEN 'hungary' THEN 'Universal public healthcare. EU citizens covered. Quality varies. Private care available.'
    WHEN 'india' THEN 'Public healthcare limited. Private hospitals good quality and affordable. Insurance recommended.'
    WHEN 'indonesia' THEN 'Public insurance available. Private hospitals better quality. Affordable private care.'
    WHEN 'ireland' THEN 'Public healthcare available. Long wait times. Private insurance common. Good quality overall.'
    WHEN 'israel' THEN 'Universal healthcare. Excellent quality. Multiple providers. High technology medical care.'
    WHEN 'italy' THEN 'Universal public healthcare (SSN). Good quality. Some regional variation. Private options available.'
    WHEN 'japan' THEN 'Universal healthcare. Excellent quality. Affordable. High life expectancy. Advanced medical care.'
    WHEN 'malaysia' THEN 'Public healthcare good and cheap. Excellent private care. Medical tourism destination.'
    WHEN 'mexico' THEN 'Public IMSS system. Private care excellent and affordable. Medical tourism popular.'
    WHEN 'morocco' THEN 'Public healthcare limited. Private care recommended. Affordable private hospitals in cities.'
    WHEN 'netherlands' THEN 'Universal healthcare. Mandatory insurance. Excellent quality. High satisfaction rates.'
    WHEN 'new-zealand' THEN 'Public healthcare free for residents. Good quality. Private insurance for faster access.'
    WHEN 'nigeria' THEN 'Public healthcare limited. Private care recommended. Quality varies. Insurance important.'
    WHEN 'norway' THEN 'Universal public healthcare. Excellent quality. Free for residents. High standard of care.'
    WHEN 'peru' THEN 'Public and private systems. Private care recommended. Affordable private hospitals.'
    WHEN 'philippines' THEN 'Public healthcare limited. Private care good and affordable. Insurance recommended.'
    WHEN 'poland' THEN 'Public healthcare for residents. EU coverage. Quality improving. Private options available.'
    WHEN 'portugal' THEN 'Universal public healthcare (SNS). Good quality. EU citizens covered. Private options available.'
    WHEN 'qatar' THEN 'Public healthcare for residents. Excellent facilities. Mandatory insurance for expats.'
    WHEN 'romania' THEN 'Public healthcare for residents. EU coverage. Quality varies. Private care available.'
    WHEN 'russia' THEN 'Public healthcare available. Quality varies greatly. Private care recommended in cities.'
    WHEN 'saudi-arabia' THEN 'Public healthcare for residents. Good quality. Private hospitals excellent. Insurance common.'
    WHEN 'singapore' THEN 'Excellent healthcare system. Subsidized public care. World-class private hospitals. Insurance important.'
    WHEN 'south-africa' THEN 'Two-tier system. Public healthcare strained. Private healthcare excellent and affordable. Insurance essential.'
    WHEN 'south-korea' THEN 'Universal healthcare. Excellent quality. Affordable. Advanced medical technology.'
    WHEN 'spain' THEN 'Universal public healthcare. Excellent quality. Free for residents. EU citizens covered.'
    WHEN 'sweden' THEN 'Universal public healthcare. Excellent quality. High taxes fund system. High satisfaction.'
    WHEN 'switzerland' THEN 'Universal healthcare. Mandatory insurance. Excellent quality. Expensive but world-class.'
    WHEN 'thailand' THEN 'Public healthcare available. Excellent private care. Medical tourism hub. Very affordable.'
    WHEN 'turkey' THEN 'Universal healthcare improving. Private care good and affordable. Medical tourism growing.'
    WHEN 'ukraine' THEN 'Public healthcare free but underfunded. Private care available. Quality varies. Current challenges.'
    WHEN 'united-arab-emirates' THEN 'Excellent healthcare facilities. Mandatory insurance. High quality private care. Expensive without insurance.'
    WHEN 'united-kingdom' THEN 'NHS universal healthcare. Free for residents. Wait times can be long. Good quality care.'
    WHEN 'united-states' THEN 'Private insurance-based system. No universal coverage. Excellent quality but very expensive. Insurance essential.'
    WHEN 'vietnam' THEN 'Public healthcare improving. Private care good and affordable. International hospitals in cities.'
  END,
  education_system = CASE country_slug
    WHEN 'argentina' THEN 'Free public education. University of Buenos Aires well-regarded. Private schools available.'
    WHEN 'australia' THEN 'Excellent education system. Top universities. Public and private schools. High international rankings.'
    WHEN 'austria' THEN 'Excellent free public education. Top universities. High standards. German language instruction.'
    WHEN 'belgium' THEN 'Excellent education system. Free public schools. Top universities. Language-based divisions.'
    WHEN 'brazil' THEN 'Public education quality varies. Private schools better. Several good universities. Expanding access.'
    WHEN 'canada' THEN 'Excellent education system. Top universities. Public schools very good. High international rankings.'
    WHEN 'chile' THEN 'Mixed quality. Private schools better. Several good universities. Education reforms ongoing.'
    WHEN 'china' THEN 'Competitive education system. Top universities. International schools available. High academic pressure.'
    WHEN 'colombia' THEN 'Quality varies. Private schools better. Several good universities. Education improving.'
    WHEN 'croatia' THEN 'Good public education. EU standards. University of Zagreb notable. Free public universities.'
    WHEN 'czech-republic' THEN 'Good public education. Free universities. Charles University prestigious. High literacy rates.'
    WHEN 'denmark' THEN 'Excellent free education. Top universities. Progressive system. High quality throughout.'
    WHEN 'egypt' THEN 'Public education overcrowded. Private schools better. Cairo University notable. Quality varies.'
    WHEN 'finland' THEN 'World-class education system. Free university. Best in international rankings. Progressive methods.'
    WHEN 'france' THEN 'Excellent public education. Grandes écoles system. Top universities. Free public universities.'
    WHEN 'germany' THEN 'Excellent free education. Top universities. Free university tuition. High standards throughout.'
    WHEN 'greece' THEN 'Good public education. Free universities. Ancient academic tradition. EU standards.'
    WHEN 'hungary' THEN 'Good public education. Free public universities. Several notable institutions. EU standards.'
    WHEN 'india' THEN 'Quality varies greatly. IITs world-renowned. Private schools better. Competitive examinations.'
    WHEN 'indonesia' THEN 'Quality varies. Private schools better. Several good universities. Education expanding.'
    WHEN 'ireland' THEN 'Excellent education system. Top universities. English-language. Trinity College Dublin prestigious.'
    WHEN 'israel' THEN 'Excellent education system. World-class universities. High tech focus. Hebrew University notable.'
    WHEN 'italy' THEN 'Good public education. Ancient universities. Bologna oldest in Europe. Free public universities.'
    WHEN 'japan' THEN 'Excellent education system. Top universities. Competitive. Tokyo University world-renowned.'
    WHEN 'malaysia' THEN 'Good education system. English-medium options. Several good universities. International schools available.'
    WHEN 'mexico' THEN 'Quality varies. Private schools better. UNAM large public university. International schools available.'
    WHEN 'morocco' THEN 'French-based system. Quality varies. Private schools better. Universities in major cities.'
    WHEN 'netherlands' THEN 'Excellent education system. Top universities. English programs available. High quality throughout.'
    WHEN 'new-zealand' THEN 'Excellent education system. Top universities. English-language. High international rankings.'
    WHEN 'nigeria' THEN 'Quality varies greatly. Private schools better. Several universities. Education challenges remain.'
    WHEN 'norway' THEN 'Excellent free education. Top universities. Progressive system. Free university tuition.'
    WHEN 'peru' THEN 'Quality varies. Private schools better. Several universities. Lima has best options.'
    WHEN 'philippines' THEN 'English-medium education. Quality varies. Private schools better. Several good universities.'
    WHEN 'poland' THEN 'Good public education. Free public universities. Jagiellonian University prestigious. EU standards.'
    WHEN 'portugal' THEN 'Good public education. Free public universities. University of Coimbra ancient. EU standards.'
    WHEN 'qatar' THEN 'Good education system. Education City hub. International schools excellent. Investing heavily.'
    WHEN 'romania' THEN 'Good public education. Free public universities. Several notable institutions. EU standards.'
    WHEN 'russia' THEN 'Good education system. Strong in sciences. Moscow State University prestigious. Free public universities.'
    WHEN 'saudi-arabia' THEN 'Improving education system. Investing heavily. International schools available. Universities expanding.'
    WHEN 'singapore' THEN 'World-class education system. Top universities. English-medium. Consistently high rankings.'
    WHEN 'south-africa' THEN 'Mixed quality. Private schools and universities good. Several top universities. International schools available.'
    WHEN 'south-korea' THEN 'Excellent education system. Top universities. Highly competitive. Seoul National University prestigious.'
    WHEN 'spain' THEN 'Good public education. Free public universities. Several top institutions. EU standards.'
    WHEN 'sweden' THEN 'Excellent free education. Top universities. Progressive methods. Free university tuition.'
    WHEN 'switzerland' THEN 'Excellent education system. World-class universities. ETH Zurich top-ranked. High standards.'
    WHEN 'thailand' THEN 'Quality varies. Private schools and international schools good. Several universities. Bangkok has best options.'
    WHEN 'turkey' THEN 'Good public education. Several top universities. Quality improving. International schools in cities.'
    WHEN 'ukraine' THEN 'Good education system. Strong in sciences. Free public universities. Quality affected by conflict.'
    WHEN 'united-arab-emirates' THEN 'Good education system. Many international schools. Universities expanding. English-medium options.'
    WHEN 'united-kingdom' THEN 'Excellent education system. World-class universities. Oxford, Cambridge. High international rankings.'
    WHEN 'united-states' THEN 'Varied quality. Top universities world-renowned. Ivy League. Public schools vary by location. Expensive higher education.'
    WHEN 'vietnam' THEN 'Education system improving. Quality varies. Private schools better. Universities expanding.'
  END,
  updated_at = now()
WHERE country_slug IN (
  'argentina', 'australia', 'austria', 'belgium', 'brazil', 'canada', 'chile', 'china',
  'colombia', 'croatia', 'czech-republic', 'denmark', 'egypt', 'finland', 'france',
  'germany', 'greece', 'hungary', 'india', 'indonesia', 'ireland', 'israel', 'italy',
  'japan', 'malaysia', 'mexico', 'morocco', 'netherlands', 'new-zealand', 'nigeria',
  'norway', 'peru', 'philippines', 'poland', 'portugal', 'qatar', 'romania', 'russia',
  'saudi-arabia', 'singapore', 'south-africa', 'south-korea', 'spain', 'sweden',
  'switzerland', 'thailand', 'turkey', 'ukraine', 'united-arab-emirates',
  'united-kingdom', 'united-states', 'vietnam'
);
