/*
  # Add Missing Pathways - Batch 1

  Adds missing goal pathways for destinations with incomplete coverage:
  Algeria, Armenia, Azerbaijan, Bahamas, Bahrain, Bangladesh, Barbados,
  Bolivia, Bulgaria, Cambodia, Costa Rica, Cuba, Cyprus

  Each record includes all required fields: key_requirements, typical_timeline, estimated_fees.
*/

INSERT INTO immigration_pathways (passport_slug, destination_slug, goal, pathway_name, summary, eligibility, key_requirements, typical_timeline, estimated_fees, pathway_type, requirements, processing_time, validity_period, official_url, last_updated)
VALUES

-- ALGERIA missing goals
('any','algeria','Study','Algeria Student Visa','Study at Algerian universities with a student residence permit.','Open to international students accepted by an Algerian university.','Valid passport; university acceptance letter; proof of financial support (~$300/month); health insurance.','4-8 weeks','Low cost (government-sponsored programs often free)','study','University acceptance letter, proof of financial support (~$300/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.education.gov.dz','2025-01-01'),
('any','algeria','Family','Algeria Family Reunification Visa','Join a family member who is a legal resident or citizen of Algeria.','Immediate family members (spouse, children) of Algerian residents or citizens.','Valid passport; proof of family relationship (marriage/birth certificate); sponsor proof of residency; financial support documents; health certificate.','6-12 weeks','Nominal government fees','family','Proof of family relationship, sponsor proof of residency/citizenship, financial support documents, health certificate.','6-12 weeks','1 year, renewable','https://www.interieur.gov.dz','2025-01-01'),
('any','algeria','Retirement','Algeria Retirement Residence Permit','Retire in Algeria with a long-stay residence permit.','Retirees with pension income and no intent to work locally.','Valid passport; proof of pension income; health insurance; accommodation proof; background check.','6-10 weeks','Nominal government fees','retirement','Proof of pension income, health insurance, accommodation proof, valid passport, background check.','6-10 weeks','1 year, renewable','https://www.interieur.gov.dz','2025-01-01'),
('any','algeria','Digital Nomad','Algeria Long-Stay Visa for Remote Workers','Work remotely from Algeria on a long-stay visa.','Remote workers employed by non-Algerian companies.','Valid passport; employment contract; proof of remote income; health insurance; accommodation details.','4-8 weeks','Nominal government fees','digital_nomad','Employment contract, proof of remote income, health insurance, accommodation details.','4-8 weeks','1 year','https://www.interieur.gov.dz','2025-01-01'),

-- ARMENIA missing goals
('any','armenia','Study','Armenia Student Residence Permit','Study at Armenian universities with a student residence permit.','Accepted students at Armenian higher education institutions.','Valid passport; university acceptance letter; proof of finances (~$400/month); health insurance.','2-4 weeks','AMD 10,000-20,000 (~$25-50)','study','University acceptance letter, proof of finances (~$400/month), health insurance.','2-4 weeks','1 year, renewable','https://migration.gov.am','2025-01-01'),
('any','armenia','Family','Armenia Family Reunification','Join a spouse or family member residing legally in Armenia.','Spouses and dependent children of Armenian residents.','Valid passport; marriage/birth certificate; sponsor proof of residency; financial support documents.','3-6 weeks','AMD 15,000-30,000 (~$35-75)','family','Marriage/birth certificate, sponsor proof of residency, financial support documents.','3-6 weeks','1 year, renewable','https://migration.gov.am','2025-01-01'),
('any','armenia','Retirement','Armenia Retirement Residence','Retire in Armenia, one of the most affordable retirement destinations.','Retirees with sufficient passive income (pension or savings).','Valid passport; proof of pension/income (~$500/month); health insurance; accommodation proof.','2-4 weeks','AMD 15,000 (~$35)','retirement','Proof of pension/income (~$500/month), health insurance, accommodation proof.','2-4 weeks','1 year, renewable','https://migration.gov.am','2025-01-01'),
('any','armenia','Digital Nomad','Armenia Digital Nomad (Remote Work)','Live and work remotely in Armenia with a standard residence permit.','Remote workers and freelancers working for non-Armenian companies.','Valid passport; proof of remote employment/income; health insurance; accommodation.','2-4 weeks','AMD 15,000 (~$35)','digital_nomad','Proof of remote employment/income, health insurance, accommodation.','2-4 weeks','1 year, renewable','https://migration.gov.am','2025-01-01'),
('any','armenia','Investor','Armenia Investor Residence','Invest in Armenia and obtain long-term residence.','Investors making qualified investments in Armenian businesses or real estate.','Valid passport; business registration or investment documentation; proof of investment (~$150,000+).','4-8 weeks','AMD 50,000+ (~$125+)','investor','Business registration or investment documentation, proof of investment (~$150,000+).','4-8 weeks','3 years, renewable','https://migration.gov.am','2025-01-01'),

-- AZERBAIJAN missing goals
('any','azerbaijan','Study','Azerbaijan Student Visa','Enroll at Azerbaijani universities on a student visa.','International students accepted to Azerbaijani universities.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','Low government fees','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.migration.gov.az','2025-01-01'),
('any','azerbaijan','Family','Azerbaijan Family Reunification','Join a legally residing family member in Azerbaijan.','Spouses and children of Azerbaijani residents.','Valid passport; family relationship proof; sponsor residence documents; financial support.','4-8 weeks','Low government fees','family','Family relationship proof, sponsor residence documents, financial support.','4-8 weeks','1 year, renewable','https://www.migration.gov.az','2025-01-01'),
('any','azerbaijan','Retirement','Azerbaijan Retirement Residence Permit','Retire in Baku and benefit from a low cost of living.','Retirees with steady pension income.','Valid passport; proof of pension; health insurance; accommodation proof; clean criminal record.','4-8 weeks','AZN 100-300 (~$60-175)','retirement','Proof of pension, health insurance, accommodation proof, clean criminal record.','4-8 weeks','1 year, renewable','https://www.migration.gov.az','2025-01-01'),
('any','azerbaijan','Digital Nomad','Azerbaijan Remote Work Residence','Work remotely from Azerbaijan with a long-stay residence permit.','Freelancers and remote employees of foreign companies.','Valid passport; proof of income; employment contract; health insurance.','3-6 weeks','AZN 100-300 (~$60-175)','digital_nomad','Proof of income, employment contract, health insurance.','3-6 weeks','1 year, renewable','https://www.migration.gov.az','2025-01-01'),

-- BAHAMAS missing goals
('any','bahamas','Study','Bahamas Student Permit','Study at a Bahamian educational institution on a student permit.','International students accepted to Bahamian institutions.','Valid passport; school acceptance letter; proof of finances; health insurance.','4-8 weeks','BSD 25-100','study','School acceptance letter, proof of finances, health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.immigration.gov.bs','2025-01-01'),
('any','bahamas','Family','Bahamas Family Permit','Join a Bahamian resident or citizen as a dependent family member.','Spouses and children of Bahamian residents/citizens.','Valid passport; proof of relationship; sponsor financial capacity.','4-8 weeks','BSD 50-200','family','Proof of relationship, sponsor financial capacity, valid passport.','4-8 weeks','1 year, renewable','https://www.immigration.gov.bs','2025-01-01'),
('any','bahamas','Retirement','Bahamas Annual Homeowner Retirement Permit','Retire in the Bahamas with the Annual Homeowner Retirement Card.','Retirees 50+ with sufficient passive income or property ownership.','Valid passport; proof of income ($1,500+/month); property ownership or lease; health insurance.','4-8 weeks','BSD 1,500-2,000 annually','retirement','Proof of income ($1,500+/month), property ownership or lease, health insurance.','4-8 weeks','Annual renewable','https://www.immigration.gov.bs','2025-01-01'),
('any','bahamas','Digital Nomad','Bahamas Extended Access Travel Stay (BEATS)','Work remotely from the Bahamas on the BEATS digital nomad program.','Remote workers and self-employed persons working for non-Bahamian clients.','Valid passport; proof of employment or self-employment; $1,000 application fee; health insurance.','2-4 weeks','USD 1,000 application fee','digital_nomad','Proof of employment or self-employment, $1,000 application fee, health insurance.','2-4 weeks','1 year','https://www.immigration.gov.bs','2025-01-01'),

-- BAHRAIN missing goals
('any','bahrain','Study','Bahrain Student Visa','Study at Bahraini universities and colleges.','Students accepted at Bahraini higher education institutions.','Valid passport; university acceptance letter; financial support (~$500/month); health insurance.','3-5 weeks','BHD 50-200 (~$133-530)','study','University acceptance letter, financial support (~$500/month), valid passport, health insurance.','3-5 weeks','1 year, renewable','https://www.immigration.gov.bh','2025-01-01'),
('any','bahrain','Family','Bahrain Family Residence Visa','Sponsor family members to reside in Bahrain.','Bahraini residents/citizens sponsoring spouse and children.','Valid passport; proof of relationship; sponsor salary ($800+/month); accommodation proof; medical checks.','3-6 weeks','BHD 100-300 (~$265-795)','family','Proof of relationship, sponsor salary ($800+/month), accommodation proof, medical checks.','3-6 weeks','2 years, renewable','https://www.immigration.gov.bh','2025-01-01'),
('any','bahrain','Retirement','Bahrain Retirement Residence','Retire in Bahrain on a retirement residence permit.','Retirees with sufficient income or significant real estate investment.','Valid passport; proof of pension or real estate investment ($500,000+); health insurance.','4-8 weeks','BHD 200-500 (~$530-1325)','retirement','Proof of pension or investment ($500,000+ property), health insurance.','4-8 weeks','2 years, renewable','https://www.immigration.gov.bh','2025-01-01'),
('any','bahrain','Digital Nomad','Bahrain Remote Work Visa','Live and work remotely from Bahrain.','Digital nomads and remote workers employed by foreign companies.','Valid passport; employment contract; proof of income ($1,500+/month); health insurance.','2-4 weeks','BHD 100-200 (~$265-530)','digital_nomad','Employment contract, proof of income ($1,500+/month), health insurance.','2-4 weeks','1 year','https://www.immigration.gov.bh','2025-01-01'),

-- BANGLADESH missing goals
('any','bangladesh','Study','Bangladesh Student Visa','Study at Bangladeshi universities and institutions.','International students accepted to Bangladeshi educational institutions.','Valid passport; acceptance letter; proof of finances; health insurance.','3-6 weeks','Low government fees','study','Acceptance letter, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.dip.gov.bd','2025-01-01'),
('any','bangladesh','Family','Bangladesh Family Visa','Join a family member residing legally in Bangladesh.','Spouses and dependent children of Bangladeshi residents.','Valid passport; family relationship proof; sponsor documents; financial capacity.','4-8 weeks','BDT 3,000-10,000 (~$25-85)','family','Family relationship proof, sponsor documents, financial capacity.','4-8 weeks','1 year, renewable','https://www.dip.gov.bd','2025-01-01'),
('any','bangladesh','Retirement','Bangladesh Retirement Visa','Retire in Bangladesh with a long-stay visa.','Retirees with sufficient pension income.','Valid passport; proof of pension income; health insurance; accommodation proof.','3-6 weeks','BDT 5,000-15,000 (~$45-130)','retirement','Proof of pension income, health insurance, accommodation proof.','3-6 weeks','1 year, renewable','https://www.dip.gov.bd','2025-01-01'),
('any','bangladesh','Digital Nomad','Bangladesh Digital Nomad Long Stay','Work remotely from Bangladesh on a multiple-entry visa.','Remote workers and freelancers.','Valid passport; proof of remote employment; income evidence; health insurance.','2-4 weeks','BDT 5,000-10,000 (~$45-85)','digital_nomad','Proof of remote employment, income evidence, health insurance.','2-4 weeks','1 year','https://www.dip.gov.bd','2025-01-01'),

-- BARBADOS missing goals
('any','barbados','Study','Barbados Student Permit','Study at Barbadian educational institutions.','International students accepted to Barbadian schools or the University of the West Indies.','Valid passport; acceptance letter; proof of finances; health insurance.','3-6 weeks','BBD 50-200','study','Acceptance letter, proof of finances, health insurance, valid passport.','3-6 weeks','Duration of study','https://www.immigration.gov.bb','2025-01-01'),
('any','barbados','Family','Barbados Family Permit','Join a Barbadian resident or citizen as a family member.','Spouses and dependent children of Barbadian residents/citizens.','Valid passport; marriage/birth certificate; sponsor documents; financial support proof.','4-8 weeks','BBD 100-300','family','Marriage/birth certificate, sponsor documents, financial support proof.','4-8 weeks','1 year, renewable','https://www.immigration.gov.bb','2025-01-01'),
('any','barbados','Retirement','Barbados Special Entry and Reside Permit (Retirement)','Retire in Barbados with a special entry permit.','Retirees with proven passive income.','Valid passport; proof of income ($2,000+/month); health insurance; clean criminal record.','4-8 weeks','BBD 500-1,000','retirement','Proof of income ($2,000+/month), health insurance, clean criminal record.','4-8 weeks','5 years, renewable','https://www.immigration.gov.bb','2025-01-01'),
('any','barbados','Investor','Barbados Investor Permit','Invest in Barbados and obtain long-term residency.','Investors making substantial investment in Barbados ($125,000+).','Valid passport; business plan or investment documentation; proof of funds ($125,000+); legal registration.','6-12 weeks','BBD 1,000-2,500','investor','Business plan or investment documentation, proof of funds, legal registration.','6-12 weeks','5 years, renewable','https://www.investbarbados.org','2025-01-01'),

-- BOLIVIA missing goals
('any','bolivia','Study','Bolivia Student Visa','Study at Bolivian universities.','International students accepted to Bolivian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','BOB 200-500 (~$29-73)','study','University acceptance, proof of finances, health insurance.','3-6 weeks','1 year, renewable','https://www.migracion.gob.bo','2025-01-01'),
('any','bolivia','Family','Bolivia Family Reunification Visa','Join a legally residing family member in Bolivia.','Spouses and children of Bolivian residents or citizens.','Valid passport; marriage/birth certificates; sponsor documents; financial proof.','4-8 weeks','BOB 300-600 (~$44-87)','family','Marriage/birth certificates, sponsor documents, financial proof.','4-8 weeks','1 year, renewable','https://www.migracion.gob.bo','2025-01-01'),
('any','bolivia','Retirement','Bolivia Retirement Visa','Retire in one of South America most affordable countries.','Retirees with verified pension income.','Valid passport; proof of pension ($1,000+/month); health insurance; clean criminal record.','4-6 weeks','BOB 500-1,000 (~$73-146)','retirement','Proof of pension ($1,000+/month), health insurance, clean criminal record.','4-6 weeks','1 year, renewable','https://www.migracion.gob.bo','2025-01-01'),
('any','bolivia','Digital Nomad','Bolivia Digital Nomad Visa','Work remotely from Bolivia on a long-stay visa.','Remote workers and freelancers.','Valid passport; proof of remote employment; income evidence; health insurance.','3-5 weeks','BOB 300-600 (~$44-87)','digital_nomad','Proof of remote employment, income evidence, health insurance.','3-5 weeks','1 year','https://www.migracion.gob.bo','2025-01-01'),

-- BULGARIA missing goals
('any','bulgaria','Study','Bulgaria Student Visa (Type D)','Study at Bulgarian universities on a long-stay student visa.','Students accepted to Bulgarian higher education.','Valid passport; university acceptance letter; proof of finances; health insurance.','3-6 weeks','BGN 50-200 (~$27-110)','study','University acceptance letter, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.mvr.bg','2025-01-01'),
('any','bulgaria','Family','Bulgaria Family Reunification','Join a legal resident of Bulgaria as a family member.','Spouses and minor children of Bulgarian residents.','Valid passport; proof of family relationship; sponsor financial capacity (BGN 300/month per family member); accommodation.','6-10 weeks','BGN 50-200 (~$27-110)','family','Proof of family relationship, sponsor financial capacity (BGN 300/month per family member), accommodation.','6-10 weeks','1 year, renewable','https://www.mvr.bg','2025-01-01'),
('any','bulgaria','Retirement','Bulgaria Retirement Residence Permit','Retire in Bulgaria, one of the EU most affordable retirement destinations.','Retirees with proven pension income meeting minimum thresholds.','Valid passport; proof of pension (600+EUR/month); health insurance; accommodation proof; clean criminal record.','6-10 weeks','BGN 200-500 (~$110-275)','retirement','Proof of pension (600+EUR/month), health insurance, accommodation proof, clean criminal record.','6-10 weeks','1 year, renewable','https://www.mvr.bg','2025-01-01'),

-- CAMBODIA missing goals
('any','cambodia','Study','Cambodia Student Visa (E-Class)','Study at Cambodian educational institutions on a student visa.','International students accepted to Cambodian schools or universities.','Valid passport; school acceptance letter; proof of finances; health insurance.','1-2 weeks','USD 35-50','study','School acceptance letter, proof of finances, health insurance.','1-2 weeks','1 year, renewable','https://www.immigration.gov.kh','2025-01-01'),
('any','cambodia','Family','Cambodia Family Visa (E-Class)','Live in Cambodia with a family member who is a legal resident.','Spouses and children of Cambodian residents.','Valid passport; proof of relationship; sponsor residence documents; financial support.','1-2 weeks','USD 35-50','family','Proof of relationship, sponsor residence documents, financial support.','1-2 weeks','1 year, renewable','https://www.immigration.gov.kh','2025-01-01'),
('any','cambodia','Retirement','Cambodia Retirement Visa (E-Class)','Retire in Cambodia, among Asia most affordable countries.','Retirees 55+ with proof of sufficient income.','Valid passport; proof of income ($1,500+/month) or savings; health insurance; clean criminal record.','1-2 weeks','USD 35-100','retirement','Proof of income ($1,500+/month) or savings, health insurance, clean criminal record.','1-2 weeks','1 year, renewable','https://www.immigration.gov.kh','2025-01-01'),
('any','cambodia','Digital Nomad','Cambodia Digital Nomad (E-Class Business Visa)','Work remotely from Cambodia using the business visa.','Remote workers and digital nomads.','Valid passport; proof of remote employment; income documentation; health insurance.','1-2 weeks','USD 35-100','digital_nomad','Proof of remote employment, income documentation, health insurance.','1-2 weeks','1 year, renewable','https://www.immigration.gov.kh','2025-01-01'),

-- COSTA RICA missing goals
('any','costa-rica','Study','Costa Rica Student Visa','Study at Costa Rican universities and language schools.','International students accepted to Costa Rican institutions.','Valid passport; school acceptance letter; proof of finances; health insurance.','4-8 weeks','CRC 50,000-150,000 (~$95-285)','study','School acceptance letter, proof of finances, health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.migracion.go.cr','2025-01-01'),
('any','costa-rica','Family','Costa Rica Family Reunification Visa','Join a Costa Rican resident or citizen as a dependent family member.','Spouses and children of Costa Rican residents.','Valid passport; marriage/birth certificate; sponsor proof of residency; financial support documents.','6-12 weeks','CRC 100,000-250,000 (~$190-475)','family','Marriage/birth certificate, sponsor proof of residency, financial support documents.','6-12 weeks','1-2 years, renewable','https://www.migracion.go.cr','2025-01-01'),
('any','costa-rica','Retirement','Costa Rica Pensionado Visa','Retire in Costa Rica with the popular Pensionado program.','Retirees with pension income of at least $1,000/month.','Valid passport; proof of pension income ($1,000+/month); health insurance; clean criminal record; authenticated documents.','2-4 months','CRC 200,000-500,000 (~$380-950)','retirement','Proof of pension income ($1,000+/month), health insurance, clean criminal record, authenticated documents.','2-4 months','2 years, renewable toward permanent residency','https://www.migracion.go.cr','2025-01-01'),
('any','costa-rica','Work','Costa Rica Work Permit','Work legally in Costa Rica under an employer or as self-employed.','Foreign workers with a job offer from a Costa Rican company, or self-employed professionals.','Valid passport; job contract; employer sponsorship; professional qualifications; clean criminal record.','4-8 weeks','CRC 100,000-300,000 (~$190-570)','work','Job contract, employer sponsorship, professional qualifications, clean criminal record.','4-8 weeks','1 year, renewable','https://www.migracion.go.cr','2025-01-01'),

-- CUBA missing goals
('any','cuba','Study','Cuba Student Visa','Study at Cuban universities, especially medical and arts programs.','International students accepted to Cuban government-approved institutions.','Valid passport; university acceptance letter; sponsoring institution documents; proof of finances; health insurance.','4-8 weeks','CUP/USD 100-300','study','University acceptance letter, sponsoring institution documents, proof of finances, health insurance.','4-8 weeks','1 year, renewable','https://www.minrex.gob.cu','2025-01-01'),
('any','cuba','Family','Cuba Family Visa','Join a family member residing in Cuba.','Spouses and children of Cuban residents.','Valid passport; proof of relationship; sponsor documents; financial support.','4-8 weeks','CUP/USD 50-200','family','Proof of relationship, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.minrex.gob.cu','2025-01-01'),
('any','cuba','Retirement','Cuba Retirement Residence','Retire in Cuba with a long-stay residence visa.','Retirees with sufficient foreign income.','Valid passport; proof of pension/income; health insurance; background check.','6-12 weeks','USD 200-500','retirement','Proof of pension/income, health insurance, valid passport, background check.','6-12 weeks','1 year, renewable','https://www.minrex.gob.cu','2025-01-01'),
('any','cuba','Digital Nomad','Cuba Digital Nomad Long Stay','Work remotely from Cuba on a long-stay visa.','Remote workers with foreign employment.','Valid passport; proof of employment abroad; income documentation; health insurance.','4-8 weeks','USD 200-500','digital_nomad','Proof of employment abroad, income documentation, health insurance.','4-8 weeks','1 year','https://www.minrex.gob.cu','2025-01-01'),

-- CYPRUS missing goals
('any','cyprus','Study','Cyprus Student Visa','Study at Cypriot universities, popular with English-language programs.','International students accepted to Cypriot higher education.','Valid passport; university acceptance letter; proof of finances (500+EUR/month); health insurance.','4-8 weeks','EUR 70-200','study','University acceptance letter, proof of finances (500+EUR/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.moi.gov.cy','2025-01-01'),
('any','cyprus','Family','Cyprus Family Reunification','Join a legally residing family member in Cyprus.','Spouses and children of Cypriot residents (non-EU).','Valid passport; proof of family relationship; sponsor income (2000+EUR/month); accommodation; health insurance.','2-3 months','EUR 100-300','family','Proof of family relationship, sponsor income (2000+EUR/month), accommodation, health insurance.','2-3 months','1 year, renewable','https://www.moi.gov.cy','2025-01-01'),
('any','cyprus','Retirement','Cyprus Retirement Residency (Cat F)','Retire in Cyprus on a Category F residence permit for non-working retirees.','Retirees with verifiable income from abroad (no local employment allowed).','Valid passport; proof of income (2000+EUR/month); clean criminal record; health insurance; accommodation.','2-3 months','EUR 300-500','retirement','Proof of income (2000+EUR/month), clean criminal record, health insurance, accommodation.','2-3 months','Initially 1 year, renewable long-term','https://www.moi.gov.cy','2025-01-01'),
('any','cyprus','Digital Nomad','Cyprus Digital Nomad Visa','Work remotely from sunny Cyprus on the Digital Nomad Visa.','Third-country nationals employed by or owning companies outside Cyprus.','Valid passport; employment contract or proof of self-employment; income 3500+EUR/month; health insurance.','4-6 weeks','EUR 70','digital_nomad','Employment contract or proof of self-employment, income 3500+EUR/month, health insurance.','4-6 weeks','1 year, extendable to 2 years','https://www.moi.gov.cy','2025-01-01')

ON CONFLICT DO NOTHING;
