/*
  # Populate Comprehensive Countries and Passports Data

  1. Purpose
    - Populates the database with 100+ countries from all global regions
    - Adds corresponding passport data for all countries
    - Provides comprehensive coverage for immigration path finding

  2. Data Included
    - Countries table: 100+ countries with name, slug, and region
    - Passports table: Corresponding passport entries for each country
    - Covers all major regions: North America, South America, Europe, Asia, Africa, Oceania, Middle East

  3. Notes
    - Uses ON CONFLICT to safely update existing records
    - Ensures data integrity with proper slugs and regional categorization
    - All countries that issue passports are included
*/

-- Insert comprehensive countries data
INSERT INTO countries (slug, name, region) VALUES
  -- North America
  ('united-states', 'United States', 'North America'),
  ('canada', 'Canada', 'North America'),
  ('mexico', 'Mexico', 'North America'),
  ('costa-rica', 'Costa Rica', 'North America'),
  ('panama', 'Panama', 'North America'),
  ('jamaica', 'Jamaica', 'North America'),
  ('cuba', 'Cuba', 'North America'),
  ('dominican-republic', 'Dominican Republic', 'North America'),
  ('haiti', 'Haiti', 'North America'),
  ('guatemala', 'Guatemala', 'North America'),
  ('honduras', 'Honduras', 'North America'),
  ('el-salvador', 'El Salvador', 'North America'),
  ('nicaragua', 'Nicaragua', 'North America'),
  ('belize', 'Belize', 'North America'),
  
  -- South America
  ('brazil', 'Brazil', 'South America'),
  ('argentina', 'Argentina', 'South America'),
  ('chile', 'Chile', 'South America'),
  ('colombia', 'Colombia', 'South America'),
  ('peru', 'Peru', 'South America'),
  ('venezuela', 'Venezuela', 'South America'),
  ('ecuador', 'Ecuador', 'South America'),
  ('bolivia', 'Bolivia', 'South America'),
  ('paraguay', 'Paraguay', 'South America'),
  ('uruguay', 'Uruguay', 'South America'),
  ('guyana', 'Guyana', 'South America'),
  ('suriname', 'Suriname', 'South America'),
  
  -- Europe
  ('united-kingdom', 'United Kingdom', 'Europe'),
  ('germany', 'Germany', 'Europe'),
  ('france', 'France', 'Europe'),
  ('italy', 'Italy', 'Europe'),
  ('spain', 'Spain', 'Europe'),
  ('portugal', 'Portugal', 'Europe'),
  ('netherlands', 'Netherlands', 'Europe'),
  ('belgium', 'Belgium', 'Europe'),
  ('switzerland', 'Switzerland', 'Europe'),
  ('austria', 'Austria', 'Europe'),
  ('sweden', 'Sweden', 'Europe'),
  ('norway', 'Norway', 'Europe'),
  ('denmark', 'Denmark', 'Europe'),
  ('finland', 'Finland', 'Europe'),
  ('ireland', 'Ireland', 'Europe'),
  ('poland', 'Poland', 'Europe'),
  ('greece', 'Greece', 'Europe'),
  ('czech-republic', 'Czech Republic', 'Europe'),
  ('hungary', 'Hungary', 'Europe'),
  ('romania', 'Romania', 'Europe'),
  ('bulgaria', 'Bulgaria', 'Europe'),
  ('croatia', 'Croatia', 'Europe'),
  ('slovakia', 'Slovakia', 'Europe'),
  ('slovenia', 'Slovenia', 'Europe'),
  ('estonia', 'Estonia', 'Europe'),
  ('latvia', 'Latvia', 'Europe'),
  ('lithuania', 'Lithuania', 'Europe'),
  ('luxembourg', 'Luxembourg', 'Europe'),
  ('malta', 'Malta', 'Europe'),
  ('cyprus', 'Cyprus', 'Europe'),
  ('iceland', 'Iceland', 'Europe'),
  ('ukraine', 'Ukraine', 'Europe'),
  ('serbia', 'Serbia', 'Europe'),
  ('albania', 'Albania', 'Europe'),
  ('north-macedonia', 'North Macedonia', 'Europe'),
  ('montenegro', 'Montenegro', 'Europe'),
  ('bosnia-herzegovina', 'Bosnia and Herzegovina', 'Europe'),
  
  -- Asia
  ('china', 'China', 'Asia'),
  ('japan', 'Japan', 'Asia'),
  ('south-korea', 'South Korea', 'Asia'),
  ('india', 'India', 'Asia'),
  ('singapore', 'Singapore', 'Asia'),
  ('malaysia', 'Malaysia', 'Asia'),
  ('thailand', 'Thailand', 'Asia'),
  ('vietnam', 'Vietnam', 'Asia'),
  ('philippines', 'Philippines', 'Asia'),
  ('indonesia', 'Indonesia', 'Asia'),
  ('pakistan', 'Pakistan', 'Asia'),
  ('bangladesh', 'Bangladesh', 'Asia'),
  ('sri-lanka', 'Sri Lanka', 'Asia'),
  ('nepal', 'Nepal', 'Asia'),
  ('myanmar', 'Myanmar', 'Asia'),
  ('cambodia', 'Cambodia', 'Asia'),
  ('laos', 'Laos', 'Asia'),
  ('brunei', 'Brunei', 'Asia'),
  ('mongolia', 'Mongolia', 'Asia'),
  ('taiwan', 'Taiwan', 'Asia'),
  ('hong-kong', 'Hong Kong', 'Asia'),
  ('macao', 'Macao', 'Asia'),
  
  -- Middle East
  ('united-arab-emirates', 'United Arab Emirates', 'Middle East'),
  ('saudi-arabia', 'Saudi Arabia', 'Middle East'),
  ('israel', 'Israel', 'Middle East'),
  ('turkey', 'Turkey', 'Middle East'),
  ('iran', 'Iran', 'Middle East'),
  ('qatar', 'Qatar', 'Middle East'),
  ('kuwait', 'Kuwait', 'Middle East'),
  ('bahrain', 'Bahrain', 'Middle East'),
  ('oman', 'Oman', 'Middle East'),
  ('jordan', 'Jordan', 'Middle East'),
  ('lebanon', 'Lebanon', 'Middle East'),
  ('iraq', 'Iraq', 'Middle East'),
  ('yemen', 'Yemen', 'Middle East'),
  ('syria', 'Syria', 'Middle East'),
  
  -- Africa
  ('south-africa', 'South Africa', 'Africa'),
  ('egypt', 'Egypt', 'Africa'),
  ('nigeria', 'Nigeria', 'Africa'),
  ('kenya', 'Kenya', 'Africa'),
  ('morocco', 'Morocco', 'Africa'),
  ('ethiopia', 'Ethiopia', 'Africa'),
  ('ghana', 'Ghana', 'Africa'),
  ('tanzania', 'Tanzania', 'Africa'),
  ('uganda', 'Uganda', 'Africa'),
  ('algeria', 'Algeria', 'Africa'),
  ('tunisia', 'Tunisia', 'Africa'),
  ('sudan', 'Sudan', 'Africa'),
  ('senegal', 'Senegal', 'Africa'),
  ('ivory-coast', 'Ivory Coast', 'Africa'),
  ('cameroon', 'Cameroon', 'Africa'),
  ('zimbabwe', 'Zimbabwe', 'Africa'),
  ('zambia', 'Zambia', 'Africa'),
  ('botswana', 'Botswana', 'Africa'),
  ('namibia', 'Namibia', 'Africa'),
  ('mauritius', 'Mauritius', 'Africa'),
  ('rwanda', 'Rwanda', 'Africa'),
  ('mozambique', 'Mozambique', 'Africa'),
  ('angola', 'Angola', 'Africa'),
  ('congo', 'Congo', 'Africa'),
  
  -- Oceania
  ('australia', 'Australia', 'Oceania'),
  ('new-zealand', 'New Zealand', 'Oceania'),
  ('fiji', 'Fiji', 'Oceania'),
  ('papua-new-guinea', 'Papua New Guinea', 'Oceania'),
  ('samoa', 'Samoa', 'Oceania'),
  ('tonga', 'Tonga', 'Oceania'),
  ('vanuatu', 'Vanuatu', 'Oceania')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region;

-- Insert comprehensive passports data (matching all countries)
INSERT INTO passports (slug, name) VALUES
  -- North America
  ('united-states', 'United States'),
  ('canada', 'Canada'),
  ('mexico', 'Mexico'),
  ('costa-rica', 'Costa Rica'),
  ('panama', 'Panama'),
  ('jamaica', 'Jamaica'),
  ('cuba', 'Cuba'),
  ('dominican-republic', 'Dominican Republic'),
  ('haiti', 'Haiti'),
  ('guatemala', 'Guatemala'),
  ('honduras', 'Honduras'),
  ('el-salvador', 'El Salvador'),
  ('nicaragua', 'Nicaragua'),
  ('belize', 'Belize'),
  
  -- South America
  ('brazil', 'Brazil'),
  ('argentina', 'Argentina'),
  ('chile', 'Chile'),
  ('colombia', 'Colombia'),
  ('peru', 'Peru'),
  ('venezuela', 'Venezuela'),
  ('ecuador', 'Ecuador'),
  ('bolivia', 'Bolivia'),
  ('paraguay', 'Paraguay'),
  ('uruguay', 'Uruguay'),
  ('guyana', 'Guyana'),
  ('suriname', 'Suriname'),
  
  -- Europe
  ('united-kingdom', 'United Kingdom'),
  ('germany', 'Germany'),
  ('france', 'France'),
  ('italy', 'Italy'),
  ('spain', 'Spain'),
  ('portugal', 'Portugal'),
  ('netherlands', 'Netherlands'),
  ('belgium', 'Belgium'),
  ('switzerland', 'Switzerland'),
  ('austria', 'Austria'),
  ('sweden', 'Sweden'),
  ('norway', 'Norway'),
  ('denmark', 'Denmark'),
  ('finland', 'Finland'),
  ('ireland', 'Ireland'),
  ('poland', 'Poland'),
  ('greece', 'Greece'),
  ('czech-republic', 'Czech Republic'),
  ('hungary', 'Hungary'),
  ('romania', 'Romania'),
  ('bulgaria', 'Bulgaria'),
  ('croatia', 'Croatia'),
  ('slovakia', 'Slovakia'),
  ('slovenia', 'Slovenia'),
  ('estonia', 'Estonia'),
  ('latvia', 'Latvia'),
  ('lithuania', 'Lithuania'),
  ('luxembourg', 'Luxembourg'),
  ('malta', 'Malta'),
  ('cyprus', 'Cyprus'),
  ('iceland', 'Iceland'),
  ('ukraine', 'Ukraine'),
  ('serbia', 'Serbia'),
  ('albania', 'Albania'),
  ('north-macedonia', 'North Macedonia'),
  ('montenegro', 'Montenegro'),
  ('bosnia-herzegovina', 'Bosnia and Herzegovina'),
  
  -- Asia
  ('china', 'China'),
  ('japan', 'Japan'),
  ('south-korea', 'South Korea'),
  ('india', 'India'),
  ('singapore', 'Singapore'),
  ('malaysia', 'Malaysia'),
  ('thailand', 'Thailand'),
  ('vietnam', 'Vietnam'),
  ('philippines', 'Philippines'),
  ('indonesia', 'Indonesia'),
  ('pakistan', 'Pakistan'),
  ('bangladesh', 'Bangladesh'),
  ('sri-lanka', 'Sri Lanka'),
  ('nepal', 'Nepal'),
  ('myanmar', 'Myanmar'),
  ('cambodia', 'Cambodia'),
  ('laos', 'Laos'),
  ('brunei', 'Brunei'),
  ('mongolia', 'Mongolia'),
  ('taiwan', 'Taiwan'),
  ('hong-kong', 'Hong Kong'),
  ('macao', 'Macao'),
  
  -- Middle East
  ('united-arab-emirates', 'United Arab Emirates'),
  ('saudi-arabia', 'Saudi Arabia'),
  ('israel', 'Israel'),
  ('turkey', 'Turkey'),
  ('iran', 'Iran'),
  ('qatar', 'Qatar'),
  ('kuwait', 'Kuwait'),
  ('bahrain', 'Bahrain'),
  ('oman', 'Oman'),
  ('jordan', 'Jordan'),
  ('lebanon', 'Lebanon'),
  ('iraq', 'Iraq'),
  ('yemen', 'Yemen'),
  ('syria', 'Syria'),
  
  -- Africa
  ('south-africa', 'South Africa'),
  ('egypt', 'Egypt'),
  ('nigeria', 'Nigeria'),
  ('kenya', 'Kenya'),
  ('morocco', 'Morocco'),
  ('ethiopia', 'Ethiopia'),
  ('ghana', 'Ghana'),
  ('tanzania', 'Tanzania'),
  ('uganda', 'Uganda'),
  ('algeria', 'Algeria'),
  ('tunisia', 'Tunisia'),
  ('sudan', 'Sudan'),
  ('senegal', 'Senegal'),
  ('ivory-coast', 'Ivory Coast'),
  ('cameroon', 'Cameroon'),
  ('zimbabwe', 'Zimbabwe'),
  ('zambia', 'Zambia'),
  ('botswana', 'Botswana'),
  ('namibia', 'Namibia'),
  ('mauritius', 'Mauritius'),
  ('rwanda', 'Rwanda'),
  ('mozambique', 'Mozambique'),
  ('angola', 'Angola'),
  ('congo', 'Congo'),
  
  -- Oceania
  ('australia', 'Australia'),
  ('new-zealand', 'New Zealand'),
  ('fiji', 'Fiji'),
  ('papua-new-guinea', 'Papua New Guinea'),
  ('samoa', 'Samoa'),
  ('tonga', 'Tonga'),
  ('vanuatu', 'Vanuatu')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name;