/*
  # Complete Country Guides Part 2 - Climate, Employment, Healthcare, Education

  1. Purpose
    - Adds climate_lifestyle, employment_opportunities
    - Adds healthcare_system, education_system
    - Comprehensive information for all 52 countries
*/

UPDATE country_guides SET
  climate_lifestyle = CASE country_slug
    WHEN 'argentina' THEN 'Varied climate. Buenos Aires temperate. Patagonia cold. Wine regions. Outdoor lifestyle. Rich culture and nightlife.'
    WHEN 'australia' THEN 'Mostly sunny and warm. Varied climates. Beach lifestyle. Outdoor activities year-round. Relaxed culture.'
    WHEN 'austria' THEN 'Alpine climate. Cold winters, mild summers. Mountain lifestyle. High quality of life. Rich cultural heritage.'
    WHEN 'belgium' THEN 'Temperate maritime climate. Mild weather. Urban lifestyle. Rich history. Excellent food and beer culture.'
    WHEN 'brazil' THEN 'Tropical to subtropical. Warm year-round in most areas. Beach culture. Vibrant nightlife. Diverse landscapes.'
    WHEN 'canada' THEN 'Cold winters, warm summers. Varied by region. Outdoor lifestyle. Multicultural cities. High quality of life.'
    WHEN 'chile' THEN 'Varied climate. Mediterranean in center. Atacama desert. Patagonia. Wine regions. Outdoor lifestyle.'
    WHEN 'china' THEN 'Varied climates. Modern urban lifestyle. Rich history. Rapid development. Diverse landscapes and culture.'
    WHEN 'colombia' THEN 'Tropical climate. Eternal spring in Medellín. Beach and mountain options. Growing expat scene. Vibrant culture.'
    WHEN 'croatia' THEN 'Mediterranean coast. Continental inland. Beautiful beaches. Historic cities. Relaxed lifestyle.'
    WHEN 'czech-republic' THEN 'Temperate climate. Cold winters. Prague''s historic beauty. Beer culture. Central European lifestyle.'
    WHEN 'denmark' THEN 'Temperate oceanic climate. Mild but cloudy. Hygge lifestyle. Cycling culture. Work-life balance.'
    WHEN 'egypt' THEN 'Hot desert climate. Mild winters. Ancient history. Nile River. Red Sea beaches. Traditional culture.'
    WHEN 'finland' THEN 'Cold winters with snow. Mild summers. Sauna culture. Northern lights. Nature-focused lifestyle.'
    WHEN 'france' THEN 'Varied climates. Mediterranean south. Continental center. Rich culture. Excellent cuisine. Work-life balance.'
    WHEN 'germany' THEN 'Temperate climate. Cold winters. Efficient lifestyle. Rich culture. Excellent infrastructure. Beer gardens.'
    WHEN 'greece' THEN 'Mediterranean climate. Hot summers. Island lifestyle. Ancient history. Relaxed pace. Excellent cuisine.'
    WHEN 'hungary' THEN 'Continental climate. Hot summers, cold winters. Thermal baths. Rich history. Central European culture.'
    WHEN 'india' THEN 'Tropical to temperate. Monsoons. Diverse cultures. Spiritual heritage. Bustling cities. Varied landscapes.'
    WHEN 'indonesia' THEN 'Tropical climate. Warm year-round. Island lifestyle. Beach culture. Diverse traditions. Growing digital nomad scene.'
    WHEN 'ireland' THEN 'Temperate oceanic. Mild but rainy. Green landscapes. Pub culture. Friendly people. Rich literary heritage.'
    WHEN 'israel' THEN 'Mediterranean climate. Hot dry summers. Modern lifestyle. Rich history. Beach culture. Startup scene.'
    WHEN 'italy' THEN 'Mediterranean climate. Varied by region. Excellent cuisine. Rich history. Relaxed lifestyle. Cultural heritage.'
    WHEN 'japan' THEN 'Four distinct seasons. Cherry blossoms. Unique culture. Modern and traditional. Efficient society. Rich traditions.'
    WHEN 'malaysia' THEN 'Tropical climate. Hot and humid. Beach lifestyle. Multicultural. Modern cities. Diverse food scene.'
    WHEN 'mexico' THEN 'Varied climates. Beach and mountain options. Rich culture. Vibrant traditions. Excellent food. Warm people.'
    WHEN 'morocco' THEN 'Mediterranean to desert. Varied landscapes. Rich culture. Historic cities. Traditional markets. African gateway.'
    WHEN 'netherlands' THEN 'Temperate maritime. Mild weather. Cycling culture. Liberal society. Efficient infrastructure. International.'
    WHEN 'new-zealand' THEN 'Temperate climate. Stunning nature. Outdoor lifestyle. Relaxed culture. Adventure activities. Clean environment.'
    WHEN 'nigeria' THEN 'Tropical climate. Humid. Vibrant culture. Bustling cities. Rich traditions. Young dynamic population.'
    WHEN 'norway' THEN 'Cold climate. Fjords. Northern lights. Outdoor lifestyle. High quality of life. Nature-focused.'
    WHEN 'peru' THEN 'Varied climates. Andes mountains. Amazon rainforest. Ancient history. Rich culture. Excellent cuisine.'
    WHEN 'philippines' THEN 'Tropical climate. Beach lifestyle. Island nation. Friendly people. Spanish influence. Growing economy.'
    WHEN 'poland' THEN 'Temperate climate. Cold winters. Rich history. Growing modern cities. Traditional culture. Central location.'
    WHEN 'portugal' THEN 'Mediterranean climate. Mild winters. Beach lifestyle. Historic cities. Relaxed pace. Excellent cuisine.'
    WHEN 'qatar' THEN 'Hot desert climate. Very hot summers. Modern lifestyle. Luxury amenities. Tax-free living. International community.'
    WHEN 'romania' THEN 'Temperate climate. Carpathian mountains. Medieval castles. Growing tech scene. Traditional culture.'
    WHEN 'russia' THEN 'Cold climate. Harsh winters. Rich culture. Historic cities. Diverse landscapes. Traditional lifestyle.'
    WHEN 'saudi-arabia' THEN 'Hot desert climate. Very hot. Modern cities. Traditional culture. Rapid modernization. Tax-free.'
    WHEN 'singapore' THEN 'Tropical climate. Hot and humid year-round. Modern city-state. Efficient. Multicultural. Excellent food.'
    WHEN 'south-africa' THEN 'Mediterranean climate in Cape Town. Varied elsewhere. Outdoor lifestyle. Wine regions. Safety concerns in some areas.'
    WHEN 'south-korea' THEN 'Four seasons. Cold winters. Modern lifestyle. Tech-focused. Rich culture. Excellent food. Fast-paced.'
    WHEN 'spain' THEN 'Mediterranean climate. Hot summers. Beach lifestyle. Siesta culture. Excellent food. Rich history.'
    WHEN 'sweden' THEN 'Cold winters. Mild summers. Lagom lifestyle. Nature-focused. Modern society. Work-life balance.'
    WHEN 'switzerland' THEN 'Alpine climate. Beautiful mountains. High quality of life. Outdoor activities. Clean environment. Efficient.'
    WHEN 'thailand' THEN 'Tropical climate. Hot year-round. Beach lifestyle. Buddhist culture. Excellent food. Friendly people.'
    WHEN 'turkey' THEN 'Mediterranean to continental. Historic cities. Rich culture. Bridge between continents. Diverse landscapes.'
    WHEN 'ukraine' THEN 'Continental climate. Cold winters. Rich history. Traditional culture. Affordable lifestyle. European values.'
    WHEN 'united-arab-emirates' THEN 'Hot desert climate. Very hot summers. Modern lifestyle. Luxury amenities. Tax-free. International community.'
    WHEN 'united-kingdom' THEN 'Temperate maritime. Rainy. Rich history. Pub culture. Diverse cities. Global connections.'
    WHEN 'united-states' THEN 'Highly varied climates. All types available. Diverse lifestyles. Opportunity-focused. Entrepreneurial culture.'
    WHEN 'vietnam' THEN 'Tropical climate. Hot and humid. Growing cities. Rich history. Excellent food. Beach lifestyle.'
  END,
  employment_opportunities = CASE country_slug
    WHEN 'argentina' THEN 'Agriculture, tourism, and services sectors. Tech growing. Economic volatility can affect job market.'
    WHEN 'australia' THEN 'Strong economy. Mining, healthcare, tech, education sectors. High demand for skilled workers.'
    WHEN 'austria' THEN 'Strong economy. Tourism, finance, technology sectors. EU job market access. Stable employment.'
    WHEN 'belgium' THEN 'EU headquarters. International organizations. Finance, pharma, logistics. Multilingual advantage.'
    WHEN 'brazil' THEN 'Largest South American economy. Agriculture, manufacturing, services. Tech sector growing rapidly.'
    WHEN 'canada' THEN 'Strong economy. Tech, healthcare, finance, resources. Immigrant-friendly policies. Many opportunities.'
    WHEN 'chile' THEN 'Most stable South American economy. Mining, agriculture, services. Growing tech sector.'
    WHEN 'china' THEN 'World''s second largest economy. Manufacturing, tech, education. Teaching English popular. Business opportunities.'
    WHEN 'colombia' THEN 'Growing economy. Services, manufacturing, agriculture. Tech sector expanding. Growing startup scene.'
    WHEN 'croatia' THEN 'Tourism major sector. EU job market. Growing tech scene. Services and agriculture.'
    WHEN 'czech-republic' THEN 'Strong manufacturing. Tech and IT growing. EU job market. Automotive industry. Low unemployment.'
    WHEN 'denmark' THEN 'Strong economy. Green energy, pharma, tech. High wages. Good work-life balance.'
    WHEN 'egypt' THEN 'Tourism, agriculture, services. Suez Canal. Growing tech sector. Large population provides opportunities.'
    WHEN 'finland' THEN 'Strong tech sector. Nokia legacy. Gaming industry. Clean tech. High-quality jobs.'
    WHEN 'france' THEN 'Large EU economy. Tourism, aerospace, luxury goods, tech. Many multinational companies.'
    WHEN 'germany' THEN 'Largest EU economy. Manufacturing, automotive, engineering, tech. Many job opportunities.'
    WHEN 'greece' THEN 'Tourism major sector. Shipping, agriculture. Recovery economy. EU job market access.'
    WHEN 'hungary' THEN 'Manufacturing, automotive, IT. Low unemployment. EU job market. Growing economy.'
    WHEN 'india' THEN 'Rapidly growing economy. IT, services, manufacturing. Tech hub. Startup ecosystem. Many opportunities.'
    WHEN 'indonesia' THEN 'Largest Southeast Asian economy. Agriculture, manufacturing, services. Tech growing. Young workforce.'
    WHEN 'ireland' THEN 'Tech hub of Europe. Google, Facebook, Apple presence. Pharma sector. Finance. English-speaking advantage.'
    WHEN 'israel' THEN 'Startup nation. High-tech sector. Cybersecurity, biotech. Innovation economy. Many opportunities.'
    WHEN 'italy' THEN 'Tourism, fashion, manufacturing. Tech growing. EU job market. Rich cultural sector.'
    WHEN 'japan' THEN 'Advanced economy. Technology, automotive, robotics. Teaching English popular. Tech opportunities.'
    WHEN 'malaysia' THEN 'Growing economy. Manufacturing, palm oil, tourism. Tech sector expanding. Regional hub.'
    WHEN 'mexico' THEN 'Manufacturing, tourism, services. NAFTA benefits. Growing tech sector. Nearshoring opportunities.'
    WHEN 'morocco' THEN 'Tourism, agriculture, manufacturing. Gateway to Africa. French companies present. Growing economy.'
    WHEN 'netherlands' THEN 'Strong economy. Logistics, tech, agriculture. International business hub. English widely used.'
    WHEN 'new-zealand' THEN 'Agriculture, tourism, tech. Film industry. Skills shortages. High quality employment.'
    WHEN 'nigeria' THEN 'Largest African economy. Oil, agriculture, services. Tech sector booming. Young population. Many opportunities.'
    WHEN 'norway' THEN 'Oil and gas, maritime, seafood, renewable energy. High wages. Strong economy.'
    WHEN 'peru' THEN 'Mining, agriculture, tourism. Growing economy. Services sector expanding. Some opportunities.'
    WHEN 'philippines' THEN 'BPO sector strong. IT growing. Manufacturing. English advantage. Young workforce.'
    WHEN 'poland' THEN 'Growing EU economy. Manufacturing, IT, services. Low unemployment. Many opportunities.'
    WHEN 'portugal' THEN 'Tourism, services, tech. Growing startup scene. EU job market. Remote work friendly.'
    WHEN 'qatar' THEN 'Oil and gas, construction, finance. Tax-free salaries. Infrastructure projects. Expat-heavy workforce.'
    WHEN 'romania' THEN 'IT and tech strong. Manufacturing. EU job market. Low costs attract companies. Growing economy.'
    WHEN 'russia' THEN 'Energy, manufacturing, agriculture. Large economy. Tech sector present. Various opportunities.'
    WHEN 'saudi-arabia' THEN 'Oil and gas, construction, finance. Saudization policies. Large projects. Tax-free income.'
    WHEN 'singapore' THEN 'Global financial hub. Tech, finance, logistics. High salaries. Competitive job market.'
    WHEN 'south-africa' THEN 'Largest African economy - mining, finance, tourism, tech growing. Unemployment high.'
    WHEN 'south-korea' THEN 'Advanced economy. Tech, automotive, electronics. Samsung, LG, Hyundai. Competitive job market.'
    WHEN 'spain' THEN 'Tourism major sector. Services, manufacturing. EU job market. Tech growing. Some opportunities.'
    WHEN 'sweden' THEN 'Strong economy. Tech, manufacturing, services. Spotify, gaming. High-quality employment.'
    WHEN 'switzerland' THEN 'Finance, pharma, precision manufacturing. High salaries. Competitive market. Multinational presence.'
    WHEN 'thailand' THEN 'Tourism, manufacturing, agriculture. Tech growing. Teaching English popular. Growing opportunities.'
    WHEN 'turkey' THEN 'Manufacturing, tourism, agriculture. Strategic location. Growing tech sector. Large domestic market.'
    WHEN 'ukraine' THEN 'IT sector strong. Agriculture. Manufacturing. Low costs attract tech companies. Challenges due to conflict.'
    WHEN 'united-arab-emirates' THEN 'Finance, tourism, real estate, tech. Dubai hub. Tax-free. Many multinational companies.'
    WHEN 'united-kingdom' THEN 'Financial center. Tech, finance, services. London global hub. Many opportunities.'
    WHEN 'united-states' THEN 'World''s largest economy. All sectors strong. Tech hubs. Entrepreneurship. Many opportunities.'
    WHEN 'vietnam' THEN 'Manufacturing, services, agriculture. Tech growing rapidly. Teaching English popular. Low costs attract companies.'
  END,
  updated_at = now()
WHERE country_slug IN (
  'argentina', 'australia', 'austria', 'belgium', 'brazil', 'canada', 'chile', 'china',
  'colombia', 'croatia', 'czech-republic', 'denmark', 'egypt', 'finland', 'france',
  'germany', 'greece', 'hungary', 'india', 'indonesia', 'ireland', 'israel', 'italy',
  'japan', 'malaysia', 'mexico', 'morocco', 'netherlands', 'new-zealand', 'nigeria',
  'norway', 'peru', 'philippines', 'poland', 'portugal', 'qatar', 'romania', 'russia',
  'saudi-arabia', 'singapore', 'south-africa', 'south-korea', 'spain', 'sweden',
  'switzerland', 'thailand', 'turkey', 'ukraine', 'united-arab-emirates',
  'united-kingdom', 'united-states', 'vietnam'
);
