/*
  # Add Pathways for African Passports

  ## Overview
  Comprehensive immigration pathways for citizens from African countries including:
  - Cameroon, Nigeria, Kenya, Ghana, South Africa, Egypt, Morocco
  
  ## Destinations
  All major immigration destinations: US, UK, Canada, Australia, Germany, France, etc.

  ## Goals
  Work, Study, Visit, Residency, Digital Nomad alternatives
*/

INSERT INTO immigration_pathways (
  passport_slug, destination_slug, goal, pathway_type, pathway_name,
  summary, eligibility, key_requirements, requirements, typical_timeline,
  processing_time, estimated_fees, validity_period, official_url
) VALUES

-- Cameroon to Canada
('cm', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points, proof of funds.',
 'IELTS/CELPIP CLB 7+, Educational Credential Assessment, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('cm', 'ca', 'Work', 'Work', 'Temporary Foreign Worker Program',
 'Employer-specific work permit.',
 'Job offer from Canadian employer with LMIA.',
 'LMIA-approved job offer, qualifications.',
 'LMIA from employer, relevant qualifications, employment contract.',
 '2-4 months', '2-4 months', 'CAD 155-230',
 '1-4 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/hire-temporary-foreign/temporary-foreign-worker-program.html'),

('cm', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at designated learning institution.',
 'Acceptance from DLI.',
 'LOA, financial capacity, language proficiency.',
 'Letter of Acceptance, CAD 10,000+ funds, English/French test, medical exam.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('cm', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism and business visits.',
 'Cameroonian passport holders.',
 'Valid passport, return ticket, funds, purpose.',
 'Valid passport, return ticket, sufficient funds, purpose documentation.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

('cm', 'ca', 'Residency', 'Residency', 'Provincial Nominee Program',
 'Province-specific permanent residence.',
 'Provincial nomination.',
 'Nomination, language test, work experience, education.',
 'Provincial nomination, IELTS/CELPIP, work experience, educational credentials.',
 '12-18 months', '12-18 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/provincial-nominees.html'),

-- Cameroon to US
('cm', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for specialized professionals.',
 'Bachelor degree, US employer sponsorship.',
 'Job offer, employer petition, degree, lottery selection.',
 'US employer petition, bachelor degree in specialty occupation, lottery win.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('cm', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Full-time academic study at SEVP-approved institution.',
 'Acceptance at SEVP-approved school.',
 'I-20 form, SEVIS fee, financial proof, interview.',
 'I-20, SEVIS fee (USD 350), financial capacity proof, embassy interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('cm', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Cameroonian passport holders.',
 'Valid passport, interview, return ticket, financial proof.',
 'Valid passport, visa interview, return ticket, sufficient funds, ties to Cameroon.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

-- Cameroon to UK
('cm', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK licensed sponsor, salary £25,600+.',
 'Certificate of Sponsorship, English proficiency, maintenance funds.',
 'CoS from licensed sponsor, English test, £1,270 funds, relevant qualifications.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('cm', 'gb', 'Study', 'Study', 'Student Visa',
 'Full-time study at UK licensed institution.',
 'Acceptance from licensed student sponsor.',
 'CAS, English test, maintenance funds, TB test.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds, TB test.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration + 2-4 months',
 'https://www.gov.uk/student-visa'),

('cm', 'gb', 'Visit', 'Visit', 'Standard Visitor Visa',
 'Tourism and business visits.',
 'Cameroonian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds, accommodation proof.',
 '3 weeks', '3 weeks', 'GBP 100',
 '6 months',
 'https://www.gov.uk/standard-visitor-visa'),

-- Cameroon to Australia
('cm', 'au', 'Work', 'Work', 'Temporary Skill Shortage Visa (Subclass 482)',
 'Employer-sponsored work visa.',
 'Job offer from Australian employer.',
 'Employer sponsorship, skills assessment, English.',
 'Employer sponsorship, skills assessment, English test, 2+ years experience.',
 '2-4 months', '2-4 months', 'AUD 1,290-2,690',
 '2-4 years',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482'),

('cm', 'au', 'Study', 'Study', 'Student Visa (Subclass 500)',
 'Full-time study at registered institution.',
 'Enrollment in registered course.',
 'CoE, financial capacity, English proficiency.',
 'Confirmation of Enrollment, financial proof, English test, OSHC health insurance.',
 '1-2 months', '1-2 months', 'AUD 650',
 'Course duration',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),

('cm', 'au', 'Visit', 'Visit', 'Visitor Visa (Subclass 600)',
 'Tourism and business visits.',
 'Cameroonian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds, purpose of visit.',
 '2-4 weeks', '2-4 weeks', 'AUD 145',
 'Up to 12 months',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600'),

-- Cameroon to Germany
('cm', 'de', 'Work', 'Work', 'EU Blue Card',
 'Work permit for highly qualified workers.',
 'University degree, job offer €45,300+ salary.',
 'Degree, employment contract, salary threshold.',
 'University degree, employment contract €45,300+, health insurance, accommodation.',
 '1-3 months', '1-3 months', 'EUR 100',
 '4 years',
 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card'),

('cm', 'de', 'Study', 'Study', 'Student Visa',
 'Study at German university.',
 'University admission.',
 'Admission letter, blocked account €11,208, health insurance.',
 'University admission, blocked account €11,208/year, health insurance, language proof.',
 '6-12 weeks', '6-12 weeks', 'EUR 75',
 'Duration of studies',
 'https://www.make-it-in-germany.com/en/study-training/study/preparations/prerequisites'),

('cm', 'de', 'Visit', 'Visit', 'Schengen Visa',
 'Short-term tourism and business.',
 'Cameroonian passport holders.',
 'Valid passport, travel insurance, return ticket.',
 'Valid passport, travel insurance €30,000+, return ticket, accommodation, funds.',
 '2-4 weeks', '2-4 weeks', 'EUR 80',
 'Up to 90 days',
 'https://www.schengenvisainfo.com/'),

-- Cameroon to France
('cm', 'fr', 'Work', 'Work', 'Passeport Talent - Skilled Worker',
 'Residence permit for skilled workers.',
 'Job offer, degree, €53,836.50+ salary.',
 'Employment contract, degree, salary threshold.',
 'Employment contract, degree certificate, €53,836.50+ annual salary.',
 '2-3 months', '2-3 months', 'EUR 225',
 '4 years renewable',
 'https://www.campusfrance.org/en/talent-passport-for-employees'),

('cm', 'fr', 'Study', 'Study', 'Long-Stay Student Visa',
 'Study at French institution.',
 'University acceptance.',
 'Campus France approval, financial capacity.',
 'University acceptance, Campus France approval, €615/month funds, health insurance.',
 '2-4 weeks', '2-4 weeks', 'EUR 50-99',
 'Duration of studies',
 'https://www.campusfrance.org/en'),

('cm', 'fr', 'Visit', 'Visit', 'Schengen Visa',
 'Tourism and business visits.',
 'Cameroonian passport holders.',
 'Valid passport, travel insurance, funds.',
 'Valid passport, travel insurance €30,000+, return ticket, accommodation.',
 '2-4 weeks', '2-4 weeks', 'EUR 80',
 'Up to 90 days',
 'https://france-visas.gouv.fr/'),

-- Nigeria to Canada
('ng', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('ng', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at designated learning institution.',
 'Acceptance from DLI.',
 'LOA, financial capacity, language proficiency.',
 'Letter of Acceptance, CAD 10,000+ funds, English/French test, medical exam.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('ng', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism and business visits.',
 'Nigerian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds, purpose documentation.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Nigeria to UK
('ng', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK licensed sponsor.',
 'Certificate of Sponsorship, English proficiency.',
 'CoS, English test, £1,270 funds, qualifications.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('ng', 'gb', 'Study', 'Study', 'Student Visa',
 'Full-time study at UK institution.',
 'Acceptance from licensed sponsor.',
 'CAS, English test, maintenance funds, TB test.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds, TB test.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration + 2-4 months',
 'https://www.gov.uk/student-visa'),

('ng', 'gb', 'Visit', 'Visit', 'Standard Visitor Visa',
 'Tourism and business visits.',
 'Nigerian passport holders.',
 'Valid passport, funds, return ticket.',
 'Valid passport, return ticket, sufficient funds, accommodation.',
 '3 weeks', '3 weeks', 'GBP 100',
 '6 months',
 'https://www.gov.uk/standard-visitor-visa'),

-- Nigeria to US
('ng', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for professionals.',
 'Bachelor degree, US employer sponsorship.',
 'Job offer, employer petition, degree, lottery.',
 'US employer petition, bachelor degree, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('ng', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP-approved school acceptance.',
 'I-20, SEVIS fee, financial proof, interview.',
 'I-20 form, SEVIS fee, financial capacity, visa interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('ng', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Nigerian passport holders.',
 'Valid passport, interview, funds.',
 'Valid passport, visa interview, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

-- Kenya to Canada
('ke', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('ke', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity, language test.',
 'Letter of Acceptance, CAD 10,000+ funds, English/French test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('ke', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits.',
 'Kenyan passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

-- Kenya to UK
('ke', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK sponsor.',
 'Certificate of Sponsorship, English test.',
 'CoS, English proficiency, £1,270 funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('ke', 'gb', 'Study', 'Study', 'Student Visa',
 'Study at UK institution.',
 'Acceptance from licensed sponsor.',
 'CAS, English test, funds, TB test.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds, TB test.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration',
 'https://www.gov.uk/student-visa'),

('ke', 'gb', 'Visit', 'Visit', 'Standard Visitor Visa',
 'Tourism and business visits.',
 'Kenyan passport holders.',
 'Valid passport, funds.',
 'Valid passport, return ticket, sufficient funds.',
 '3 weeks', '3 weeks', 'GBP 100',
 '6 months',
 'https://www.gov.uk/standard-visitor-visa'),

-- South Africa to Canada
('za', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('za', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at DLI.',
 'Acceptance from designated institution.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('za', 'ca', 'Visit', 'Visit', 'Electronic Travel Authorization (eTA)',
 'Electronic visa for air travel.',
 'South African passport holders.',
 'Valid passport.',
 'Valid passport, online eTA application.',
 'Minutes', 'Minutes', 'CAD 7',
 'Up to 5 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html')

ON CONFLICT (id) DO NOTHING;