/*
  # Add Full Rich Content - Batch 3

  Countries covered:
  - Finland, Greece, Hungary, India, Israel, Mexico, Peru, Philippines, Poland, Qatar

  Each country gets:
  - Comprehensive intro_md (400-550 chars)
  - 7 detailed FAQs (faq_json)
  - warning_md with practical cautions
  - next_steps_md with actionable guidance
*/

DO $$
DECLARE
  v_id uuid;
BEGIN

  -- ============================================================
  -- FINLAND
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'finland';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Finland is a Nordic country with a highly educated workforce, a strong tech and gaming industry (Nokia, Supercell, Rovio), and one of the world''s best education systems. The Finnish Immigration Service (Migri) manages all permits. Finland offers a Specialist Permit for highly qualified workers and a Start-Up Permit for entrepreneurs. Helsinki is the main expat hub. High income taxes are offset by exceptional public services, free university education, and comprehensive social security.',
      '[
        {"question": "What is the Finnish Specialist Permit?", "answer": "The Specialist Permit is for highly qualified professionals with expert knowledge in a specific field. Employers must pay the standard salary for the occupation. Application through EnterFinland (Migri''s online system). Fee EUR 690 for a 1-year permit, EUR 450 for extension. Processing takes 2-4 weeks for most cases. Does not require a labour market test, making it faster than the regular employed worker permit."},
        {"question": "How does the regular Finnish work permit (employed worker) work?", "answer": "The standard employed worker permit requires your employer to confirm they could not find a Finnish or EU citizen for the role (partial labour market test). Migri coordinates with the TE service (employment office). Fee EUR 690 for main applicant (1 year). Processing 1-3 months. Salary must meet the minimum for the field based on collective agreements."},
        {"question": "What is the Finland Start-Up Permit?", "answer": "The Start-Up Permit (Business Finland endorsed) allows entrepreneurs to found or join an innovative high-growth startup in Finland. Business Finland evaluates the business concept. No minimum investment required. Permit fee EUR 690. Holders can work at their startup and apply for permanent residence after 4 years of cumulative residence. The permit lasts 2 years."},
        {"question": "How high are Finnish income taxes?", "answer": "Finnish income taxes are among Europe''s highest. State tax is progressive: 12.64-44% above EUR 19,200/year. Municipal tax averages 20-22%. Church tax is optional. Total effective rate for a EUR 60,000 salary: approximately 43-47%. However, these taxes fund free healthcare, free university education (also for residents), and comprehensive social security including unemployment benefits of 60-75% of previous salary."},
        {"question": "How long until Finnish permanent residence?", "answer": "Permanent residence (Permanent Residence Permit Type A) is available after 4 years of continuous residence on a work permit. Must have lived in Finland continuously, had stable income, and no significant criminal history. Fee EUR 450. After 5 years of legal residence (4 years on a long-term permit), you can apply for a Long-Term EU Resident Permit (P-EU) which carries more EU-level rights."},
        {"question": "Is Finnish language required for a work permit?", "answer": "Finnish language is NOT required for work permits. English is widely spoken in Finnish workplaces, especially in tech and international companies. However, Finnish (or Swedish) B1 level is required for citizenship (naturalization) after 5 years of residence. Migri offers free language assessment. Free Finnish language courses are available for residents through local employment services."},
        {"question": "What is the Finnish personal ID (Henkilotunnus) and why is it needed?", "answer": "The Finnish personal identity code (Henkilotunnus) is issued by the Digital and Population Data Services Agency (DVV) after registering as a Finnish resident. It is required for banking, healthcare, tax, phone contracts, and almost all services. Register at a DVV service point after arrival. EU citizens can register directly; non-EU citizens need a valid residence permit first. Without it, even basic tasks become difficult."}
      ]'::jsonb,
      'Finnish winters are long and dark, which affects quality of life significantly — many expats underestimate this. Finnish language skills, while not required for work permits, are essential for long-term integration and citizenship. Housing in Helsinki is competitive; secure accommodation before arrival. The Specialist Permit process is fast but regular employed worker permits with labour market tests can take longer than expected.',
      'Check if your occupation qualifies for the Specialist Permit to avoid the slower labour market test process, apply through EnterFinland online before travelling to Finland, register with DVV for your Henkilotunnus promptly after arrival, set up a Finnish bank account (Nordea, OP, or Danske Bank), register with the local tax office (Vero) to receive your tax card, and begin Finnish language lessons through local employment services or an online course.'
    );
  END IF;

  -- ============================================================
  -- GREECE
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'greece';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Greece offers several attractive immigration pathways including the Digital Nomad Visa, Golden Visa (property investment), and a Non-Dom tax regime for wealthy new residents. Greece is a member of the EU and Schengen, making it attractive for those seeking European residency. Athens and Thessaloniki are major expat hubs, while the islands attract retirees and digital nomads. Cost of living is relatively affordable compared to northern Europe, and the Greek government has actively courted foreign residents with tax incentives.',
      '[
        {"question": "What is the Greece Digital Nomad Visa?", "answer": "The Greece Digital Nomad Visa allows remote workers employed by or providing services to companies outside Greece to live in Greece for 1 year (extendable to 2 years). Income requirement: EUR 3,500/month (main applicant). Visa fee: EUR 75. Allows working remotely without Greek work authorization. After 5 years of residence, can apply for permanent residence. The visa can be converted to a residence permit after arrival."},
        {"question": "What is the Greece Golden Visa?", "answer": "The Golden Visa grants 5-year renewable residency through investment. As of 2024, minimum real estate investment increased to EUR 800,000 in Athens, Thessaloniki, Mykonos, Santorini, and islands with 3,100+ population. EUR 400,000 elsewhere. Alternative: EUR 400,000 in investment funds or bonds. Application fee EUR 2,000 (main applicant). Grants EU residency and Schengen travel; citizenship after 7 years of residence."},
        {"question": "What is the Greece Non-Dom tax regime?", "answer": "Greece''s Non-Dom regime allows new tax residents who invest EUR 500,000+ in Greece to pay a flat annual tax of EUR 100,000 covering all foreign-source income, regardless of amount. Valid for up to 15 years. No need to declare foreign income sources. Popular with high-net-worth individuals. Alternatively, pensioners can pay a flat 7% tax on foreign pension income for 15 years if they transfer tax residency to Greece."},
        {"question": "How much does a standard Greece employment visa cost?", "answer": "For non-EU nationals hired by Greek companies: employment visa fee EUR 75 at the consulate, then residence permit application EUR 300 after arrival. Greek employer must advertise the role for 2 weeks first. Processing takes 2-4 months. Salary must meet Greek minimum wage (EUR 950/month in 2024) at minimum, though actual salaries vary by sector. Greek employers are required to pay social security contributions."},
        {"question": "How does Greek healthcare work for residents?", "answer": "Greece has a public healthcare system (ESY) funded by social contributions. Employed workers and their employers pay into EFKA (social security), which covers healthcare, pension, and unemployment. Remote workers and self-employed must register with EFKA and pay contributions approximately 26% of income. Private health insurance (EUR 50-150/month) is recommended for faster access to private hospitals, especially outside Athens."},
        {"question": "What is the AMKA number and why is it essential?", "answer": "AMKA (Arithmos Mitroou Koinonikis Asfalisis) is the Greek social security number required for employment, healthcare, and tax. Apply at a KEP citizen service center. Required documents: passport and proof of address in Greece. EU citizens get AMKA easily; non-EU residents need a residence permit first. Without AMKA you cannot receive a salary legally, access public healthcare, or register for Greek tax obligations."},
        {"question": "Can I get Greek (EU) citizenship through the Golden Visa?", "answer": "Yes. Golden Visa residence permits count toward the 7-year residency requirement for Greek citizenship. You must actually reside in Greece (183+ days/year) during those years; mere ownership of property without residence does not count toward citizenship. Greek citizenship grants EU citizenship, allowing you to live and work in any EU member state. Application requires A2 Greek language, knowledge of Greek history, and no criminal record."}
      ]'::jsonb,
      'Greek Golden Visa investment thresholds increased significantly in 2024 and may increase further in high-demand areas. Immigration bureaucracy in Greece is known for delays; legal representation is strongly recommended. All documents must be apostilled and translated by a certified Greek translator. Processing at Greek immigration services can extend beyond stated timelines. The Digital Nomad Visa conversion to a residence permit must be done within 30 days of arrival.',
      'Apply for your AFM (Greek tax number) at the local tax authority (AADE) immediately upon arrival, register for AMKA at a KEP center, engage a licensed Greek immigration attorney for Golden Visa or employment permit applications, verify current Golden Visa investment thresholds as they are subject to change, open a Greek bank account (required for most residency applications), and track your physical residence days carefully if working toward citizenship.'
    );
  END IF;

  -- ============================================================
  -- HUNGARY
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'hungary';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Hungary is a Central European EU member with a flat 15% income tax rate — one of the lowest in the EU. Budapest is a vibrant capital with a strong tech and startup scene and significantly lower costs than Western Europe. The Hungarian Guest Investor Program (relaunched in 2024) offers EU residency through investment. Hungary is part of Schengen. The government has positioned Hungary as a business-friendly destination with competitive tax rates and lower operational costs.',
      '[
        {"question": "What is Hungary''s flat income tax rate?", "answer": "Hungary has a flat personal income tax of 15% on all income — one of the lowest in the EU. Social contributions (employee side): 18.5% (pension + health). Employer side: 13% social contribution tax. Total employment cost is competitive. For a EUR 3,000/month gross salary, the employee takes home approximately EUR 1,995 after tax and contributions. Dividend income from business is taxed at 15% PIT + 13% social contribution above a threshold."},
        {"question": "What is the Hungary Guest Investor Visa?", "answer": "Hungary relaunched a Guest Investor Program in 2024. Investment options include: EUR 500,000 in a Hungarian real estate fund (not direct property purchase), or EUR 1,000,000 donation to a Hungarian higher education institution supporting arts/sciences. Grants a 10-year renewable residence permit for the investor and family. Government fee approximately EUR 70-110. No Schengen citizenship directly but full EU residence rights."},
        {"question": "How does Hungary work permit sponsorship work for non-EU nationals?", "answer": "Non-EU nationals need a Single Permit (work + residence) sponsored by a Hungarian employer. The employer must obtain prior authorization from the National Directorate-General for Aliens Policing (OIF). Salary must meet at least the Hungarian minimum wage (HUF 266,800/month in 2024). Application fee approximately HUF 23,800. Processing takes 4-8 weeks. The Single Permit is issued for 1-2 years."},
        {"question": "What is the cost of living in Budapest vs Western Europe?", "answer": "Budapest offers significantly lower costs than Western European capitals. Average rent for a 1-bedroom apartment in Budapest: EUR 600-1,000/month. Monthly grocery budget for one person: EUR 250-350. Restaurant meal: EUR 8-15. Monthly transport pass: EUR 25. Total monthly budget for comfortable living: EUR 1,500-2,500. These are roughly 40-60% lower than equivalent costs in Vienna, Paris, or Amsterdam."},
        {"question": "Can I work as a freelancer or digital nomad in Hungary?", "answer": "Hungary does not have a dedicated digital nomad visa. EU/EEA citizens can freely work as freelancers in Hungary. Non-EU citizens typically register a Hungarian sole trader (egyeni vallalkozo) or company (Kft - Korlátolt Felel ssegu Tarsasag) to obtain legal work status. Kft registration costs approximately EUR 200-500 in legal fees. The Guest Investor Visa does not authorize employment."},
        {"question": "How do I get Hungarian permanent residence?", "answer": "EU/EEA citizens can apply for permanent residence after 5 years of lawful residence. Non-EU nationals can apply for a Long-Term EU Residence Permit after 5 years of continuous legal residence on a valid permit. Requirements: stable income, health insurance, no criminal record, and basic Hungarian language proficiency (B1 for permanent residence application). Naturalization to Hungarian citizenship requires 8 years of residence (3 years for those married to Hungarians)."},
        {"question": "What is the Hungarian address card and why is it needed?", "answer": "Upon establishing residence in Hungary, you must register at the local government office (polgarmesteri hivatal) to receive an address card (lakcimkartya). This is required for everything: bank accounts, tax registration (adószám), healthcare enrollment, and utilities. EU citizens register directly; non-EU citizens need their Single Permit first. Registration is free and must be done within 3 days of establishing a permanent address in Hungary."}
      ]'::jsonb,
      'Hungary is an EU member but has ongoing disputes with EU institutions over rule-of-law concerns; this does not typically affect day-to-day immigration or residency. The Guest Investor Program was reformed in 2024 — direct real estate purchase no longer qualifies. Hungarian is a notoriously difficult language; English is common in Budapest''s professional and expat communities but limited outside the capital. Registration deadlines (within 3 days of address establishment) are strict.',
      'Register your Hungarian address at the local government office within 3 days of arrival, obtain your Hungarian tax number (adószám) from the National Tax Authority (NAV), open a Hungarian bank account, register with the National Health Insurance Fund (NEAK) for healthcare coverage, and for non-EU workers confirm your employer has obtained OIF authorization before you begin work.'
    );
  END IF;

  -- ============================================================
  -- INDIA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'india';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'India is the world''s most populous country and a major destination for multinational professionals, particularly in Mumbai (finance), Bangalore (technology), Delhi (government and commerce), and Hyderabad (pharmaceuticals and IT). The Employment Visa is the primary route for foreign professionals. India has strict rules against unauthorized work and requires foreign nationals to register with the Foreigners Regional Registration Office (FRRO) within 14 days of arrival in most cases.',
      '[
        {"question": "What is the India Employment Visa?", "answer": "The Employment Visa is for foreign nationals employed by Indian companies or multinationals. Requirements: minimum salary of USD 25,000/year (exemptions for certain ethnic cooks and language teachers). Visa fee varies by nationality (USD 25-100 at consulates). Valid for 1 year initially, extendable up to 5 years in India through FRRO. Employment Visa holders are taxed in India on India-source income."},
        {"question": "What is the FRRO (Foreigners Regional Registration Office) requirement?", "answer": "Foreign nationals holding Employment, Business, Research, or Student visas must register with the FRRO or FRO within 14 days of arrival at their place of stay. Registration is done online through the e-FRRO portal (indianfrro.gov.in). Required documents: visa, passport, employer letter, proof of address. Failure to register within 14 days can result in penalties or visa complications. Residence Permit is issued after FRRO registration."},
        {"question": "Can I bring my family to India on a dependent visa?", "answer": "Yes. Spouses and dependent children of Employment Visa holders can obtain an Entry Visa (X visa) or Dependent Visa. This visa does NOT automatically authorize work. If a spouse wants to work, they must convert to an Employment Visa with their own employer sponsorship. Dependent visa fees are similar to the main applicant visa fees. FRRO registration is also required for dependent visa holders if they intend to stay more than 180 days."},
        {"question": "What is the Business Visa for India?", "answer": "The Business Visa (B visa) allows attendance at business meetings, conferences, and exploration of business opportunities. Valid for up to 5 years with multiple entries, maximum stay 180 days per visit. Does NOT authorize employment or earning income in India. Fee varies by nationality. Cannot be converted to an Employment Visa inside India; must exit and re-enter on the correct visa."},
        {"question": "How does Indian income tax work for foreign workers?", "answer": "India taxes residents (those present 182+ days/year) on worldwide income. Non-residents are taxed only on India-source income. Tax rates: 5% on INR 300,001-600,000, 10% on INR 600,001-900,000, 15% on INR 900,001-1,200,000, up to 30% above INR 1,500,000. PAN card (Permanent Account Number) is mandatory for all taxpayers. Must file Indian tax return if income exceeds INR 250,000/year."},
        {"question": "Do I need a PAN card in India and how do I get one?", "answer": "The PAN (Permanent Account Number) is mandatory for financial transactions, salary payments, opening a bank account, and filing tax returns in India. Foreign nationals apply using Form 49AA at NSDL or UTIITSL centers or their portals. Required documents: passport, visa, proof of address in India, passport photo. Fee INR 107 for Indian applicants; higher for foreign applicants. Processing takes 2-4 weeks. Without PAN, a 20-30% tax withholding applies to income."},
        {"question": "Is there a path to Indian permanent residence or citizenship for foreigners?", "answer": "India has very limited permanent residence options. The OCI (Overseas Citizen of India) card is for foreign nationals of Indian origin (parents/grandparents born in India) — this grants lifelong multi-entry visa and near-permanent resident rights but not voting rights or citizenship. For other foreign nationals, naturalization requires 11 years of residence (typically through marriage or extraordinary contribution). India does not permit dual citizenship; Indian citizenship requires renouncing previous citizenship."}
      ]'::jsonb,
      'FRRO registration within 14 days is legally mandatory and should be treated as a priority upon arrival. Employment Visa holders must work only for the specified employer; switching employers requires a new visa. India does not generally grant permanent residence to foreign nationals outside the OCI route. Air quality in Delhi and several other major cities can be a significant health concern; research this factor when deciding your base city.',
      'Apply for your Employment Visa at the Indian consulate with complete documentation, register with FRRO online within 14 days of arrival, apply for PAN card immediately upon arrival to avoid high tax withholding, open an Indian bank account (NRE/NRO account at a major bank like HDFC, SBI, or ICICI), engage a local HR or tax advisor for payroll and compliance, and keep your visa and Residential Permit documents current throughout your stay.'
    );
  END IF;

  -- ============================================================
  -- ISRAEL
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'israel';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Israel is a leading global tech hub (often called "Startup Nation") with one of the world''s highest concentrations of tech startups per capita. Tel Aviv, Jerusalem, and Haifa are major centers for technology, finance, and research. The Law of Return grants immigration rights to Jews and their families. For other nationalities, work visas are employer-sponsored. Israel has a strong economy, world-class universities, and a vibrant expat community despite its complex geopolitical environment.',
      '[
        {"question": "What is the Law of Return and who qualifies?", "answer": "The Law of Return grants every Jew, their spouse, children, and grandchildren (and their spouses) the right to immigrate to Israel and become citizens (Aliyah). This is the most significant immigration pathway to Israel. Application through the Jewish Agency or Nefesh B''Nefesh. There are financial absorption grants (approximately USD 10,000-17,000 per adult immigrant depending on employment status) and subsidized Hebrew language courses (Ulpan)."},
        {"question": "How do non-Jewish foreigners get a work visa in Israel?", "answer": "Non-Jewish foreign nationals need an employer-sponsored B/1 work visa. The employer applies to the Population and Immigration Authority (PIBA) for a work permit. Fee approximately ILS 500-1,000. Processing takes 4-8 weeks. PIBA approval is based on whether the employer can justify hiring a foreign national. Salary must meet Israeli minimum wage (ILS 5,571/month in 2024). The visa is initially 1 year, renewable."},
        {"question": "What is the Israel tech sector immigration pathway?", "answer": "Israel''s tech sector is a major employer of foreign professionals. Companies like Google, Microsoft, and local unicorns hire internationally. Tech workers typically receive B/1 work visas. Senior roles may be facilitated by Israel''s Innovation Authority. There is no dedicated tech visa, but the process is employer-driven and most large tech employers have established relationships with immigration attorneys and PIBA."},
        {"question": "How much does it cost to live in Tel Aviv?", "answer": "Tel Aviv is one of the most expensive cities globally. Average 1-bedroom apartment rent: ILS 7,000-10,000/month (USD 1,900-2,700). Monthly food budget for one: ILS 2,500-3,500. Total monthly budget for comfortable living: ILS 12,000-18,000 (USD 3,200-4,900). Jerusalem and Haifa are somewhat cheaper. Beer Sheva and other southern cities significantly cheaper. High salaries in tech (ILS 25,000-60,000+/month) generally offset living costs for professionals."},
        {"question": "What are Israeli income tax rates?", "answer": "Israeli income tax is progressive: 10% up to ILS 81,480/year, 14% to ILS 116,760, 20% to ILS 187,440, 31% to ILS 260,520, 35% to ILS 557,400, 47% above. National Insurance (Bituach Leumi) and health insurance contributions add approximately 12-14% employee side. New immigrants (Olim) under the Law of Return receive a 10-year tax exemption on foreign-source income — a major financial benefit."},
        {"question": "What is the Israel Oleh absorption basket?", "answer": "New Jewish immigrants (Olim) through the Law of Return receive an Absorption Basket (sal klita) of financial benefits: approximately USD 10,000-17,000 for a single adult in cash grants over the first year, free Ulpan Hebrew language courses for 5 months, reduced taxes for 10 years on foreign-source income, and preferential mortgage terms. The Jewish Agency and Nefesh B''Nefesh provide support services for North American, UK, and other diaspora immigrants."},
        {"question": "Do I need to serve in the Israeli military as an immigrant?", "answer": "Jewish immigrants under 26 who make Aliyah are typically required to serve in the IDF (Israeli Defense Forces). Those aged 22-26 usually serve for shorter periods. Immigrants over 28 are generally exempt. Non-Jewish work visa holders are not subject to military service. The military service requirement is an important consideration for younger immigrants making Aliyah and should be discussed with the Jewish Agency before immigration."}
      ]'::jsonb,
      'The security situation in Israel and the region requires ongoing monitoring; travel advisories from your home country should be checked regularly. Standard employment visa holders are bound to their sponsoring employer; switching requires a new work permit application. Cost of living in Tel Aviv is very high; ensure salary offers account for this. Hebrew language, while not required for work permits, is essential for daily life and integration outside the main tech hubs.',
      'Jewish individuals and eligible family members should contact the Jewish Agency or Nefesh B''Nefesh to explore Aliyah as the most comprehensive pathway including citizenship and financial benefits. Non-Jewish professionals should ensure employer sponsorship is in place before travel. Register with PIBA after arrival, obtain an Israeli bank account and Teudat Zehut (ID number), register for National Insurance (Bituach Leumi), and consult an Israeli tax advisor regarding your residency and tax obligations.'
    );
  END IF;

  -- ============================================================
  -- MEXICO
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'mexico';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Mexico has become one of the world''s most popular destinations for digital nomads and remote workers, with Mexico City (CDMX) consistently ranking among the top nomad cities globally. The Temporary Resident Visa (Residente Temporal) is the primary pathway for those planning to stay beyond 180 days. Mexico City, Playa del Carmen, Tulum, Oaxaca, and Guadalajara are major expat hubs. Mexico has no dedicated digital nomad visa; most remote workers use the Temporary Resident Visa based on income or savings.',
      '[
        {"question": "What is the Mexico Temporary Resident Visa?", "answer": "The Temporary Resident Visa allows stays of 1-4 years. Requirements at the consulate: proof of sufficient income (approximately USD 1,620/month for a single applicant as of 2024) or savings (approximately USD 27,000). Visa fee approximately USD 36. After arrival, you must visit INM (Instituto Nacional de Migracion) to get your Temporary Resident Card (TRC): fee approximately MXN 4,000 (USD 240). The TRC allows you to open a bank account and is essential for daily life."},
        {"question": "Can I work remotely from Mexico as a digital nomad?", "answer": "Mexico has no dedicated digital nomad visa. However, Temporary Resident Visa holders whose income comes entirely from foreign employers or clients can live and work remotely from Mexico legally. The visa is based on income/savings, not employment status. You cannot work for Mexican employers without a separate work authorization. Most nomads use the Temporary Resident route for stays exceeding 6 months."},
        {"question": "What are Mexican income tax implications for long-term residents?", "answer": "Mexico taxes residents (those present more than 183 days per year) on worldwide income. Tax rates: 1.92% up to MXN 8,952/year, progressive to 35% above MXN 3,498,600/year. Foreign-source income is taxable for Mexican tax residents. Many digital nomads structure their stay to spend under 183 days per year in Mexico to avoid Mexican tax residency. RFC (Registro Federal de Contribuyentes) is Mexico''s tax ID, required for most formal financial activities."},
        {"question": "How much does it cost to live in Mexico City?", "answer": "Mexico City is among the most affordable major global cities. Average 1-bedroom apartment in Roma/Condesa/Polanco: MXN 15,000-25,000/month (USD 900-1,500). Food is very affordable: restaurant meals MXN 80-250 (USD 5-15). Monthly budget for comfortable living: USD 1,500-2,500 in CDMX. Coastal towns (Playa del Carmen, Tulum) have higher rents due to nomad demand. Guadalajara and Oaxaca offer excellent value."},
        {"question": "What is the Mexico Permanent Resident Visa?", "answer": "After 4 years as a Temporary Resident, you can apply for Permanent Resident status. Alternatively, retirees/pensioners with income of approximately USD 2,000/month can apply directly for Permanent Resident status. Also available to those with family ties to Mexican citizens. Permanent Resident Card fee approximately MXN 3,400 (USD 200). Permanent residents have the right to work without additional permits."},
        {"question": "Is Mexico City safe for expats?", "answer": "Mexico City''s popular expat neighborhoods (Roma Norte, Condesa, Polanco, Coyoacan, Santa Fe) are generally safe for day-to-day life. The city has millions of foreign residents and visitors. However, like any major city, situational awareness, avoiding certain neighborhoods, and common-sense precautions are important. Research the specific neighborhood before committing to housing. Theft and petty crime are more common concerns than violent crime in expat areas."},
        {"question": "Do I need to speak Spanish to live in Mexico?", "answer": "Spanish is strongly recommended for long-term living in Mexico. While Mexico City''s expat neighborhoods have many English speakers and services, Spanish is essential for dealing with INM, banks, landlords, healthcare providers, and daily life outside tourist areas. Basic conversational Spanish (B1) significantly improves quality of life. Spanish is not required for Temporary Resident or Permanent Resident applications."}
      ]'::jsonb,
      'Temporary Resident Visa income/savings requirements are set by each Mexican consulate and can vary; verify with the specific consulate in your country before applying. The INM registration appointment for your Temporary Resident Card must be completed within 30 days of entry on the long-stay visa. Mexico''s 183-day tax residency rule should be taken seriously; consult a Mexican accountant if you intend to stay year-round. CDMX rental market has become expensive in popular nomad neighborhoods due to high demand.',
      'Apply for your Temporary Resident Visa at a Mexican consulate before travel with bank statements showing required income/savings, book your INM appointment for the Temporary Resident Card as soon as you arrive (within 30 days), get your RFC tax number from SAT to open bank accounts, open a Mexican bank account (BBVA, Santander, or Banamex are common), consider renting month-to-month initially to find your preferred neighborhood, and consult a Mexican accountant if planning to stay 183+ days per year.'
    );
  END IF;

  -- ============================================================
  -- PERU
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'peru';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Peru is an increasingly popular destination for expats, digital nomads, and retirees drawn to Lima''s cosmopolitan culture, world-class cuisine, and affordable cost of living. The Peruvian government offers a range of residency permits including the Rentista (passive income), Inversionista (investor), and Trabajador (work permit). MIGRACIONES (Superintendencia Nacional de Migraciones) manages all immigration. Lima''s Miraflores and San Isidro districts are major expat hubs.',
      '[
        {"question": "What is the Peru Rentista (Passive Income) Residency Visa?", "answer": "The Rentista visa grants residency to those receiving regular passive income from abroad (pension, investment returns, rental income). Minimum income requirement: approximately USD 1,000/month (verify current thresholds as these update). Initial visa is 1 year, renewable annually. Application through MIGRACIONES in Peru. Fee approximately PEN 200-300. After 3 years, can apply for permanent residency."},
        {"question": "What is the Peru Trabajador (Work Permit) Visa?", "answer": "The Trabajador visa requires sponsorship by a Peruvian employer. The employer must prove a genuine need for a foreign worker and that the position could not be filled locally. Initial permit is 1 year, renewable. Government fee approximately PEN 200-400. Total costs including legal fees: USD 1,500-3,500. Work permit holders pay Peruvian income tax on Peru-sourced income."},
        {"question": "How much does it cost to live in Lima?", "answer": "Lima is one of South America''s most affordable major cities for expats. 1-bedroom apartment in Miraflores: USD 600-1,200/month. Monthly food and groceries: USD 300-500. Total monthly budget for comfortable living: USD 1,200-2,000. Cusco and Arequipa are even more affordable. Lima''s food scene (internationally ranked) and relatively low cost make it attractive for long-term stays."},
        {"question": "What is the Peru Inversionista (Investor) Visa?", "answer": "The Inversionista visa is for those making a qualifying investment in Peru. Minimum investment: USD 30,000 in a registered Peruvian company or property. Application through MIGRACIONES. Fee approximately PEN 500. A certified accountant or attorney is recommended to structure the investment correctly. After 3 years as an investor resident, permanent residency can be requested."},
        {"question": "How does the Carnet de Extranjeria work in Peru?", "answer": "The Carnet de Extranjeria (Foreigner''s Card) is the official residency ID issued to all long-term foreign residents in Peru. It is issued by MIGRACIONES after approving a residency visa. Required for opening bank accounts, signing leases, and interacting with government agencies. Must be renewed annually (or per the visa term). Always carry it with your passport when in Peru."},
        {"question": "What are Peruvian income tax rates?", "answer": "Peru taxes residents (183+ days/year) on worldwide income. Non-residents are taxed on Peru-source income only at a flat 30%. Resident income tax rates: 8% up to 5 UIT (approximately PEN 26,000), 14% to 20 UIT, 17% to 35 UIT, 20% to 45 UIT, and 30% above 45 UIT. The UIT (Tax Reference Unit) is updated annually. Consult a Peruvian accountant for specific guidance on foreign-source income treatment."},
        {"question": "Is Spanish required for Peru residency?", "answer": "Spanish is not officially required for residency applications in Peru. However, practical daily life, dealing with MIGRACIONES, landlords, and healthcare providers all require at least basic Spanish outside Lima''s expat neighborhoods. Peru''s immigration forms and government processes are in Spanish only. A bilingual immigration attorney is highly recommended for non-Spanish speakers navigating the MIGRACIONES process."}
      ]'::jsonb,
      'Peruvian immigration requirements and fee schedules are updated frequently; always verify current thresholds directly with MIGRACIONES or a licensed immigration attorney before applying. MIGRACIONES offices can have long queues; online appointment booking is essential. Political instability in Peru can periodically affect bureaucratic processing times. All foreign documents must be apostilled and officially translated into Spanish.',
      'Book MIGRACIONES appointments online in advance as walk-ins are not accepted for most processes, get all foreign documents apostilled and translated into Spanish before arriving, obtain a RUC (Peruvian tax ID from SUNAT) for financial activities, open a Peruvian bank account (BCP, Interbank, or Scotiabank are expat-friendly), engage a Peruvian immigration attorney for residency permit applications, and apply for your Carnet de Extranjeria promptly after permit approval.'
    );
  END IF;

  -- ============================================================
  -- PHILIPPINES
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'philippines';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'The Philippines is a popular destination for English-speaking expats and retirees, particularly through the SRRV (Special Resident Retiree''s Visa). The Bureau of Immigration (BI) manages all visas. The Philippines Retirement Authority (PRA) manages the SRRV program. Manila (Makati, BGC), Cebu, and Davao are major expat hubs. English is an official language, removing a key barrier for integration. Cost of living is low relative to Western countries.',
      '[
        {"question": "What is the Philippines SRRV (Special Resident Retiree''s Visa)?", "answer": "The SRRV is a special long-stay visa for retirees managed by the PRA. Options: SRRV Classic (deposit USD 20,000 for those 50+ without pension; USD 10,000 with pension of USD 800+/month), SRRV Smile (USD 20,000 for those under 35-50), SRRV Human Touch (for those with medical/health needs). Annual fee to PRA: USD 360. One-time processing fee: USD 1,400. Visa holders can live indefinitely, work or invest in the Philippines."},
        {"question": "How does a Philippines work permit work?", "answer": "Foreign nationals must obtain an Alien Employment Permit (AEP) from DOLE (Department of Labor and Employment) for employment with Philippine companies. Employer applies for AEP: fee PHP 8,000 for 1 year, PHP 12,000 for 2 years. The 9G Working Visa is then issued by the Bureau of Immigration: fee PHP 8,000-10,000. Processing takes 4-8 weeks. Total costs for employer and employee: approximately PHP 20,000-30,000 (USD 350-535)."},
        {"question": "Can I work remotely from the Philippines?", "answer": "The Philippines does not have a formal digital nomad visa. Remote workers employed by non-Philippine companies typically enter on tourist visas (extendable up to 36 months via BI extensions) or obtain the SRRV. Technically, working for foreign employers while on a tourist visa is in a legal grey area. The SRRV allows work and investment, making it the most practical legal long-stay option for remote workers who qualify for the retirement pathway."},
        {"question": "How much does it cost to live in Manila or Cebu?", "answer": "The Philippines offers very affordable living. 1-bedroom apartment in Makati/BGC: PHP 25,000-45,000/month (USD 430-780). In Cebu: PHP 15,000-30,000/month (USD 260-520). Monthly food and essentials: USD 300-500. Total monthly budget for comfortable living: USD 1,000-1,800 in Manila; less in provincial cities. The strong US dollar-to-peso exchange rate makes the Philippines particularly attractive for Americans."},
        {"question": "What is the Philippine 9G Working Visa?", "answer": "The 9G Working Visa (Pre-Arranged Employment Visa) is for foreign nationals with a job offer from a Philippine company. Requires AEP approval first. Issued by the Bureau of Immigration for 1-2 years. Fee PHP 8,000 (1 year) or PHP 14,000 (2 years). Application also requires payment of ACR I-Card (Alien Certificate of Registration Identity Card) at PHP 10,000. Total 9G costs: approximately PHP 25,000-35,000 (USD 430-600)."},
        {"question": "What is the ACR I-Card and why is it required?", "answer": "The ACR I-Card (Alien Certificate of Registration Identity Card) is the official ID for foreign nationals staying in the Philippines for more than 59 days. Required for long-term visa holders, SRRV holders, and 9G workers. Issued by the Bureau of Immigration. Initial fee PHP 10,000. Annual renewal PHP 2,500 for most categories. Must be carried at all times and presented to authorities or during banking/government transactions."},
        {"question": "Is there a path to Philippine citizenship?", "answer": "Philippine naturalization requires 10 years of continuous legal residence for most nationalities (5 years for nationals of countries with Filipino-friendly laws). Conditions include: good moral character, income sufficient to support yourself and family, ability to speak Filipino or any major Philippine language, and formal renunciation of prior citizenship. The Philippines generally does not allow dual citizenship for naturalized citizens (though natural-born Filipinos who acquired foreign citizenship may retain Philippine citizenship)."}
      ]'::jsonb,
      'Philippine visa extension chains at the Bureau of Immigration require regular visits and fees; plan these in advance to avoid overstay penalties. SRRV deposits must remain in Philippine banks throughout the visa validity. Typhoon season (June-November) affects much of the country; consider this for location choice. Manila traffic is severe; proximity to your workplace or coworking space significantly impacts quality of life.',
      'Apply for the SRRV through a PRA-accredited agent if you qualify (most practical long-term route), ensure AEP is obtained by your employer before applying for the 9G Working Visa, obtain your ACR I-Card immediately upon approval of long-term visa, open a Philippine bank account (BDO, BPI, or Metrobank are commonly used by expats), register with the BIR (Bureau of Internal Revenue) for a TIN if earning Philippine-source income, and plan Bureau of Immigration visits for annual or bi-annual visa renewals.'
    );
  END IF;

  -- ============================================================
  -- POLAND
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'poland';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Poland is one of Europe''s fastest-growing economies and a significant destination for skilled workers, particularly from Ukraine, Belarus, and increasingly from Asia and South America. Warsaw, Krakow, Wroclaw, and Gdansk are major economic hubs with strong tech, finance, and manufacturing sectors. Poland is an EU and Schengen member, making it a gateway to EU residence. Government fees are modest, and the cost of living is significantly lower than Western Europe.',
      '[
        {"question": "What work permits are available in Poland for non-EU nationals?", "answer": "Main work permits: Type A (employer-sponsored, most common), Type B (for board members), Type C (for intracompany transferees), Type D (seasonal), Type S (self-employed). The Poland EU Blue Card requires a degree and salary of PLN 9,062+/month (2024) and is issued for 3 years. Work Permit Type A requires employer sponsorship via the Voivodeship Office. Fees: PLN 100-200 for most permit types."},
        {"question": "What is the Poland EU Blue Card and how does it differ from a work permit?", "answer": "The EU Blue Card is a premium permit for highly skilled non-EU workers with: a recognized university degree (3+ years), a job offer in a qualifying profession, and salary at least 1.5x the average gross wage (PLN 9,062/month for most regions). Valid 3 years, renewable. Faster permanent residence eligibility (after 2 years on EU Blue Card). Spouses can work without restrictions. Application through the Voivodeship Office: fee PLN 440."},
        {"question": "How affordable is Poland compared to Western Europe?", "answer": "Poland is significantly more affordable. Warsaw 1-bedroom apartment: PLN 3,000-5,500/month (USD 730-1,350). Grocery budget for one: USD 200-350/month. Restaurant meal: USD 7-15. Total monthly budget for comfortable Warsaw living: USD 1,500-2,500. Krakow and Wroclaw are 15-20% cheaper than Warsaw. These lower costs combined with EU-level salaries in many sectors make Poland attractive for tech professionals."},
        {"question": "What is the PESEL number in Poland and why is it essential?", "answer": "PESEL (Powszechny Elektroniczny System Ewidencji Ludnosci) is Poland''s universal electronic personal identification system number. Required for: opening a bank account, signing a lease, healthcare registration, tax filing, and most government services. EU citizens can register for PESEL at their local gmina (municipality) office. Non-EU residents get PESEL automatically when their temporary residence permit (Karta Pobytu) is issued. Without PESEL, most administrative tasks are blocked."},
        {"question": "What is the Polish Karta Pobytu (Residence Card)?", "answer": "The Karta Pobytu is the Polish temporary residence card issued to non-EU nationals after their residence permit application is approved. Application submitted to the Voivodeship Office (Urzad Wojewodzki) within 45 days of entry or before the current permit expires. Fee PLN 340. Processing takes 1-6 months and varies significantly by office. The Karta Pobytu combines work authorization (if applicable) and residence in a single document."},
        {"question": "How long until Polish permanent residence and EU citizenship rights?", "answer": "Non-EU nationals can apply for permanent residence (pobyt staly) after 5 years of continuous legal residence. EU Long-Term Residence Permit is available after 5 years, granting right to live and work in any EU country. Polish citizenship requires 3 years of continuous residence for those married to Polish citizens, 5 years after obtaining PR, or 10 years for standard naturalization. Polish citizenship grants full EU citizenship rights."},
        {"question": "Is Polish language required for work permits?", "answer": "Polish is NOT required for work permits or the EU Blue Card. Warsaw and major cities have many English-speaking workplaces, especially in IT, finance, and shared service centers. However, B1 Polish is required for citizenship (naturalization). Polish language courses are available through local cultural centers and online platforms. Learning Polish greatly improves daily life quality outside international workplaces."}
      ]'::jsonb,
      'Polish Voivodeship Offices are experiencing significant application backlogs due to the large number of Ukrainian and other foreign worker applications. Apply for your Karta Pobytu well before your current visa or stamp expires. Processing times of 6-12 months are not uncommon. Ensure you receive a confirmation stamp (odcisk stempla) in your passport when you submit your application, as this allows you to stay and work legally while waiting.',
      'Submit your Karta Pobytu application to the Voivodeship Office well before your permitted stay expires and obtain the confirmation stamp, register for PESEL at your gmina office, obtain your NIP (tax identification number) from the tax office (Urzad Skarbowy), open a Polish bank account (PKO, Pekao, or mBank are popular), register with the National Health Fund (NFZ) for healthcare coverage, and consider taking Polish language classes early if planning for citizenship.'
    );
  END IF;

  -- ============================================================
  -- QATAR
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'qatar';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Qatar is a high-income Gulf state with zero income tax and a rapidly modernizing economy following the 2022 FIFA World Cup. Doha is the primary destination for expatriates, who make up approximately 85-90% of Qatar''s population. Qatar reformed its kafala (sponsorship) system in 2020-2021, introducing some labor mobility and a minimum wage. Key sectors include energy (LNG, oil), finance, construction, aviation, and education. Qatar Foundation and Qatar Airways are major employers of international professionals.',
      '[
        {"question": "How does employment sponsorship work in Qatar?", "answer": "Qatar still operates a modified kafala system. Your employer sponsors your residence permit (RP) and work visa. The employer applies to the Ministry of Interior. You enter on a work visa, complete a medical test, and receive your QID (Qatar ID). Since 2021 reforms, workers can change jobs without employer permission after completing 1 year of service (or before with employer consent or through Ministry arbitration). Exit permits were abolished in 2020."},
        {"question": "Is there income tax in Qatar?", "answer": "Qatar has no personal income tax. This is the primary financial attraction for professionals. There is a 10% corporate tax on certain businesses. No capital gains tax, no inheritance tax. VAT has not been implemented (as of 2024). Combined with high salaries in the energy, finance, and tech sectors, Qatar offers strong net income for qualified professionals. Many packages also include housing allowances and return flights."},
        {"question": "What is the Qatar QID and why is it essential?", "answer": "The QID (Qatar ID / Resident Permit) is the national identity card for all expatriate residents. Required for: opening a bank account, signing a lease, accessing healthcare, getting a driving license, and virtually all government services. Issued by the Ministry of Interior after medical fitness test completion. Fee approximately QAR 100-200. Must be renewed annually (fee QAR 100-200). Lost or expired QID should be renewed immediately to avoid overstay penalties."},
        {"question": "What is the Qatar residency permit fee structure?", "answer": "Qatar RP costs: visa fee QAR 200-500 (varies by nationality and type), medical examination QAR 300-500, QID issuance QAR 100-200. Total government fees: QAR 600-1,200 (approximately USD 165-330). However, most employers cover these costs as part of the employment package for professional roles. Annual QID renewal is paid by the employee or employer depending on contract terms."},
        {"question": "Can I bring my family to Qatar?", "answer": "Residents earning at least QAR 5,000/month can sponsor family members (spouse, children under 18, and sometimes parents). Family RP costs are similar to the main applicant. Spouses cannot work without their own separate work visa. Qatar has an International School market and healthcare facilities for families. Family housing in Doha: villas in family compounds QAR 10,000-20,000/month; apartments QAR 4,000-8,000/month."},
        {"question": "Is permanent residence or citizenship possible in Qatar?", "answer": "Permanent residence in Qatar was introduced in 2018 for certain categories: those who have resided for 20+ years, those with special skills needed by Qatar, children of Qatari mothers married to non-Qataris. Permanent residents get QID without expiry and access to healthcare and education benefits. Naturalization to Qatari citizenship is extremely rare and discretionary, generally reserved for those who have made exceptional contributions to Qatar."},
        {"question": "What is the cost of living in Doha?", "answer": "Doha has moderate-to-high costs. 1-bedroom apartment in central Doha: QAR 5,000-8,000/month (USD 1,370-2,200). Housing costs are the largest expense; many professional packages include housing allowance (QAR 5,000-10,000+/month) which significantly offsets this. Food: QAR 1,500-3,000/month depending on lifestyle. No alcohol in most settings (some licensed hotels). Total monthly costs excluding housing: QAR 4,000-8,000 (USD 1,100-2,200)."}
      ]'::jsonb,
      'Qatar''s kafala reforms improved labor mobility but the system still ties your legal residence to your employment; losing your job means a limited window to find new employment or leave. All medical examinations must be completed at approved Qatar government health centers. Alcohol is restricted (licensed venues only); research cultural expectations before arrival. QID renewal should be tracked carefully as overstaying even a day triggers penalties.',
      'Confirm your employment contract clearly states who covers RP and QID fees, complete your medical fitness examination at a Qatar-approved health center promptly after arrival, obtain your QID as soon as possible after arrival as it is required for all other steps, open a Qatar bank account (QNB, Commercial Bank, or Doha Bank are common), register with your local embassy or consulate for emergency contact purposes, and understand the current job change rules under the reformed kafala system before making any employment decisions.'
    );
  END IF;

END $$;
