/*
  # Add Missing Pathways - Batch 4

  1. Adds "Family" goal alias for Chile (which only had "Family Reunification")
  2. Adds "Visit" goal for destinations missing it (tourist/short-stay)
  3. Adds "Residency" goal for destinations that had "Permanent Residency" only
  4. Fills any remaining common goals for smaller destinations
*/

INSERT INTO immigration_pathways (passport_slug, destination_slug, goal, pathway_name, summary, eligibility, key_requirements, typical_timeline, estimated_fees, pathway_type, requirements, processing_time, validity_period, official_url, last_updated)
VALUES

-- CHILE - add "Family" alias (currently only has "Family Reunification")
('any','chile','Family','Chile Family Reunification Visa','Join a legally residing family member in Chile.','Spouses and children of Chilean residents or citizens.','Valid passport; marriage/birth certificate; sponsor documents; financial proof; clean criminal record.','4-8 weeks','USD 200-400','family','Marriage/birth certificate, sponsor documents, financial proof, clean criminal record.','4-8 weeks','1 year, renewable','https://www.extranjeria.gob.cl','2025-01-01'),

-- Add "Visit" goal for countries that are missing it (tourism/short-stay)
('any','argentina','Visit','Argentina Tourist Visa','Visit Argentina as a tourist for up to 90 days.','Citizens of most countries can visit Argentina visa-free for 90 days. Some nationalities require a Reciprocity Fee.','Valid passport; proof of sufficient funds; return ticket; proof of accommodation.','Visa on arrival or e-visa (1-3 days)','Free for most nationalities; USD 160 reciprocity fee for some','visit','Valid passport, proof of sufficient funds, return ticket, proof of accommodation.','Visa on arrival or e-visa (1-3 days)','Up to 90 days','https://www.migraciones.gov.ar','2025-01-01'),
('any','brazil','Visit','Brazil Tourist Visa','Visit Brazil as a tourist. Most nationalities enter visa-free.','Citizens of most countries enter visa-free. Some nationalities require a tourist visa.','Valid passport; sufficient funds; return ticket; accommodation details.','Visa on arrival or e-visa (1-5 days)','Free for most; BRL 400+ for some nationalities','visit','Valid passport, sufficient funds, return ticket, accommodation details.','Visa on arrival or e-visa (1-5 days)','Up to 90 days','https://www.gov.br/mre/en','2025-01-01'),
('any','turkey','Visit','Turkey Tourist e-Visa','Visit Turkey on the easy online e-Visa system.','Citizens of over 100 nationalities are eligible for the Turkey e-Visa.','Valid passport; completed online e-Visa application; travel insurance recommended.','1-3 business days','USD 50-100 (varies by nationality)','visit','Valid passport, completed online e-Visa application.','1-3 business days','Up to 90 days within 180 days','https://www.evisa.gov.tr','2025-01-01'),
('any','thailand','Visit','Thailand Tourist Visa (METV/Visa Exemption)','Visit Thailand as a tourist — visa-free for many nationalities.','Citizens of over 60 countries enter Thailand visa-free for 30-60 days.','Valid passport; sufficient funds (THB 20,000); return ticket; accommodation details.','Visa exemption (no processing) or 1-5 days for visa','THB 2,000 (~$55) for tourist visa; free for exempt nationalities','visit','Valid passport, sufficient funds (THB 20,000), return ticket, accommodation details.','Visa exemption or 1-5 days','30-60 days (visa exemption) or 60 days (tourist visa)','https://www.thaiembassy.com','2025-01-01'),
('any','malaysia','Visit','Malaysia Tourist Visa / Visa Free','Visit Malaysia as a tourist — visa-free for most nationalities.','Citizens of over 160 countries enter Malaysia visa-free.','Valid passport; sufficient funds; return ticket; proof of accommodation.','Visa on arrival or no processing needed','Free for most nationalities','visit','Valid passport, sufficient funds, return ticket, proof of accommodation.','Visa on arrival or no processing','Up to 90 days','https://www.imi.gov.my','2025-01-01'),
('any','indonesia','Visit','Indonesia Visa on Arrival','Visit Indonesia on a Visa on Arrival or Visa Free entry.','Citizens of many countries are eligible for Visa on Arrival or Visa Free access.','Valid passport; USD 35 for Visa on Arrival; return ticket; sufficient funds.','On arrival','USD 35 (Visa on Arrival); free for Visa Free countries','visit','Valid passport, return ticket, sufficient funds, USD 35 for Visa on Arrival.','On arrival','30 days, extendable to 60 days','https://evisa.imigrasi.go.id','2025-01-01'),
('any','vietnam','Visit','Vietnam e-Visa','Visit Vietnam on the easy online e-Visa.','Citizens of over 80 countries are eligible for Vietnam e-Visa.','Valid passport; completed e-Visa application; accommodation address; return ticket.','3 business days','USD 25','visit','Valid passport, completed e-Visa application, accommodation address, return ticket.','3 business days','Up to 90 days (single or multiple entry)','https://evisa.xuatnhapcanh.gov.vn','2025-01-01'),
('any','philippines','Visit','Philippines Tourist Visa','Visit the Philippines as a tourist — visa-free for most nationalities.','Citizens of over 150 countries enter visa-free for 30 days.','Valid passport; return ticket; sufficient funds; proof of accommodation.','Visa exemption (no processing) or 1-5 days for visa','Free for most nationalities','visit','Valid passport, return ticket, sufficient funds, proof of accommodation.','Visa exemption or 1-5 days','30 days (visa-free), extendable to 59 days','https://www.immigration.gov.ph','2025-01-01'),
('any','south-korea','Visit','South Korea Tourist Visa / K-ETA','Visit South Korea as a tourist — visa-free for many nationalities.','Citizens of over 110 countries enter Korea visa-free for 90 days.','Valid passport; K-ETA or tourist visa application; sufficient funds; return ticket.','K-ETA: 72 hours; tourist visa: 5-10 business days','K-ETA: USD 10; tourist visa: USD 40-80','visit','Valid passport, K-ETA or tourist visa, sufficient funds, return ticket.','K-ETA: 72 hours; tourist visa: 5-10 business days','Up to 90 days','https://www.immigration.go.kr','2025-01-01'),
('any','australia','Visit','Australia Tourist Visa (eVisitor/ETA)','Visit Australia on the electronic Tourist Visa.','Citizens of many passport-eligible countries can apply for an eVisitor or ETA online.','Valid passport; completed online application; evidence of sufficient funds; return travel plans.','1-7 business days','eVisitor: Free; ETA: AUD 20','visit','Valid passport, completed online application, evidence of sufficient funds, return travel plans.','1-7 business days','Up to 12 months, stays up to 3 months at a time','https://immi.homeaffairs.gov.au','2025-01-01'),
('any','new-zealand','Visit','New Zealand Visitor Visa / NZeTA','Visit New Zealand on the NZeTA (New Zealand Electronic Travel Authority).','Citizens of visa-waiver countries need the NZeTA before arrival.','Valid passport; NZeTA application; IVL fee; travel insurance; sufficient funds.','72 hours','NZD 17 online + NZD 35 IVL','visit','Valid passport, NZeTA application, IVL fee, travel insurance, sufficient funds.','72 hours','Up to 90 days','https://www.immigration.govt.nz','2025-01-01'),
('any','canada','Visit','Canada Visitor Visa / eTA','Visit Canada on a Visitor Visa or Electronic Travel Authorization (eTA).','eTA: citizens of visa-exempt countries traveling by air. Visitor Visa: all others.','Valid passport; completed online application; purpose of visit; sufficient funds; return ticket.','eTA: minutes to 72 hours; Visitor Visa: 2-4 weeks','eTA: CAD 7; Visitor Visa: CAD 100','visit','Valid passport, completed application, purpose of visit, sufficient funds, return ticket.','eTA: minutes to 72 hours; Visitor Visa: 2-4 weeks','Up to 6 months','https://www.canada.ca/immigration','2025-01-01'),
('any','united-states','Visit','USA Tourist Visa (B-2) / ESTA','Visit the United States on the Visa Waiver Program (ESTA) or B-2 Tourist Visa.','ESTA: citizens of 42 Visa Waiver Program countries. B-2: all other nationalities.','Valid passport; ESTA or B-2 visa application; proof of ties to home country; sufficient funds.','ESTA: minutes to 72 hours; B-2: 2-6 weeks','ESTA: USD 21; B-2 visa: USD 160','visit','Valid passport, ESTA or B-2 visa application, proof of ties to home country, sufficient funds.','ESTA: minutes to 72 hours; B-2: 2-6 weeks','ESTA: up to 90 days; B-2: up to 6 months','https://travel.state.gov','2025-01-01'),
('any','united-kingdom','Visit','UK Standard Visitor Visa','Visit the United Kingdom as a tourist or for short business/study stays.','Citizens of many countries can visit the UK visa-free for up to 6 months. Others require a Standard Visitor Visa.','Valid passport; completed online application; proof of ties to home country; sufficient funds; travel history.','3-6 weeks','GBP 115','visit','Valid passport, completed online application, proof of ties to home country, sufficient funds, travel history.','3-6 weeks','Up to 6 months per visit','https://www.gov.uk/standard-visitor-visa','2025-01-01'),
('any','china','Visit','China Tourist Visa (L Visa)','Visit China on a tourist visa (L visa).','All nationalities (except visa-free eligible) must apply for an L visa at a Chinese consulate.','Valid passport; completed application form; invitation letter or tour booking; passport photos; bank statements.','4-7 business days','USD 100-200 (varies by nationality)','visit','Valid passport, completed application form, invitation letter or tour booking, passport photos, bank statements.','4-7 business days','Usually 30-90 days per entry','https://www.visaforchina.cn','2025-01-01'),
('any','india','Visit','India Tourist Visa (e-Visa)','Visit India on the convenient e-Visa system.','Citizens of over 160 countries are eligible for India e-Visa.','Valid passport; completed e-Visa application; digital passport photo; return/onward ticket.','1-4 business days','USD 25-100 (varies by nationality)','visit','Valid passport, completed e-Visa application, digital passport photo, return/onward ticket.','1-4 business days','30-60 days per entry (varies)','https://indianvisaonline.gov.in','2025-01-01'),
('any','singapore','Visit','Singapore Tourist Visa / Visa-Free','Visit Singapore as a tourist — visa-free for most nationalities.','Citizens of over 160 countries enter Singapore visa-free.','Valid passport; return ticket; sufficient funds; proof of accommodation.','No processing for visa-free; 1-2 weeks for visa countries','Free for most nationalities','visit','Valid passport, return ticket, sufficient funds, proof of accommodation.','No processing for visa-free; 1-2 weeks for visa countries','Up to 30-90 days','https://www.ica.gov.sg','2025-01-01'),
('any','united-arab-emirates','Visit','UAE Tourist Visa','Visit the UAE as a tourist — many nationalities enter visa-free.','Citizens of GCC countries and visa-waiver nationalities enter visa-free.','Valid passport; return ticket; sufficient funds; proof of accommodation; travel insurance.','1-3 business days for visa on arrival','Free for visa-free nationalities; AED 30-100 for visa on arrival','visit','Valid passport, return ticket, sufficient funds, proof of accommodation.','1-3 business days','30 days (extendable to 60 days)','https://www.icp.gov.ae','2025-01-01'),
('any','saudi-arabia','Visit','Saudi Arabia Tourist e-Visa','Visit Saudi Arabia on the online tourist e-Visa, open to 51 nationalities.','Citizens of 51 eligible countries can apply online.','Valid passport; completed e-Visa application; travel/health insurance; debit/credit card.','1-3 business days','SAR 300 (~$80) + VAT','visit','Valid passport, completed e-Visa application, travel/health insurance.','1-3 business days','90 days per visit, valid 1 year','https://visa.visitsaudi.com','2025-01-01'),
('any','egypt','Visit','Egypt Tourist Visa / Visa on Arrival','Visit Egypt — available as e-Visa or visa on arrival for most nationalities.','Citizens of most countries are eligible for Egypt visa on arrival or e-Visa.','Valid passport; completed application; USD 25 fee; return ticket; accommodation details.','e-Visa: 1-3 business days; Visa on Arrival: upon arrival','USD 25','visit','Valid passport, completed application, USD 25 fee, return ticket, accommodation details.','e-Visa: 1-3 business days; Visa on Arrival: upon arrival','30 days (extendable once to 60 days)','https://visa2egypt.gov.eg','2025-01-01'),
('any','morocco','Visit','Morocco Tourist Visa','Visit Morocco — visa-free for citizens of many countries.','Citizens of over 60 countries enter Morocco visa-free for 90 days.','Valid passport; return ticket; sufficient funds; accommodation details.','No processing for visa-free countries','Free for most nationalities','visit','Valid passport, return ticket, sufficient funds, accommodation details.','No processing','Up to 90 days','https://www.marocain.ma','2025-01-01'),
('any','south-africa','Visit','South Africa Tourist Visa','Visit South Africa — visa-free for many nationalities.','Citizens of over 70 countries enter South Africa visa-free.','Valid passport (6 months validity); return ticket; sufficient funds; proof of accommodation; yellow fever certificate (if applicable).','1-15 business days for visa; no processing for visa-free','ZAR 300-500 (~$16-27) for visa; free for exempt','visit','Valid passport, return ticket, sufficient funds, proof of accommodation.','1-15 business days for visa; no processing for visa-free','Up to 90 days','https://www.dha.gov.za','2025-01-01'),
('any','brazil','Visit','Brazil Visa-Free Entry','Visit Brazil — visa-free for citizens of many countries for up to 90 days.','Citizens of over 90 countries enter Brazil visa-free.','Valid passport; return ticket; sufficient funds; accommodation details.','No processing required','Free','visit','Valid passport, return ticket, sufficient funds, accommodation details.','No processing','Up to 90 days per 180 days','https://www.gov.br/mre/en','2025-01-01'),
('any','colombia','Visit','Colombia Tourist Visa','Visit Colombia — visa-free for most nationalities.','Citizens of over 100 countries enter Colombia visa-free for 90 days.','Valid passport; return ticket; sufficient funds; accommodation details; yellow fever certificate (recommended).','No processing for visa-free countries','Free for visa-free nationalities','visit','Valid passport, return ticket, sufficient funds, accommodation details.','No processing','Up to 90 days (extendable to 180 days/year)','https://www.cancilleria.gov.co','2025-01-01'),
('any','peru','Visit','Peru Tourist Visa','Visit Peru — visa-free for most nationalities.','Citizens of most countries enter Peru visa-free for 90 days.','Valid passport; return ticket; sufficient funds; accommodation details.','No processing for visa-free countries','Free for most nationalities','visit','Valid passport, return ticket, sufficient funds, accommodation details.','No processing','Up to 90 days (extendable to 183 days/year)','https://migraciones.gob.pe','2025-01-01'),
('any','nigeria','Visit','Nigeria Tourist Visa','Visit Nigeria on a tourist visa.','All nationalities require a visa to visit Nigeria (except ECOWAS citizens).','Valid passport; completed online application; invitation letter or hotel booking; bank statements; yellow fever certificate.','5-10 business days','USD 100-160','visit','Valid passport, completed online application, invitation letter or hotel booking, bank statements, yellow fever certificate.','5-10 business days','Up to 30 days (extendable)','https://portal.immigration.gov.ng','2025-01-01'),
('any','kenya','Visit','Kenya e-Visa','Visit Kenya on the online e-Visa system.','All nationalities (except EAC citizens) must apply for an e-Visa.','Valid passport; completed e-Visa application; return ticket; accommodation booking; USD 100 fee.','3 business days','USD 100','visit','Valid passport, completed e-Visa application, return ticket, accommodation booking.','3 business days','Up to 90 days (single entry)','https://evisa.go.ke','2025-01-01'),
('any','tanzania','Visit','Tanzania e-Visa','Visit Tanzania including Zanzibar on the online e-Visa.','Most nationalities must apply for an e-Visa before arrival.','Valid passport; completed e-Visa application; return ticket; USD 50 fee; accommodation details.','2-5 business days','USD 50','visit','Valid passport, completed e-Visa application, return ticket, USD 50 fee.','2-5 business days','Up to 90 days','https://eservices.immigration.go.tz','2025-01-01'),
('any','ghana','Visit','Ghana e-Visa','Visit Ghana on the online e-Visa system.','Most nationalities require an e-Visa to visit Ghana.','Valid passport; completed e-Visa application; return ticket; bank statement; USD 100-150 fee.','5-7 business days','USD 100-150','visit','Valid passport, completed e-Visa application, return ticket, bank statement.','5-7 business days','Up to 60 days','https://www.ghana.gov.gh','2025-01-01'),

-- Add Residency for destinations that only had "Permanent Residency"
('any','egypt','Residency','Egypt Long-Term Residence Permit','Obtain long-term residency in Egypt through investment or property.','Foreign nationals investing in Egypt or purchasing property valued at $100,000+ USD.','Valid passport; proof of investment or property purchase ($100,000+); clean criminal record; health certificate.','2-3 months','USD 200-500','residency','Proof of investment or property purchase, clean criminal record, health certificate.','2-3 months','3-5 years, renewable','https://www.immigration.gov.eg','2025-01-01'),
('any','mexico','Residency','Mexico Temporary Resident Card','Obtain temporary residency in Mexico through financial solvency or employment.','Foreign nationals with proven financial solvency ($2,000+ monthly income) or a job offer.','Valid passport; proof of financial solvency; Mexican consulate application; background check.','4-8 weeks','MXN 2,000-5,000 (~$100-250) consular fee','residency','Proof of financial solvency, Mexican consulate application, background check.','4-8 weeks','1-4 years, renewable','https://www.gob.mx/inm','2025-01-01'),
('any','greece','Residency','Greece Golden Visa (Real Estate)','Obtain residency in Greece through real estate investment (EUR 250,000+).','Non-EU nationals investing EUR 250,000+ in Greek real estate.','Valid passport; proof of real estate investment (EUR 250,000+); health insurance; clean criminal record.','2-4 months','EUR 2,000-5,000 government fees','residency','Proof of real estate investment (EUR 250,000+), health insurance, clean criminal record.','2-4 months','5 years, renewable','https://www.migration.gov.gr','2025-01-01')

ON CONFLICT DO NOTHING;
