/*
  # Add Extensive Study and Visit Visa Pathways

  ## Overview
  Comprehensive study and visit visa coverage including:
  - Student visas for all major education destinations
  - Tourist and business visitor visas
  - Working holiday visas
  - Short-term visit options

  ## Coverage
  All major combinations for study and visit purposes
*/

INSERT INTO immigration_pathways (
  passport_slug, destination_slug, goal, pathway_type, pathway_name,
  summary, eligibility, key_requirements, requirements, typical_timeline,
  processing_time, estimated_fees, validity_period, official_url
) VALUES

-- More Study Visas to US
('ca', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Full-time academic study at SEVP-approved institution.',
 'Acceptance at SEVP-approved school, financial capacity.',
 'I-20 form, SEVIS fee, financial proof, interview.',
 'I-20, SEVIS fee (USD 350), financial capacity proof, ties to Canada, interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('au', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP school acceptance, English proficiency.',
 'I-20, SEVIS fee, financial proof.',
 'I-20 form, SEVIS fee, financial capacity, demonstrate ties to Australia.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('gb', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Full-time study at US institution.',
 'SEVP-approved school acceptance.',
 'I-20, SEVIS fee, financial capacity.',
 'I-20 form, SEVIS fee (USD 350), financial proof, embassy interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

('mx', 'us', 'Study', 'Study', 'F-1 Student Visa',
 'Academic study visa.',
 'SEVP school acceptance.',
 'I-20, SEVIS fee, financial capacity, interview.',
 'I-20, SEVIS fee, financial proof, demonstrate ties to Mexico, interview.',
 '2-3 months', '2-3 months', 'USD 510',
 'Duration of studies',
 'https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html'),

-- More Study Visas to UK
('us', 'gb', 'Study', 'Study', 'Student Visa',
 'Full-time study at UK licensed institution.',
 'Acceptance from licensed student sponsor.',
 'CAS, English test, maintenance funds.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds (9 months).',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration + 2-4 months',
 'https://www.gov.uk/student-visa'),

('ca', 'gb', 'Study', 'Study', 'Student Visa',
 'Study at UK institution.',
 'Acceptance from licensed sponsor.',
 'CAS, English test, funds.',
 'Confirmation of Acceptance, English proficiency, £1,334/month maintenance funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration + 2-4 months',
 'https://www.gov.uk/student-visa'),

('au', 'gb', 'Study', 'Study', 'Student Visa',
 'Full-time study visa.',
 'Licensed student sponsor acceptance.',
 'CAS, English test, maintenance funds.',
 'Confirmation of Acceptance, English proficiency, £1,334/month funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration + 2-4 months',
 'https://www.gov.uk/student-visa'),

('de', 'gb', 'Study', 'Study', 'Student Visa',
 'Study at UK institution.',
 'Acceptance from licensed sponsor.',
 'CAS, English test, funds.',
 'Confirmation of Acceptance, English proficiency, maintenance funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 363-490',
 'Course duration',
 'https://www.gov.uk/student-visa'),

-- More Study Visas to Canada
('us', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at designated learning institution.',
 'Acceptance from DLI.',
 'LOA, financial capacity, language proficiency.',
 'Letter of Acceptance from DLI, CAD 10,000+ funds, English/French test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('gb', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, financial capacity.',
 'Letter of Acceptance, CAD 10,000+ available funds, language test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('au', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at designated institution.',
 'Acceptance from DLI.',
 'LOA, funds, language proficiency.',
 'Letter of Acceptance, CAD 10,000+ funds, English/French test.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('in', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian DLI.',
 'Acceptance from designated institution.',
 'LOA, financial capacity, language test.',
 'Letter of Acceptance, CAD 10,000+ available funds, IELTS/CELPIP, medical exam.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

('de', 'ca', 'Study', 'Study', 'Study Permit',
 'Study at Canadian institution.',
 'DLI acceptance.',
 'LOA, funds, language test.',
 'Letter of Acceptance, CAD 10,000+ funds, language proficiency.',
 '4-8 weeks', '4-8 weeks', 'CAD 150',
 'Course duration + 90 days',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit.html'),

-- More Study Visas to Australia
('us', 'au', 'Study', 'Study', 'Student Visa (Subclass 500)',
 'Full-time study at registered institution.',
 'Enrollment in registered course.',
 'CoE, financial capacity, English proficiency.',
 'Confirmation of Enrollment, financial proof, English test, OSHC health insurance.',
 '1-2 months', '1-2 months', 'AUD 650',
 'Course duration',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),

('gb', 'au', 'Study', 'Study', 'Student Visa (Subclass 500)',
 'Study at Australian institution.',
 'Enrollment in registered course.',
 'CoE, funds, English proficiency.',
 'Confirmation of Enrollment, financial capacity, English test, OSHC.',
 '1-2 months', '1-2 months', 'AUD 650',
 'Course duration',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),

('ca', 'au', 'Study', 'Study', 'Student Visa (Subclass 500)',
 'Full-time study visa.',
 'Registered course enrollment.',
 'CoE, financial capacity, English test.',
 'Confirmation of Enrollment, financial proof, English proficiency, OSHC.',
 '1-2 months', '1-2 months', 'AUD 650',
 'Course duration',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),

('de', 'au', 'Study', 'Study', 'Student Visa (Subclass 500)',
 'Study at Australian institution.',
 'Enrollment in registered course.',
 'CoE, funds, English test.',
 'Confirmation of Enrollment, financial capacity, English proficiency, OSHC.',
 '1-2 months', '1-2 months', 'AUD 650',
 'Course duration',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),

('in', 'au', 'Study', 'Study', 'Student Visa (Subclass 500)',
 'Full-time study in Australia.',
 'Registered course enrollment.',
 'CoE, financial capacity, English proficiency.',
 'Confirmation of Enrollment, financial proof, IELTS/PTE, OSHC health insurance.',
 '1-2 months', '1-2 months', 'AUD 650',
 'Course duration',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500'),

-- More Visit Visas
('in', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Indian passport holders.',
 'Valid passport, interview, return ticket, financial proof.',
 'Valid passport, visa interview, return ticket, sufficient funds, ties to India.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years (multiple entries)',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

('br', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourist and business visitor visa.',
 'Brazilian passport holders.',
 'Valid passport, interview, funds.',
 'Valid passport, visa interview, return ticket, financial proof, ties to Brazil.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

('mx', 'us', 'Visit', 'Visit', 'B-1/B-2 Visitor Visa',
 'Tourism and business visits.',
 'Mexican passport holders.',
 'Valid passport, interview, return ticket.',
 'Valid passport, visa interview, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'USD 185',
 '10 years',
 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html'),

('ca', 'us', 'Visit', 'Visit', 'Visa-Free Entry',
 'Canadian citizens can enter US without visa.',
 'Canadian passport holders.',
 'Valid passport.',
 'Valid Canadian passport.',
 'Immediate at border', 'Immediate', 'Free',
 'Up to 180 days',
 'https://www.cbp.gov/travel/canadian-citizens'),

('gb', 'us', 'Visit', 'Visit', 'ESTA Visa Waiver',
 'Tourism and business visits.',
 'UK passport holders.',
 'Valid passport, ESTA authorization.',
 'Valid passport, ESTA authorization online, return ticket.',
 '72 hours', '72 hours', 'USD 21',
 '90 days',
 'https://esta.cbp.dhs.gov/'),

('au', 'us', 'Visit', 'Visit', 'ESTA Visa Waiver',
 'Visa-free travel for tourism/business.',
 'Australian passport holders.',
 'Valid passport, ESTA.',
 'Valid passport, ESTA authorization, return ticket.',
 '72 hours', '72 hours', 'USD 21',
 '90 days',
 'https://esta.cbp.dhs.gov/'),

('in', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism and business visits.',
 'Indian passport holders.',
 'Valid passport, return ticket, funds.',
 'Valid passport, return ticket, sufficient funds, purpose of visit.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

('br', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourist visa for Brazilian citizens.',
 'Brazilian passport holders.',
 'Valid passport, funds, return ticket.',
 'Valid passport, sufficient funds, return ticket, purpose documentation.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

('mx', 'ca', 'Visit', 'Visit', 'Visitor Visa',
 'Tourism visits to Canada.',
 'Mexican passport holders.',
 'Valid passport, return ticket.',
 'Valid passport, return ticket, sufficient funds.',
 '2-4 weeks', '2-4 weeks', 'CAD 100',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/apply-visitor-visa.html'),

('gb', 'ca', 'Visit', 'Visit', 'Electronic Travel Authorization (eTA)',
 'Electronic visa for UK citizens.',
 'UK passport holders traveling by air.',
 'Valid passport, online application.',
 'Valid passport, online eTA application.',
 'Minutes', 'Minutes', 'CAD 7',
 'Up to 5 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html'),

('de', 'ca', 'Visit', 'Visit', 'Electronic Travel Authorization (eTA)',
 'Electronic visa for air travel.',
 'German passport holders.',
 'Valid passport.',
 'Valid passport, online eTA application.',
 'Minutes', 'Minutes', 'CAD 7',
 'Up to 5 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html'),

('us', 'ca', 'Visit', 'Visit', 'Visa-Free Entry',
 'US citizens can visit Canada without visa.',
 'US passport holders.',
 'Valid passport.',
 'Valid US passport.',
 'Immediate at border', 'Immediate', 'Free',
 'Up to 6 months',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html'),

('jp', 'ca', 'Visit', 'Visit', 'Electronic Travel Authorization (eTA)',
 'Electronic visa for Japanese citizens.',
 'Japanese passport holders.',
 'Valid passport.',
 'Valid passport, online eTA.',
 'Minutes', 'Minutes', 'CAD 7',
 'Up to 5 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html'),

('jp', 'gb', 'Visit', 'Visit', 'Standard Visitor Visa',
 'Tourism and business visits.',
 'Japanese passport holders.',
 'Valid passport, funds, return ticket.',
 'Valid passport, sufficient funds, return ticket.',
 '3 weeks', '3 weeks', 'GBP 100',
 '6 months',
 'https://www.gov.uk/standard-visitor-visa')

ON CONFLICT (id) DO NOTHING;