/*
  # Add Extensive Residency, Investor, and Retirement Pathways

  ## Overview
  Comprehensive coverage of:
  - Permanent residence pathways
  - Golden visas and investor programs
  - Retirement visas
  - Family reunification visas
  - Entrepreneur visas

  ## Countries Covered
  All major immigration destinations
*/

INSERT INTO immigration_pathways (
  passport_slug, destination_slug, goal, pathway_type, pathway_name,
  summary, eligibility, key_requirements, requirements, typical_timeline,
  processing_time, estimated_fees, validity_period, official_url
) VALUES

-- More Residency Pathways to US
('in', 'us', 'Residency', 'Residency', 'EB-2 National Interest Waiver',
 'Green card for those whose work benefits US national interest.',
 'Advanced degree or exceptional ability, work benefits US.',
 'Advanced degree, exceptional ability, evidence of national interest.',
 'Advanced degree or equivalent, exceptional ability proof, national interest documentation.',
 '18-36 months', '18-36 months', 'USD 700-1,500',
 'Permanent',
 'https://www.uscis.gov/working-in-the-united-states/permanent-workers/employment-based-immigration-second-preference-eb-2'),

('in', 'us', 'Residency', 'Residency', 'EB-3 Skilled Worker Green Card',
 'Permanent residence for skilled workers.',
 'Bachelor degree or 2+ years experience, job offer.',
 'Job offer, labor certification, qualifications.',
 'Employer sponsorship, labor certification, bachelor degree or 2+ years experience.',
 '2-4 years', '2-4 years', 'USD 700-1,500',
 'Permanent',
 'https://www.uscis.gov/working-in-the-united-states/permanent-workers/employment-based-immigration-third-preference-eb-3'),

('gb', 'us', 'Residency', 'Residency', 'EB-2 National Interest Waiver',
 'Green card through national interest.',
 'Advanced degree, work benefits US.',
 'Degree, exceptional ability, national interest.',
 'Advanced degree, exceptional ability, evidence benefiting US national interest.',
 '18-36 months', '18-36 months', 'USD 700-1,500',
 'Permanent',
 'https://www.uscis.gov/working-in-the-united-states/permanent-workers/employment-based-immigration-second-preference-eb-2'),

('ca', 'us', 'Residency', 'Residency', 'EB-3 Skilled Worker Green Card',
 'Permanent residence through employment.',
 'Job offer, qualifications.',
 'Employer sponsorship, labor certification.',
 'US employer sponsorship, labor certification, bachelor degree or experience.',
 '2-4 years', '2-4 years', 'USD 700-1,500',
 'Permanent',
 'https://www.uscis.gov/working-in-the-united-states/permanent-workers/employment-based-immigration-third-preference-eb-3'),

-- More Residency to UK
('in', 'gb', 'Residency', 'Residency', 'Skilled Worker Visa (Settlement Route)',
 'Work visa leading to permanent settlement.',
 'Job offer from UK sponsor, 5 years residence.',
 'Certificate of Sponsorship, 5 years in UK on eligible visa.',
 'CoS from licensed sponsor, £25,600+ salary, 5 years residence, English test.',
 '5+ years', '3-8 weeks', 'GBP 625-2,885',
 '5 years, leads to settlement',
 'https://www.gov.uk/skilled-worker-visa'),

('us', 'gb', 'Residency', 'Residency', 'Global Talent Visa (Settlement)',
 'Talent visa leading to settlement.',
 'Leader/emerging leader in field.',
 'Endorsement, evidence of talent, 3-5 years residence.',
 'Endorsement from UK body, portfolio, 3-5 years in UK for settlement.',
 '3-5 years', '3-8 weeks', 'GBP 623-716',
 '5 years, leads to settlement',
 'https://www.gov.uk/global-talent'),

('de', 'gb', 'Residency', 'Residency', 'Skilled Worker Visa (Settlement Route)',
 'Work-based settlement pathway.',
 'UK job offer, 5 years residence.',
 'Certificate of Sponsorship, residence period.',
 'CoS, £25,600+ salary, 5 years residence in UK.',
 '5+ years', '3-8 weeks', 'GBP 625-1,423',
 '5 years to settlement',
 'https://www.gov.uk/skilled-worker-visa'),

-- More Residency to Canada
('br', 'ca', 'Residency', 'Residency', 'Provincial Nominee Program',
 'Province-specific permanent residence.',
 'Provincial nomination.',
 'Nomination, language test, work experience.',
 'Provincial nomination, IELTS/CELPIP, work experience, education.',
 '12-18 months', '12-18 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/provincial-nominees.html'),

('jp', 'ca', 'Residency', 'Residency', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, Educational Credential Assessment, 67+ points, funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('mx', 'ca', 'Residency', 'Residency', 'Provincial Nominee Program',
 'Provincial permanent residence.',
 'Provincial nomination.',
 'Nomination, language proficiency, work experience.',
 'Provincial nomination, IELTS/CELPIP, relevant work experience.',
 '12-18 months', '12-18 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/provincial-nominees.html'),

-- More Residency to Australia
('us', 'au', 'Residency', 'Residency', 'Skilled Nominated Visa (Subclass 190)',
 'State-nominated permanent residence.',
 'State nomination, skilled occupation.',
 'State nomination, skills assessment, 65+ points.',
 'State/territory nomination, skills assessment, 65+ points, English test.',
 '6-12 months', '6-12 months', 'AUD 4,115',
 'Permanent',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190'),

('de', 'au', 'Residency', 'Residency', 'Skilled Independent Visa (Subclass 189)',
 'Points-based permanent residence.',
 'Skilled occupation, under 45, 65+ points.',
 'Skills assessment, English proficiency.',
 'Skills assessment, IELTS 6.0+, 65+ points, health checks.',
 '6-9 months', '6-9 months', 'AUD 4,115',
 'Permanent',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189'),

('jp', 'au', 'Residency', 'Residency', 'Skilled Nominated Visa (Subclass 190)',
 'State-sponsored permanent residence.',
 'State nomination, skilled occupation.',
 'State nomination, skills assessment, points.',
 'State/territory nomination, skills assessment, 65+ points, English proficiency.',
 '6-12 months', '6-12 months', 'AUD 4,115',
 'Permanent',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190'),

-- More Investor Visas
('in', 'pt', 'Investor', 'Investor', 'Portugal Golden Visa',
 'Investment-based residence permit.',
 'Investment in Portuguese real estate or business.',
 'Investment €280,000-500,000+, clean record.',
 'Investment proof (€280,000-500,000+), clean criminal record, health insurance.',
 '6-12 months', '6-12 months', 'EUR 5,325-5,847',
 '2 years renewable, leads to citizenship',
 'https://www.imigrante.sef.pt/'),

('jp', 'pt', 'Investor', 'Investor', 'Portugal Golden Visa',
 'Residence through investment.',
 'Investment in Portugal.',
 'Investment €280,000-500,000+, clean record.',
 'Investment (€280,000-500,000+), clean record, health insurance.',
 '6-12 months', '6-12 months', 'EUR 5,325-5,847',
 '2 years renewable',
 'https://www.imigrante.sef.pt/'),

('us', 'es', 'Investor', 'Investor', 'Spain Golden Visa',
 'Investment residence permit.',
 'Investment €500,000+ real estate or €1M+ business.',
 'Investment proof, health insurance.',
 '€500,000+ property or €1M+ investment, health insurance, clean record.',
 '2-3 months', '2-3 months', 'EUR 60-5,180',
 '2 years renewable',
 'https://www.exteriores.gob.es/'),

('ca', 'es', 'Investor', 'Investor', 'Spain Golden Visa',
 'Residence through investment.',
 'Investment in Spanish property/business.',
 'Investment proof, health insurance, clean record.',
 '€500,000+ real estate or €1M+ investment, health insurance, clean record.',
 '2-3 months', '2-3 months', 'EUR 60-5,180',
 '2 years renewable',
 'https://www.exteriores.gob.es/'),

('in', 'ae', 'Investor', 'Investor', 'UAE Investor Visa',
 'Residence through investment.',
 'Investment AED 2M+ in property or business.',
 'Investment proof, clean record.',
 'Investment AED 2M+ (property/business/fund), passport, emirates ID.',
 '2-3 months', '2-3 months', 'AED 3,000-5,000',
 '5-10 years renewable',
 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas-for-investors-and-entrepreneurs'),

('gb', 'ae', 'Investor', 'Investor', 'UAE Investor Visa',
 'Long-term residence through investment.',
 'Investment AED 2M+ in UAE.',
 'Investment proof.',
 'Investment AED 2M+ (property/business), passport, clean record.',
 '2-3 months', '2-3 months', 'AED 3,000-5,000',
 '5-10 years renewable',
 'https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas-for-investors-and-entrepreneurs'),

('us', 'sg', 'Investor', 'Investor', 'Global Investor Programme',
 'Permanent residence through investment.',
 'Business track record, SGD 2.5M+ investment.',
 'Business experience, investment, business plan.',
 'Entrepreneurial background, SGD 2.5M+ investment, detailed business proposal.',
 '4-6 months', '4-6 months', 'SGD 9,650',
 'Permanent residence',
 'https://www.edb.gov.sg/en/how-we-help/global-investor-programme.html'),

('ca', 'sg', 'Investor', 'Investor', 'Global Investor Programme',
 'Investment-based permanent residence.',
 'Established business track record.',
 'Business experience, SGD 2.5M+ investment.',
 'Entrepreneurial background, SGD 2.5M+ investment, business plan.',
 '4-6 months', '4-6 months', 'SGD 9,650',
 'Permanent',
 'https://www.edb.gov.sg/en/how-we-help/global-investor-programme.html'),

-- More Retirement Visas
('gb', 'pt', 'Retirement', 'Retirement', 'D7 Passive Income Visa',
 'Retirement visa for pension earners.',
 'Passive income €820+/month.',
 'Income proof, bank account, accommodation.',
 'Passive income proof (€820/month), Portuguese bank account, accommodation, health insurance.',
 '2-4 months', '2-4 months', 'EUR 83',
 '2 years renewable',
 'https://www.imigrante.sef.pt/'),

('us', 'pt', 'Retirement', 'Retirement', 'D7 Passive Income Visa',
 'For retirees with pension or passive income.',
 'Monthly income €820+ from pension/investments.',
 'Income proof, bank account, accommodation.',
 'Passive income proof (€820/month), bank account, accommodation, health insurance.',
 '2-4 months', '2-4 months', 'EUR 83',
 '2 years renewable',
 'https://www.imigrante.sef.pt/'),

('au', 'pt', 'Retirement', 'Retirement', 'D7 Passive Income Visa',
 'Retirement visa.',
 'Passive income €820+/month.',
 'Income proof, accommodation, health insurance.',
 'Passive income €820/month, bank account, accommodation, health insurance.',
 '2-4 months', '2-4 months', 'EUR 83',
 '2 years renewable',
 'https://www.imigrante.sef.pt/'),

('ca', 'es', 'Retirement', 'Retirement', 'Non-Lucrative Visa',
 'Retirement visa for financial independence.',
 'Income €28,800+/year.',
 'Income proof, health insurance, clean record.',
 'Income €28,800+/year, health insurance, clean criminal record, medical exam.',
 '1-3 months', '1-3 months', 'EUR 80',
 '1 year renewable',
 'https://www.exteriores.gob.es/'),

('gb', 'es', 'Retirement', 'Retirement', 'Non-Lucrative Visa',
 'For retirees with financial means.',
 'Annual income €28,800+.',
 'Income/savings proof, health insurance.',
 'Income €28,800+/year, health insurance, clean record, medical certificate.',
 '1-3 months', '1-3 months', 'EUR 80',
 '1 year renewable',
 'https://www.exteriores.gob.es/'),

('us', 'mx', 'Retirement', 'Retirement', 'Temporary Resident Visa (Retiree)',
 'Retirement based on financial solvency.',
 'Monthly income USD 2,000+ or savings USD 32,000+.',
 'Bank statements, income proof.',
 'Income USD 2,000+/month or USD 32,000+ savings, bank statements, passport.',
 '2-4 weeks', '2-4 weeks', 'USD 45-60',
 '1-4 years renewable',
 'https://www.inm.gob.mx/'),

('ca', 'mx', 'Retirement', 'Retirement', 'Temporary Resident Visa (Retiree)',
 'Retirement visa.',
 'Income USD 2,000+/month or savings.',
 'Bank statements, income proof.',
 'Income USD 2,000+/month or USD 32,000+ savings, bank statements.',
 '2-4 weeks', '2-4 weeks', 'USD 45-60',
 '1-4 years renewable',
 'https://www.inm.gob.mx/'),

('gb', 'cr', 'Retirement', 'Retirement', 'Pensionado Visa',
 'Retirement visa for pension recipients.',
 'Pension USD 1,000+/month.',
 'Pension proof, police clearance, health certificate.',
 'Pension USD 1,000+/month, police clearance, birth certificate, health exam.',
 '3-6 months', '3-6 months', 'USD 350',
 '2 years renewable',
 'https://www.migracion.go.cr/'),

('us', 'cr', 'Retirement', 'Retirement', 'Pensionado Visa',
 'For retirees with pension.',
 'Monthly pension USD 1,000+.',
 'Pension proof, police clearance.',
 'Pension USD 1,000+/month, police clearance, birth certificate, health certificate.',
 '3-6 months', '3-6 months', 'USD 350',
 '2 years renewable',
 'https://www.migracion.go.cr/')

ON CONFLICT (id) DO NOTHING;