/*
  # Add Missing Pathways - Batch 2

  Adds missing goal pathways for:
  Dominican Republic, Ecuador, Estonia, Ethiopia, Georgia, Ghana,
  Iceland, Jamaica, Jordan, Kazakhstan, Kenya, Kuwait, Laos,
  Latvia, Lithuania, Luxembourg
*/

INSERT INTO immigration_pathways (passport_slug, destination_slug, goal, pathway_name, summary, eligibility, key_requirements, typical_timeline, estimated_fees, pathway_type, requirements, processing_time, validity_period, official_url, last_updated)
VALUES

-- DOMINICAN REPUBLIC missing goals
('any','dominican-republic','Study','Dominican Republic Student Visa','Study at Dominican universities and colleges.','International students accepted to Dominican educational institutions.','Valid passport; university acceptance letter; proof of finances; health insurance.','3-6 weeks','DOP 2,000-6,000 (~$35-105)','study','University acceptance letter, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.migracion.gob.do','2025-01-01'),
('any','dominican-republic','Family','Dominican Republic Family Visa','Join a legal resident or citizen of the Dominican Republic as a family member.','Spouses and children of Dominican residents/citizens.','Valid passport; proof of family relationship; sponsor documents; financial support.','4-8 weeks','DOP 3,000-8,000 (~$53-140)','family','Proof of family relationship, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.migracion.gob.do','2025-01-01'),
('any','dominican-republic','Retirement','Dominican Republic Retirement Visa (Pensionado)','Retire in the Dominican Republic on the Pensionado program.','Retirees with verified pension income of at least $1,500/month.','Valid passport; proof of pension ($1,500+/month); health insurance; clean criminal record.','4-8 weeks','USD 200-500','retirement','Proof of pension ($1,500+/month), health insurance, clean criminal record.','4-8 weeks','1 year, renewable','https://www.migracion.gob.do','2025-01-01'),
('any','dominican-republic','Digital Nomad','Dominican Republic Digital Nomad Visa','Work remotely from the Dominican Republic.','Remote workers and freelancers employed by non-Dominican companies.','Valid passport; proof of remote employment; income ($1,500+/month); health insurance.','3-6 weeks','USD 100-300','digital_nomad','Proof of remote employment, income ($1,500+/month), health insurance.','3-6 weeks','1 year','https://www.migracion.gob.do','2025-01-01'),

-- ECUADOR missing goals
('any','ecuador','Study','Ecuador Student Visa','Study at Ecuadorian universities.','International students accepted to Ecuadorian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','USD 50-200','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.cancilleria.gob.ec','2025-01-01'),
('any','ecuador','Family','Ecuador Family Reunification Visa','Join a legally residing family member in Ecuador.','Spouses and children of Ecuadorian residents.','Valid passport; marriage/birth certificate; sponsor documents; financial proof.','4-8 weeks','USD 200-400','family','Marriage/birth certificate, sponsor documents, financial proof.','4-8 weeks','1 year, renewable','https://www.cancilleria.gob.ec','2025-01-01'),
('any','ecuador','Retirement','Ecuador Retirement Visa (Jubilado)','Retire in Ecuador, one of South America most popular retirement destinations.','Retirees with pension income of at least $800/month.','Valid passport; proof of pension ($800+/month); health insurance; clean criminal record; authenticated documents.','2-3 months','USD 200-500','retirement','Proof of pension ($800+/month), health insurance, clean criminal record, authenticated documents.','2-3 months','2 years, renewable toward permanent residency','https://www.cancilleria.gob.ec','2025-01-01'),
('any','ecuador','Work','Ecuador Work Visa','Work legally in Ecuador for an Ecuadorian employer or as self-employed.','Foreign workers with a job offer from an Ecuadorian company.','Valid passport; job contract; employer sponsorship; professional qualifications; clean criminal record.','4-8 weeks','USD 200-400','work','Job contract, employer sponsorship, professional qualifications, clean criminal record.','4-8 weeks','1 year, renewable','https://www.cancilleria.gob.ec','2025-01-01'),

-- ESTONIA missing goals
('any','estonia','Study','Estonia Student Visa (D)','Study at Estonian universities, especially Tartu or Tallinn University of Technology.','International students accepted to Estonian higher education.','Valid passport; university acceptance; proof of finances (EUR 266+/month); health insurance.','4-6 weeks','EUR 80-200','study','University acceptance, proof of finances (EUR 266+/month), health insurance, valid passport.','4-6 weeks','1 year, renewable','https://www.politsei.ee','2025-01-01'),
('any','estonia','Family','Estonia Family Reunification','Join a legally residing family member in Estonia.','Spouses and children of Estonian residents.','Valid passport; proof of family relationship; sponsor income documents; accommodation.','6-10 weeks','EUR 80-200','family','Proof of family relationship, sponsor income documents, accommodation.','6-10 weeks','1 year, renewable','https://www.politsei.ee','2025-01-01'),
('any','estonia','Retirement','Estonia Retirement Residence','Retire in Estonia with a long-stay residence permit.','Retirees with verified pension income.','Valid passport; proof of pension; health insurance; accommodation proof; clean criminal record.','6-10 weeks','EUR 80-200','retirement','Proof of pension, health insurance, accommodation proof, clean criminal record.','6-10 weeks','1 year, renewable','https://www.politsei.ee','2025-01-01'),
('any','estonia','Digital Nomad','Estonia Digital Nomad Visa','Work remotely from Estonia on the world-renowned Digital Nomad Visa.','Remote workers employed by companies outside Estonia or self-employed with foreign clients.','Valid passport; proof of employment or self-employment abroad; income EUR 3,504+/month; health insurance.','2-4 weeks','EUR 80-160','digital_nomad','Proof of employment or self-employment abroad, income EUR 3,504+/month, health insurance.','2-4 weeks','1 year','https://www.politsei.ee','2025-01-01'),
('any','estonia','Investor','Estonia Startup Visa / Investor Residence','Invest in Estonia or launch a startup with backing from a qualified committee.','Investors and entrepreneurs with qualifying business plans or investments.','Valid passport; business plan approved by Startup Estonia; proof of investment (EUR 65,000+); clean background.','4-8 weeks','EUR 80-200','investor','Business plan, proof of investment (EUR 65,000+), clean background.','4-8 weeks','1 year, renewable','https://investinestonia.com','2025-01-01'),

-- ETHIOPIA missing goals
('any','ethiopia','Study','Ethiopia Student Visa','Study at Ethiopian universities.','International students accepted to Ethiopian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','Low government fees','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.evisa.gov.et','2025-01-01'),
('any','ethiopia','Family','Ethiopia Family Visa','Join a legally residing family member in Ethiopia.','Spouses and children of Ethiopian residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','ETB 1,000-5,000 (~$20-90)','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.evisa.gov.et','2025-01-01'),
('any','ethiopia','Retirement','Ethiopia Retirement Residence','Retire in Ethiopia with a long-stay residence permit.','Retirees with sufficient pension income.','Valid passport; proof of pension income; health insurance; accommodation proof.','4-8 weeks','ETB 2,000-8,000 (~$36-145)','retirement','Proof of pension income, health insurance, accommodation proof.','4-8 weeks','1 year, renewable','https://www.evisa.gov.et','2025-01-01'),
('any','ethiopia','Digital Nomad','Ethiopia Digital Nomad Long Stay','Work remotely from Ethiopia on a long-stay visa.','Remote workers and freelancers with foreign income.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','ETB 2,000-5,000 (~$36-90)','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.evisa.gov.et','2025-01-01'),

-- GEORGIA missing goals
('any','georgia','Study','Georgia Student Residence Permit','Study at Georgian universities in affordable English-language programs.','International students accepted to Georgian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','2-4 weeks','GEL 50-200 (~$18-73)','study','University acceptance, proof of finances, health insurance, valid passport.','2-4 weeks','1 year, renewable','https://www.mia.gov.ge','2025-01-01'),
('any','georgia','Family','Georgia Family Reunification','Join a legally residing family member in Georgia.','Spouses and children of Georgian residents.','Valid passport; proof of family relationship; sponsor documents; financial support.','2-4 weeks','GEL 50-150 (~$18-55)','family','Proof of family relationship, sponsor documents, financial support.','2-4 weeks','1 year, renewable','https://www.mia.gov.ge','2025-01-01'),
('any','georgia','Retirement','Georgia Retirement Residence','Retire in Tbilisi, one of Europe most affordable retirement destinations.','Retirees with sufficient foreign pension income.','Valid passport; proof of pension income; health insurance; accommodation proof.','2-4 weeks','GEL 50-150 (~$18-55)','retirement','Proof of pension income, health insurance, accommodation proof.','2-4 weeks','1 year, renewable','https://www.mia.gov.ge','2025-01-01'),
('any','georgia','Work','Georgia Work Permit','Work legally in Georgia for a Georgian company.','Foreign workers with a job offer from a Georgian employer.','Valid passport; job contract; employer sponsorship; professional qualifications.','2-4 weeks','GEL 50-200 (~$18-73)','work','Job contract, employer sponsorship, professional qualifications.','2-4 weeks','1 year, renewable','https://www.mia.gov.ge','2025-01-01'),

-- GHANA missing goals
('any','ghana','Study','Ghana Student Visa','Study at Ghanaian universities.','International students accepted to Ghanaian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','4-8 weeks','GHS 200-600 (~$14-43)','study','University acceptance, proof of finances, health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.ghanaimmigration.org','2025-01-01'),
('any','ghana','Family','Ghana Family Visa','Join a legally residing family member in Ghana.','Spouses and children of Ghanaian residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','GHS 300-800 (~$21-57)','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.ghanaimmigration.org','2025-01-01'),
('any','ghana','Retirement','Ghana Retirement Visa','Retire in Ghana with a long-stay resident permit.','Retirees with sufficient foreign pension income.','Valid passport; proof of pension income; health insurance; accommodation proof.','4-8 weeks','USD 200-500','retirement','Proof of pension income, health insurance, accommodation proof.','4-8 weeks','1 year, renewable','https://www.ghanaimmigration.org','2025-01-01'),
('any','ghana','Digital Nomad','Ghana Digital Nomad Visa','Work remotely from Ghana, a growing tech hub in Africa.','Remote workers and freelancers with foreign income.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','USD 100-300','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.ghanaimmigration.org','2025-01-01'),

-- ICELAND missing goals
('any','iceland','Study','Iceland Student Residence Permit','Study at the University of Iceland or other Icelandic institutions.','International students accepted to Icelandic higher education.','Valid passport; university acceptance; proof of finances (ISK 150,000+/month); health insurance.','4-8 weeks','ISK 2,000-10,000 (~$14-73)','study','University acceptance, proof of finances (ISK 150,000+/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.utl.is','2025-01-01'),
('any','iceland','Family','Iceland Family Reunification','Join a legally residing family member in Iceland.','Spouses and children of Icelandic residents.','Valid passport; proof of family relationship; sponsor income; accommodation.','6-10 weeks','ISK 5,000-20,000 (~$36-145)','family','Proof of family relationship, sponsor income, accommodation.','6-10 weeks','1 year, renewable','https://www.utl.is','2025-01-01'),
('any','iceland','Retirement','Iceland Retirement Residence Permit','Retire in Iceland with a long-stay residence permit.','Retirees with proven pension income and health insurance.','Valid passport; proof of pension income; comprehensive health insurance; accommodation proof.','6-10 weeks','ISK 10,000-30,000 (~$73-218)','retirement','Proof of pension income, comprehensive health insurance, accommodation proof.','6-10 weeks','1 year, renewable','https://www.utl.is','2025-01-01'),
('any','iceland','Investor','Iceland Investor Residence','Invest in Iceland and obtain long-term residence.','Investors with qualifying business investments in Iceland.','Valid passport; business plan; proof of investment capital; clean criminal record.','6-12 weeks','ISK 20,000-50,000 (~$145-363)','investor','Business plan, proof of investment capital, clean criminal record.','6-12 weeks','1 year, renewable','https://www.utl.is','2025-01-01'),

-- JAMAICA missing goals
('any','jamaica','Study','Jamaica Student Permit','Study at Jamaican universities and colleges.','International students accepted to Jamaican educational institutions.','Valid passport; school acceptance letter; proof of finances; health insurance.','3-6 weeks','JMD 5,000-20,000 (~$32-130)','study','School acceptance letter, proof of finances, health insurance, valid passport.','3-6 weeks','Duration of study','https://www.mns.gov.jm','2025-01-01'),
('any','jamaica','Family','Jamaica Family Permit','Join a Jamaican resident or citizen as a dependent family member.','Spouses and children of Jamaican residents/citizens.','Valid passport; marriage/birth certificate; sponsor documents; financial support.','4-8 weeks','JMD 10,000-30,000 (~$65-195)','family','Marriage/birth certificate, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.mns.gov.jm','2025-01-01'),
('any','jamaica','Retirement','Jamaica Retirement Permit','Retire in Jamaica with a retirement residence permit.','Retirees with proven passive income.','Valid passport; proof of income ($2,000+/month); health insurance; clean criminal record.','4-8 weeks','USD 200-500','retirement','Proof of income ($2,000+/month), health insurance, clean criminal record.','4-8 weeks','5 years, renewable','https://www.mns.gov.jm','2025-01-01'),
('any','jamaica','Investor','Jamaica Investment Permit','Invest in Jamaica and obtain long-term residency.','Investors making qualifying investments in Jamaica.','Valid passport; business plan; proof of investment; legal registration.','6-12 weeks','USD 500-2,000','investor','Business plan, proof of investment, legal registration.','6-12 weeks','5 years, renewable','https://www.jampro.org','2025-01-01'),

-- JORDAN missing goals
('any','jordan','Study','Jordan Student Residence Permit','Study at Jordanian universities.','International students accepted to Jordanian higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','JOD 50-150 (~$70-210)','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.moi.gov.jo','2025-01-01'),
('any','jordan','Family','Jordan Family Reunification','Join a legally residing family member in Jordan.','Spouses and children of Jordanian residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','JOD 50-200 (~$70-280)','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.moi.gov.jo','2025-01-01'),
('any','jordan','Retirement','Jordan Retirement Residence','Retire in Jordan, a culturally rich destination with a moderate cost of living.','Retirees with sufficient pension income.','Valid passport; proof of pension; health insurance; accommodation proof.','4-8 weeks','JOD 100-300 (~$140-420)','retirement','Proof of pension, health insurance, accommodation proof.','4-8 weeks','1 year, renewable','https://www.moi.gov.jo','2025-01-01'),
('any','jordan','Digital Nomad','Jordan Digital Nomad Visa','Work remotely from Jordan.','Remote workers and freelancers with foreign income.','Valid passport; proof of remote employment; income documentation; health insurance.','3-6 weeks','JOD 50-150 (~$70-210)','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-6 weeks','1 year','https://www.moi.gov.jo','2025-01-01'),

-- KAZAKHSTAN missing goals
('any','kazakhstan','Study','Kazakhstan Student Visa','Study at Kazakh universities such as Nazarbayev University.','International students accepted to Kazakhstani higher education.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','KZT 5,000-20,000 (~$10-43)','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://www.gov.kz','2025-01-01'),
('any','kazakhstan','Family','Kazakhstan Family Reunification','Join a legally residing family member in Kazakhstan.','Spouses and children of Kazakhstani residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','KZT 10,000-30,000 (~$22-65)','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://www.gov.kz','2025-01-01'),
('any','kazakhstan','Retirement','Kazakhstan Retirement Residence','Retire in Kazakhstan, a growing Central Asian destination.','Retirees with sufficient pension income.','Valid passport; proof of pension; health insurance; accommodation proof; clean criminal record.','4-8 weeks','KZT 10,000-30,000 (~$22-65)','retirement','Proof of pension, health insurance, accommodation proof, clean criminal record.','4-8 weeks','1 year, renewable','https://www.gov.kz','2025-01-01'),
('any','kazakhstan','Digital Nomad','Kazakhstan Digital Nomad Visa','Work remotely from Kazakhstan.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','KZT 10,000-20,000 (~$22-43)','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://www.gov.kz','2025-01-01'),

-- KENYA missing goals
('any','kenya','Study','Kenya Student Pass','Study at Kenyan universities and colleges.','International students accepted to Kenyan educational institutions.','Valid passport; university acceptance; proof of finances; health insurance.','3-6 weeks','KES 5,000-20,000 (~$39-155)','study','University acceptance, proof of finances, health insurance, valid passport.','3-6 weeks','1 year, renewable','https://immigration.ecitizen.go.ke','2025-01-01'),
('any','kenya','Family','Kenya Family Dependent Pass','Join a legally residing family member in Kenya.','Spouses and children of Kenyan residents.','Valid passport; family relationship proof; sponsor documents; financial support.','4-8 weeks','KES 10,000-30,000 (~$78-233)','family','Family relationship proof, sponsor documents, financial support.','4-8 weeks','1 year, renewable','https://immigration.ecitizen.go.ke','2025-01-01'),
('any','kenya','Retirement','Kenya Special Pass for Retirees','Retire in Kenya, known for its wildlife and growing expat community.','Retirees with sufficient passive income.','Valid passport; proof of income; health insurance; accommodation proof; clean criminal record.','4-8 weeks','KES 20,000-50,000 (~$155-388)','retirement','Proof of income, health insurance, accommodation proof, clean criminal record.','4-8 weeks','1 year, renewable','https://immigration.ecitizen.go.ke','2025-01-01'),
('any','kenya','Digital Nomad','Kenya Digital Nomad Visa','Work remotely from Kenya, a tech hub in East Africa.','Remote workers and freelancers with foreign income.','Valid passport; proof of remote employment; income documentation; health insurance.','3-5 weeks','KES 10,000-25,000 (~$78-194)','digital_nomad','Proof of remote employment, income documentation, health insurance.','3-5 weeks','1 year','https://immigration.ecitizen.go.ke','2025-01-01'),

-- KUWAIT missing goals
('any','kuwait','Study','Kuwait Student Visa','Study at Kuwaiti universities.','International students accepted to Kuwaiti higher education.','Valid passport; university acceptance; financial support; health insurance.','3-5 weeks','KWD 50-200 (~$162-650)','study','University acceptance, financial support, health insurance, valid passport.','3-5 weeks','1 year, renewable','https://www.moi.gov.kw','2025-01-01'),
('any','kuwait','Family','Kuwait Family Residence Visa','Sponsor family members to reside in Kuwait.','Kuwaiti residents/citizens sponsoring spouse and children.','Valid passport; proof of relationship; sponsor salary; accommodation; medical checks.','3-6 weeks','KWD 50-300 (~$162-975)','family','Proof of relationship, sponsor salary, accommodation, medical checks.','3-6 weeks','2 years, renewable','https://www.moi.gov.kw','2025-01-01'),
('any','kuwait','Retirement','Kuwait Retirement Residence','Retire in Kuwait on a long-stay residence visa.','Retirees with sufficient income (usually requires property or sponsorship).','Valid passport; proof of income; health insurance; accommodation proof.','4-8 weeks','KWD 100-300 (~$325-975)','retirement','Proof of income, health insurance, accommodation proof.','4-8 weeks','1 year, renewable','https://www.moi.gov.kw','2025-01-01'),
('any','kuwait','Digital Nomad','Kuwait Remote Work Visa','Work remotely from Kuwait.','Remote workers employed by foreign companies.','Valid passport; employment contract; proof of income; health insurance.','3-6 weeks','KWD 100-300 (~$325-975)','digital_nomad','Employment contract, proof of income, health insurance.','3-6 weeks','1 year','https://www.moi.gov.kw','2025-01-01'),

-- LAOS missing goals
('any','laos','Study','Laos Student Visa','Study at Lao universities.','International students accepted to Lao higher education.','Valid passport; university acceptance; proof of finances; health insurance.','2-4 weeks','USD 30-100','study','University acceptance, proof of finances, health insurance, valid passport.','2-4 weeks','1 year, renewable','https://www.laoevisa.gov.la','2025-01-01'),
('any','laos','Family','Laos Family Visa','Join a legally residing family member in Laos.','Spouses and children of Lao residents.','Valid passport; family relationship proof; sponsor documents; financial support.','2-4 weeks','USD 30-100','family','Family relationship proof, sponsor documents, financial support.','2-4 weeks','1 year, renewable','https://www.laoevisa.gov.la','2025-01-01'),
('any','laos','Retirement','Laos Retirement Visa','Retire in Laos on a business/retirement visa extension.','Retirees with sufficient pension income.','Valid passport; proof of pension; health insurance; accommodation proof.','2-4 weeks','USD 50-200','retirement','Proof of pension, health insurance, accommodation proof.','2-4 weeks','1 year, renewable','https://www.laoevisa.gov.la','2025-01-01'),
('any','laos','Digital Nomad','Laos Digital Nomad Long Stay','Work remotely from Laos on a long-stay visa.','Remote workers and freelancers.','Valid passport; proof of remote employment; income documentation; health insurance.','2-3 weeks','USD 50-150','digital_nomad','Proof of remote employment, income documentation, health insurance.','2-3 weeks','1 year','https://www.laoevisa.gov.la','2025-01-01'),

-- LATVIA missing goals
('any','latvia','Study','Latvia Student Residence Permit','Study at Latvian universities, popular with international students.','Students accepted to Latvian higher education.','Valid passport; university acceptance; proof of finances (EUR 230+/month); health insurance.','4-8 weeks','EUR 50-200','study','University acceptance, proof of finances (EUR 230+/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.pmlp.gov.lv','2025-01-01'),
('any','latvia','Family','Latvia Family Reunification','Join a legally residing family member in Latvia.','Spouses and children of Latvian residents.','Valid passport; proof of family relationship; sponsor income; accommodation.','6-10 weeks','EUR 50-200','family','Proof of family relationship, sponsor income, accommodation.','6-10 weeks','1 year, renewable','https://www.pmlp.gov.lv','2025-01-01'),
('any','latvia','Retirement','Latvia Retirement Residence Permit','Retire in Latvia on a long-term residence permit.','Retirees with proven pension income.','Valid passport; proof of pension (EUR 300+/month); health insurance; accommodation proof; clean criminal record.','6-10 weeks','EUR 50-200','retirement','Proof of pension (EUR 300+/month), health insurance, accommodation proof, clean criminal record.','6-10 weeks','1 year, renewable','https://www.pmlp.gov.lv','2025-01-01'),
('any','latvia','Digital Nomad','Latvia Digital Nomad Visa','Work remotely from Latvia in the EU.','Remote workers employed by non-Latvian companies.','Valid passport; proof of employment abroad; income EUR 2,185+/month; health insurance.','4-8 weeks','EUR 50-150','digital_nomad','Proof of employment abroad, income EUR 2,185+/month, health insurance.','4-8 weeks','1 year','https://www.pmlp.gov.lv','2025-01-01'),

-- LITHUANIA missing goals
('any','lithuania','Study','Lithuania Student Residence Permit','Study at Lithuanian universities such as Vilnius University.','Students accepted to Lithuanian higher education.','Valid passport; university acceptance; proof of finances (EUR 400+/month); health insurance.','4-8 weeks','EUR 40-200','study','University acceptance, proof of finances (EUR 400+/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.migracija.lt','2025-01-01'),
('any','lithuania','Family','Lithuania Family Reunification','Join a legally residing family member in Lithuania.','Spouses and children of Lithuanian residents.','Valid passport; proof of family relationship; sponsor income; accommodation.','6-10 weeks','EUR 40-200','family','Proof of family relationship, sponsor income, accommodation.','6-10 weeks','1 year, renewable','https://www.migracija.lt','2025-01-01'),
('any','lithuania','Retirement','Lithuania Retirement Residence Permit','Retire in Lithuania, an affordable EU destination.','Retirees with proven pension income.','Valid passport; proof of pension; health insurance; accommodation proof; clean criminal record.','6-10 weeks','EUR 40-200','retirement','Proof of pension, health insurance, accommodation proof, clean criminal record.','6-10 weeks','1 year, renewable','https://www.migracija.lt','2025-01-01'),
('any','lithuania','Digital Nomad','Lithuania Digital Nomad Visa','Work remotely from Lithuania in the EU.','Remote workers and freelancers employed by non-Lithuanian companies.','Valid passport; proof of employment abroad; income EUR 2,000+/month; health insurance.','4-8 weeks','EUR 40-150','digital_nomad','Proof of employment abroad, income EUR 2,000+/month, health insurance.','4-8 weeks','1 year','https://www.migracija.lt','2025-01-01'),

-- LUXEMBOURG missing goals
('any','luxembourg','Study','Luxembourg Student Visa (D)','Study at the University of Luxembourg.','Students accepted to Luxembourg higher education.','Valid passport; university acceptance; proof of finances (EUR 1,000+/month); health insurance.','4-8 weeks','EUR 50-200','study','University acceptance, proof of finances (EUR 1,000+/month), health insurance, valid passport.','4-8 weeks','1 year, renewable','https://www.guichet.lu','2025-01-01'),
('any','luxembourg','Family','Luxembourg Family Reunification','Join a legally residing family member in Luxembourg.','Spouses and children of Luxembourg residents.','Valid passport; proof of family relationship; sponsor income (EUR 1,800+/month); accommodation; health insurance.','2-3 months','EUR 50-200','family','Proof of family relationship, sponsor income (EUR 1,800+/month), accommodation, health insurance.','2-3 months','1 year, renewable','https://www.guichet.lu','2025-01-01'),
('any','luxembourg','Retirement','Luxembourg Retirement Residence Permit','Retire in Luxembourg on a long-stay residence permit.','Retirees with substantial income (Luxembourg is high cost of living).','Valid passport; proof of pension (EUR 2,500+/month); health insurance; accommodation proof; clean criminal record.','2-3 months','EUR 50-200','retirement','Proof of pension (EUR 2,500+/month), health insurance, accommodation proof, clean criminal record.','2-3 months','1 year, renewable','https://www.guichet.lu','2025-01-01'),
('any','luxembourg','Digital Nomad','Luxembourg Remote Work Residence Permit','Work remotely from one of Europe wealthiest countries.','Remote workers employed abroad with high income.','Valid passport; proof of employment abroad; income EUR 4,000+/month; health insurance; accommodation.','4-8 weeks','EUR 50-200','digital_nomad','Proof of employment abroad, income EUR 4,000+/month, health insurance, accommodation.','4-8 weeks','1 year','https://www.guichet.lu','2025-01-01')

ON CONFLICT DO NOTHING;
