/*
  # Add Extensive Work Visa Pathways

  ## Overview
  Comprehensive work visa coverage for all major country combinations including:
  - More US work visas (H-1B, L-1, O-1, E-2, TN)
  - UK work visas for all major passports
  - Canada Express Entry and work permits
  - Australia skilled migration
  - European work permits
  - Asia-Pacific work visas

  ## Countries Covered
  All combinations between: US, UK, CA, AU, NZ, DE, FR, ES, PT, SG, AE, MX, CR, JP, IN, BR
*/

INSERT INTO immigration_pathways (
  passport_slug, destination_slug, goal, pathway_type, pathway_name,
  summary, eligibility, key_requirements, requirements, typical_timeline,
  processing_time, estimated_fees, validity_period, official_url
) VALUES

-- More US Work Visas
('in', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Work visa for specialized professionals with bachelor degree or higher.',
 'Bachelor degree in specialty occupation, US employer sponsorship.',
 'Job offer, employer petition, degree, lottery selection.',
 'US employer petition, bachelor degree or equivalent, specialty occupation, lottery win.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('in', 'us', 'Work', 'Work', 'L-1 Intracompany Transfer',
 'Transfer within company to US office.',
 'Worked for company abroad 1+ year, transferring to US branch.',
 'Employment 1+ year, managerial/specialized role, employer petition.',
 '1+ year with employer abroad, specialized knowledge or managerial position, L petition.',
 '2-4 months', '2-4 months', 'USD 460-805',
 '1-7 years',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/l-1a-intracompany-transferee-executive-or-manager'),

('jp', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Professional work visa.',
 'Bachelor degree, US employer sponsorship.',
 'Job offer, employer petition, degree, lottery.',
 'Employer petition, bachelor degree, specialty occupation, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('de', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Specialty occupation work visa.',
 'Bachelor degree, employer sponsorship.',
 'Job offer, degree, employer petition.',
 'US employer petition, bachelor degree, specialty occupation, lottery win.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('au', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Professional work visa.',
 'Bachelor degree, US job offer.',
 'Employer petition, degree, lottery.',
 'US employer petition, bachelor degree, specialty occupation, lottery selection.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

('br', 'us', 'Work', 'Work', 'L-1 Intracompany Transfer',
 'Transfer within multinational company.',
 'Worked for company in Brazil 1+ year.',
 'Employment 1+ year, managerial/specialized role.',
 '1+ year with employer, specialized knowledge or manager, L petition.',
 '2-4 months', '2-4 months', 'USD 460-805',
 '1-7 years',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/l-1a-intracompany-transferee-executive-or-manager'),

('mx', 'us', 'Work', 'Work', 'H-1B Specialty Occupation Visa',
 'Specialty occupation visa.',
 'Bachelor degree, employer sponsorship.',
 'Job offer, degree, petition.',
 'Employer petition, bachelor degree, specialty occupation, lottery.',
 '3-6 months', '3-6 months', 'USD 460-780',
 '3 years renewable',
 'https://www.uscis.gov/working-in-the-united-states/temporary-workers/h-1b-specialty-occupations'),

-- More UK Work Visas
('us', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK licensed sponsor, salary £25,600+.',
 'Certificate of Sponsorship, English proficiency, maintenance funds.',
 'CoS from licensed sponsor, English test, £1,270 funds, relevant qualifications.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('in', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work visa.',
 'Job offer from UK sponsor, salary threshold.',
 'Certificate of Sponsorship, English test, funds.',
 'CoS, English language test, £1,270 maintenance funds, qualifications.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('au', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Work visa with employer sponsorship.',
 'Job offer from licensed UK sponsor.',
 'Certificate of Sponsorship, English test.',
 'CoS from sponsor, English proficiency, maintenance funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('br', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Employer-sponsored work.',
 'UK job offer, salary £25,600+.',
 'Certificate of Sponsorship, English test.',
 'CoS, English language test, £1,270 funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

('mx', 'gb', 'Work', 'Work', 'Skilled Worker Visa',
 'Work visa with sponsorship.',
 'Job offer from UK employer.',
 'Certificate of Sponsorship, English proficiency.',
 'CoS from licensed sponsor, English test, maintenance funds.',
 '3-8 weeks', '3-8 weeks', 'GBP 625-1,423',
 '5 years',
 'https://www.gov.uk/skilled-worker-visa'),

-- More Canada Work Visas
('us', 'ca', 'Work', 'Work', 'Intra-Company Transfer',
 'Transfer within company to Canadian branch.',
 'Work for company 1+ year, transferring to Canada.',
 'Employment 1+ year, specialized knowledge or management.',
 '1+ year with employer, specialized role or manager, job offer.',
 '2-3 months', '2-3 months', 'CAD 155-230',
 '1-3 years',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/work-canada/permit/temporary/intra-company-transfers.html'),

('in', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence for skilled workers.',
 'Skilled work experience, language proficiency.',
 'Language test, ECA, 67+ points.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('au', 'ca', 'Work', 'Work', 'Federal Skilled Worker Program',
 'Permanent residence through Express Entry.',
 'Skilled experience, language ability.',
 'Language test, ECA, points.',
 'IELTS/CELPIP CLB 7+, Educational Credential Assessment, 67+ points, funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('de', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Skilled worker permanent residence.',
 'Work experience, language proficiency.',
 'Language test, ECA, points test.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('br', 'ca', 'Work', 'Work', 'Express Entry - Federal Skilled Worker',
 'Permanent residence pathway.',
 'Skilled experience, language ability.',
 'Language test, ECA, points.',
 'IELTS/CELPIP CLB 7+, Educational assessment, 67+ points, funds proof.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

('mx', 'ca', 'Work', 'Work', 'Federal Skilled Worker Program',
 'Permanent residence through Express Entry.',
 'Skilled work experience.',
 'Language test, ECA, points test.',
 'IELTS/CELPIP CLB 7+, ECA, 67+ points, CAD 13,000+ funds.',
 '6-12 months', '6-12 months', 'CAD 1,365',
 'Permanent',
 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html'),

-- More Australia Work Visas
('gb', 'au', 'Work', 'Work', 'Skilled Independent Visa (Subclass 189)',
 'Points-based permanent skilled migration.',
 'Skilled occupation, under 45, 65+ points.',
 'Skills assessment, English proficiency, points test.',
 'Skills assessment, IELTS 6.0+, 65+ points, health and character checks.',
 '6-9 months', '6-9 months', 'AUD 4,115',
 'Permanent',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189'),

('gb', 'au', 'Work', 'Work', 'Temporary Skill Shortage Visa (Subclass 482)',
 'Employer-sponsored work visa.',
 'Job offer from Australian employer.',
 'Employer sponsorship, skills, English proficiency.',
 'Employer sponsorship, skills assessment, English test, 2+ years experience.',
 '2-4 months', '2-4 months', 'AUD 1,290-2,690',
 '2-4 years',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482'),

('ca', 'au', 'Work', 'Work', 'Skilled Independent Visa (Subclass 189)',
 'Points-based skilled migration.',
 'Skilled occupation, under 45.',
 'Skills assessment, English proficiency, 65+ points.',
 'Skills assessment, IELTS 6.0+, 65+ points, health checks.',
 '6-9 months', '6-9 months', 'AUD 4,115',
 'Permanent',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189'),

('fr', 'au', 'Work', 'Work', 'Temporary Skill Shortage Visa (Subclass 482)',
 'Employer-sponsored temporary work.',
 'Job offer from Australian employer.',
 'Employer sponsorship, skills assessment.',
 'Employer sponsorship, relevant skills assessment, English test, experience.',
 '2-4 months', '2-4 months', 'AUD 1,290-2,690',
 '2-4 years',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482'),

('br', 'au', 'Work', 'Work', 'Skilled Nominated Visa (Subclass 190)',
 'State-nominated skilled migration.',
 'State nomination, skilled occupation.',
 'State nomination, skills assessment, 65+ points.',
 'State/territory nomination, skills assessment, 65+ points, English test.',
 '6-12 months', '6-12 months', 'AUD 4,115',
 'Permanent',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190'),

('mx', 'au', 'Work', 'Work', 'Temporary Skill Shortage Visa (Subclass 482)',
 'Employer-sponsored work visa.',
 'Job offer from Australian employer.',
 'Employer sponsorship, skills, English.',
 'Employer sponsorship, skills assessment, English proficiency, 2+ years experience.',
 '2-4 months', '2-4 months', 'AUD 1,290-2,690',
 '2-4 years',
 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/temporary-skill-shortage-482'),

-- Germany Work Visas
('us', 'de', 'Work', 'Work', 'EU Blue Card',
 'Work and residence permit for highly qualified workers.',
 'University degree, job offer with €45,300+ salary (€41,041.80+ for shortage occupations).',
 'University degree, employment contract, salary threshold.',
 'Degree certificate, employment contract €45,300+ salary, health insurance, accommodation.',
 '1-3 months', '1-3 months', 'EUR 100',
 '4 years',
 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card'),

('gb', 'de', 'Work', 'Work', 'EU Blue Card',
 'Work permit for highly qualified professionals.',
 'University degree, job offer €45,300+ salary.',
 'Degree, employment contract, salary threshold.',
 'University degree, employment contract, €45,300+ salary, health insurance.',
 '1-3 months', '1-3 months', 'EUR 100',
 '4 years',
 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card'),

('in', 'de', 'Work', 'Work', 'EU Blue Card',
 'Skilled worker residence permit.',
 'Degree, job offer with salary threshold.',
 'University degree, employment contract.',
 'Degree certificate, employment contract €45,300+, health insurance, accommodation.',
 '1-3 months', '1-3 months', 'EUR 100',
 '4 years',
 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card'),

('ca', 'de', 'Work', 'Work', 'EU Blue Card',
 'Work permit for qualified workers.',
 'University degree, job offer.',
 'Degree, employment contract, salary threshold.',
 'University degree, employment contract €45,300+, health insurance.',
 '1-3 months', '1-3 months', 'EUR 100',
 '4 years',
 'https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card'),

-- France Work Visas
('us', 'fr', 'Work', 'Work', 'Passeport Talent - Skilled Worker',
 'Residence permit for skilled workers.',
 'Job offer, degree, €53,836.50+ salary.',
 'Employment contract, degree, salary threshold.',
 'Employment contract, degree certificate, €53,836.50+ annual salary.',
 '2-3 months', '2-3 months', 'EUR 225',
 '4 years renewable',
 'https://www.campusfrance.org/en/talent-passport-for-employees'),

('gb', 'fr', 'Work', 'Work', 'Passeport Talent - Skilled Worker',
 'Skilled worker residence permit.',
 'Job offer, degree, salary €53,836.50+.',
 'Employment contract, qualifications.',
 'Employment contract, degree, €53,836.50+ salary.',
 '2-3 months', '2-3 months', 'EUR 225',
 '4 years renewable',
 'https://www.campusfrance.org/en/talent-passport-for-employees'),

('in', 'fr', 'Work', 'Work', 'Passeport Talent - Skilled Worker',
 'Work residence permit.',
 'Job offer, degree, salary threshold.',
 'Employment contract, qualifications, salary.',
 'Employment contract, degree certificate, €53,836.50+ annual salary.',
 '2-3 months', '2-3 months', 'EUR 225',
 '4 years renewable',
 'https://www.campusfrance.org/en/talent-passport-for-employees')

ON CONFLICT (id) DO NOTHING;