/*
  # Batch 1 Group 6: Turkey, Russia, Ukraine, Qatar, Saudi Arabia, Israel, Morocco
  
  Adds all 6 goal pathways for these destinations.
*/

INSERT INTO immigration_pathways (passport_slug, destination_slug, goal, pathway_name, summary, eligibility, key_requirements, typical_timeline, estimated_fees, pathway_type, processing_time, validity_period, last_updated)
VALUES

-- TURKEY
('any', 'turkey', 'Work', 'Work Permit (Çalışma İzni)',
 'Foreign nationals working in Turkey require a work permit from the Ministry of Family and Social Services. Turkey has a favorable geographic location at the crossroads of Europe and Asia, with a growing economy. Employer-sponsored work permits are the main pathway.',
 'Must have a job offer from a Turkish employer. The company must employ at least 5 Turkish nationals per 1 foreign worker. The foreign worker''s salary must be at least minimum wage (higher for specific roles). Permit is employer-tied.',
 'Employment contract, valid passport, employer''s company registration (ticaret sicil), educational qualifications, criminal background check, health insurance.',
 'Typically 4–8 weeks', 'USD 200–500 (varies by permit duration)',
 'work', '4–8 weeks', '1–3 years, renewable', CURRENT_DATE),

('any', 'turkey', 'Study', 'Student Residence Permit (Öğrenci İkamet İzni)',
 'International students studying at Turkish universities or educational institutions for 3+ months must obtain a student residence permit from the Directorate General of Migration Management (DGMM). Turkey has world-class universities and relatively low tuition fees.',
 'Must be enrolled at a recognized Turkish educational institution (accredited by YÖK — Council of Higher Education). Must have proof of financial means (approximately TRY 2,000–3,000/month). Must have health insurance.',
 'Enrollment certificate from Turkish institution, financial proof, health insurance, valid passport, biometric photos, rental contract or accommodation proof.',
 'Typically 2–4 weeks (DGMM application)', 'TRY 2,000–3,000',
 'study', '2–4 weeks', '1 year, renewable per academic year', CURRENT_DATE),

('any', 'turkey', 'Digital Nomad', 'Short-Term Residence Permit (Kısa Dönem)',
 'Turkey doesn''t have a dedicated digital nomad visa, but a Short-Term Residence Permit (valid 2 years renewable) is available for remote workers who can prove financial self-sufficiency. Turkey (especially Istanbul) is a growing digital nomad hub due to low costs and great infrastructure.',
 'Must have sufficient financial means to support yourself in Turkey without working for Turkish companies. Work for foreign companies in a remote capacity is in a legal grey area. Must have health insurance covering Turkey.',
 'Proof of financial means (bank statements showing USD 500+ per month), health insurance, valid passport, rental contract, clean criminal record, biometric photos.',
 'Typically 2–4 weeks (DGMM application after entering on a tourist or e-visa)', 'TRY 2,000–3,000',
 'digital_nomad', '2–4 weeks', '2 years, renewable', CURRENT_DATE),

('any', 'turkey', 'Retirement', 'Short-Term Residence Permit (Financially Independent)',
 'Retirees can obtain a Short-Term Residence Permit as financially independent persons. Turkey''s low cost of living, Mediterranean and Aegean coasts, and quality healthcare make it attractive. Property purchase also enables a residence permit.',
 'Must demonstrate sufficient passive income (pension, savings) for living costs in Turkey. Alternatively, purchasing property worth at least USD 200,000 qualifies for a real estate residence permit (and potentially Turkish citizenship via investment).',
 'Proof of income or savings, health insurance, valid passport, rental contract or property title deed, biometric photos.',
 'Typically 2–4 weeks', 'TRY 2,000–3,000 (property: additional costs apply)',
 'retirement', '2–4 weeks', '2 years, renewable', CURRENT_DATE),

('any', 'turkey', 'Investor', 'Turkish Citizenship by Investment (Turquoise Card)',
 'Turkey offers citizenship to investors who meet specific investment thresholds. The fastest route is a USD 400,000 real estate purchase or USD 500,000 in fixed capital investment. Turkey also has a Turquoise Card (similar to a green card) for highly skilled professionals and investors.',
 'Citizenship routes: USD 400,000 real estate (3-year hold); USD 500,000 in fixed capital investment or bank deposit; creating 50+ jobs for Turkish citizens; or USD 500,000 government bonds. Real estate is the most popular route.',
 'Investment documentation (property deed/share certificates), proof of funds and legitimate source, valid passport, criminal background check, health insurance, biometric photos.',
 'Typically 3–6 months (citizenship); 4–8 weeks (residence permit)', 'USD 500–1,500 (administrative fees)',
 'investor', '3–6 months', 'Turkish citizenship: lifetime', CURRENT_DATE),

('any', 'turkey', 'Family', 'Family Residence Permit (Aile İkamet İzni)',
 'Spouses and minor children of Turkish citizens or foreigners with valid Turkish residence permits can obtain a Family Residence Permit. Valid for the sponsor''s permit duration (up to 3 years renewable).',
 'Must be the spouse or unmarried child under 18 of: a Turkish citizen, OR a foreigner with a valid Turkish residence permit. Sponsor must have sufficient income and accommodation.',
 'Marriage certificate or birth certificate (apostilled and notarized Turkish translation), sponsor''s valid ID or residence permit, proof of income (minimum Turkish minimum wage × family members), accommodation proof, health insurance.',
 'Typically 2–4 weeks', 'TRY 2,000–3,000',
 'family', '2–4 weeks', 'Up to 3 years (matches sponsor''s permit duration)', CURRENT_DATE),

-- RUSSIA
('any', 'russia', 'Work', 'Work Visa + Temporary Residence Permit (RVP)',
 '⚠️ Due to the ongoing conflict in Ukraine and international sanctions, many countries'' nationals face restrictions on travelling to Russia, and banking/financial services access is extremely limited. This information is provided for general reference only. Verify current visa issuing status with the Russian embassy in your country.',
 'Must have a work invitation from a Russian employer who has obtained a "quota" from Russian regional authorities. Highly Qualified Specialists (HQS) can bypass the quota system with salaries above RUB 167,000/month (approximately USD 1,800).',
 'Work invitation from Russian employer, valid passport, criminal background check, medical tests (HIV, drug abuse), health insurance, migration card on entry, biometric photos.',
 'Typically 2–4 months (quota + visa + RVP)', 'USD 100–300',
 'work', '2–4 months', '1 year (work visa), then TRP/TP applications possible', CURRENT_DATE),

('any', 'russia', 'Study', 'Student Visa',
 '⚠️ Due to sanctions and the ongoing geopolitical situation, studying in Russia has become significantly more challenging for students from Western countries. This information is provided for reference. Russian universities offer scholarships through the Russian Government Scholarship program.',
 'Must be admitted to a Russian university or educational institution. Russian Government scholarships available for students from developing countries and CIS nations. Must have acceptable entry qualifications.',
 'Invitation letter from Russian university, valid passport, criminal background check, health insurance, biometric photos, HIV-negative certificate.',
 'Typically 4–8 weeks', 'RUB 1,600–3,500 (visa fee varies by nationality)',
 'study', '4–8 weeks', '1 year, renewable per academic year', CURRENT_DATE),

('any', 'russia', 'Digital Nomad', 'E-Visa / Tourist Visa',
 '⚠️ Russia''s e-visa program (previously covering select regions) has been significantly impacted by sanctions. Many Western country nationals have their Russian e-visa/visa programs suspended or severely restricted. Travelers should exercise extreme caution and check current advisories.',
 'Subject to current geopolitical restrictions. Previously, e-visas were available for 113 countries for up to 16-day single-entry stays. Most Western countries currently have limited or no regular visa service with Russia.',
 'Valid passport, invitation letter, return ticket, health insurance, sufficient funds.',
 'Varies significantly by nationality and current political situation', 'USD 50–300',
 'digital_nomad', 'Varies', 'Varies by visa type (generally 30–90 days tourist; multiple-entry up to 1 year)', CURRENT_DATE),

('any', 'russia', 'Retirement', 'Temporary Residence Permit (RVP) – Retiree',
 '⚠️ Geopolitical restrictions apply. For those who do qualify and wish to retire in Russia — typically CIS country nationals and specific bilateral agreement countries — a TRP (Temporary Residence Permit) can be obtained as a first step toward long-term residence.',
 'CIS country nationals and those with Russian-citizen spouses, parents, or children have priority pathways. Must have sufficient income for self-support. Western country nationals face significant barriers.',
 'Proof of income, health insurance, valid passport, documents establishing eligibility category.',
 'Typically 4–8 months', 'RUB 1,000–3,500',
 'retirement', '4–8 months', 'TRP: 3 years (then Permanent Residence possible after 1 year)', CURRENT_DATE),

('any', 'russia', 'Investor', 'Business Visa / Investor Permit',
 '⚠️ Significant sanctions and financial restrictions make business investment in Russia extremely difficult for Western nationals. Banking restrictions, SWIFT disconnections, and legal risks are severe. This is provided for informational reference only.',
 'Foreign business investors in Russia can apply for multi-entry business visas. Setting up a Russian company (ООО — LLC) allows for work authorization. Sanctions-affected nationals face near-complete barriers.',
 'Business invitation from Russian organization, company registration documents (if establishing a business), valid passport.',
 'Varies significantly', 'USD 100–500',
 'investor', 'Varies', 'Business visa: up to 1 year, multi-entry; TRP after establishing business', CURRENT_DATE),

('any', 'russia', 'Family', 'Family-Based Residence (RVP/RP)',
 'Foreign nationals with Russian citizen spouses, parents, or children can apply for a Temporary Residence Permit (RVP) outside the annual quota, and subsequently for Permanent Residence (RP).',
 'Must be legally married to a Russian citizen, OR have a Russian citizen parent or child. Marriage must be registered in Russia or recognized under Russian law.',
 'Marriage certificate or birth certificate (notarized Russian translation), Russian citizen''s passport, valid foreign passport, health certificates.',
 'Typically 4–6 months', 'RUB 1,000–3,500',
 'family', '4–6 months', 'TRP: 3 years; RP: 5 years (renewable)', CURRENT_DATE),

-- UKRAINE
('any', 'ukraine', 'Work', 'Temporary Residence Permit (Work)',
 '⚠️ Due to the ongoing war (Russian invasion, February 2022 onwards), most Ukrainian territory carries extreme security risks. Travel is not recommended by most foreign governments. This information is provided for reference — applicability depends entirely on future peace and security developments.',
 'In pre-war conditions: Must have employment with a Ukrainian company. Work permit required from the State Employment Service of Ukraine. Labor market test applies.',
 'Employment contract, valid passport, criminal background check, health insurance, accommodation proof.',
 'Typically 1–3 months (pre-war conditions)', 'UAH 300–500',
 'work', '1–3 months', '1–3 years, renewable', CURRENT_DATE),

('any', 'ukraine', 'Study', 'Student Visa / Temporary Residence Permit',
 '⚠️ Ukraine''s universities have been severely impacted by the ongoing war. Many universities have relocated students and operations. Check current situation before applying. Ukraine historically had many international students, especially in medicine.',
 'Must be enrolled at a Ukrainian Ministry of Education-accredited institution. Must demonstrate financial means. Security situation must be assessed.',
 'Enrollment letter from Ukrainian institution, financial proof, valid passport, health insurance, criminal background check.',
 'Varies (check current operational status)', 'UAH 300–500',
 'study', 'Varies', '1 year, renewable per academic year', CURRENT_DATE),

('any', 'ukraine', 'Digital Nomad', 'Temporary Residence Permit (Self-Employment/Freelancer)',
 '⚠️ Due to the ongoing conflict, Ukraine is not a viable digital nomad destination. Under pre-war conditions, Ukraine was becoming popular among digital nomads (Kyiv, Lviv, Odessa) due to very low costs and fast internet. This is historical information — assess carefully when peace conditions return.',
 'Pre-war: Must be self-employed or work remotely for non-Ukrainian companies. Financial self-sufficiency required. Must register with local migration services.',
 'Proof of freelance income or remote employment, financial means, valid passport, accommodation proof.',
 'Varies', 'UAH 300–500',
 'digital_nomad', 'Varies', '1 year, renewable', CURRENT_DATE),

('any', 'ukraine', 'Retirement', 'Temporary Residence Permit (Financially Independent)',
 '⚠️ Travel to Ukraine is strongly discouraged due to the active armed conflict. Under pre-war conditions, Ukraine was an affordable retirement option. This information is provided for future reference when peace conditions are restored.',
 'Must demonstrate financial self-sufficiency without Ukrainian employment. Proof of passive income required.',
 'Proof of pension or passive income, health insurance, valid passport, accommodation proof.',
 'Varies', 'UAH 300–500',
 'retirement', 'Varies', '1 year, renewable', CURRENT_DATE),

('any', 'ukraine', 'Investor', 'Temporary Residence Permit (Investor)',
 '⚠️ Investment in Ukraine carries extreme risk due to the ongoing conflict. Post-war reconstruction may create significant investment opportunities. Ukraine''s government has indicated plans for post-war international investment frameworks.',
 'Must have registered a business in Ukraine or made a qualifying investment. Pre-war minimum investment was UAH 100 times minimum wage per employee for certain permit categories.',
 'Business registration documents, investment proof, valid passport, company incorporation documents.',
 'Varies', 'UAH 300–500',
 'investor', 'Varies', '1 year, renewable', CURRENT_DATE),

('any', 'ukraine', 'Family', 'Temporary Residence Permit (Family of Ukrainian Citizen)',
 'Foreign nationals who are spouses, children, or parents of Ukrainian citizens can obtain a Temporary Residence Permit for family reunification. Under current conflict conditions, many Ukrainian citizens are abroad.',
 'Must be the spouse, child, or parent of a Ukrainian citizen. Marriage certificate or birth certificate required. Ukrainian citizen must be willing to sponsor the application.',
 'Marriage certificate or birth certificate (apostilled), Ukrainian citizen''s documents, valid passport, health insurance.',
 'Varies', 'UAH 300–500',
 'family', 'Varies', '1 year, renewable', CURRENT_DATE),

-- QATAR
('any', 'qatar', 'Work', 'Qatar Work Visa (Residence Permit)',
 'Qatar is a major employer destination in the Middle East, especially for construction, healthcare, education, and finance. The employer sponsors the work visa and residence permit. Qatar reformed its kafala system in 2021, allowing workers to change jobs more freely.',
 'Must have a job offer from a Qatar-registered employer who initiates the visa process. No personal work visa applications — all processing is employer-led. Medical examination required upon arrival. Must be under 60 years old for most work categories.',
 'Job offer/contract from Qatari employer, valid passport (6+ months validity), educational certificates (attested), medical fitness certificate, passport photos.',
 'Typically 2–4 weeks (employer process)', 'QAR 200–500 (employer pays)',
 'work', '2–4 weeks', '2 years, renewable', CURRENT_DATE),

('any', 'qatar', 'Study', 'Student Visa (Qatar)',
 'Qatar is home to Education City, which hosts campuses of prestigious international universities including Cornell, Georgetown, Northwestern, and others. Students obtain residence permits through their educational institution.',
 'Must be enrolled at a Qatar-accredited institution. Education City institutions manage most of the visa process. Must pass medical examination.',
 'Enrollment letter, valid passport, passport photos, medical examination, financial means proof.',
 'Typically 2–4 weeks', 'QAR 100–300',
 'study', '2–4 weeks', 'Duration of studies', CURRENT_DATE),

('any', 'qatar', 'Digital Nomad', 'Tourist Visa / Short-Stay',
 '⚠️ Qatar does not have a digital nomad visa. Citizens of 95 countries can visit Qatar visa-free for up to 30–90 days. Qatar is primarily a transit and business destination. Working remotely for foreign companies while on a tourist visa is in a legal grey area.',
 'Visa-free entry for 95+ nationalities for 30–90 days. Must have return ticket, sufficient funds, and accommodation plans. Working for Qatari companies requires a separate work permit.',
 'Valid passport, return ticket, accommodation, sufficient funds.',
 'Visa-free: immediate', 'Free (visa-free countries) or QAR 100–200 (visa required countries)',
 'digital_nomad', 'Immediate (visa-free)', '30–90 days (visa-free)', CURRENT_DATE),

('any', 'qatar', 'Retirement', 'Long-Term Residence (Permanent Residency for Expatriates)',
 'Qatar introduced a permanent residency card scheme in 2018 for select expats who have lived in Qatar for 20+ years or have special achievements. Additionally, a long-term "privileged residency" was introduced in 2020 for investors and special categories.',
 'Standard permanent residency: 20+ years of legal continuous residence in Qatar. Privileged Residency (2020): Investors of at least QAR 5,000,000 in Qatar real estate, or spouses/children of Qatari citizens, or those with outstanding achievements.',
 'Proof of continuous residence (20+ years), or investment documentation (QAR 5,000,000), or relevant achievement documentation. Valid passport, health insurance.',
 'Typically 6–12 months for privileged residency application', 'QAR 1,000–5,000',
 'retirement', '6–12 months', 'Permanent (renewable annually)', CURRENT_DATE),

('any', 'qatar', 'Investor', 'Qatar Privileged Residency (Investor)',
 'Qatar''s Privileged Residency scheme (2020) grants long-term/permanent residency to investors in real estate or business. Two tracks: QAR 5,000,000 in Qatari real estate with full ownership (can also use QAR 3,750,000 in QIFF-regulated funds), or qualifying business investment.',
 'Investment Track A: Minimum QAR 5,000,000 in Qatari real estate or QAR 3,750,000 in regulated investment funds. Investment Track B: Business investment with approval from Ministry of Commerce. No age restriction.',
 'Investment documentation (property title deed or fund investment certificate), proof of funds and legitimate source, valid passport, medical examination.',
 'Typically 3–6 months', 'QAR 1,000–5,000',
 'investor', '3–6 months', 'Permanent (annually renewable)', CURRENT_DATE),

('any', 'qatar', 'Family', 'Family Sponsorship (Qatar)',
 'Qatar residents with a valid Residence Permit (RP) who earn above the minimum sponsorship income can sponsor their spouse and children to join them. The minimum salary for family sponsorship varies by family size.',
 'Must hold a valid Qatar Residence Permit. Must earn at least QAR 10,000/month (approximately USD 2,750) to sponsor spouse; higher for larger families. Housing must be appropriate for family size.',
 'Sponsor''s Residence Permit, marriage certificate (attested by Qatar embassy or apostilled), birth certificates for children, sponsor''s payslips and rental contract, valid passports for family members.',
 'Typically 2–4 weeks', 'QAR 200–500 per person',
 'family', '2–4 weeks', 'Tied to sponsor''s RP (typically 1–3 years)', CURRENT_DATE),

-- SAUDI ARABIA
('any', 'saudi-arabia', 'Work', 'Saudi Work Visa + Iqama (Residence Permit)',
 'Saudi Arabia is one of the world''s largest labor markets for expatriates. Employers (sponsors/kafeel) initiate the work visa process. The Iqama (residence permit) is obtained after arrival. Saudi Arabia has been liberalizing its labor market under Vision 2030 reforms.',
 'Must have a job offer from a Saudi-registered employer who serves as the visa sponsor (kafeel). Must pass medical examination. Work visa types vary: work and residence visa (single/multiple entry). Must be under 60 years old for most categories.',
 'Employment contract (attested by Saudi Embassy), valid passport (6+ months), passport photos, medical fitness certificate (including HIV test), educational credentials (attested), criminal background check.',
 'Typically 2–6 weeks (employer process)', 'SAR 200–2,000 (employer pays most fees)',
 'work', '2–6 weeks', 'Iqama: 1–2 years, renewable', CURRENT_DATE),

('any', 'saudi-arabia', 'Study', 'Saudi Student Visa',
 'International students studying at Saudi universities (including world-ranked King Abdullah University of Science and Technology — KAUST which is tuition-free) can obtain student visas. Saudi Arabia offers generous government scholarships for foreign students.',
 'Must be enrolled at a Saudi Ministry of Education-accredited institution. KAUST: open international applications, tuition-free with stipend. Other universities: acceptance letter required. Must pass medical examination.',
 'Enrollment/acceptance letter, valid passport, medical fitness certificate, passport photos, financial means proof (if not on scholarship).',
 'Typically 2–4 weeks', 'SAR 100–500',
 'study', '2–4 weeks', 'Duration of studies, renewable', CURRENT_DATE),

('any', 'saudi-arabia', 'Digital Nomad', 'Saudi Tourist e-Visa / Visit Visa',
 '⚠️ Saudi Arabia does not have a digital nomad visa. In 2019, Saudi Arabia opened tourism for the first time, offering e-visas to 49 nationalities. Remote workers visiting Saudi Arabia typically use the tourist e-visa. Working for Saudi companies requires a separate work permit.',
 'E-visa: citizens of 49 eligible countries. Must have return ticket, accommodation, sufficient funds. Working remotely for non-Saudi companies while on a tourist visa is in a legal grey area.',
 'Valid passport, e-visa application (online), return ticket, accommodation proof.',
 'E-visa: typically 3–5 days', 'SAR 440 (tourist e-visa)',
 'digital_nomad', '3–5 days (e-visa)', 'E-visa: 90 days per visit, valid for 1 year multiple-entry', CURRENT_DATE),

('any', 'saudi-arabia', 'Retirement', 'Saudi Premium Residency (Platinum Residency)',
 'Saudi Arabia''s Premium Residency program (launched 2019, expanded 2021) grants long-term or permanent residency to qualifying investors and individuals. Platinum Residency: SAR 800,000 one-time fee for permanent status. Annual Premium Residency: SAR 100,000/year.',
 'Platinum Residency: one-time payment of SAR 800,000 (approximately USD 213,000) for permanent residency. Annual Premium: SAR 100,000/year (approximately USD 26,700). Must have no criminal record. No age or minimum income requirement.',
 'Payment of fee, valid passport, medical examination, criminal background check.',
 'Typically 1–3 months', 'SAR 100,000/year or SAR 800,000 (one-time permanent)',
 'retirement', '1–3 months', 'Annual renewal or Permanent (Platinum)', CURRENT_DATE),

('any', 'saudi-arabia', 'Investor', 'Saudi Investment Visa / Special Integrated Logistics Zone Permits',
 'Saudi Arabia is actively attracting foreign investment under Vision 2030. The Saudi Investment Authority (SAGIA/MISA) issues investment licenses. Special Economic Zones (Neom, King Abdullah Economic City, etc.) have specific investor incentives including residency rights.',
 'Must establish or invest in a Saudi business registered with MISA (Ministry of Investment). 100% foreign ownership is now allowed in most sectors. Minimum investment varies by sector and zone.',
 'MISA investment license, company registration documents, proof of investment capital, valid passport, medical examination.',
 'Typically 2–4 months (MISA process)', 'SAR 2,000–10,000 (MISA fees)',
 'investor', '2–4 months', 'Iqama: 1–2 years renewable; Premium Residency option after 1 year', CURRENT_DATE),

('any', 'saudi-arabia', 'Family', 'Family Iqama (Dependent Residency)',
 'Saudi Iqama holders earning above the income threshold can sponsor their spouse and children as dependents. Dependent family members must also pass medical examinations. Different rules apply for domestic workers.',
 'Must hold a valid Saudi Iqama. Must earn at least SAR 4,000/month to sponsor spouse only; SAR 6,000/month for spouse + children. Housing must be appropriate.',
 'Sponsor''s Iqama, marriage certificate (attested by Saudi Embassy), birth certificates for children, sponsor''s payslips, medical fitness certificates for family members.',
 'Typically 2–4 weeks', 'SAR 400–800 per person',
 'family', '2–4 weeks', 'Tied to sponsor''s Iqama', CURRENT_DATE),

-- ISRAEL
('any', 'israel', 'Work', 'B-1 Work Visa / Expert Visa',
 'Israel''s B-1 work visa is for foreign nationals employed by Israeli companies. Israel''s thriving tech ecosystem ("Startup Nation") attracts significant skilled talent. The Expert Visa is a common route for specialized professionals in tech, engineering, and medicine.',
 'Must have a job offer from an Israeli employer. Expert visa: requires specialized skills not readily available in the Israeli labor market. General B-1: employer sponsors through the Ministry of Interior. Salary must meet minimum threshold.',
 'Employment contract, valid passport, employer''s company registration, educational qualifications, criminal background check.',
 'Typically 2–4 months (including employer sponsorship process)', 'USD 100–300',
 'work', '2–4 months', '1 year, renewable (up to 5 years maximum)', CURRENT_DATE),

('any', 'israel', 'Study', 'Student Visa (A-2)',
 'International students enrolled at Israeli universities can obtain a student visa (A-2) and subsequent residence permit (A-1 after 6 months). Israel has world-ranked universities including Weizmann Institute, Hebrew University, and Technion.',
 'Must be enrolled at an Israeli Ministry of Education-accredited institution. Must demonstrate financial means (approximately USD 1,000/month). Must have health insurance.',
 'Enrollment letter from Israeli institution, financial proof, health insurance, valid passport, criminal background check.',
 'Typically 2–4 weeks (at Israeli embassy)', 'USD 100–200',
 'study', '2–4 weeks', '1 year, renewable', CURRENT_DATE),

('any', 'israel', 'Digital Nomad', 'Tourist Visa (B-2) – Remote Work',
 'Israel does not have a dedicated digital nomad visa. Most nationalities can enter Israel visa-free for 90 days. Remote workers continuing work for foreign employers while on a tourist visa are generally tolerated but not explicitly authorized. Tel Aviv is a popular tech hub.',
 'Citizens of 100+ countries can enter Israel visa-free for 90 days. Must have return ticket, accommodation, sufficient funds. Must not be conducting work for Israeli companies without a work visa.',
 'Valid passport, return ticket, sufficient funds, accommodation details.',
 'Visa-free: immediate at airport', 'Free (visa-free countries)',
 'digital_nomad', 'Immediate (visa-free)', 'Up to 90 days (extendable to 6 months in some cases)', CURRENT_DATE),

('any', 'israel', 'Retirement', 'Aliyah (Jewish Immigration) / Long-Term Residency',
 'The primary long-term immigration pathway to Israel is Aliyah — immigration for Jewish people under the Law of Return, granting immediate citizenship. Non-Jewish retirees have limited options: repeated tourist stays (90 days max per entry for most nationalities), or marriage to an Israeli citizen.',
 'Aliyah: Must be Jewish (by birth — Jewish mother or grandmother — or by halachic conversion) or spouse/child/grandchild of a Jewish person. Non-Jewish options: marriage to Israeli citizen, or outstanding professional status (B-1 expert).',
 'Aliyah: proof of Jewish identity (Jewish community membership, rabbinical letter, birth certificates showing Jewish lineage), valid passport. Non-Jewish: proof of qualifying relationship to Israeli citizen.',
 'Aliyah: typically 3–6 months (through Jewish Agency); Non-Jewish: varies', 'Aliyah: minimal fees (Jewish Agency assistance available)',
 'retirement', '3–6 months (Aliyah)', 'Aliyah: permanent citizenship; Non-Jewish: limited options', CURRENT_DATE),

('any', 'israel', 'Investor', 'Investor Visa / Innovation Authority Programs',
 'Israel actively attracts foreign investors, especially in tech, biotech, and cleantech through the Israel Innovation Authority (IIA) programs. Foreign companies establishing R&D centers in Israel can receive significant grants. The B-1 Expert Visa covers investors managing their Israeli businesses.',
 'Must establish a business or make a qualifying investment in Israel. IIA programs require meeting specific tech/innovation criteria. No minimum investment amount for general business visa, but investment must be substantial and create economic benefit.',
 'Company registration documents (registered in Israel), investment proof, valid passport, business plan.',
 'Typically 2–4 months', 'USD 100–500',
 'investor', '2–4 months', '1 year, renewable', CURRENT_DATE),

('any', 'israel', 'Family', 'Family Reunification Visa / Citizenship under Law of Return',
 'Spouses of Israeli citizens can obtain an A-5 residence permit and eventually citizenship. Under the Law of Return, spouses, children, and grandchildren of Jews may also be eligible for Aliyah.',
 'A-5 for spouse of Israeli citizen: must be legally married to an Israeli citizen, genuine relationship. Law of Return: spouse/child/grandchild of a Jewish person. Same-sex partnerships recognized for immigration purposes (but not marriage by Israeli law).',
 'Marriage certificate, Israeli citizen''s documents, proof of genuine relationship (for A-5), valid passport.',
 'A-5: typically 3–6 months; Aliyah: 3–6 months', 'USD 100–300',
 'family', '3–6 months', 'A-5: gradual — temporary, then permanent after 4+ years; Aliyah: immediate citizenship', CURRENT_DATE),

-- MOROCCO
('any', 'morocco', 'Work', 'Work Visa (Carte de Séjour – Employé)',
 'Foreign nationals working in Morocco require a work contract visa and then obtain a Residence Card (Carte de Séjour). Morocco is increasingly attracting foreign workers in IT, renewable energy, and business process outsourcing sectors.',
 'Must have a signed employment contract with a Moroccan employer registered with the Ministry of Employment. The contract must be registered and approved by ANAPEC (National Agency for Employment Promotion) in most cases.',
 'Employment contract (attested), valid passport, passport photos, criminal record certificate, medical certificate, accommodation proof.',
 'Typically 4–8 weeks', 'MAD 300–700',
 'work', '4–8 weeks', '1 year, renewable', CURRENT_DATE),

('any', 'morocco', 'Study', 'Student Visa (Type D)',
 'International students enrolled at Moroccan universities and educational institutions. Morocco''s Mohammed V University and Cadi Ayyad University are well-regarded. Government offers scholarships for students from African and Arab countries.',
 'Must be enrolled at a recognized Moroccan educational institution. Financial proof required (approximately MAD 5,000/month). Health insurance recommended.',
 'Enrollment letter from Moroccan institution, financial proof, valid passport, criminal record, medical certificate.',
 'Typically 4–8 weeks', 'MAD 300–700',
 'study', '4–8 weeks', 'Duration of studies, renewable', CURRENT_DATE),

('any', 'morocco', 'Digital Nomad', 'Morocco Digital Nomad Initiative / Long-Stay Visa',
 'Morocco has announced plans to launch a digital nomad visa as part of its digital transformation strategy. Casablanca, Rabat, and Marrakech are growing remote work hubs. Currently, most digital nomads use extended tourist stays (90 days for most nationalities).',
 'Currently: most nationalities can visit Morocco visa-free for 90 days without formal work authorization for remote work for foreign companies. No dedicated digital nomad visa launched as of 2025 (announced for future).',
 'Valid passport, return ticket, accommodation, sufficient funds.',
 'Visa-free: immediate', 'Free (visa-free) or MAD 300 (visa required)',
 'digital_nomad', 'Immediate (visa-free)', 'Up to 90 days (extendable in some circumstances)', CURRENT_DATE),

('any', 'morocco', 'Retirement', 'Residence Card for Financially Independent Persons',
 'Morocco is a popular retirement destination for Europeans and North Americans, especially in Marrakech, Essaouira, and Tangier. Long-term retirees can obtain a Carte de Séjour (residence card) as financially independent persons.',
 'Must demonstrate passive income sufficient to cover living costs in Morocco without working. Typically: EUR 2,000–3,000/month from pension or investments. Must have health insurance. No minimum age requirement.',
 'Proof of passive income (pension letter or bank statements), health insurance, valid passport, accommodation proof (long-term lease or property purchase), criminal record certificate.',
 'Typically 4–8 weeks (initial visa at embassy + 1–3 months for Carte de Séjour)', 'MAD 300–700',
 'retirement', '4–8 weeks', '1 year, renewable annually', CURRENT_DATE),

('any', 'morocco', 'Investor', 'Business Residence Visa (Investor)',
 'Morocco actively courts foreign investment in manufacturing, renewable energy, agriculture, and tech. The Casablanca Finance City (CFC) hub offers special residency and tax benefits for financial firms. Foreign investors establishing businesses can obtain residence as business owners.',
 'Must establish a business in Morocco (SARL or other legal form) with capital registered at ADES and Ministry of Industry. Investment above MAD 200,000 (approximately USD 20,000) facilitates easier residency. CFC status requires higher capital and approval.',
 'Business registration documents (RC — Registre de Commerce), investment transfer proof, valid passport, business plan.',
 'Typically 2–4 months (business setup + visa)', 'MAD 300–700 (visa) + business registration costs',
 'investor', '2–4 months', '1 year, renewable', CURRENT_DATE),

('any', 'morocco', 'Family', 'Family Reunification Visa',
 'Foreign nationals legally residing in Morocco can apply for family reunification for their spouse and dependent children. Moroccan citizens can also sponsor foreign family members.',
 'Must be legally residing in Morocco with a valid Carte de Séjour. Must have adequate income and accommodation for the family. Sponsor must have been residing in Morocco for at least 1 year.',
 'Sponsor''s Carte de Séjour, marriage certificate (translated and notarized in Arabic), birth certificates for children, financial proof, accommodation proof, valid passports.',
 'Typically 4–8 weeks', 'MAD 300–700',
 'family', '4–8 weeks', '1 year, renewable', CURRENT_DATE)

ON CONFLICT DO NOTHING;
