/*
  # Add Full Rich Content - Batch 4b

  Countries covered:
  - Czech Republic, Denmark, Romania, Russia, Saudi Arabia, Turkey, Ukraine, Vietnam

  Each country gets:
  - Comprehensive intro_md (400-550 chars)
  - 7 detailed FAQs (faq_json)
  - warning_md with practical cautions
  - next_steps_md with actionable guidance
*/

DO $$
DECLARE
  v_id uuid;
BEGIN

  -- ============================================================
  -- CZECH REPUBLIC
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'czech-republic';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'The Czech Republic is a Central European EU and Schengen member with a thriving economy centered on automotive, electronics, and a growing tech sector. Prague is a top expat destination combining Central European quality of life with costs well below Western Europe. The Employee Card combines work and residence authorization. The Czech Republic offers clear pathways to EU permanent residence and Czech citizenship. Prague''s tech scene has grown significantly, attracting international professionals.',
      '[
        {"question": "What is the Czech Employee Card?", "answer": "The Employee Card (Zamestnanecka karta) is the main work and residence permit for non-EU nationals employed by Czech companies. Employer must obtain clearance from the Labour Office (Urad prace) confirming no suitable Czech/EU candidate exists. Application submitted at Czech embassy. Fee approximately CZK 2,500 (EUR 100). Processing 60-90 days. Valid for the duration of the employment contract, up to 2 years. Grants both work authorization and residence in one document."},
        {"question": "What is the Czech Blue Card?", "answer": "The EU Blue Card is for highly qualified non-EU professionals with: a university degree (3+ years), a job offer in a corresponding profession, and salary at least 1.5x the average Czech gross wage (approximately CZK 64,000+/month in 2024). Fee approximately CZK 2,500. Valid 2 years, renewable. Blue Card holders can apply for permanent residence after 2 years (vs 5 years for standard residents). Spouses receive work authorization automatically."},
        {"question": "How affordable is Prague compared to Western Europe?", "answer": "Prague offers significantly lower costs than Western European capitals. 1-bedroom apartment in Prague 2/3/6/7 (popular expat areas): CZK 20,000-35,000/month (EUR 800-1,400). Monthly grocery budget: EUR 250-380. Restaurant meal: EUR 8-16. Total monthly budget for comfortable Prague living: EUR 1,500-2,500. Prague tech salaries have grown substantially; EUR 3,000-6,000+/month gross is common in senior tech roles, making the Prague value proposition very strong."},
        {"question": "What is the Czech trade license (Živnostenský list) for freelancers?", "answer": "EU citizens and legal residents can obtain a Trade License (živnostenský list) to work as self-employed (OSVČ). Application at the Trade Licensing Office (živnostenský úřad): fee CZK 1,000 (EUR 40). Freelancers pay health insurance (minimum CZK 2,968/month in 2024) and social insurance (minimum CZK 3,852/month). Trade licenses cover most freelance services. Non-EU nationals need a valid residence permit first to obtain a trade license."},
        {"question": "What are Czech income tax rates?", "answer": "Czech income tax rates: 15% on income up to CZK 1,935,552/year (4x average wage), 23% above. Effective rate for average salaries is approximately 15%. Social and health insurance (employee): approximately 11% of gross salary. Combined effective tax burden: approximately 22-26% for typical professional salaries — among the lowest in the EU. The Czech Republic does not tax capital gains on shares held over 3 years or property held over 10 years."},
        {"question": "How do I get Czech permanent residence?", "answer": "Non-EU nationals can apply for permanent residence after 5 years of continuous legal residence (2 years on EU Blue Card). Requirements: continuous legal residence, basic Czech language proficiency (A1 for most, A2 for permanent residence strengthened requirements), stable income, and no criminal record. Fee CZK 2,500 (EUR 100). EU Long-Term Residence Permit grants rights in all EU member states. Czech citizenship requires 5 years of permanent residence (10 years total legal residence)."},
        {"question": "What is the Czech Foreign Police registration requirement?", "answer": "Non-EU nationals must register at the Foreign Police (Odbor cizinecke policie) within 3 days of arriving in the Czech Republic (hotels do this automatically). Long-term stay applicants submit applications here. After approval, the residence permit sticker is placed in your passport. Additionally, you must have a Czech address (domicile/trvalé bydliště) registered for all permit applications. Keep your registration documents with you during your stay."}
      ]'::jsonb,
      'Czech Labour Office processing for Employee Cards can take longer than the official 60-day timeline during high-demand periods. The Czech language requirement has been strengthened for various permit stages; begin Czech language study early. Prague rental market has tightened considerably in recent years; research accommodation before committing to a start date. All foreign documents must be apostilled (Czech Republic is an Apostille Convention member) and officially translated into Czech.',
      'Ensure your employer files the Labour Office notification for your Employee Card before you apply for the visa, submit your Employee Card application at the Czech embassy with all translated and apostilled documents, register with Foreign Police within 3 days of arrival, obtain your Czech ID number (rodné číslo equivalent for foreigners) from the Foreign Police, open a Czech bank account (Česká spořitelna, ČSOB, or Moneta are popular), register with the health insurance fund (VZP or another) immediately upon arrival.'
    );
  END IF;

  -- ============================================================
  -- DENMARK
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'denmark';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Denmark is a Nordic EU and Schengen member with one of the world''s highest standards of living, a strong welfare state, and a thriving startup ecosystem (Copenhagen is Scandinavia''s startup capital). SIRI (The Danish Agency for International Recruitment and Integration) manages most work permits. The Pay Limit Scheme and Positive List offer two clear pathways for skilled workers. High taxes are offset by free healthcare, free university education, and comprehensive social security. Copenhagen is the main expat hub.',
      '[
        {"question": "What is the Denmark Pay Limit Scheme?", "answer": "The Pay Limit Scheme allows non-EU nationals to work in Denmark if their annual salary is at least DKK 475,000 (2024, approximately EUR 63,700). No specific educational requirements. Employer applies online through SIRI. Work and residence permit issued together. Fee DKK 4,165 (approximately EUR 560). Processing takes 1-2 months. The permit is valid for up to 4 years. This is the most common route for senior tech, finance, and management professionals."},
        {"question": "What is the Danish Positive List scheme?", "answer": "The Positive List scheme grants work permits for occupations experiencing labor shortages in Denmark. The list is updated quarterly by SIRI. Common positive list roles include IT specialists, engineers, doctors, nurses, and certain trades. Salary requirement: DKK 375,000+/year (2024). Educational requirements match the occupation. Application via employer through SIRI. Same fee and processing as Pay Limit Scheme. Check the current positive list at newtodenmark.dk."},
        {"question": "What are Danish income tax rates?", "answer": "Denmark has the world''s highest income tax rates. Municipal tax: 24-27.8% (varies by municipality). State tax: 15% (top-up for income above DKK 552,500). Labor market contribution (AM-bidrag): 8% of gross income. Total marginal rate above top bracket: approximately 55-56%. However, Denmark''s Expat Tax Scheme (formerly called the Researcher Scheme) allows qualifying new employees to pay a flat 32.84% tax (including AM-bidrag) for 7 years — a major benefit for high earners."},
        {"question": "What is the Danish Expat Tax Scheme?", "answer": "The Expat Tax Scheme allows non-Danish residents taking up employment in Denmark to pay a flat 32.84% tax rate for up to 7 years, compared to the standard 55%+ marginal rate. Requirements: salary of at least DKK 75,100/month (2024), not having been a Danish tax resident in the previous 10 years, and the employment must meet certain conditions. The employer must apply within 6 months of the employment start date. Saves substantial amounts for high earners."},
        {"question": "What is the CPR number in Denmark and why is it essential?", "answer": "The CPR (Central Person Register) number is Denmark''s national identification number. Issued to all residents (including expats with valid permits) when registering at the local citizen service center (Borgerservice). Required for: healthcare (yellow health insurance card), bank accounts, tax registration, library cards, and virtually all public services. Non-EU residents receive their CPR number when their residence permit is approved. Registration should be done within 5 days of establishing a permanent address."},
        {"question": "How long until Danish permanent residence?", "answer": "Permanent residence (tidsubegrænset opholdstilladelse) requires 8 years of continuous legal residence for the standard path (4 years with enhanced integration — language, work, civic knowledge). Requirements include: Danish language at A2 level (Prøve i Dansk 2), maintaining continuous employment, passing a citizenship test, and no criminal record. Danish citizenship requires 9 years of legal residence (down to 7 years with enhanced integration). Denmark conditionally allows dual citizenship since 2015."},
        {"question": "What is Copenhagen''s cost of living?", "answer": "Copenhagen is one of Europe''s most expensive cities. 1-bedroom apartment: DKK 12,000-18,000/month (EUR 1,610-2,415). Monthly food budget: EUR 500-700. Public transport monthly pass: DKK 430 (EUR 58). Total monthly budget for comfortable Copenhagen living: EUR 3,500-5,000 excluding rent. However, Danish salaries are proportionally high (average gross EUR 4,000-6,000+/month for professionals) and the expat tax scheme significantly reduces take-home tax for qualifying employees."}
      ]'::jsonb,
      'The Expat Tax Scheme application is strictly time-limited to 6 months from employment start; missing this window forfeits the benefit entirely. Danish municipality tax rates vary; check the specific rate for your municipality when budgeting. Permanent residence requirements have been toughened significantly in recent years; language and integration tests must be carefully planned. Copenhagen housing market is extremely competitive; start searching for accommodation well in advance.',
      'Have your employer apply for your work and residence permit through SIRI before you relocate, apply for the Expat Tax Scheme within 6 months of employment start date if you qualify, register at Borgerservice to receive your CPR number within 5 days of establishing your Danish address, receive your yellow health insurance card (sundhedskort) linked to your CPR, open a Danish bank account (Danske Bank, Nordea, or Lunar for digital banking), and enroll in Danish language courses at a language center (sprogskole) to work toward the integration requirements.'
    );
  END IF;

  -- ============================================================
  -- ROMANIA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'romania';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Romania is an EU member that joined Schengen land borders in January 2024. Bucharest is a rapidly growing tech and business hub with a vibrant startup scene and significantly lower costs than Western Europe. Romania has a flat 10% income tax — one of the EU''s lowest. IT professionals in Romania enjoy even more favorable tax treatment. Cluj-Napoca, Timisoara, and Iasi are major secondary tech hubs. Romania offers a straightforward path to EU residency and citizenship.',
      '[
        {"question": "What work permits are available for non-EU nationals in Romania?", "answer": "Non-EU nationals need a Long-Stay Visa for Employment (Type D, work) and subsequently a Residence Permit (Permis de sedere) issued by the General Inspectorate for Immigration (IGI). The employer must first obtain a work authorization from the IGI based on quota availability. Fee approximately EUR 120-150 for the work authorization and residence permit. Processing takes 4-8 weeks for work authorization; residence permit issued within 30 days of arrival."},
        {"question": "What is Romania''s flat income tax rate?", "answer": "Romania has a flat 10% personal income tax rate — one of the lowest in the EU. Social contributions (employee): 25% pension insurance + 10% health insurance = 35% total (these apply to gross salary before the 10% income tax). Employer contributions: 2.25%. The combined employee take-home on a EUR 2,000/month gross salary: approximately EUR 1,100-1,200. Romania also has a 0% income tax for IT professionals (registered in the IT sector) — a major incentive."},
        {"question": "What is Romania''s 0% income tax for IT professionals?", "answer": "Romania offers a complete income tax exemption (0% income tax) for software developers, software testers, and other qualifying IT professionals who work for companies registered as IT companies under specific CAEN (activity) codes. Only the 35% social contributions apply. This is a legally established benefit creating one of Europe''s most favorable tax environments for tech workers. Requires employment with a qualifying Romanian IT company. Many international tech companies have Romanian development centers specifically because of this."},
        {"question": "How affordable is Bucharest compared to Western Europe?", "answer": "Bucharest offers very strong value. 1-bedroom apartment in central districts (Floreasca, Herastrau, Dorobanti): EUR 500-900/month. Monthly grocery budget: EUR 250-400. Restaurant meal: EUR 8-15. Total monthly budget for comfortable Bucharest living: EUR 1,200-2,000. Cluj-Napoca (major tech hub): slightly lower costs than Bucharest. These costs combined with EU-level tech salaries (EUR 2,000-5,000+/month for experienced developers) make Romania exceptionally competitive."},
        {"question": "What is the Romanian CNP and residence registration?", "answer": "The CNP (Cod Numeric Personal) is Romania''s personal identification code. Non-EU residents receive their CNP when their residence permit is issued by IGI. Registration of address at the local town hall (primarie) is required within 3 days of establishing a fixed address in Romania. The Residence Permit card (card de rezidenta) is issued after your application is processed and serves as your main identity document in Romania. Required for banking, healthcare, and all official interactions."},
        {"question": "What is Romania''s path to EU permanent residence and citizenship?", "answer": "Non-EU nationals can apply for EU Long-Term Resident status after 5 years of continuous legal residence. Requirements: continuous legal status, stable income, health insurance. Romanian citizenship requires 8 years of legal residence (5 years with certain criteria). Descendants of Romanian citizens (even those who lost citizenship under communism) can reclaim Romanian citizenship under Law 21/1991 — this is a widely used pathway to EU citizenship for those with Romanian heritage."},
        {"question": "What is the Romania Tech Visa program?", "answer": "Romania introduced a dedicated Digital Nomad/Tech Visa in 2021 for non-EU remote workers. Requirements: proof of remote work or freelance activity for non-Romanian employers, income of at least EUR 3,300/month (3x Romanian average net wage), health insurance. Valid 1 year, extendable. Application at Romanian consulates. Fee approximately EUR 120. After consecutive applications totaling 5 years, permanent residence can be sought. One of the more recently established EU digital nomad programs."}
      ]'::jsonb,
      'Romania''s work authorization system uses annual immigration quotas; if quotas are exhausted, new work authorizations pause until the next quota year. The IT tax exemption requires proper employer registration under qualifying CAEN codes; verify this with your employer before relying on the tax benefit. Romania joined Schengen land borders in January 2024 but air/sea Schengen expansion was ongoing; verify current Schengen status when planning travel. All foreign documents need apostilles and certified Romanian translation.',
      'Have your employer submit the work authorization application to IGI well before your planned start date, apply for your Long-Stay D Work Visa at the Romanian consulate after work authorization approval, register your address at the local primarie within 3 days of arrival, apply for your Residence Permit card at the IGI territorial office, obtain your CNP and open a Romanian bank account (BCR, BRD, or Banca Transilvania are major retail banks), and if working in IT confirm your employer''s CAEN code qualifies for the 0% income tax benefit.'
    );
  END IF;

  -- ============================================================
  -- RUSSIA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'russia';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Russia is the world''s largest country by area with a major economy centered on energy, mining, and a significant industrial and technology base. Moscow and St. Petersburg are the primary destinations for international professionals. Since the 2022 invasion of Ukraine, most Western nations have significantly restricted engagement with Russia, many multinationals have exited, and numerous sanctions are in effect. Information here reflects the formal immigration system; individuals should consult current government advisories from their home country before considering travel or relocation.',
      '[
        {"question": "What work visa categories exist in Russia?", "answer": "Russia''s main work authorization is the Work Permit (razresheniye na rabotu), required for most non-CIS nationals. The Highly Qualified Specialist (HQS) permit requires a minimum annual salary of RUB 2,000,000/year (approximately USD 22,000+ at current rates) and offers significant benefits: 13% flat income tax (vs 30% standard non-resident rate), faster processing, and family members can work. Application through the employer with the Ministry of Internal Affairs (MVD)."},
        {"question": "What is the Highly Qualified Specialist (HQS) permit in Russia?", "answer": "The HQS (Vysokokvalifitsirovanny Spetsialist) permit is Russia''s premium work authorization for foreign professionals earning RUB 2,000,000+/year (higher thresholds for some sectors). Benefits: 13% income tax flat rate (same as Russian citizens), no mandatory work permit quota, can apply for 3-year residence permit directly, family members can work without separate permits. Processing 14 business days after application submission to MVD. For organizations and sectors not under international sanctions."},
        {"question": "What are Russian income tax rates?", "answer": "Russian residents (183+ days/year) pay 13% income tax on income up to RUB 5,000,000/year, 15% above. Non-residents pay 30% flat rate on Russian-source income (with exceptions for HQS holders who pay 13% regardless of residency status). No state-level income tax. Social contributions (employer-paid): 30% on salary up to RUB 2,225,000/year, 15.1% above. Russia''s tax compliance system is largely employer-managed for formally employed workers."},
        {"question": "How does Russian address registration (propiska/registration) work?", "answer": "All persons in Russia (including foreign visitors and residents) must register their address with the MVD within 7 working days of arrival. Hotels automatically register guests. Those staying in private apartments must register at the local MVD office or MFC (multifunctional center). Failure to register is a violation. Temporary registration is issued for the duration of your stay. Permanent registration (propiska) is for long-term residents with a valid residence permit."},
        {"question": "What is the Russian Temporary Residence Permit (RVP)?", "answer": "The Temporary Residence Permit (Razresheniye na Vremennoye Prozhivaniye) allows a 3-year stay in Russia. After 8 months on a work permit, eligible workers can apply for RVP. Annual quota system applies (exceptions for HQS holders, spouses of Russian citizens, etc.). Application fee RUB 1,600. After 1 year on RVP, can apply for permanent residence permit (Vid na Zhitelstvo). RVP is regional — you must live in the region where it was issued."},
        {"question": "What is the current geopolitical situation affecting immigration to Russia?", "answer": "Since February 2022, most Western countries (EU, USA, UK, Canada, Australia) have imposed extensive sanctions on Russia and strongly advise their citizens against travel there. Most Western multinational corporations have exited or suspended Russian operations. Banking and financial access is severely restricted due to SWIFT exclusions and payment processing limitations. Travel insurance from Western providers typically excludes Russia. Individuals considering Russia should consult current government travel advisories from their home country."},
        {"question": "What CIS and visa-free agreements does Russia have?", "answer": "Russia has visa-free agreements with CIS member states (Armenia, Azerbaijan, Belarus, Kazakhstan, Kyrgyzstan, Moldova, Tajikistan, Uzbekistan) and several other countries (Argentina, Brazil, Israel, South Korea, Serbia, and others — the full list is on the MID Russia website). These allow entry without a visa but still require registration. Citizens of these countries also have simpler work permit procedures under bilateral agreements. China and Russia have expanded travel and business links since 2022."}
      ]'::jsonb,
      'CRITICAL: Most Western governments (USA, EU member states, UK, Canada, Australia, and others) have issued strong Do Not Travel advisories for Russia since February 2022 due to the ongoing war in Ukraine. Sanctions, banking restrictions, and legal risks for Western nationals are significant. Anyone from a Western country considering travel or relocation to Russia should consult their government''s current travel advisory and obtain specialized legal and security advice before proceeding. Information above reflects the formal legal framework only.',
      'Consult your home government''s current travel advisory for Russia before making any decisions, seek specialized legal and security counsel if considering relocation despite advisories, verify that your employer is not subject to international sanctions that could expose you to legal risk, understand banking and financial access limitations given SWIFT exclusions and payment restrictions, ensure you have valid international health insurance as access to some medical care may be complicated, and register your address with the MVD within 7 working days of arrival in Russia.'
    );
  END IF;

  -- ============================================================
  -- SAUDI ARABIA
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'saudi-arabia';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Saudi Arabia is undergoing a major economic transformation under Vision 2030, creating significant demand for international professionals in construction, tourism, finance, healthcare, and technology. Riyadh, Jeddah, and NEOM are major destination cities for expatriates. Saudi Arabia has no personal income tax. The kafala sponsorship system has been partially reformed. NEOM and Red Sea Project are multi-decade megaprojects creating sustained demand for specialized international talent.',
      '[
        {"question": "How does Saudi Arabia''s employment sponsorship (kafala) system work?", "answer": "Saudi Arabia''s modified kafala system ties your residence to your employer. Your employer (sponsor) applies for your work visa and manages your Iqama (residence permit). Since 2021 reforms, workers with 2+ years of service can transfer employers without needing sponsor consent in some cases (Premium Residency holders have more freedom). Exit re-entry visa reforms in 2021 gave workers more travel flexibility. Your Iqama must remain valid at all times."},
        {"question": "Is there income tax in Saudi Arabia?", "answer": "Saudi Arabia has no personal income tax for individuals. This is the primary financial attraction for professionals. Zakat (2.5% of net assets) applies to Saudi nationals and Saudi-owned businesses only. Foreign workers pay no income tax, capital gains tax, or inheritance tax. VAT of 15% applies to most goods and services (increased from 5% in 2020). Combined with high professional salaries and employer-provided benefits (housing, transport, flights home), Saudi Arabia offers very high net income."},
        {"question": "What is the Saudi Iqama (Residence Permit)?", "answer": "The Iqama is the official Saudi residence permit card, required for all expatriates living and working in Saudi Arabia. Issued by the Jawazat (Passport Department) after arrival on a work visa. Must be carried at all times. Renewed annually by the employer, who pays the annual Iqama renewal fee (SAR 650-12,000+ depending on employee category and Saudization requirements). Expired Iqama results in significant fines. Most employers handle renewal automatically."},
        {"question": "What is the Saudi Premium Residency (Green Card)?", "answer": "Saudi Arabia''s Premium Residency (Iqama Premium) grants long-term residency without employer sponsorship. Two types: Permanent (SAR 800,000 one-time fee, approximately USD 213,000) and Temporary (SAR 100,000/year, approximately USD 26,600/year). Benefits: no employer sponsorship needed, own a property in most areas, start a business, sponsor family. Premium Residency holders can work for any employer and sponsor their own family visas. Aimed at attracting wealthy investors and top talent."},
        {"question": "What is the Saudization (Nitaqat) system?", "answer": "Saudization (Nitaqat program) requires companies to employ minimum percentages of Saudi nationals depending on industry and company size. Companies are rated Platinum, Green, Yellow, or Red. Red-rated companies cannot transfer Iqamas, hire new foreign workers, or renew existing work visas. For foreign workers, your employer''s Nitaqat status directly affects visa issuance and renewals. Premium and Green companies offer the most stable employment environment for expats."},
        {"question": "Can women work and live independently in Saudi Arabia?", "answer": "Saudi Arabia has significantly liberalized rules for women since 2017. Women can now: drive, obtain a passport and travel without male guardian permission (for those over 21), live independently, start a business, and access most public spaces. Women can work in most sectors including government and private employment. Female expat professionals are employed across finance, healthcare, tech, and education. Cultural expectations still differ from Western norms; research current standards before relocating."},
        {"question": "What are the main megaprojects employing international talent in Saudi Arabia?", "answer": "Vision 2030 megaprojects creating major expatriate employment: NEOM (the linear city and surrounding region in Tabuk — hundreds of billions in planned investment), Red Sea Project (luxury tourism development), Diriyah Gate (cultural heritage district in Riyadh), Qiddiya (entertainment city near Riyadh), and King Salman Park (Riyadh). These projects employ engineers, architects, planners, project managers, and specialists from around the world on multi-year contracts with competitive packages."}
      ]'::jsonb,
      'Your legal status in Saudi Arabia is tied to your employer; losing your job requires finding a new sponsor or departing within a grace period. Iqama expiry without renewal results in significant escalating fines (overstay penalties). Saudi Arabia''s strict Islamic law applies to all residents; research laws regarding alcohol, dress codes, public behavior, and social media use before relocating. Employment contracts should clearly state package components (housing, transport, flights home) as these are critical to your effective compensation.',
      'Confirm your employment contract includes all package components (housing allowance, transport, annual flights home) before signing, ensure your employer has a Green or Platinum Nitaqat rating, complete your medical examination at a Saudi-approved facility in your home country before visa issuance, obtain your Iqama promptly after arrival and keep it valid at all times, consider applying for a Premium Residency if planning long-term independence from employer sponsorship, and register with your home country''s embassy in Riyadh or Jeddah upon arrival.'
    );
  END IF;

  -- ============================================================
  -- TURKEY
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'turkey';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Turkey straddles Europe and Asia and has become an increasingly popular destination for digital nomads, investors, and retirees, particularly in Istanbul. The Turkish lira has experienced significant depreciation, creating very favorable conditions for hard-currency earners. Turkey''s real estate citizenship program has been popular with non-EU investors. Istanbul is a world-class city with a vibrant culture, excellent cuisine, and modern infrastructure. Antalya, Bodrum, and Izmir are popular coastal alternatives.',
      '[
        {"question": "What residency options does Turkey offer for expats?", "answer": "Main options: Short-Term Residence Permit (for those renting or owning property, with a tourist or business reason), Long-Term Residence Permit (after 8 years of continuous legal residence), Work Permit (employer-sponsored or self-employed), and Citizenship by Investment. Short-Term Residence Permit can be renewed indefinitely and is popular with digital nomads and retirees. Application through the e-ikamet online system. Fee approximately USD 80-200 depending on nationality and duration."},
        {"question": "What is Turkey''s Citizenship by Investment program?", "answer": "Turkish citizenship can be obtained through: real estate purchase of at least USD 400,000 (held for 3 years), or bank deposit of USD 500,000 in a Turkish bank (held for 3 years), or creating 50 jobs for Turkish citizens, or investing USD 500,000 in fixed capital. Application through the General Directorate of Land Registry. Processing 3-6 months. Turkey allows dual citizenship. Turkish passport grants visa-free or visa-on-arrival access to 110+ countries."},
        {"question": "How does the Turkish lira situation benefit hard-currency earners?", "answer": "The Turkish lira has depreciated significantly against USD and EUR over recent years. Those earning in hard currency experience very favorable purchasing power in Turkey. A salary of USD 3,000/month provides a very comfortable standard of living in Istanbul. However, inflation in Turkey is high (40-60%+ in recent years), meaning TRY-denominated costs increase rapidly. Budget in USD/EUR rather than TRY for stability. Rents in Istanbul''s expat neighborhoods are often quoted in USD or EUR by landlords."},
        {"question": "Do digital nomads need a work permit in Turkey?", "answer": "Turkey does not have a dedicated digital nomad visa. Remote workers employed exclusively by non-Turkish companies typically apply for a Short-Term Residence Permit based on property rental or other grounds. Technically, working remotely for foreign employers while on a tourist visa or Short-Term Residence Permit is a grey area in Turkish law. A Short-Term Residence Permit legalizes your stay but does not explicitly authorize work. Turkey has discussed introducing a digital nomad visa but had not formalized it as of 2024."},
        {"question": "What is the Turkish work permit (Calişma İzni) for employed professionals?", "answer": "Foreign nationals employed by Turkish companies need a work permit issued by the Ministry of Labor and Social Security. The employer applies online (e-Devlet system). Requirements: minimum monthly salary of approximately TRY 33,000+ (verify current rate), relevant qualifications, and an employer employing at least 5 Turkish citizens per foreign employee (ratio requirement). Fee varies by permit type. Processing takes 30-90 days. Work permit combines work and residence authorization."},
        {"question": "What is the cost of living in Istanbul?", "answer": "Istanbul offers very strong value in USD/EUR terms. 1-bedroom apartment in Beyoglu/Sisli/Besiktas: USD 400-900/month (though TRY prices fluctuate rapidly). Monthly food budget: USD 300-500. Total monthly budget for comfortable Istanbul living: USD 1,200-2,200 when earning in hard currency. Antalya and Izmir are 20-30% cheaper than Istanbul. The combination of low effective costs (due to lira depreciation), rich culture, excellent cuisine, and Mediterranean climate makes Turkey extremely popular."},
        {"question": "What is the Turkish KIMLIK number and Ikamet card?", "answer": "The Ikamet (Residence Permit) is the official documentation for foreign residents. After approval, you receive an Ikamet card with a Yabanci Kimlik Numarası (Foreign Identification Number / KIMLIK). This number is essential for: opening a Turkish bank account, signing leases, phone contracts, and accessing healthcare. Apply online through the e-ikamet system (goc.gov.tr). Processing takes 2-4 weeks. Keep your Ikamet card valid at all times; overstay fines are enforced at exit."}
      ]'::jsonb,
      'Turkish lira inflation means any TRY-denominated budget figures become outdated quickly; always use USD/EUR equivalents for planning. Residence permit processing times can exceed stated timelines. Citizenship by Investment real estate minimum thresholds have increased over time and may continue to change. Turkish rental market in Istanbul has become competitive; research neighborhoods thoroughly. Short-Term Residence Permit applicants must show proof of sufficient funds; requirements are assessed at the immigration office.',
      'Apply for your Short-Term Residence Permit through the e-ikamet online system (goc.gov.tr) before your tourist visa expires, obtain your Yabanci Kimlik Numarası (KIMLIK) from the Residence Permit card, open a Turkish bank account (Garanti BBVA, Ziraat Bank, or Akbank are widely used), register with the SGK (Social Security Institution) if employed by a Turkish company, obtain Turkish health insurance or maintain international coverage meeting SGK equivalency, and for citizenship by investment engage a Turkish real estate attorney and the General Directorate of Land Registry.'
    );
  END IF;

  -- ============================================================
  -- UKRAINE
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'ukraine';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Ukraine is a large Eastern European country with a significant IT sector (Ukrainian developers are among the world''s most in-demand), strong agricultural exports, and a pre-war population of 44 million. Kyiv, Lviv, and Kharkiv were major tech hubs. Since the Russian invasion in February 2022, much of the country remains under martial law. Ukraine''s IT sector has largely continued operating remotely or from western Ukraine and abroad. Lviv, which is further from the front lines, has become the primary destination for those remaining in Ukraine.',
      '[
        {"question": "What is the current situation for foreigners in Ukraine?", "answer": "Since Russia''s full-scale invasion in February 2022, Ukraine has been under martial law. The State Migration Service of Ukraine (SMS) continues to function for residency and immigration matters, primarily in Kyiv and western Ukraine. Foreign nationals can legally reside in Ukraine on valid permits. Most Western governments have Do Not Travel advisories in place. Those with essential reasons to be in Ukraine (humanitarian work, journalism, business) should consult current government advisories and maintain detailed security protocols."},
        {"question": "What residency options does Ukraine offer when accessible?", "answer": "Under normal conditions, Ukraine offers: Temporary Residence Permit (Timchasovyi Dozvil na Prozhivannia) for employed workers, spouses of Ukrainian citizens, and others. Permanent Residence Permit after 5 years of continuous temporary residence. D Visa (long-stay visa) for initial entry. Work permit from the Employment Service. Digital Nomad Visa is in development but not formally launched as of 2024. Fee for temporary residence permit: approximately UAH 350-700."},
        {"question": "What is Ukraine''s IT sector status since 2022?", "answer": "Ukraine''s IT industry has demonstrated remarkable resilience. Most IT companies (EPAM, GlobalLogic, SoftServe, Intellias, and thousands of others) continued operating through relocation of some staff, remote work, and operations in western Ukraine (Lviv, Uzhhorod). The IT Association of Ukraine (ITUA) and government have worked to maintain the sector. Ukrainian developers continue to be hired globally. The Ukraine Diia City Special Tax Regime for IT companies (5% income tax + 22% social contribution on IT professionals) remains in operation."},
        {"question": "What is Ukraine''s Diia City and its tax benefits?", "answer": "Diia City is Ukraine''s special legal regime for IT companies, launched in 2022. IT workers in qualifying Diia City companies pay: 5% personal income tax (vs standard 18%) + 1.5% military levy. Diia City residents can be individual entrepreneurs (FOP) contracted to Diia City companies. Social contributions are reduced. This makes Ukraine one of the most attractive tax environments for IT professionals in Europe outside special zones. Companies in Diia City include major Ukrainian and international tech firms."},
        {"question": "What is the Individual Entrepreneur (FOP) system in Ukraine?", "answer": "Ukraine''s FOP (Fizychna Osoba Pidpryiemets) system allows individuals to register as sole traders with simplified taxation. FOP Group 3 (most common for IT): 5% tax on all income (or 3% + VAT). FOP registration is done through the tax service or Diia app. Required: Ukrainian tax number (RNOKPP), Ukrainian bank account. Many international IT workers contracted to Ukrainian companies use FOP status. Under Diia City, FOP arrangements with qualifying companies have additional protections and the 5% special rate."},
        {"question": "What is the BO (Individual Entrepreneur) registration process?", "answer": "FOP (Individual Entrepreneur) registration in Ukraine requires: Ukrainian Identification Number (RNOKPP), valid residence permit or Ukrainian citizenship. Register at the State Registrar (derived from the Ministry of Justice) or through Diia (Ukraine''s government digital platform). Registration fee is minimal (approximately UAH 250). Opening a Ukrainian business bank account requires the FOP registration extract. Most registrations complete within 1-3 business days under normal operating conditions."},
        {"question": "What are Ukraine''s income tax rates under normal conditions?", "answer": "Standard Ukrainian income tax: 18% on employment income + 1.5% military levy + 22% social security (for FOPs, standard rate). For Diia City IT professionals: 5% PIT + 1.5% military levy + 22% unified social contribution (capped at 22% of minimum wage for some structures). VAT 20% for most goods and services; 0% for IT export services. Ukraine signed double taxation avoidance treaties with most major economies. Consult a Ukrainian tax advisor (accountant/attorney) for current wartime adjustments."}
      ]'::jsonb,
      'CRITICAL: Most Western governments (USA, EU, UK, Canada, Australia) have issued Do Not Travel advisories for Ukraine due to the ongoing Russian invasion. Air travel to Ukrainian airports is suspended. Entry is primarily by road from Poland, Hungary, Romania, Slovakia, and Moldova. Active combat zones exist in the east and south. Anyone traveling to Ukraine for essential purposes must consult current government travel advisories, maintain detailed security plans, and register with their embassy. Immigration information here reflects the pre-war and current formal legal framework.',
      'Consult your home government''s current travel advisory before any plans related to Ukraine, register with your home country''s embassy if traveling to Ukraine for essential purposes, engage a Ukrainian immigration lawyer for any residency applications (services continue to operate in Kyiv and Lviv), obtain your RNOKPP (Ukrainian tax number) through the State Tax Service for financial and business activity, explore Diia City registration for IT professional employment structures, and monitor the Ukraine State Migration Service website for the latest procedural updates during martial law.'
    );
  END IF;

  -- ============================================================
  -- VIETNAM
  -- ============================================================
  SELECT id INTO v_id FROM immigration_cost_countries WHERE slug = 'vietnam';
  IF v_id IS NOT NULL THEN
    DELETE FROM immigration_cost_content WHERE country_id = v_id AND pathway_id IS NULL;
    INSERT INTO immigration_cost_content (country_id, pathway_id, intro_md, faq_json, warning_md, next_steps_md)
    VALUES (
      v_id, NULL,
      'Vietnam is one of Southeast Asia''s fastest-growing economies and a popular destination for digital nomads, English teachers, and entrepreneurs. Ho Chi Minh City (Saigon) and Hanoi are the main business hubs; Da Nang is a beach city increasingly popular with nomads. Vietnam does not have a formal digital nomad visa; most long-term residents use consecutive tourist visas or work permits. Cost of living is very low. Vietnam granted 3-month tourist visa exemptions to many countries in 2023.',
      '[
        {"question": "How do digital nomads stay long-term in Vietnam?", "answer": "Vietnam has no dedicated digital nomad visa. Common approaches: e-Visa (90-day single/multiple entry) extendable via Vietnamese travel agencies; 90-day tourist visa exemption for qualifying nationalities (30 nationalities as of 2023); consecutive visa renewals by brief border exits to Cambodia, Laos, or Thailand. Work permits require employer sponsorship and are not available for self-employed nomads. Many nomads use the 90-day e-Visa and re-enter after brief neighboring country visits."},
        {"question": "What is Vietnam''s e-Visa and how does it work?", "answer": "Vietnam''s e-Visa is available online (evisa.xuatnhapcanh.gov.vn) for citizens of most countries. Fee USD 25 per application. Valid for 90 days, single or multiple entry. Cannot be extended inside Vietnam beyond 90 days without leaving and re-entering. Can be applied for from abroad and receives approval within 3 working days. e-Visa entry is available at most international airports, major land borders, and seaports. One of Southeast Asia''s most convenient visa systems."},
        {"question": "What is the Vietnam work permit (giay phep lao dong)?", "answer": "Work permits are required for foreign nationals employed by Vietnamese companies, NGOs, or representative offices. Employer applies to the Department of Labor (DOLISA). Requirements: degree matching the job, 3+ years relevant experience, health certificate, police clearance, criminal background check. Processing 15-20 working days. Fee VND 400,000-600,000 (approximately USD 16-25). Valid up to 2 years. Tied to the employing organization. After approval, use it to obtain a Temporary Residence Card (TRC)."},
        {"question": "What is the Vietnam Temporary Residence Card (TRC)?", "answer": "The TRC (The tu tru) is a multi-year residence document issued to work permit holders and their dependents, valid for 1-2 years. Applied for at the Immigration Police Department after receiving a work permit. Fee VND 3,000,000-5,000,000 (approximately USD 120-200). TRC holders do not need a visa stamp and can enter/exit Vietnam freely. TRC holders also can apply for permanent residence after 3 years of continuous legal residence on TRC."},
        {"question": "How much does it cost to live in Ho Chi Minh City or Da Nang?", "answer": "Vietnam is extremely affordable. Ho Chi Minh City (Saigon): 1-bedroom apartment in District 2/3/7 (expat areas): USD 400-800/month. Monthly food budget: USD 200-400. Total monthly budget for comfortable living: USD 900-1,600. Da Nang: even more affordable, 1-bedroom USD 300-600/month. Hanoi: similar to HCMC. These figures are USD 400-800/month cheaper than equivalent lifestyle in Bangkok or Bali. Vietnam''s excellent street food culture allows very cheap daily meals (USD 1-3 per meal)."},
        {"question": "What are Vietnam income tax rates for foreign workers?", "answer": "Vietnam taxes residents (183+ days/year, or those with permanent domicile) on worldwide income. Tax rates: 5% up to VND 60M/year, 10% to VND 120M, 15% to VND 216M, 20% to VND 384M, 25% to VND 624M, 30% to VND 960M, 35% above. Non-residents: flat 20% on Vietnam-source income only. Personal deduction: VND 11M/month for the taxpayer. Most employed foreigners use Vietnamese PIT through employer payroll. Remote workers earning exclusively from abroad and staying under 183 days generally do not trigger Vietnamese PIT."},
        {"question": "What are the most popular expat destinations in Vietnam?", "answer": "Ho Chi Minh City (Saigon): Southeast Asia''s most dynamic business hub, large expat community in Districts 2, 3, and 7. Hanoi: capital city, more traditional atmosphere, expats in Tay Ho (West Lake) district. Da Nang: beach city with cooler climate, rapidly growing nomad scene, excellent for outdoor enthusiasts. Hoi An (near Da Nang): historic town popular with slower-paced lifestyle seekers. Each city has a different feel; HCMC is fast-paced, Hanoi more formal, Da Nang relaxed and scenic."}
      ]'::jsonb,
      'Vietnam''s lack of a formal digital nomad visa means long-term stays rely on visa chains (re-entry after border runs), which the government periodically scrutinizes. Overstaying a Vietnamese visa results in fines and potential blacklisting from future entry. Work without a valid work permit is technically illegal. The e-Visa portal can experience technical issues; apply well in advance of your planned travel. Climate varies significantly by region: Da Nang has a typhoon season (September-November); HCMC has a dry and rainy season split.',
      'Apply for your 90-day e-Visa at evisa.xuatnhapcanh.gov.vn at least 5 business days before travel, track your visa validity dates carefully and plan exit/re-entry before expiry, for long-term work obtain a valid work permit through your employer before starting employment, apply for a Temporary Residence Card after work permit approval to avoid ongoing visa management, obtain a Vietnam tax code (Ma so thue) from the General Department of Taxation if earning Vietnamese-source income, and register your residence with the local ward police (phuong) within 24-48 hours of establishing a new address.'
    );
  END IF;

END $$;
