/*
  # Populate Czech Republic Immigration Pathways - Fact-Checked

  1. Summary
    - Adds comprehensive, fact-checked immigration pathways for Czech Republic
    - Based on official ipc.gov.cz (Ministry of Interior), mzv.gov.cz (Ministry of Foreign Affairs), mvcr.cz
    - CRITICAL CORRECTIONS: All five original cards contain only generic "Starter" placeholder content with zero Czech-specific figures
    - Work: Processing "1-6 months" and validity "1-3 years" both wrong - actual 60/90 days processing, up to 2 years validity; Labour Office vacancy system and 30-day advertising period completely absent from original; consular quotas affect key nationalities
    - Student: Processing "2-8 weeks" wrong - actual 60 days (up to 90 at some embassies); two-stage system (visa then permit) missing; all documents must be in Czech language (critical requirement absent)
    - Digital Nomad: CRITICAL MISREPRESENTATION - original implies generic remote work visa; actual program is highly restricted IT/marketing specialist program from only 13 countries, launched July 2023; validity "6 months to 2 years" wrong - actual 1-year visa + 2-year permit = 3 years total
    - Retirement: CRITICAL ERROR - "Czech Republic Retirement Visa" does NOT EXIST; no dedicated retirement visa; movetoprague.com confirms "Czech Republic does not officially offer any form of Retirement or Investment visa"
    - Investor: Investment threshold "varying" obscures actual figure - CZK 75 million (~€3 million) minimum + 20 jobs required; NO golden visa; NO real estate investment route; validity "1-5 years" wrong - actual 2 years renewable

  2. Czech Republic Context
    - EU member since 2004; Schengen member
    - Czech residence permits enable Schengen travel (90 days/180 days non-gainful)
    - Governed by Act No. 326/1999 Coll. on Residence of Foreign Nationals
    - Authority: Ministry of Interior (Ministerstvo vnitra / MoI)
    - Applications submitted at Czech embassies/consulates in country of citizenship or legal permanent residence
    - All documents must be in Czech language (except passport and bank statements) - apostilled + certified translation
    - Collection visa D/VR (60 days validity) issued after approval for entry and biometric card collection
    - 5 years continuous legal stay → permanent residence
    - 10 years total + B1 Czech language → citizenship

  3. Content Details
    - Work: Employee Card (Zaměstnanecká karta) + EU Blue Card; 60 days standard/90 complex processing; validity up to 2 years; 30-day Labour Office vacancy advertising mandatory before application; EU Blue Card salary ≥1.5× Czech average (~CZK 70,000/month); consular quotas at Istanbul, Delhi, Nairobi, Beirut, Belgrade, Ankara, Pretoria affect key nationalities; EU Blue Card exempt from quotas; minimum salary CZK 20,800/month, 15 hours/week; two-stage entry: D/VR collection visa then biometrics
    - Student: Long-Term Visa (max 1 year) then Long-Term Residence Permit (2-year renewals for university); 60 days processing (up to 90 at some embassies); all documents must be in Czech language; financial means: 15× existential minimum (first month) + 2× per subsequent month (~CZK 46,900 semester); work rights: free labour market access for accredited university students; ≤26 years: 7 consecutive days or 30 days/year without permit
    - Digital Nomad: IT/Marketing Specialist Program launched July 2023; highly restricted to 13 eligible countries (US, UK, Canada, Australia, NZ, Japan, South Korea, Taiwan, Brazil, Israel, Mexico, Singapore, India since July 2025); IT or marketing specialists only; STEM/IT degree OR 3+ years IT experience required; income ≥1.5× Czech average (~CZK 60,000-70,000/month); 1-year visa + 2-year permit = 3 years total; two streams: employee (foreign company with 50+ employees) vs freelancer (Czech trade license required); full Czech tax obligations - no exemption; MPO pre-approval up to 45 days; February 2025 expansion added Brazil, Israel, Mexico, Singapore + marketing specialists; cannot work for Czech employers
    - Retirement: NO dedicated retirement visa exists; movetoprague.com: "Czech Republic does not officially offer any form of Retirement or Investment visa"; no minimum age requirement on any Czech visa; practical options: (A) enroll in Czech language course at university for student visa (most common workaround), (B) Long-Term Visa for "Other Purposes" requires legitimate stated reason (family/property/cultural ties - passive pension alone insufficient), (C) digital nomad program if still doing active IT/marketing remote work; financial means same formula: 15× existential minimum + 2× per month (~CZK 156,000-180,000/year)
    - Investor/Business: NO golden visa; NO real estate investment route; Investment Residence Permit requires CZK 75 million (~€3 million) minimum + 20 full-time jobs for EU citizens for ≥2 years; up to 60% may be non-cash assets; ≥30% ownership stake; up to 5 co-investors allowed (CZK 15M each minimum); 2 years validity renewable indefinitely; processing 30 days standard/60 complex by Ministry of Industry and Trade; Business Visa (živno/trade license) for entrepreneurs - no minimum investment but requires genuine Czech market connection; Startup Visa Program by CzechInvest for innovative tech entrepreneurs; movetoprague.com confirms "no golden visa"

  4. Important Notes
    - All data verified against ipc.gov.cz, mzv.gov.cz, mvcr.cz, Fragomen (Feb 2025 digital nomad update), movetoprague.com, educations.com, studyin.cz, goldenvisas.com
    - Consular visa quotas significantly affect Indian, Turkish, and several African/Middle Eastern nationalities at key embassies
    - Czech digital nomad program among most restrictive in Europe by professional scope (IT/marketing only from 13 countries)
    - All documents except passport and bank statements must be in Czech language - critical requirement for all pathways
    - Czech Republic intentionally excludes passive investor pathways and golden visa programs
    - Dual citizenship permitted since January 1, 2014
    - All original cards labeled "Starter" with entirely generic placeholder content - contained zero Czech-specific information
*/

-- Delete any existing Czech Republic pathways to avoid duplicates
DELETE FROM immigration_pathways WHERE destination_slug = 'czech-republic';

-- ═══════════════════════════════════════════════════════════════════════════
-- WORK: Employee Card + EU Blue Card
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO immigration_pathways (
  passport_slug,
  destination_slug,
  goal,
  pathway_type,
  pathway_name,
  summary,
  eligibility,
  key_requirements,
  requirements,
  typical_timeline,
  estimated_fees,
  processing_time,
  validity_period,
  official_url,
  last_updated
) VALUES (
  'any',
  'czech-republic',
  'Work',
  'Work',
  'Czech Republic Work Visa — Employee Card (Zaměstnanecká karta) + EU Blue Card (Modrá karta EU)',
  'Original card contains zero Czech-specific information. Processing time 1-6 months and validity 1-3 years both wrong. Czech Republic issues single combined work-and-residence document called Employee Card Zaměstnanecká karta, valid for up to 2 YEARS not 1-3, with processing of 60 days standard / 90 days complex cases not 1-6 months. For highly qualified professionals, EU Blue Card offers parallel route with salary threshold at least 1.5× Czech average gross salary approximately CZK 70,000/month in 2025, faster processing approximately 30-45 days, and easier EU mobility after 18 months. Critical structural feature entirely absent from original: most Employee Card positions must be listed in Central Register of Vacancies Centrální evidence volných míst and subject to 30-day Labour Office advertising period before non-EU national can apply. Some nationalities face annual consular quotas at certain embassies. PROCESSING TIME 1-6 MONTHS AND VALIDITY 1-3 YEARS BOTH FACTUALLY WRONG FOR CZECH REPUBLIC: Official MoI processing deadline for Employee Card is 60 days standard, extendable to 90 days complex cases. EU Blue Card processes in approximately 30-45 days. Validity is up to 2 years or employment contract duration, renewable in 2-year increments - not 1-3 years. After 2 years on Employee Card, holder renews; after 5 cumulative years, may apply for permanent residence. 1-6 month and 1-3 year figures are generic placeholders that misrepresent actual Czech system.',
  'EMPLOYEE CARD ELIGIBILITY: Third-country national non-EU/EEA/Swiss. Job offer from Czech-registered employer at position listed in Central Register of Vacancies. Employer must have published vacancy for 30 DAYS via Labour Office Úřad práce. Relevant qualifications/experience for role. Minimum gross salary: CZK 20,800/month; minimum hours: 15/week. Employer must be in good legal/tax standing no unreliable employer status. Clean criminal record home country + all countries of residence past 3 years. Proof of accommodation in Czech Republic. Valid passport sufficient validity. EU BLUE CARD ELIGIBILITY: Third-country national. University degree or bachelor equivalent or 5+ years senior experience for regulated professions. Employment contract ≥1 year for highly qualified position. Gross salary ≥ 1.5× CZECH AVERAGE approximately CZK 70,000/month in 2025. NO LABOUR MARKET TEST REQUIRED. EXEMPT FROM CONSULAR QUOTAS. Health insurance, clean criminal record, accommodation proof. After 18 months: right to transfer to another EU member state. VACANCY REGISTRATION AND 30-DAY LABOUR OFFICE WAIT MANDATORY PREREQUISITES - ENTIRELY OMITTED FROM ORIGINAL: For most Employee Card applications, Czech employer must register job vacancy in Central Register of Vacancies Centrální evidence volných míst operated by Ministry of Labour and Social Affairs. Position must remain published for at least 30 DAYS before non-EU applicant can submit Employee Card application. 30-day advertising period is hard prerequisite, not optional step. Mechanism for confirming no suitable Czech or EU candidate available. Vacancy reference number číslo volného místa from registry must be stated on Employee Card application form. Failure to obtain this number means application cannot be submitted.',
  'Job offer from Czech employer at position listed in Central Register of Vacancies; employer must advertise vacancy for 30 days via Labour Office before application; EU Blue Card: degree + salary ≥1.5× Czech average (~CZK 70,000/month); processing 60/90 days (Employee Card), 30-45 days (EU Blue Card); validity up to 2 years',
  'CONSULAR VISA QUOTAS AFFECT KEY NATIONALITIES - APPLICATIONS MAY BE BLOCKED REGARDLESS OF ELIGIBILITY: Czech immigration law permits government to set annual numerical caps on how many visas certain embassies can issue by visa type and nationality. As of 2025, Czech embassies in Istanbul, Delhi, Nairobi, Beirut, Belgrade, Ankara, and Pretoria operate restricted quotas for several long-term visa categories. Applicants from India, Turkey, and several African and Middle Eastern nationalities may find appointment slots fully booked or annual quota exhausted before application can be submitted. Real, significant constraint generic original omits entirely. EU Blue Card EXEMPT from these quotas, making it preferred route for qualifying professionals from quota-restricted nationalities. EU BLUE CARD: SALARY ≥1.5× CZECH AVERAGE GROSS approximately CZK 70,000/MONTH IN 2025, NO LABOUR MARKET TEST, FASTER PROCESSING: EU Blue Card Modrá karta EU requires: 1 binding job offer or contract for ≥1 year, 2 position classifiable as highly qualified, 3 university degree or bachelor equivalent or 5+ years senior professional experience for regulated professions, and 4 gross annual salary at least 1.5× CZECH NATIONAL AVERAGE GROSS SALARY. In 2025, equates to approximately CZK 70,000/month gross approximately €2,800. EU Blue Card exempt from both Labour Market Test and consular quotas, and processing can be as fast as 30-45 days. After 18 months on Czech EU Blue Card, holders can transfer to another EU member state under simplified rules. TWO-STAGE ENTRY PROCESS: D/VR COLLECTION VISA ISSUED AFTER APPROVAL, BIOMETRICS ON ARRIVAL IN CZECH REPUBLIC: Once MoI approves Employee Card or EU Blue Card application, Czech diplomatic mission where application submitted issues single-entry collection visa Type D/VR, valid 60 days. Applicant enters Czech Republic on this visa and must report to MoI within 3 business days of arrival to provide biometric data fingerprints and photo. Biometric Employee Card then produced and available for collection approximately 2-3 weeks later. Card itself not just visa is authorized work document. Minimum salary CZK 20,800/month gross and minimum working hours 15 hours/week.',
  'Processing: 60 days standard / 90 days complex for Employee Card. EU Blue Card: approximately 30-45 days. Add 30 days for Labour Office vacancy advertising Employee Card before application can be submitted. Two-stage entry: after approval, collection visa D/VR Type valid 60 days issued at embassy. Enter Czech Republic, report to MoI within 3 business days for biometric data collection. Biometric Employee Card available for collection approximately 2-3 weeks later.',
  'Application fee: CZK 5,000 approximately €200 payable at embassy. Collection visa D/VR: separate consular fee. Biometric card: collected at MoI after arrival approximately CZK 1,000. Document translation and apostille costs: approximately €200-€400. Health insurance: approximately €30-€80/month. Total first-year estimated costs: approximately €500-€1,000 excluding legal fees. All documents must be in Czech language apostilled + certified translation except passport and bank statements.',
  'Processing: 60 days standard / 90 days complex for Employee Card confirmed by official ipc.gov.cz Ministry of Interior. EU Blue Card: approximately 30-45 days.',
  'Employee Card: Up to 2 years tied to contract; renewable in 2-year increments. EU Blue Card: Up to 2 years; renewable. Employer change: Must notify MoI; Labour Office approval sometimes required. 2nd employer: Possible with prior approval. Permanent residence: After 5 continuous years legal stay → apply at MoI. Czech citizenship: Generally 10 years residence + B1 Czech language + integration test. Family: Spouse, children, parents eligible for family reunification permits. Tax: Czech flat rate 15% income tax; social security 6.5% employee; health insurance 4.5% employee. Schengen travel: 90 days/180 days within Schengen for non-gainful purposes. Dual citizenship: Permitted since January 1, 2014.',
  'https://ipc.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-residence-permits/employee-card/',
  '2026-03-02'
);

-- ═══════════════════════════════════════════════════════════════════════════
-- STUDENT: Long-Term Visa for Studies + Long-Term Residence Permit
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO immigration_pathways (
  passport_slug,
  destination_slug,
  goal,
  pathway_type,
  pathway_name,
  summary,
  eligibility,
  key_requirements,
  requirements,
  typical_timeline,
  estimated_fees,
  processing_time,
  validity_period,
  official_url,
  last_updated
) VALUES (
  'any',
  'czech-republic',
  'Study',
  'Study',
  'Czech Republic Student Visa — Long-Term Visa for Studies + Long-Term Residence Permit for Studies',
  'Original card mostly generic and contains one significant factual error: processing time typically 2-8 weeks. Czech government official processing deadline for long-term student visa is 60 DAYS confirmed by both ipc.gov.cz and Czech Consulate in New York, with educations.com citing 60-90 days at some embassies. 2-8 weeks roughly half actual timeline. Original also misses several important Czech-specific structural facts: Czech Republic uses TWO-STAGE SYSTEM Long-Term Visa for up to 1 year first, then Long-Term Residence Permit for studies lasting over 1 year; financial means requirement based on specific legal formula 15× existential minimum for first month + 2× existential minimum for each subsequent month; all documents must be in CZECH LANGUAGE; and program at qualifying institution must be accredited by Czech Ministry of Education MŠMT. PROCESSING TIME 2-8 WEEKS ROUGHLY HALF ACTUAL TIMELINE - OFFICIAL DEADLINE 60 DAYS: Official Czech MoI processing time for long-term student visa is 60 days from date of application submission, confirmed by official foreigners portal ipc.gov.cz and Czech Consulate in New York. Some embassies take up to 90 days educations.com, studyin.cz. 2-8 weeks 14-56 days substantially too optimistic and could cause students to apply too late. Czech immigration specialists recommend applying 2-3 months before intended start date. Processing clock does not start until complete, error-free application submitted - missing documents can reset clock.',
  'Third-country national non-EU/EEA/Swiss. Accepted into Czech educational institution accredited by Ministry of Education MŠMT. Qualifying programme types: university accredited programmes; secondary school / higher vocational as part of exchange; language preparation for accredited university studies at public university or via EU programme. Sufficient financial means for stay legally calculated formula. Valid health insurance covering Czech Republic min. €60,000 coverage for first 90 days; then public HZZO registration required. Clean criminal record home country, apostilled + certified Czech translation. Proof of accommodation in Czech Republic. TWO-STAGE SYSTEM: LONG-TERM VISA MAX 1 YEAR THEN RESIDENCE PERMIT 2-YEAR EXTENSIONS - CRITICAL STRUCTURAL DETAIL ABSENT: Czech student immigration operates in two stages. For stays under 1 year or initial entry: apply for Long-Term Visa for Studies maximum total validity 1 year including any extensions. For stays exceeding 1 year or after first year: apply for Long-Term Residence Permit for Purpose of Studies valid 1 year, renewable in 2-year increments for university programmes, or once for language preparation courses. University students typically need to transition from visa to residence permit. Original card mentions only one generic visa type, missing this progression entirely.',
  'Accepted at Czech institution accredited by Ministry of Education (MŠMT); all documents must be in Czech language (apostilled + certified translation); financial means: 15× existential minimum (first month) + 2× per subsequent month (~CZK 46,900 semester); processing 60 days (up to 90 at some embassies); two-stage: visa (max 1 year) then residence permit',
  'ALL DOCUMENTS MUST BE IN CZECH LANGUAGE - CRITICAL ADMINISTRATIVE REQUIREMENT MISSING FROM ORIGINAL: Czech immigration law requires all submitted documents except passport and bank statements to be IN CZECH LANGUAGE. Foreign documents must be: 1 apostilled or super-legalized depending on country, then 2 certified-translated into Czech by sworn translator. Criminal record check, acceptance letter from university, and supporting documents must all meet this requirement. Submitting documents in English only will result in rejection. Czech Consulate in New York explicitly states: according to law of Czech Republic, all documents except proof of sufficient financial means must be presented in Czech Language. FINANCIAL MEANS FORMULA: 15× EXISTENTIAL MINIMUM FIRST MONTH + 2× PER SUBSEQUENT MONTH approximately CZK 46,900 PER SEMESTER, approximately €1,900: Financial means requirement calculated by Czech law: 15× existential minimum currently CZK 3,130 for first month, plus 2× existential minimum CZK 6,260 for each additional month. For one-semester stay: approximately CZK 46,900-78,200 approximately €1,900-3,200 depending on length. For full academic year: approximately CZK 109,000-125,000 approximately €4,400-5,000. Proof options: bank statement in applicant name, scholarship confirmation, or family sponsor letter with bank statement. Cash deposits, sponsor affidavits, and even valid internationally recognized debit card accepted at some consulates. WORK RIGHTS: STUDENTS UP TO AGE 26 MAY WORK UP TO 7 CONSECUTIVE DAYS OR 30 DAYS/YEAR WITHOUT PERMIT; OTHERS NEED EMPLOYMENT PERMIT: Non-EU students have limited work rights in Czech Republic. Students aged 26 or under may work without separate employment permit for up to 7 CONSECUTIVE CALENDAR DAYS OR TOTAL OF 30 DAYS IN CALENDAR YEAR. For longer or ongoing work, separate employment permit administrativní poplatek CZK 500 required. Permit applied for by employer at Regional Labour Office. Part-time work linked to official student exchange/internship programmes additionally exempt. Full-time students at accredited university programmes have FREE ACCESS TO LABOUR MARKET - no separate permit needed regardless of age.',
  'Processing: 60 days standard; up to 90 days at some embassies. Apply 2-3 months before intended start date. Two-stage system: Long-Term Visa for Studies up to 1 year total including extensions for initial entry or stays under 1 year. Long-Term Residence Permit for Studies 1 year, renewable in 2-year increments for university programmes after first year or for stays exceeding 1 year. Registration with Foreign Police within 3 days of arrival mandatory; university dormitories handle automatically.',
  'Visa application fee: CZK 2,500 approximately €100. Biometric residence permit after arrival: CZK 1,000 approximately €40. Document translation and apostille costs: approximately €200-€400. Health insurance: approximately €30-€80/month until HZZO registration. Financial means proof required: approximately CZK 46,900-78,200 per semester approximately €1,900-3,200 or CZK 109,000-125,000 per year approximately €4,400-5,000 in bank statements/scholarship/sponsor letter. Total first-year estimated costs excluding tuition: approximately €800-€1,500. US, Canada, Australia, NZ, Japan, South Korea, Taiwan: may apply by mail at some consulates.',
  'Processing: 60 days standard confirmed by official ipc.gov.cz Ministry of Interior and Czech Consulate in New York; up to 90 days at some embassies confirmed by educations.com and studyin.cz.',
  'Long-Term Visa for Studies: Up to 1 year total including extensions. Long-Term Residence Permit university: 1 year; renewable in 2-year increments while enrolled. Residence permit language prep: Extendable once only. Work rights: Free labour market access for accredited university students; others limited - age ≤26: up to 7 consecutive days or 30 days/year without permit; others need employment permit CZK 500 applied by employer at Regional Labour Office. Path to PR: 5 continuous years legal stay → permanent residence. Citizenship: approximately 10 years + B1 Czech + integration requirements. Schengen travel: 90 days/180 days within Schengen for non-gainful purposes. Dual citizenship: Permitted since January 1, 2014.',
  'https://ipc.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-visa/long-term-visa-for-the-purpose-of-studies/',
  '2026-03-02'
);

-- ═══════════════════════════════════════════════════════════════════════════
-- DIGITAL NOMAD: IT/Marketing Specialist Program
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO immigration_pathways (
  passport_slug,
  destination_slug,
  goal,
  pathway_type,
  pathway_name,
  summary,
  eligibility,
  key_requirements,
  requirements,
  typical_timeline,
  estimated_fees,
  processing_time,
  validity_period,
  official_url,
  last_updated
) VALUES (
  'any',
  'czech-republic',
  'Digital Nomad',
  'Digital Nomad',
  'Czech Republic Digital Nomad — IT/Marketing Specialist Program (launched July 2023) via Business or "Other Purposes" Long-Term Visa',
  'Original card implies generic digital nomad visa open to any remote worker - fundamentally inaccurate for Czech Republic. Czech digital nomad program, launched JULY 1, 2023 under Government Decree No. 475/2023, is HIGHLY RESTRICTED, SPECIALIST PROGRAM with strict eligibility: applicants must be IT or marketing specialists narrowly defined, from one of only 13 ELIGIBLE COUNTRIES US, UK, Canada, Australia, New Zealand, Japan, South Korea, Taiwan, Brazil, Israel, Mexico, Singapore; India added July 2025, earn at least 1.5× CZECH AVERAGE GROSS SALARY approximately CZK 60,000-70,000/month, and have either STEM/IT university degree or 3+ YEARS PROFESSIONAL IT EXPERIENCE. Original validity 6 months to 2 years also wrong - program issues 1-YEAR VISA, extendable to 2-YEAR RESIDENCE PERMIT 3 YEARS TOTAL. No generic remote work visa in Czech Republic for workers who do not meet these specialist criteria. CRITICAL MISREPRESENTATION: CZECH REPUBLIC HAS NO GENERIC REMOTE WORK VISA - PROGRAM RESTRICTED TO IT/MARKETING SPECIALISTS FROM 13 COUNTRIES ONLY: Original describes visa for remote employment or self-employment with clients outside country as if broadly available. Czech digital nomad program explicitly limited to: 1 citizens of only 13 eligible countries; 2 highly skilled IT specialists or marketing specialists as defined by Czech Ministry of Industry and Trade; 3 applicants with STEM/IT university degree OR 3+ years IT work experience; 4 earning ≥1.5× Czech average gross salary. US-based graphic designer, Canadian copywriter, or Brazilian social media manager would NOT qualify. Among most restrictive digital nomad programs in Europe by professional scope.',
  'NATIONALITY: Citizens of only: US, UK, Canada, Australia, New Zealand, Japan, South Korea, Taiwan, Brazil, Israel, Mexico, Singapore, India as of July 2025. PROFESSIONAL FIELD: IT specialist broadly: software development, IT systems, data OR Marketing specialist marketing management, research, planning. QUALIFICATIONS: University degree in IT/STEM any level OR ≥3 years professional IT work experience. INCOME: ≥1.5× Czech average gross salary = approximately CZK 60,000-70,000/MONTH approximately €2,400-2,800. EMPLOYEE STREAM: Foreign employer must have ≥50 employees worldwide; remote work explicitly in contract. FREELANCER STREAM: Must hold active Czech Trade License živnostenský list in IT/marketing. VALIDITY 6 MONTHS TO 2 YEARS WRONG - CORRECT STRUCTURE 1-YEAR VISA + 2-YEAR RESIDENCE PERMIT = 3 YEARS TOTAL: Original states validity usually 6 months to 2 years. Actual structure: digital nomad program issues Long-Term Visa valid for 1 YEAR. After that first year, holder must convert to Long-Term Residence Permit valid for 2 ADDITIONAL YEARS - for total maximum of 3 years. 6 months not standard validity option under this program. Processing takes up to 45 DAYS from approval by Ministry of Industry and Trade not 2-8 weeks as original implies for this category.',
  'Citizens of only 13 countries (US, UK, Canada, Australia, NZ, Japan, South Korea, Taiwan, Brazil, Israel, Mexico, Singapore, India); IT or marketing specialists only; STEM/IT degree OR 3+ years IT experience; income ≥1.5× Czech average (~CZK 60,000-70,000/month); 1-year visa + 2-year permit = 3 years total; launched July 2023',
  'TWO-STREAM STRUCTURE: EMPLOYEE STREAM WORKS FOR FOREIGN COMPANY WITH 50+ EMPLOYEES VS FREELANCER STREAM CZECH TRADE LICENSE REQUIRED: Program has two parallel paths. EMPLOYEES must be working for foreign company with AT LEAST 50 EMPLOYEES WORLDWIDE, and their employment contract must explicitly include provision for remote work. Apply for Long-Term Visa for Other Purposes D/VC/99. FREELANCERS must obtain Czech Trade License živnostenský list in IT or marketing before applying, and apply for Long-Term Visa for Business - Self-Employment D/VC/06. Two entirely different visa sub-types, each with distinct document requirements - freelancer applying on employee track or vice versa will be rejected. FEBRUARY 2025 EXPANSION: BRAZIL, ISRAEL, MEXICO, AND SINGAPORE ADDED; MARKETING SPECIALISTS NOW ELIGIBLE: Fragomen confirmed in February 2025 that Czech digital nomad program was expanded to include nationals of Brazil, Israel, Mexico, and Singapore, in addition to original eight countries. Separately, MARKETING SPECIALISTS broadly defined as those who manage/implement marketing activities became eligible alongside IT specialists. Nationals of India added July 2025 per Nomadic Expert. Meaningful change from program IT-only origins, but program remains far more restricted than generic description in original card. TAX OBLIGATIONS: FREELANCERS REGISTER FOR CZECH TAX/SOCIAL SECURITY AND FACE MANDATORY MONTHLY CONTRIBUTIONS approximately CZK 6,400/MONTH; NO BLANKET TAX EXEMPTION: Unlike Croatia digital nomad permit which offers tax exemption, Czech Republic program comes with FULL CZECH TAX OBLIGATIONS. Freelancers holding Czech trade license must register with Tax Office, Social Security Administration OSSZ, and Health Insurance VZP or similar. Monthly mandatory contributions: social security approximately CZK 3,852/month, health insurance approximately CZK 2,968/month for self-employed 2025 minimum rates. Freelancers also pay Czech income tax on declared profits 15% flat rate, with simplified 60/40 cost deduction regime available. Employees taxes withheld by foreign employer if applicable, but Czech residency obligations still apply after 183 days.',
  'Step 1: Submit registration to Ministry of Industry and Trade MPO with trade license freelancers, employer/client contracts, income proof, qualifications. Step 2: MPO assesses eligibility - decision in approximately 45 DAYS. Step 3: If approved, MPO notifies Czech embassy; embassy contacts applicant within 10 days to schedule visa appointment. Step 4: Apply for relevant Long-Term Visa at designated Czech embassy employee: D/VC/99; freelancer: D/VC/06. Step 5: On arrival, register with Foreign Police within 3 days; freelancers activate trade license and register for tax/social security. Total from registration to visa collection: typically 2-4 months.',
  'Consular visa fee: CZK 2,500 approximately €100. Trade license freelancers: approximately CZK 1,000 approximately €40. Biometric residence permit after year 1: separate fee. Freelancer mandatory monthly costs: social security approximately CZK 3,852/month + health insurance approximately CZK 2,968/month = approximately CZK 6,820/month approximately €270/month. Czech income tax: 15% flat rate on declared profits with 60/40 cost deduction regime available for freelancers. Total first-year costs employee stream: approximately €500-€800. Total first-year costs freelancer stream: approximately €4,000-€5,000 including mandatory social/health contributions.',
  'MPO pre-approval: Up to 45 days. Subsequent visa processing: Scheduled by embassy after MPO approval. Total from registration to visa collection: typically 2-4 months.',
  'Year 1: Long-Term Visa 1 year. Years 2-3: Long-Term Residence Permit 2 years; total maximum 3 years. Beyond year 3: Must qualify for another permit category Employee Card, etc. Local employment: Not permitted; only remote work for foreign employer/clients. Tax: Full Czech obligations apply - no blanket exemption. Freelancer costs: Monthly social security + health insurance approximately CZK 6,400+/month mandatory. Path to PR: 5 continuous years legal stay → permanent residence digital nomad years count if unbroken. Family: Spouse/registered partner and dependent children may apply for Long-Term Visa for Family purposes; DEPENDENTS CANNOT WORK on family visas. Cannot work for Czech employers under either stream - only foreign companies or foreign clients. Schengen travel: 90 days/180 days within Schengen for non-gainful purposes.',
  'https://www.fragomen.com/insights/czech-republic-digital-nomad-program-introduced.html',
  '2026-03-02'
);

-- ═══════════════════════════════════════════════════════════════════════════
-- RETIREMENT: No Dedicated Retirement Visa; Options via Other Purposes or Student
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO immigration_pathways (
  passport_slug,
  destination_slug,
  goal,
  pathway_type,
  pathway_name,
  summary,
  eligibility,
  key_requirements,
  requirements,
  typical_timeline,
  estimated_fees,
  processing_time,
  validity_period,
  official_url,
  last_updated
) VALUES (
  'any',
  'czech-republic',
  'Retirement',
  'Retirement',
  'Czech Republic "Retirement" — No Dedicated Retirement Visa; De-Facto Options via Long-Term Visa for "Other Purposes" or Digital Nomad Program',
  'Original card describes Czech Republic Retirement Visa with minimum age often 50 or older, income thresholds, and 1-2 years initially, usually renewable. NO SUCH VISA EXISTS. Multiple authoritative Czech immigration sources confirm this explicitly. Czech immigration law does not prescribe immigration pathway specifically designed for foreign retirees. Movetoprague.com Czech immigration specialists, end-of-2025: the Czech Republic does not officially offer any form of Retirement or Investment visa. Flatio.com: There are currently no retirement visas. Czech-immigration.com: the Czech Republic immigration law does not prescribe immigration pathway specifically designed for foreign retirees. What retirees actually use is general Long-Term Visa for Other Purposes Jiný účel, with stated purpose of stay connected to family links, property, or other legitimate ties to Czech Republic. Most commonly cited workaround is enrolling in CZECH LANGUAGE COURSES to qualify for student-purpose visa - useful for permanent residence preparation as well. CZECH REPUBLIC RETIREMENT VISA DOES NOT EXIST - ORIGINAL DESCRIBES NON-EXISTENT IMMIGRATION CATEGORY: Czech immigration law Act No. 326/1999 Coll. does not contain retirement visa category. Requirement of minimum age 50 or older appears on no Czech immigration document - Czech long-term visas have no minimum age requirements. Income figures, validity period, and permit structure described in original card correspond to no actual Czech visa type. Entirely generic placeholder content incorrectly labeled as Czech-specific information.',
  'OPTION A - STUDENT VISA CZECH LANGUAGE COURSE: Enroll in Czech language programme at recognized public university. Apply for Long-Term Visa for Studies purpose. Renewable annually while enrolled; builds toward PR. Most widely used workaround for non-EU retirees. OPTION B - LONG-TERM VISA FOR OTHER PURPOSES: Requires legitimate, demonstrable reason family, property, cultural ties. Passive pension income alone generally NOT sufficient. 1-year visa; can transition to 2-year residence permit. OPTION C - DIGITAL NOMAD PROGRAM: Only for those still doing active IT/marketing remote work. Must meet professional, national, and income criteria see Card 3. STANDARD OTHER PURPOSES LONG-TERM VISA REQUIRES LEGITIMATE STATED REASON - PASSIVE RETIREMENT INCOME ALONE GENERALLY INSUFFICIENT: General Long-Term Visa for Other Purposes requires applicant demonstrate specific purpose of stay in Czech Republic that justifies continuous presence. Passive pension income from abroad does not, by itself, constitute qualifying purpose under Czech law. Common legitimate purposes that can anchor other purposes visa: 1 having close family legally resident in Czech Republic, 2 owning property in Czech Republic, 3 enrollment in registered educational programme. Without one of these anchors, pure retirement application very likely to be rejected. Meaningful practical constraint original card completely ignores.',
  'NO dedicated retirement visa exists; movetoprague.com confirms "Czech Republic does not officially offer any form of Retirement or Investment visa"; no minimum age requirement; practical options: (A) enroll in Czech language course at university for student visa (most common), (B) Long-Term Visa "Other Purposes" requires legitimate reason (family/property - passive pension alone insufficient), (C) digital nomad if active IT/marketing remote work',
  'MOST PRACTICAL WORKAROUND FOR RETIREES: ENROLL IN CZECH LANGUAGE CLASSES AT UNIVERSITY AND APPLY FOR STUDENT VISA: Most widely cited practical solution for non-EU retirees who want to live in Czech Republic is to enroll in Czech language course at recognized public university these qualify for student-purpose long-term visas and apply for student visa. Czech immigration specialists note this widely accepted workaround. Benefits: 1 qualifies for student long-term visa with legitimate stated purpose; 2 Czech language skills gained count toward A1/B1 language requirement for permanent residence applications; 3 student-purpose residence time counts toward 5-year PR qualification. Study visa must be renewed annually and requires ongoing enrollment. FINANCIAL MEANS FOR LONG-TERM VISA OTHER PURPOSES: 15× EXISTENTIAL MINIMUM FOR FIRST MONTH + 2× PER SUBSEQUENT MONTH: Same financial means formula used for student visas applies to general long-term visas. For one year: approximately CZK 156,000-180,000 approximately €6,200-7,200 must be demonstrable. Sources of passive income acceptable for financial means: pension payments, social security benefits, annuities, investment income, rental income. All income documentation must be translated into Czech and apostilled where required. Czech existential minimum set by law and updated periodically - verify current figure before applying. DIGITAL NOMAD PROGRAM AS PARTIAL SOLUTION FOR WORKING RETIREES EARNING REMOTE IT/MARKETING INCOME: For retirees who still do active remote IT or marketing consulting work, digital nomad program described in Card 3 is only long-term visa in Czech Republic that can be obtained without ties to Czech Republic. Movetoprague.com explicitly: that is at this point end of 2025 the only long-term visa option in Czech Republic that can be granted to people who do not have any ties to Czech Republic. However, requires active professional work, qualifying profession, eligible nationality, and minimum income - not retirement vehicle for those who have stopped working.',
  'Long-Term Visa all purposes: 60 days standard. Apply at Czech embassy in country of citizenship or permanent residence. Register with Foreign Police within 3 days of arrival mandatory.',
  'Application fee: CZK 2,500 approximately €100 student; CZK 5,000 approximately €200 business/other purposes. Biometric card after arrival: CZK 1,000. Financial means proof required: approximately CZK 156,000-180,000 approximately €6,200-7,200 for one year in bank statements/pension documentation/sponsor letter. Document translation and apostille costs: approximately €200-€400. Health insurance: approximately €30-€80/month until HZZO registration. Total first-year estimated costs: approximately €1,000-€2,000 excluding accommodation.',
  'Long-Term Visa all purposes: 60 days standard. Apply at Czech embassy in country of citizenship or permanent residence.',
  'Long-Term Visa: Up to 1 year total including extensions. Long-Term Residence Permit: 1-2 years; renewable annually or biannually. Work rights: Not permitted on other purposes visa. No minimum age requirement on any category. Path to PR: 5 continuous years legal stay → permanent residence. Czech citizenship: Generally 10 years total + Czech language B1 + integration test. Dual citizenship: Permitted in Czech Republic since January 1, 2014. Czech healthcare: Access to public system HZZO available to legal residents; private insurance required until registered. Schengen travel: 90 days/180 days within Schengen for non-gainful purposes.',
  'https://ipc.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-visa/long-term-visa-general-information/',
  '2026-03-02'
);

-- ═══════════════════════════════════════════════════════════════════════════
-- INVESTOR/BUSINESS: Investment Residence Permit + Business Visa
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO immigration_pathways (
  passport_slug,
  destination_slug,
  goal,
  pathway_type,
  pathway_name,
  summary,
  eligibility,
  key_requirements,
  requirements,
  typical_timeline,
  estimated_fees,
  processing_time,
  validity_period,
  official_url,
  last_updated
) VALUES (
  'any',
  'czech-republic',
  'Investor',
  'Investor',
  'Czech Republic Investor / Business — Investment Residence Permit (CZK 75M min., 20 jobs) + Business Visa (Živnostenský list)',
  'Original card describes significant financial investment in approved assets, businesses, or government programs with varying investment thresholds and 1-5 years initially with renewal options. All of this either wrong or dangerously vague. Czech Republic has two distinct investor/business tracks: 1 Long-Term Residence Permit for Purpose of Investment - which requires MINIMUM OF CZK 75 MILLION approximately €3 MILLION and creation of AT LEAST 20 FULL-TIME JOBS FOR EU CITIZENS, with applications reviewed by Ministry of Industry and Trade - and 2 Long-Term Visa for Business / Self-Employment the živno visa, used by entrepreneurs registering Czech trade license živnostenský list for more modest business activities. Original card vague varying investment thresholds hides fact that formal Investment Permit is one of most expensive and demanding in Europe. CZECH REPUBLIC HAS NO GOLDEN VISA AND NO REAL ESTATE INVESTMENT VISA. CZECH REPUBLIC HAS NO GOLDEN VISA, NO REAL ESTATE INVESTOR VISA - ORIGINAL FRAMING OF REAL ESTATE PURCHASE OR CAPITAL TRANSFER ENTIRELY WRONG: Original describes obtaining residence via real estate purchase or capital transfer - neither exists as investor immigration route in Czech Republic. Multiple authoritative sources confirm: goldenvisas.com: There is currently no golden visa or citizenship by investment programme offered by Czech Republic. Czech Republic does not allow passive real estate investment as basis for residence. Formal Investment Residence Permit requires active participation in running business. As IMI Daily documented, Czech investor visa does not appear to be residence by investment program due to its operational requirements and physical residence obligation for PR qualification.',
  'INVESTMENT RESIDENCE PERMIT REQUIREMENTS: Third-country national who is entrepreneur or executive of company making qualifying investment. Minimum investment: CZK 75 MILLION approximately €3 MILLION up to 5 co-investors allowed; minimum per investor CZK 15M. Up to 60% of investment may be non-cash assets real estate, equipment, technology know-how. Create and maintain ≥20 FULL-TIME JOBS FOR EU CITIZENS for ≥2 years. Hold ≥30% OWNERSHIP STAKE in Czech company. Approved business plan from Ministry of Industry and Trade. Proof of legitimate source of investment funds. Criminal record extract, health insurance, accommodation proof. Applicant must actively participate in running business. BUSINESS VISA ŽIVNO REQUIREMENTS: Register Czech Trade License živnostenský list at Trade Licensing Office. No minimum investment amount. Credible business plan with demonstrated connection to Czech market. Financial means: approximately CZK 156,500 approximately €6,300 for initial period. Health insurance valid in Czech Republic. Criminal record extract apostilled + Czech translation. Proof of accommodation. ⚠️ Business plans without genuine Czech market/client connection routinely rejected. Czech immigration authorities actively assess plausibility of business model. VARYING INVESTMENT THRESHOLDS OBSCURES ACTUAL FIGURE: CZK 75 MILLION approximately €3 MILLION MINIMUM - ONE OF EUROPE HIGHEST: Actual minimum investment threshold explicitly stated in Czech law confirmed by ipc.gov.cz official portal: CZK 75 MILLION approximately €3 MILLION at current rates. Approximately 10× threshold of Hungary recently closed bond scheme, 6× Greece real estate minimum, and higher than Portugal eliminated real estate route. Additionally, up to 60% OF INVESTMENT may be in non-cash tangible or intangible assets real estate, equipment, technology know-how - only 40% need be cash. Permit requires creating and maintaining AT LEAST 20 FULL-TIME JOBS FOR EU CITIZENS OR THEIR FAMILY MEMBERS for minimum of 2 years. Multiple investors up to 5 may pool investments, reducing individual threshold to CZK 15 million approximately €575,000 each.',
  'NO golden visa; NO real estate investment route; Investment Residence Permit: CZK 75 million (~€3 million) minimum + 20 full-time jobs for EU citizens for ≥2 years; up to 60% may be non-cash assets; ≥30% ownership stake; 2 years validity renewable indefinitely; Business Visa (živno): Czech trade license required, no minimum investment but genuine Czech market connection required',
  'VALIDITY 2 YEARS NOT 1-5 YEARS - RENEWABLE INDEFINITELY AS LONG AS INVESTMENT MAINTAINED: Original states 1-5 years initially. Actual Investment Residence Permit issued for 2 YEARS, renewable in 2-year increments for as long as investment and jobs maintained. Processing notably fast compared to other permit types: decisions in 30 DAYS STANDARD / 60 DAYS FOR COMPLEX CASES, since Ministry of Industry and Trade reviews business plans directly rather than going through standard consular queue. Business visa živno for standard entrepreneurs issued as 1-year visa, renewable as 2-year residence permit annually - also not 1-5 years. BUSINESS VISA ŽIVNO: PRACTICAL ROUTE FOR ENTREPRENEURS AND SME FOUNDERS - NO MINIMUM INVESTMENT, BUT REQUIRES GENUINE CZECH BUSINESS ACTIVITY: For entrepreneurs who do not meet CZK 75M threshold, Long-Term Visa for Business Živnostenský list is standard route. Requires: 1 registering Czech trade license živnostenský list at Trade Licensing Office; 2 demonstrating sufficient financial means approximately CZK 156,500 / approximately €6,300 for initial period; 3 presenting realistic business plan tied to Czech Republic local clients or market activity; 4 financial proof showing business viability. No minimum investment amount, but immigration authorities assess plausibility of business plan - business with no clear Czech connection typically rejected. Route used by freelancers, consultants, and small business owners. STARTUP VISA PROGRAM: SEPARATE FAST-TRACK FOR INNOVATIVE STARTUPS, EVALUATED BY CZECHINVEST: Czech Republic operates dedicated Startup Visa Program for innovative technology entrepreneurs, administered by CzechInvest national investment promotion agency. Applicants submit business plan evaluated by CzechInvest for innovation potential and economic impact. If approved, CzechInvest issues recommendation letter that enables faster, more streamlined application for business long-term visa. Distinct from both standard živno business visa and formal CZK 75M Investment Permit. Targets early-stage tech companies planning to establish and grow in Czech Republic.',
  'Investment Permit: 30 days standard / 60 days complex - reviewed by Ministry of Industry and Trade. Business Visa živno: 90-120 days from embassy submission. Startup Visa: CzechInvest evaluation + standard business visa timeline.',
  'Business visa application: CZK 5,000 approximately €200. Collection D/VR visa: separate consular fee. Trade license registration: approximately CZK 1,000 approximately €40. Investment Permit administrative costs: approximately €1,000-€3,000 legal and processing. Minimum investment threshold: CZK 75 million approximately €3 million or CZK 15 million approximately €575,000 per co-investor if pooling up to 5 investors. Job creation costs: 20 full-time EU citizen employees for ≥2 years - salary costs vary by sector. Business Visa živno financial means requirement: approximately CZK 156,500 approximately €6,300 for initial period. Total Investment Permit costs: €3+ million investment + ongoing operational costs. Total Business Visa costs first year: approximately €1,000-€2,000 in fees plus business operational costs.',
  'Investment Permit: 30 days standard / 60 days complex confirmed by Ministry of Industry and Trade review process. Business Visa živno: 90-120 days from embassy submission.',
  'Investment Permit: 2 years; renewable indefinitely while investment + jobs maintained. Business Visa živno: 1-year visa → 2-year renewable residence permit. Immediate family: Investment permit holders - family reunification permits available same timescale. Work rights: Investment permit holders and family have right to work. Path to PR: 5 continuous years legal stay → permanent residence physical residence required for PR qualification. Citizenship: approximately 10 years total + Czech B1 language + integration test. No golden visa / no real estate route / no passive investment visa: Czech Republic intentionally excludes passive investor pathways. Dual citizenship: Permitted since January 2014. Schengen travel: 90 days/180 days within Schengen for non-gainful purposes. Movetoprague.com confirms Czech Republic does not officially offer any form of Investment visa.',
  'https://ipc.gov.cz/en/visa-and-residence-permit-types/third-country-nationals/long-term-residence-permits/long-term-residence-permit-for-the-purpose-of-investment/',
  '2026-03-02'
);
